import fs from "node:fs";
import path from "node:path";

import {
  AlignmentType,
  BorderStyle,
  Document,
  Footer,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from "docx";
import ExcelJS from "exceljs";

import type { HandbookTemplate } from "../../../shared/handbook";

/**
 * The generated default for a handbook template (v4.2, decision D3): a plain, branded DOCX or XLSX
 * built from the entry itself, until an admin uploads Oyelabs' own version.
 *
 * - `blank`: the sections as headings (docx) or the header row (xlsx).
 * - `filled`: the same, plus the entry's `example` rows.
 */

export const BRAND_BLUE = "2067D3";
export const TEMPLATE_FOOTER = "Generated by Oyelearn. Replace with Oyelabs' own version in Admin → Handbook.";
export const TEMPLATE_VARIANTS = ["blank", "filled"] as const;
export type TemplateVariant = (typeof TEMPLATE_VARIANTS)[number];

export const MIME = {
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
} as const;

export const titleOf = (t: HandbookTemplate) => `Oyelabs — ${t.name}`;

const norm = (s: string) => s.trim().toLowerCase();

/** Example rows split into those that answer a section/column and the rest. */
function splitExample(t: HandbookTemplate): { bySection: Map<string, string>; rest: [string, string][] } {
  const sections = new Set(t.sections.map(norm));
  const bySection = new Map<string, string>();
  const rest: [string, string][] = [];
  for (const [field, value] of t.example) {
    if (sections.has(norm(field)) && !bySection.has(norm(field))) bySection.set(norm(field), value);
    else rest.push([field, value]);
  }
  return { bySection, rest };
}

export async function buildDocx(t: HandbookTemplate, variant: TemplateVariant): Promise<Buffer> {
  const children: (Paragraph | Table)[] = [
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [new TextRun({ text: titleOf(t), bold: true, color: BRAND_BLUE, size: 40 })],
    }),
    new Paragraph({ children: [new TextRun({ text: t.purpose, italics: true, color: "555555" })], spacing: { after: 240 } }),
  ];
  const { bySection, rest } = splitExample(t);
  for (const section of t.sections) {
    children.push(new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text: section, color: BRAND_BLUE, bold: true })] }));
    const value = variant === "filled" ? bySection.get(norm(section)) : undefined;
    children.push(new Paragraph({ children: [new TextRun({ text: value ?? "" })], spacing: { after: 200 } }));
  }
  if (variant === "filled" && rest.length > 0) {
    children.push(new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text: "Worked example", color: BRAND_BLUE, bold: true })] }));
    const border = { style: BorderStyle.SINGLE, size: 4, color: "BFC7D5" };
    const borders = { top: border, bottom: border, left: border, right: border };
    children.push(
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: rest.map(
          ([field, value]) =>
            new TableRow({
              children: [
                new TableCell({ borders, width: { size: 30, type: WidthType.PERCENTAGE }, children: [new Paragraph({ children: [new TextRun({ text: field, bold: true })] })] }),
                new TableCell({ borders, width: { size: 70, type: WidthType.PERCENTAGE }, children: [new Paragraph(value)] }),
              ],
            }),
        ),
      }),
    );
  }
  const doc = new Document({
    creator: "Oyelearn",
    title: titleOf(t),
    sections: [
      {
        footers: {
          default: new Footer({
            children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: TEMPLATE_FOOTER, size: 16, color: "777777" })] })],
          }),
        },
        children,
      },
    ],
  });
  return Packer.toBuffer(doc);
}

export async function buildXlsx(t: HandbookTemplate, variant: TemplateVariant): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Oyelearn";
  wb.title = titleOf(t);
  // Sheet names: max 31 characters, none of : \ / ? * [ ]
  const sheetName = t.name.replace(/[:\\/?*[\]]/g, " ").slice(0, 31).trim() || "Template";
  const ws = wb.addWorksheet(sheetName, { headerFooter: { oddFooter: `&C${TEMPLATE_FOOTER}` } });

  const title = ws.addRow([titleOf(t)]);
  title.font = { bold: true, size: 16, color: { argb: `FF${BRAND_BLUE}` } };
  ws.addRow([t.purpose]).font = { italic: true, color: { argb: "FF555555" } };
  ws.addRow([]);

  const header = ws.addRow(t.sections);
  header.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: `FF${BRAND_BLUE}` } };
    cell.alignment = { vertical: "middle", wrapText: true };
  });
  t.sections.forEach((section, i) => {
    ws.getColumn(i + 1).width = Math.min(48, Math.max(14, section.length + 4));
  });
  ws.views = [{ state: "frozen", ySplit: header.number }];

  const { bySection, rest } = splitExample(t);
  if (variant === "filled") {
    if (bySection.size > 0) ws.addRow(t.sections.map((s) => bySection.get(norm(s)) ?? "")).alignment = { vertical: "top", wrapText: true };
    if (rest.length > 0) {
      const ex = wb.addWorksheet("Example");
      const h = ex.addRow(["Field", "Value"]);
      h.font = { bold: true, color: { argb: "FFFFFFFF" } };
      h.eachCell((cell) => {
        cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: `FF${BRAND_BLUE}` } };
      });
      for (const r of rest) ex.addRow(r).alignment = { vertical: "top", wrapText: true };
      ex.getColumn(1).width = 28;
      ex.getColumn(2).width = 80;
    }
  }
  ws.addRow([]);
  ws.addRow([TEMPLATE_FOOTER]).font = { size: 9, color: { argb: "FF777777" } };

  const out = await wb.xlsx.writeBuffer();
  return Buffer.from(out as ArrayBuffer);
}

export function buildTemplateFile(t: HandbookTemplate, variant: TemplateVariant): Promise<Buffer> {
  return t.format === "docx" ? buildDocx(t, variant) : buildXlsx(t, variant);
}

// ---------------------------------------------------------------------------
// Admin uploads: DATA_DIR/handbook/<id>.<docx|xlsx>
// ---------------------------------------------------------------------------

export const UPLOAD_MAX_BYTES = 5 * 1024 * 1024;

export function uploadDir(dataDir: string): string {
  return path.join(dataDir, "handbook");
}

/** DOCX and XLSX are both ZIP containers: they start with `PK\x03\x04`. */
export function looksLikeOfficeFile(buf: Buffer): boolean {
  return buf.length >= 4 && buf[0] === 0x50 && buf[1] === 0x4b && buf[2] === 0x03 && buf[3] === 0x04;
}

export function saveUpload(dataDir: string, id: string, format: "docx" | "xlsx", body: Buffer): string {
  const dir = uploadDir(dataDir);
  fs.mkdirSync(dir, { recursive: true });
  const name = `${id}.${format}`;
  fs.writeFileSync(path.join(dir, name), body);
  return name;
}

export function removeUpload(dataDir: string, name: string): void {
  fs.rmSync(path.join(uploadDir(dataDir), path.basename(name)), { force: true });
}

export function readUpload(dataDir: string, name: string): Buffer | null {
  const file = path.join(uploadDir(dataDir), path.basename(name));
  return fs.existsSync(file) ? fs.readFileSync(file) : null;
}
