import type { PracticalOutcomeSeed } from "../../../../shared/goals";

/**
 * v4.3 practical outcomes for the PM department: what an agency PM can visibly do on custom and
 * white-label projects. Levels 1–5 climb on the same skills so a next-level suggestion always exists.
 *
 * Capstones point at the v4.1/v4.2 topics whose practice task already proves the outcome; where no
 * topic fits, the capstone is a task (any `taskSchema` kind). No Oyelabs-specific prices, percentages
 * or durations are stated here; numbers inside tasks are made-up project data.
 */

const topic = (title: string, topicId: string) => ({ kind: "topic" as const, title, topicId });

const RP_RUBRIC = [
  { label: "Clarity", points: 2, description: "Short, plain messages; the main point first; no jargon the client would not know." },
  { label: "Empathy", points: 2, description: "Acknowledges the client's situation and asks about the underlying need before defending a position." },
  { label: "Scope and process held", points: 3, description: "Refers to the signed scope or acceptance criteria as evidence and does not concede free work the contract does not cover." },
  { label: "A clear next step", points: 2, description: "Ends with a concrete next step: who does what, by when." },
];

export default [
  // -------------------------------------------------------------------------
  // Custom lifecycle: BD handover → kickoff → discovery
  // -------------------------------------------------------------------------
  {
    id: "pm-run-bd-handover",
    departmentId: "pm",
    title: "Run a BD-to-delivery handover and log the open questions",
    statement: "Can run the BD-to-delivery handover meeting, check the handover pack against a checklist and write up the open questions and owners before planning starts.",
    skillIds: ["pm-proc-custom", "pm-kickoff", "pm-sow"],
    level: 2,
    aliases: ["bd handover", "sales to delivery handover", "handover pack", "deal handover"],
    capstone: topic("Write the handover note for a newly sold project", "pmp-a01-handover-checklist"),
  },
  {
    id: "pm-read-sow-like-a-pm",
    departmentId: "pm",
    title: "Read a SOW and MSA and sort what each clause commits the team to",
    statement: "Can read a signed SOW and MSA and sort each clause into deliverable, assumption, exclusion, acceptance or commercial term before the plan is made.",
    skillIds: ["pm-sow", "pm-proc-custom", "pm-contract-management"],
    level: 3,
    aliases: ["read a sow", "sow review", "msa review", "contract reading"],
    capstone: topic("Sort the clauses of a real SOW extract", "pmp-a01-reading-sow"),
  },
  {
    id: "pm-flag-risky-assumptions",
    departmentId: "pm",
    title: "Spot the risky assumptions in a sold deal before committing a plan",
    statement: "Can review a proposal, estimate and SOW and mark the assumptions that will break the date or budget, then raise them in the RAID log before the team commits.",
    skillIds: ["pm-sow", "pm-risk-management", "pm-proc-custom"],
    level: 4,
    aliases: ["risky assumptions", "assumption review", "pre-commit review", "deal risks"],
    capstone: topic("Find the assumptions that will hurt this project", "pmp-a01-risky-assumptions"),
  },
  {
    id: "pm-run-internal-kickoff",
    departmentId: "pm",
    title: "Run the internal kickoff and leave with a plan, risks and environments",
    statement: "Can run the internal kickoff with the tech lead, designers and QA and record the plan, risk register, environments and owners in the MoM.",
    skillIds: ["pm-kickoff", "pm-proc-custom", "pm-proc-meetings"],
    level: 2,
    aliases: ["internal kickoff", "team kickoff", "project kickoff internal"],
    capstone: topic("Write the internal kickoff minutes", "pmp-d01-internal-kickoff"),
  },
  {
    id: "pm-run-client-kickoff",
    departmentId: "pm",
    title: "Run a client kickoff call with the agreed agenda",
    statement: "Can run the client kickoff call: introduce the team, agree the SPOC, cadence, tools and next steps, and capture them on the kickoff template.",
    skillIds: ["pm-kickoff", "pm-proc-meetings", "pm-client-meetings"],
    level: 2,
    aliases: ["client kickoff", "kickoff call", "kickoff meeting", "project kickoff"],
    capstone: topic("Fill the client kickoff record", "pmp-a04-client-kickoff"),
  },
  {
    id: "pm-set-governance-at-kickoff",
    departmentId: "pm",
    title: "Set expectations and governance with a new client",
    statement: "Can write the governance a client agrees at kickoff: status cadence, sign-off owners, CR route, escalation path and what the client must supply by when.",
    skillIds: ["pm-kickoff", "pm-expectation-management", "pm-client-management"],
    level: 3,
    aliases: ["governance", "set expectations", "client ground rules", "ways of working"],
    capstone: topic("Write the governance and expectations note", "pmp-a04-expectations-governance"),
  },
  {
    id: "pm-run-discovery",
    departmentId: "pm",
    title: "Run discovery and sort what the client said into requirements",
    statement: "Can run a discovery workshop and sort the client's statements into requirements, assumptions, open questions and out-of-scope items.",
    skillIds: ["pm-requirements-gathering", "pm-workshops", "pm-proc-custom"],
    level: 2,
    aliases: ["discovery", "requirements workshop", "discovery workshop", "requirement gathering"],
    capstone: topic("Sort the notes from a discovery session", "pmp-a05-discovery"),
  },
  {
    id: "pm-get-discovery-signoff",
    departmentId: "pm",
    title: "Get written discovery and requirements sign-off",
    statement: "Can prepare the requirement sign-off document, walk the client through it and record who signed what version, so the baseline for CRs exists.",
    skillIds: ["pm-requirements-gathering", "pm-proc-templates", "pm-proc-custom"],
    level: 3,
    aliases: ["requirement sign-off", "discovery sign-off", "srs sign-off", "baseline sign-off"],
    capstone: topic("Complete the requirement sign-off template", "pmp-e01-requirement-signoff"),
  },
  {
    id: "pm-freeze-requirements",
    departmentId: "pm",
    title: "Freeze requirements and handle late asks after sign-off",
    statement: "Can declare a requirements freeze, record the signed version and route every later ask through the CR process without losing the client's goodwill.",
    skillIds: ["pm-requirements-gathering", "pm-scope-control", "pm-proc-custom"],
    level: 4,
    aliases: ["requirement freeze", "scope freeze", "late requirements"],
    capstone: topic("Record the freeze and sign-off", "pmp-a05-freeze-signoff"),
  },
  {
    id: "pm-write-user-stories",
    departmentId: "pm",
    title: "Write user stories with testable acceptance criteria",
    statement: "Can write user stories in the as-a / I-want / so-that form with Given-When-Then acceptance criteria that QA can test and the client can sign off.",
    skillIds: ["pm-user-stories", "pm-acceptance-criteria"],
    level: 2,
    aliases: ["user stories", "acceptance criteria", "gherkin", "write stories"],
    capstone: topic("Write stories and acceptance criteria for a feature", "pm-b-user-stories-acceptance-criteria"),
  },
  {
    id: "pm-review-stories-for-gaps",
    departmentId: "pm",
    title: "Review a backlog and catch weak stories before the sprint",
    statement: "Can review a set of user stories and mark the ones with vague, untestable or missing acceptance criteria before they enter a sprint.",
    skillIds: ["pm-user-stories", "pm-acceptance-criteria", "pm-backlog-refinement"],
    level: 3,
    aliases: ["story review", "backlog review", "definition of ready check"],
    capstone: topic("Spot the weak stories", "pmp-a05-stories-acceptance"),
  },
  {
    id: "pm-manage-design-rounds",
    departmentId: "pm",
    title: "Manage design review rounds to an approved UI",
    statement: "Can run design reviews with the client, keep feedback inside the agreed revision rounds and record the approved screens before development starts.",
    skillIds: ["pm-proc-custom", "pm-client-management", "pm-scope-control"],
    level: 3,
    aliases: ["design approval", "design revisions", "ui sign-off", "figma review"],
    capstone: topic("Spot the problems in a design review thread", "pmp-a06-review-rounds"),
  },
  {
    id: "pm-run-sprint-zero",
    departmentId: "pm",
    title: "Run Sprint 0: repos, environments, CI and backlog ready",
    statement: "Can run Sprint 0 and check that repos, environments, CI, access and a ready backlog exist before Sprint 1 starts.",
    skillIds: ["pm-environments", "pm-sdlc", "pm-proc-custom"],
    level: 3,
    aliases: ["sprint 0", "sprint zero", "project setup", "environment setup"],
    capstone: topic("Spot what Sprint 0 missed", "pmp-a07-sprint0"),
  },

  // -------------------------------------------------------------------------
  // Sprint execution
  // -------------------------------------------------------------------------
  {
    id: "pm-run-standup-eod",
    departmentId: "pm",
    title: "Run a daily stand-up and send the EOD update",
    statement: "Can run a fifteen-minute stand-up, pull out blockers and owners, and send the end-of-day update the client and team expect.",
    skillIds: ["pm-standups", "pm-proc-custom", "pm-ms-teams"],
    level: 1,
    aliases: ["standup", "daily scrum", "eod update", "end of day report"],
    capstone: topic("Write the EOD update from a stand-up", "pmp-a08-eod-updates"),
  },
  {
    id: "pm-compute-sprint-capacity",
    departmentId: "pm",
    title: "Calculate a team's sprint capacity from leave and focus hours",
    statement: "Can calculate the available person-days and focus hours for a sprint from each person's leave, so the sprint commitment matches real capacity.",
    skillIds: ["pm-velocity-capacity", "pm-sprint-planning"],
    level: 2,
    aliases: ["sprint capacity", "capacity calculation", "availability", "focus hours"],
    capstone: {
      kind: "task",
      title: "Work out Sprint 6's capacity",
      task: {
        kind: "calculate",
        prompt:
          "Sprint 6 of a food-delivery app is 10 working days. The table shows each developer's leave in the sprint and the focus hours per day the team agreed (time actually spent on sprint work, after meetings and support). Calculate the available person-days and the total focus hours for the sprint.",
        table: {
          columns: ["Developer", "Sprint days", "Leave days", "Focus hours per day"],
          rows: [
            ["Asha (Flutter)", "10", "0", "6"],
            ["Ravi (Laravel)", "10", "2", "6"],
            ["Meera (React)", "10", "0", "6"],
            ["Karan (QA)", "10", "1", "6"],
          ],
        },
        fields: [
          {
            id: "personDays",
            label: "Available person-days",
            unit: "days",
            answer: 37,
            tolerance: 0,
            expression: "(T[0][1]-T[0][2]) + (T[1][1]-T[1][2]) + (T[2][1]-T[2][2]) + (T[3][1]-T[3][2])",
          },
          {
            id: "focusHours",
            label: "Total focus hours",
            unit: "h",
            answer: 222,
            tolerance: 0,
            expression: "(T[0][1]-T[0][2])*T[0][3] + (T[1][1]-T[1][2])*T[1][3] + (T[2][1]-T[2][2])*T[2][3] + (T[3][1]-T[3][2])*T[3][3]",
          },
        ],
        explanation:
          "Subtract leave from the sprint days for each person (10 + 8 + 10 + 9 = 37 person-days), then multiply each person's available days by the focus hours (37 × 6 = 222 h). Planning against 4 × 10 × 8 = 320 h would over-commit the sprint by about a third.",
      },
    },
  },
  {
    id: "pm-plan-a-sprint",
    departmentId: "pm",
    title: "Plan a sprint against real capacity and a clear sprint goal",
    statement: "Can run sprint planning: set a sprint goal, pull ready stories up to the team's real capacity and record what was left out and why.",
    skillIds: ["pm-sprint-planning", "pm-velocity-capacity", "pm-estimation"],
    level: 3,
    aliases: ["sprint planning", "plan the sprint", "sprint goal", "sprint commitment"],
    capstone: topic("Fill the sprint planning record", "pmp-d02-sprint-planning"),
  },
  {
    id: "pm-run-sprint-demo",
    departmentId: "pm",
    title: "Run a sprint demo and capture the client's feedback",
    statement: "Can run a sprint demo on staging, capture each piece of client feedback and tag it as accepted, bug, enhancement or CR in the follow-up.",
    skillIds: ["pm-client-meetings", "pm-proc-meetings", "pm-scrum-events"],
    level: 3,
    aliases: ["sprint demo", "sprint review", "client demo", "demo feedback"],
    capstone: topic("Record the feedback from a sprint demo", "pmp-a08-demos-feedback"),
  },
  {
    id: "pm-handle-demo-pushback",
    departmentId: "pm",
    title: "Handle a client demo that turns into new asks",
    statement: "Can keep a live client demo on track when the client starts adding requests, acknowledging each one and routing it without promising it.",
    skillIds: ["pm-client-meetings", "pm-proc-meetings", "pm-expectation-management"],
    level: 4,
    aliases: ["demo goes wrong", "difficult demo", "demo pushback"],
    capstone: topic("Run the sprint review conversation", "pmp-d02-sprint-demo"),
  },

  // -------------------------------------------------------------------------
  // Scope control: bug vs enhancement vs CR
  // -------------------------------------------------------------------------
  {
    id: "pm-classify-requests",
    departmentId: "pm",
    title: "Sort incoming client requests into bug, enhancement and CR",
    statement: "Can classify each incoming client request as bug, enhancement, change request, new feature or clarification using the signed scope as evidence.",
    skillIds: ["pm-proc-terms", "pm-change-requests"],
    level: 2,
    aliases: ["bug or cr", "classify requests", "request triage", "is it a bug"],
    capstone: topic("Classify a batch of client requests", "pmp-a09-classifying-requests"),
  },
  {
    id: "pm-classify-and-raise-cr",
    departmentId: "pm",
    title: "Classify a client request as bug, enhancement or CR and raise a CR",
    statement: "Can classify a client request against the signed scope as bug, enhancement or CR and, when it is a CR, raise it on the CR form with impact, effort, new date and approver.",
    skillIds: ["pm-change-requests", "pm-proc-terms", "pm-scope-control", "pm-proc-templates"],
    level: 3,
    aliases: ["raise a cr", "change request", "cr form", "bug vs cr", "scope change"],
    capstone: {
      kind: "task",
      title: "Classify the request and raise CR-006",
      task: {
        kind: "form",
        variant: "cr",
        templateId: "cr-form",
        prompt:
          "Decide whether the client's ask is a bug, an enhancement or a change request, then fill the CR form as you would before sending it for approval. Do not invent a price: state the pricing basis.",
        context: `**Client email (Head of Operations), 6 October:**

> The booking screen only lets members pick one class at a time. Our members want to book a whole week of classes in one go. Please fix this before launch, it feels like a bug.

**Signed requirements v1.2, section 4.1:** "A member books one class per booking. Each booking shows the class, time and studio."

**Acceptance criteria 4.1 (signed):** booking one class works on iOS and Android and the admin panel shows it. All passed QA.

**Tech lead note:** multi-select calendar, batch booking API, partial-failure handling, admin view. Dev 4 days, QA 1.5 days, PM 0.5 day. The UAT drop on **3 November** moves one week.

**SOW section 8:** CRs are approved in writing by the client's Managing Director. The CR register's last entry is CR-005. Pricing per the rate card in Annex B.`,
        fields: [
          { id: "crId", label: "CR ID", input: "text", required: true },
          {
            id: "classification",
            label: "Classification",
            input: "select",
            options: ["Bug", "Enhancement", "Change request", "New feature", "Clarification"],
            required: true,
          },
          { id: "evidence", label: "Why this classification (cite the baseline)", input: "textarea", required: true },
          { id: "description", label: "Description of the change", input: "textarea", required: true },
          { id: "impact", label: "Impact on scope, apps and testing", input: "textarea", required: true },
          { id: "effortDays", label: "Total effort (days)", input: "number", required: true },
          { id: "newUatDate", label: "New UAT drop date", input: "date", required: true },
          { id: "cost", label: "Cost basis and payment", input: "textarea", required: true },
          {
            id: "approver",
            label: "Approver",
            input: "select",
            options: ["Head of Operations", "Managing Director", "Oyelabs PM", "Oyelabs account manager"],
            required: true,
          },
        ],
        checks: [
          { fieldId: "crId", expected: "CR-006" },
          { fieldId: "classification", expected: "Change request" },
          { fieldId: "effortDays", expected: 6 },
          { fieldId: "newUatDate", expected: "2026-11-10" },
          { fieldId: "approver", expected: "Managing Director" },
        ],
        rubric: [
          {
            label: "Classification is justified by the baseline",
            points: 2,
            description: "Cites requirement 4.1 and its passed acceptance criteria: one class per booking was specified and works, so multi-class booking changes agreed behaviour and is a CR, not a bug.",
          },
          {
            label: "Impact is complete",
            points: 2,
            description: "Covers the multi-select calendar, batch booking API, partial-failure handling, admin view, both apps and regression testing, with effort by role.",
          },
          {
            label: "Commercials and approval are correct",
            points: 2,
            description: "Prices per the Annex B rate card without inventing a figure, names the Managing Director as approver and says work starts only after written approval.",
          },
        ],
        sampleAnswer: {
          crId: "CR-006",
          classification: "Change request",
          evidence: "Signed requirement 4.1 says a member books one class per booking, and acceptance criteria 4.1 passed QA. The app does what was agreed, so booking several classes at once is a change to agreed behaviour, not a bug.",
          description: "Let a member select several classes in a week view and book them in one action, with a summary of what was booked and what failed.",
          impact: "New multi-select calendar in the iOS and Android apps, a batch booking API with partial-failure handling, an admin view of batch bookings, and regression of single booking and payments. Dev 4 days, QA 1.5 days, PM 0.5 day.",
          effortDays: "6",
          newUatDate: "2026-11-10",
          cost: "6 days priced per the SOW rate card (Annex B), invoiced with the UAT milestone after written approval.",
          approver: "Managing Director",
        },
      },
    },
  },
  {
    id: "pm-hold-the-line-bug-vs-cr",
    departmentId: "pm",
    title: "Hold the line when a client insists a CR is a warranty bug",
    statement: "Can talk a client through why a missing feature is a change request and not a warranty bug, using the signed acceptance criteria, while offering a fast fair path.",
    skillIds: ["pm-proc-terms", "pm-change-requests", "pm-difficult-conversations"],
    level: 4,
    aliases: ["it's a bug not a cr", "warranty dispute", "free fix request", "bug or cr call"],
    capstone: {
      kind: "task",
      title: "This is a bug, not a CR",
      task: {
        kind: "roleplay",
        prompt: "The client says missing SMS reminders are a bug you must fix free under warranty. SMS was never in the signed requirements.",
        scenarioId: "bug-or-cr",
        personaId: "startup-founder",
        maxTurns: 6,
        brief:
          "Acknowledge the business problem first. Check the signed requirements and acceptance criteria with him, explain bug vs enhancement simply and without blame, classify the ask as a change request, offer a fast path (a quick CR, an interim workaround) and agree a next step with a time.",
        rubric: RP_RUBRIC,
        followUp: true,
      },
    },
  },
  {
    id: "pm-say-no-to-scope-creep",
    departmentId: "pm",
    title: "Say no (or not now) to a mid-sprint scope addition",
    statement: "Can respond to a 'small' mid-sprint request by protecting the sprint, explaining the CR route and offering a date, without damaging the relationship.",
    skillIds: ["pm-scope-control", "pm-change-requests", "pm-expectation-management"],
    level: 3,
    aliases: ["scope creep", "say no to client", "mid-sprint change", "one more small thing"],
    capstone: {
      kind: "task",
      title: "Just one more small thing",
      task: {
        kind: "roleplay",
        prompt: "Mid-sprint on a fixed bid, the founder asks for a loyalty-points module before the investor demo and calls it tiny.",
        scenarioId: "scope-creep",
        personaId: "startup-founder",
        maxTurns: 6,
        brief:
          "Find out what the demo really needs before answering. Explain that loyalty points are outside the signed scope and would put the sprint and the milestone at risk, offer options (a CR for a later sprint, a clickable mock for the demo, a trade against another story) and agree the next step.",
        rubric: RP_RUBRIC,
        followUp: false,
      },
    },
  },
  {
    id: "pm-classify-tricky-requests",
    departmentId: "pm",
    title: "Classify tricky requests, including warranty and post-warranty bugs",
    statement: "Can classify a mixed list of twenty requests, telling delivery bugs, warranty bugs, paid support bugs, enhancements, CRs and clarifications apart.",
    skillIds: ["pm-proc-terms", "pm-change-requests", "pm-qa-coordination"],
    level: 4,
    aliases: ["classification drill", "warranty vs support", "request classification"],
    capstone: topic("Classify twenty client requests", "pmp-c08-classification-drill"),
  },
  {
    id: "pm-negotiate-cr-price",
    departmentId: "pm",
    title: "Negotiate a CR when the client pushes back on the price",
    statement: "Can explain what a CR's hours cover, keep the rate card, and reshape the scope into options the client can afford instead of discounting the same work.",
    skillIds: ["pm-change-requests", "pm-proc-meetings", "pm-difficult-conversations"],
    level: 4,
    aliases: ["cr negotiation", "cr pushback", "price objection", "too expensive cr"],
    capstone: topic("Negotiate the CR with the client", "pmp-d03-cr-negotiation"),
  },
  {
    id: "pm-replan-after-change",
    departmentId: "pm",
    title: "Re-plan and re-baseline after an approved change",
    statement: "Can re-plan the remaining sprints after an approved CR, agree the new baseline and milestone dates with the client and update the plan, RAID log and invoices.",
    skillIds: ["pm-change-requests", "pm-scope-control", "pm-schedule-basics"],
    level: 5,
    aliases: ["re-baseline", "replan", "new baseline", "revised plan"],
    capstone: topic("Re-plan with the client after a change", "pmp-a09-replanning"),
  },

  // -------------------------------------------------------------------------
  // QA, UAT and sign-off
  // -------------------------------------------------------------------------
  {
    id: "pm-separate-qa-uat",
    departmentId: "pm",
    title: "Tell QA findings from UAT findings and route each one",
    statement: "Can sort testing activities and findings into internal QA or client UAT and route each to the right owner and board.",
    skillIds: ["pm-uat", "pm-qa-coordination"],
    level: 2,
    aliases: ["qa vs uat", "testing types", "uat basics"],
    capstone: topic("Sort QA and UAT activities", "pmp-a10-qa-vs-uat"),
  },
  {
    id: "pm-triage-severity-priority",
    departmentId: "pm",
    title: "Triage bugs by severity and priority",
    statement: "Can set severity and priority on each reported bug separately and explain why a low-severity bug can still be top priority.",
    skillIds: ["pm-qa-coordination", "pm-proc-terms"],
    level: 3,
    aliases: ["bug triage", "severity vs priority", "p1 p2", "bug priority"],
    capstone: topic("Set severity and priority on reported bugs", "pmp-c04-severity-priority"),
  },
  {
    id: "pm-run-uat-walkthrough",
    departmentId: "pm",
    title: "Run a UAT walkthrough and log the client's findings",
    statement: "Can run a UAT walkthrough with the client's testers, log each finding with steps and classification, and agree the fix-and-retest plan.",
    skillIds: ["pm-uat", "pm-proc-meetings", "pm-qa-coordination"],
    level: 3,
    aliases: ["uat walkthrough", "uat session", "user acceptance testing"],
    capstone: topic("Record the UAT walkthrough", "pmp-d04-uat-walkthrough"),
  },
  {
    id: "pm-get-uat-signoff",
    departmentId: "pm",
    title: "Get UAT sign-off after the client rejects the build",
    statement: "Can turn a UAT rejection into a clean sign-off: separate real defects from new asks, agree the fix list and get written UAT sign-off before go-live.",
    skillIds: ["pm-uat", "pm-proc-custom", "pm-difficult-conversations"],
    level: 4,
    aliases: ["uat sign-off", "uat rejection", "acceptance sign-off", "client rejected uat"],
    capstone: topic("Win back the UAT sign-off", "pmp-a10-uat-signoff"),
  },
  {
    id: "pm-decide-under-uat-pressure",
    departmentId: "pm",
    title: "Decide what to do when UAT finds a critical bug the day before go-live",
    statement: "Can weigh a late critical UAT defect against the go-live date and choose, with the client, between fixing, descoping or moving the date, with evidence.",
    skillIds: ["pm-release-management", "pm-uat", "pm-risk-management"],
    level: 5,
    aliases: ["late critical bug", "go-live risk", "uat blocker"],
    capstone: {
      kind: "task",
      title: "Critical bug, go-live tomorrow",
      task: {
        kind: "scenario",
        prompt:
          "A grocery-delivery app is due to go live tomorrow at 10:00. At 16:00 today the client's UAT tester finds that applying a promo code at checkout charges the full price but shows the discounted total. Promo codes are part of the launch campaign. The tech lead estimates the fix at a few hours plus a regression pass of checkout. UAT sign-off has not been given yet.",
        steps: [
          {
            id: "s1",
            question: "What do you do first?",
            options: [
              "Ship tomorrow as planned and hotfix promo codes next week; the bug is small",
              "Confirm and reproduce the defect with QA, log it as a critical UAT bug, and tell the client's SPOC within the hour with what you know",
              "Ask the developer to fix it tonight and say nothing until it is fixed",
              "Remove promo codes from the app without telling the client",
            ],
            correctIndex: 1,
            explanation: "A charging defect is critical. Confirm it, log it and tell the client early with facts; never ship or descope silently.",
          },
          {
            id: "s2",
            question: "The fix is ready at 22:00 but the checkout regression pass will not finish before 10:00. What do you propose to the client?",
            options: [
              "Go live at 10:00 with the untested fix",
              "Offer options with their risks: move go-live until regression passes, or go live with promo codes switched off by configuration and enable them after a passed retest; the client decides and signs off in writing",
              "Cancel the launch and replan from scratch",
              "Go live and ask customer support to refund any wrong charges",
            ],
            correctIndex: 1,
            explanation: "Give the client real options with their risks and get the decision and the UAT sign-off in writing. Shipping an untested payment change is not an option.",
          },
        ],
      },
    },
  },

  // -------------------------------------------------------------------------
  // Release, go-live and cutover
  // -------------------------------------------------------------------------
  {
    id: "pm-run-go-no-go",
    departmentId: "pm",
    title: "Run a go/no-go meeting and record the decision",
    statement: "Can run a go/no-go meeting against agreed criteria (UAT sign-off, open defects, rollback ready, client readiness) and record the decision and owners.",
    skillIds: ["pm-release-management", "pm-proc-meetings"],
    level: 3,
    aliases: ["go no go", "go/no-go", "launch decision", "release readiness"],
    capstone: topic("Make the go/no-go call", "pmp-d04-go-no-go"),
  },
  {
    id: "pm-prepare-golive-checklist",
    departmentId: "pm",
    title: "Prepare a go-live checklist with owners and times",
    statement: "Can fill a go-live checklist covering DNS, SSL, environment variables, store builds, data migration, smoke tests and client communication, each with an owner.",
    skillIds: ["pm-release-management", "pm-deployment-basics", "pm-proc-templates"],
    level: 3,
    aliases: ["go-live checklist", "launch checklist", "release checklist"],
    capstone: topic("Complete the go-live checklist", "pmp-e03-golive-checklist"),
  },
  {
    id: "pm-plan-cutover-rollback",
    departmentId: "pm",
    title: "Write a cutover and rollback plan for go-live",
    statement: "Can write a timed cutover plan with a rollback trigger, rollback steps and a named decision-maker, and agree the change window with the client.",
    skillIds: ["pm-release-management", "pm-deployment-basics", "pm-proc-custom"],
    level: 4,
    aliases: ["cutover plan", "rollback plan", "go-live plan", "launch runbook"],
    capstone: topic("Write the cutover and rollback plan", "pmp-a11-cutover-rollback"),
  },
  {
    id: "pm-decide-hotfix-vs-release",
    departmentId: "pm",
    title: "Decide between a hotfix and the next release",
    statement: "Can decide whether a live issue needs a hotfix or waits for the next release, and get the approval the process requires.",
    skillIds: ["pm-agency-sdlc", "pm-release-management", "pm-deployment-basics"],
    level: 3,
    aliases: ["hotfix", "hotfix or release", "production fix"],
    capstone: topic("Choose hotfix or release", "pma-hotfix-vs-release"),
  },

  // -------------------------------------------------------------------------
  // Hypercare, handover/KT, support, closure
  // -------------------------------------------------------------------------
  {
    id: "pm-run-hypercare",
    departmentId: "pm",
    title: "Run hypercare after go-live and keep the hypercare log",
    statement: "Can run the hypercare period: log every post-launch issue with severity, owner and status, and report daily to the client until exit criteria are met.",
    skillIds: ["pm-proc-custom", "pm-qa-coordination", "pm-proc-templates"],
    level: 3,
    aliases: ["hypercare", "post go-live support", "hypercare log", "launch support"],
    capstone: topic("Fill the hypercare log", "pmp-e03-hypercare-log"),
  },
  {
    id: "pm-judge-warranty-claims",
    departmentId: "pm",
    title: "Judge warranty claims against the contract",
    statement: "Can decide whether each post-launch claim is covered by warranty, billable support or a CR, citing the contract and the go-live date.",
    skillIds: ["pm-proc-terms", "pm-contract-management", "pm-proc-custom"],
    level: 5,
    aliases: ["warranty claims", "warranty vs support", "free fixes after launch"],
    capstone: topic("Classify warranty claims", "pmp-a12-warranty-claims"),
  },
  {
    id: "pm-run-handover-kt",
    departmentId: "pm",
    title: "Run a handover and knowledge transfer to the client or support team",
    statement: "Can run handover and KT with a checklist: documentation, repos, credentials, environments, open issues and recorded walkthrough sessions, with sign-off.",
    skillIds: ["pm-proc-custom", "pm-proc-templates", "pm-documentation-tools"],
    level: 3,
    aliases: ["handover", "knowledge transfer", "kt session", "project handover"],
    capstone: topic("Complete the handover and KT checklist", "pmp-e03-handover-kt"),
  },
  {
    id: "pm-transfer-ownership-securely",
    departmentId: "pm",
    title: "Transfer accounts, code and credentials securely at handover",
    statement: "Can plan the transfer of repos, cloud, store and domain ownership and credentials to the client through secure channels, and catch unsafe practices in a handover plan.",
    skillIds: ["pm-proc-custom", "pm-client-management", "pm-github-for-pms"],
    level: 4,
    aliases: ["credential handover", "ownership transfer", "transfer repo", "account transfer"],
    capstone: topic("Spot the unsafe steps in a handover plan", "pmp-a13-ownership-credentials"),
  },
  {
    id: "pm-set-up-support-model",
    departmentId: "pm",
    title: "Set up a support model with levels and SLAs",
    statement: "Can match client issues to support levels and SLAs (response vs resolution time) and explain which support model fits the client.",
    skillIds: ["pm-commercial-retainer", "pm-proc-terms", "pm-agency-sdlc"],
    level: 3,
    aliases: ["support sla", "support model", "amc", "maintenance contract"],
    capstone: topic("Sort issues into support levels", "pmp-a14-support-models"),
  },
  {
    id: "pm-calculate-sla-tat",
    departmentId: "pm",
    title: "Calculate SLA response, resolution and TAT from a ticket log",
    statement: "Can calculate response time, resolution time and turnaround for tickets and say which ones breached the SLA.",
    skillIds: ["pm-proc-terms", "pm-qa-coordination", "pm-commercial-retainer"],
    level: 4,
    aliases: ["sla breach", "tat", "response time", "resolution time"],
    capstone: topic("Work out SLA times from a ticket log", "pmp-c04-response-resolution-tat"),
  },
  {
    id: "pm-close-a-project",
    departmentId: "pm",
    title: "Close a project with a retrospective and a closure report",
    statement: "Can run the closure retrospective and fill the project closure report: delivered vs planned, open items, lessons and final sign-off.",
    skillIds: ["pm-proc-custom", "pm-retrospectives", "pm-proc-templates"],
    level: 3,
    aliases: ["project closure", "closure report", "close project", "post mortem"],
    capstone: topic("Fill the project closure report", "pmp-e03-closure-report"),
  },
  {
    id: "pm-turn-closure-into-upsell",
    departmentId: "pm",
    title: "Turn a closed project into a case study and the next engagement",
    statement: "Can write the client-approved case study request and propose a sensible next phase or support plan after closure.",
    skillIds: ["pm-client-management", "pm-proc-custom", "pm-email-etiquette"],
    level: 4,
    aliases: ["upsell", "case study", "next phase", "account growth"],
    capstone: topic("Write the case-study and next-phase email", "pmp-a15-case-study-upsell"),
  },

  // -------------------------------------------------------------------------
  // White-label lifecycle
  // -------------------------------------------------------------------------
  {
    id: "pm-explain-white-label",
    departmentId: "pm",
    title: "Tell the core product from the client's white-label instance",
    statement: "Can sort the parts of a white-label project into core product and client instance and explain to a client what that means for changes.",
    skillIds: ["pm-proc-whitelabel"],
    level: 1,
    aliases: ["white label", "white-label basics", "core vs instance", "whitelabel"],
    capstone: topic("Sort core product vs client instance", "pmp-b01-core-vs-instance"),
  },
  {
    id: "pm-run-wl-demo-call",
    departmentId: "pm",
    title: "Run a white-label product demo and requirement call",
    statement: "Can demo the core product, capture the client's requirements against it and record what is standard, configurable or custom in the call notes.",
    skillIds: ["pm-proc-whitelabel", "pm-proc-meetings", "pm-client-meetings"],
    level: 2,
    aliases: ["white-label demo", "product demo call", "requirement call"],
    capstone: topic("Record the white-label demo call", "pmp-b02-demo-call"),
  },
  {
    id: "pm-run-wl-gap-analysis",
    departmentId: "pm",
    title: "Run a white-label gap analysis",
    statement: "Can classify each client ask on a white-label project as out of the box, configuration, customisation or new feature, so the gaps can be estimated and billed.",
    skillIds: ["pm-proc-whitelabel", "pm-requirements-gathering", "pm-scope-control"],
    level: 3,
    aliases: ["gap analysis", "fit gap", "ootb vs custom", "white-label gaps"],
    capstone: {
      kind: "task",
      title: "Sort a reseller's asks into the gap analysis",
      task: {
        kind: "categorize",
        mode: "gap-analysis",
        prompt:
          "A reseller is launching the white-label taxi app for a client in a new city. The core product supports rider and driver apps, an admin panel, card and cash payments, promo codes, per-city fares, and configurable branding and languages. Put each ask in the right bucket.",
        categories: [
          { id: "ootb", label: "Out of the box" },
          { id: "configuration", label: "Configuration" },
          { id: "customisation", label: "Customisation" },
          { id: "new-feature", label: "New feature" },
        ],
        items: [
          { id: "i1", text: "Riders can pay by card or cash.", explanation: "Already in the core product, unchanged." },
          { id: "i2", text: "Use the client's logo, colours and app name.", explanation: "Branding is set through configuration, not code." },
          { id: "i3", text: "Set base fare and per-km rate for the new city.", explanation: "Per-city fares are an admin setting." },
          { id: "i4", text: "Add Arabic as an app language using the existing language system.", explanation: "Languages are configurable; translations are supplied, no code change." },
          { id: "i5", text: "Change the driver rating screen to ask three questions instead of one star score.", explanation: "Modifies an existing core screen for this client only: customisation." },
          { id: "i6", text: "Integrate the client's corporate-account billing system so companies get one monthly invoice.", explanation: "Functionality the core does not have at all: new feature." },
          { id: "i7", text: "Promo codes for the launch week.", explanation: "Promo codes exist in the core; creating them is normal admin use." },
          { id: "i8", text: "Move the fare estimate above the map on the booking screen for this client.", explanation: "A client-specific code change to an existing screen: customisation." },
        ],
        answer: { i1: "ootb", i2: "configuration", i3: "configuration", i4: "configuration", i5: "customisation", i6: "new-feature", i7: "ootb", i8: "customisation" },
      },
    },
  },
  {
    id: "pm-price-wl-gaps",
    departmentId: "pm",
    title: "Estimate and bill the gaps from a white-label gap analysis",
    statement: "Can turn a gap analysis into estimated effort per gap and a billing summary, separating licence, configuration and paid customisation.",
    skillIds: ["pm-proc-whitelabel", "pm-estimation", "pm-commercial-fixed-bid"],
    level: 4,
    aliases: ["gap estimate", "price customisation", "white-label quote"],
    capstone: topic("Estimate and bill the gaps", "pmp-b03-estimating-billing-gaps"),
  },
  {
    id: "pm-stop-customisation-creep",
    departmentId: "pm",
    title: "Stop customisation creep on a white-label client",
    statement: "Can spot when white-label asks are drifting from configuration into customisation and steer them back to configuration or a priced CR.",
    skillIds: ["pm-proc-whitelabel", "pm-scope-control", "pm-change-requests"],
    level: 5,
    aliases: ["customisation creep", "too much custom", "white-label scope creep"],
    capstone: topic("Classify asks that creep into customisation", "pmp-b03-avoiding-custom-creep"),
  },
  {
    id: "pm-collect-brand-kit",
    departmentId: "pm",
    title: "Collect a complete brand kit from a white-label client",
    statement: "Can request and check a client's brand kit (logos, icons, colours, fonts, splash, store screenshots copy) and catch what is missing or in the wrong format.",
    skillIds: ["pm-proc-whitelabel", "pm-client-management"],
    level: 2,
    aliases: ["brand kit", "brand assets", "logo and colours", "branding checklist"],
    capstone: topic("Spot the problems in a submitted brand kit", "pmp-b04-brand-kit"),
  },
  {
    id: "pm-collect-client-accounts",
    departmentId: "pm",
    title: "Collect the client-owned store, cloud and domain accounts",
    statement: "Can get the client to create and own their Apple, Google Play, cloud and domain accounts and grant the team access, recorded on the onboarding form.",
    skillIds: ["pm-proc-whitelabel", "pm-client-management", "pm-proc-templates"],
    level: 3,
    aliases: ["client accounts", "developer accounts", "apple developer account", "play console access"],
    capstone: topic("Fill the developer-account onboarding form", "pmp-b05-store-developer-accounts"),
  },
  {
    id: "pm-unblock-missing-store-account",
    departmentId: "pm",
    title: "Unblock a launch when the client has no store account",
    statement: "Can explain to a white-label client why the store account must be theirs, what it takes to create it and how the launch date moves, without taking ownership on their behalf.",
    skillIds: ["pm-proc-whitelabel", "pm-client-management", "pm-difficult-conversations"],
    level: 4,
    aliases: ["missing store account", "account ownership", "who owns the app store account"],
    capstone: topic("Talk the client through account ownership", "pmp-b05-accounts-ownership"),
  },
  {
    id: "pm-onboard-wl-client",
    departmentId: "pm",
    title: "Onboard a white-label client with the onboarding checklist",
    statement: "Can run a new white-label client through the onboarding checklist: licence, brand kit, accounts, configuration values and launch plan.",
    skillIds: ["pm-proc-whitelabel", "pm-proc-templates"],
    level: 2,
    aliases: ["white-label onboarding", "client onboarding checklist"],
    capstone: topic("Complete the white-label onboarding checklist", "pmp-e03-whitelabel-onboarding"),
  },
  {
    id: "pm-submit-to-stores",
    departmentId: "pm",
    title: "Submit a rebranded app to the App Store and Google Play",
    statement: "Can sequence the store submission steps for a rebranded app, from listing assets and privacy declarations to review and release.",
    skillIds: ["pm-proc-whitelabel", "pm-release-management"],
    level: 3,
    aliases: ["store submission", "app store submission", "play store release", "publish app"],
    capstone: topic("Order the store submission steps", "pmp-b09-submission"),
  },
  {
    id: "pm-handle-store-rejection",
    departmentId: "pm",
    title: "Handle an App Store rejection and resubmit",
    statement: "Can read a store rejection (including 4.2.6 template/spam), agree the fix with the client, decide who pays for it and resubmit with a clear reply to review.",
    skillIds: ["pm-proc-whitelabel", "pm-release-management", "pm-client-management"],
    level: 5,
    aliases: ["app rejected", "store rejection", "4.2.6", "resubmission"],
    capstone: topic("Handle the rejection with the client", "pmp-b09-rejections"),
  },
  {
    id: "pm-sync-core-upgrades",
    departmentId: "pm",
    title: "Plan a core product upgrade across white-label client instances",
    statement: "Can decide which client instances take a core upgrade as-is, need customisation rework or need a CR, and plan the rollout.",
    skillIds: ["pm-proc-whitelabel", "pm-release-management", "pm-technical-tradeoffs"],
    level: 4,
    aliases: ["core upgrade", "version sync", "white-label upgrade"],
    capstone: topic("Classify instances for a core upgrade", "pmp-b11-version-sync"),
  },
  {
    id: "pm-run-wl-portfolio",
    departmentId: "pm",
    title: "Run many white-label clients with templates and automation",
    statement: "Can set up the templates, checklists and board automation that let one PM run several white-label launches without missed steps.",
    skillIds: ["pm-proc-whitelabel", "pm-multi-project", "pm-tool-automation"],
    level: 5,
    aliases: ["white-label portfolio", "many clients", "launch templates"],
    capstone: topic("Design the white-label portfolio template", "pmp-b12-portfolio-templates"),
  },

  // -------------------------------------------------------------------------
  // Meetings
  // -------------------------------------------------------------------------
  {
    id: "pm-write-mom",
    departmentId: "pm",
    title: "Write minutes of meeting with decisions and actions",
    statement: "Can write a MoM that lists attendees, decisions, action items with owners and dates, and open questions, ready to send the same day.",
    skillIds: ["pm-meeting-facilitation", "pm-proc-templates"],
    level: 2,
    aliases: ["mom", "minutes of meeting", "meeting minutes", "meeting notes"],
    capstone: topic("Fill the MoM template from a meeting", "pmp-e02-mom"),
  },
  {
    id: "pm-weekly-status-call-mom",
    departmentId: "pm",
    title: "Run a weekly client status call and send the MoM",
    statement: "Can run the weekly client status call (done, next, risks, decisions), set an honest RAG status, and send the MoM with owners and dates within a day.",
    skillIds: ["pm-proc-meetings", "pm-meeting-facilitation", "pm-status-reporting", "pm-client-meetings"],
    level: 3,
    aliases: ["weekly status call", "status meeting", "client update call", "weekly mom", "status call minutes"],
    capstone: {
      kind: "task",
      title: "Send the MoM for this week's status call",
      task: {
        kind: "form",
        variant: "mom",
        templateId: "mom",
        prompt:
          "You ran the weekly status call for a clinic-booking app. Write the MoM from the call notes. Set the overall RAG status honestly and give every action an owner and a date.",
        context: `**Weekly status call, Tuesday 13 October, 30 min (Teams).**
Client: Dr. Lina (Product Owner), Omar (IT). Oyelabs: you (PM), Vikram (tech lead).

- Done: patient sign-up and appointment booking are on staging. Admin calendar is 80% done.
- Risk: the SMS gateway credentials promised by Omar for 9 October have still not arrived. Without them, OTP login cannot be tested; the UAT drop on **30 October** is at risk if they slip past Friday.
- Decision: Dr. Lina agreed to drop the "reschedule by WhatsApp" idea from this release.
- Decision: UAT testers will be Dr. Lina and two receptionists.
- Action: Omar to send SMS gateway credentials by Friday 16 October.
- Action: Vikram to share the staging test accounts with the testers by Thursday 15 October.
- Next call: Tuesday **20 October**, same time.`,
        fields: [
          { id: "attendees", label: "Attendees", input: "textarea", required: true },
          {
            id: "rag",
            label: "Overall RAG status",
            input: "select",
            options: ["Green", "Amber", "Red"],
            required: true,
          },
          { id: "progress", label: "Progress since last call", input: "textarea", required: true },
          { id: "risks", label: "Risks and issues", input: "textarea", required: true },
          { id: "decisions", label: "Decisions", input: "textarea", required: true },
          { id: "actions", label: "Action items (owner, date)", input: "textarea", required: true },
          { id: "actionCount", label: "Number of action items", input: "number", required: true },
          { id: "nextCall", label: "Next call", input: "date", required: true },
        ],
        checks: [
          { fieldId: "rag", expected: "Amber" },
          { fieldId: "actionCount", expected: 2 },
          { fieldId: "nextCall", expected: "2026-10-20" },
        ],
        rubric: [
          {
            label: "Risk stated with its consequence",
            points: 2,
            description: "States that the SMS credentials are late (due 9 October), what they block (OTP login testing) and that the 30 October UAT drop is at risk if they slip past Friday.",
          },
          {
            label: "Decisions and actions are unambiguous",
            points: 2,
            description: "Records both decisions as decisions, and each action with one owner and a date; nothing vague like 'team to check'.",
          },
          {
            label: "Client-ready tone",
            points: 1,
            description: "Short, factual, no blame; a reader who missed the call understands it in a minute.",
          },
        ],
        sampleAnswer: {
          attendees: "Client: Dr. Lina (Product Owner), Omar (IT). Oyelabs: PM, Vikram (tech lead).",
          rag: "Amber",
          progress: "Patient sign-up and appointment booking are on staging. Admin calendar is about 80% done.",
          risks: "SMS gateway credentials (due 9 October) have not arrived. OTP login cannot be tested without them. If they arrive after Friday 16 October, the 30 October UAT drop is at risk.",
          decisions: "1. 'Reschedule by WhatsApp' is out of this release. 2. UAT testers: Dr. Lina and two receptionists.",
          actions: "1. Omar: send SMS gateway credentials by Fri 16 Oct. 2. Vikram: share staging test accounts with the testers by Thu 15 Oct.",
          actionCount: "2",
          nextCall: "2026-10-20",
        },
      },
    },
  },
  {
    id: "pm-send-mom-follow-up",
    departmentId: "pm",
    title: "Send the MoM and follow-up email within 24 hours",
    statement: "Can turn a messy meeting into a MoM email sent within a day that the client can act on, with decisions, owners and dates.",
    skillIds: ["pm-meeting-facilitation", "pm-email-etiquette", "pm-client-meetings"],
    level: 4,
    aliases: ["mom email", "meeting follow-up", "follow up email"],
    capstone: topic("Write the MoM follow-up email", "pma-mom-follow-up-24h"),
  },
  {
    id: "pm-timebox-and-get-decisions",
    departmentId: "pm",
    title: "Timebox a client meeting and leave with decisions",
    statement: "Can keep a client meeting to its agenda and time, park side topics and close with recorded decisions and action items.",
    skillIds: ["pm-meeting-facilitation", "pm-proc-meetings", "pm-client-meetings"],
    level: 3,
    aliases: ["timebox", "run meetings", "get decisions", "meeting control"],
    capstone: topic("Get decisions inside the timebox", "pmp-d05-craft-timebox-decisions"),
  },
  {
    id: "pm-handle-tough-questions",
    departmentId: "pm",
    title: "Handle tough client questions in an update meeting",
    statement: "Can answer hard client questions in a meeting honestly, without guessing dates or blaming the team, and follow up with facts.",
    skillIds: ["pm-client-meetings", "pm-expectation-management"],
    level: 4,
    aliases: ["tough questions", "difficult client questions", "hostile meeting"],
    capstone: topic("Answer the hard questions", "pma-tough-questions"),
  },
  {
    id: "pm-write-bad-news-email",
    departmentId: "pm",
    title: "Write an early bad-news email about a slip",
    statement: "Can write a short email that gives bad news early: what slipped, why, the new date and what it depends on, and the options.",
    skillIds: ["pm-difficult-conversations", "pm-email-etiquette", "pm-expectation-management"],
    level: 3,
    aliases: ["bad news email", "delay email", "slip notice"],
    capstone: topic("Write the bad-news email", "pma-bad-news-early"),
  },
  {
    id: "pm-deliver-bad-news-call",
    departmentId: "pm",
    title: "Tell a client on a call that the release will slip",
    statement: "Can give a delay in the first minute of a call, explain the causes without blame, offer options and agree how the revised plan reaches the client in writing.",
    skillIds: ["pm-difficult-conversations", "pm-proc-meetings", "pm-expectation-management"],
    level: 4,
    aliases: ["bad news call", "delay call", "release slips", "tell client about delay"],
    capstone: topic("Tell the client the release slips", "pmp-d03-bad-news-delay"),
  },
  {
    id: "pm-use-escalation-matrix",
    departmentId: "pm",
    title: "Escalate through the escalation matrix at the right level",
    statement: "Can decide when an issue must be escalated, to which level and by when, and record it on the escalation matrix.",
    skillIds: ["pm-escalations", "pm-proc-templates"],
    level: 3,
    aliases: ["escalation matrix", "when to escalate", "escalation levels"],
    capstone: topic("Fill the escalation matrix", "pmp-c06-escalation-matrix"),
  },
  {
    id: "pm-handle-unhappy-escalation",
    departmentId: "pm",
    title: "Handle an escalation from an unhappy client",
    statement: "Can take an escalation call from an angry client, find the real concern, own Oyelabs' part, agree a recovery plan and confirm it in writing.",
    skillIds: ["pm-escalations", "pm-difficult-conversations", "pm-client-management"],
    level: 5,
    aliases: ["client escalation", "angry client", "unhappy client", "recovery call"],
    capstone: topic("Handle the escalation with the client", "pmp-d03-unhappy-escalation"),
  },
  {
    id: "pm-run-account-review",
    departmentId: "pm",
    title: "Run a quarterly account review with a client",
    statement: "Can run a quarterly business review: delivery against plan, satisfaction, open risks and the next quarter's priorities, with decisions recorded.",
    skillIds: ["pm-client-management", "pm-proc-meetings", "pm-value-realisation"],
    level: 5,
    aliases: ["qbr", "account review", "quarterly review", "business review"],
    capstone: topic("Run the account review", "pmp-d04-account-review"),
  },

  // -------------------------------------------------------------------------
  // Templates: RAG status, RAID log
  // -------------------------------------------------------------------------
  {
    id: "pm-write-rag-status-email",
    departmentId: "pm",
    title: "Write a weekly RAG status email to the client",
    statement: "Can write a weekly status email with an honest RAG, what was done, what is next, risks with owners and the decisions needed from the client.",
    skillIds: ["pm-status-reporting", "pm-email-etiquette", "pm-client-communication"],
    level: 2,
    aliases: ["status email", "weekly status", "rag email", "client update email"],
    capstone: {
      kind: "task",
      title: "Write this week's status email",
      task: {
        kind: "write",
        variant: "email",
        prompt:
          "Write this week's status email to the client's product owner from the facts below. Give an overall RAG status, done, next, risks and the one decision you need from her.",
        context:
          "Project: e-commerce app (iOS, Android, admin panel), Sprint 4 of 6.\nDone: product listing, cart and wishlist on staging; 11 of 14 Sprint 4 stories closed.\nNext: checkout and order history in Sprint 5.\nRisk: the payment gateway's sandbox keys were requested from the client on 1 October and have not arrived; checkout development starts Monday and cannot be tested without them.\nDecision needed: whether guest checkout is in or out of the first release (the SOW is silent).\nMilestone: UAT drop on 6 November, currently on track if the keys arrive by Friday.",
        wordLimit: 220,
        rubric: [
          { id: "rag", label: "Honest RAG", description: "Gives Amber (on track only if the keys arrive) with the reason in one line, rather than Green.", weight: 1.5 },
          { id: "structure", label: "Scannable structure", description: "Short sections or bullets for done, next, risks and decision; subject line states project, week and status.", weight: 1 },
          { id: "risk", label: "Risk with owner and date", description: "States the missing sandbox keys, what they block, who must act (the client) and by when (Friday), and the effect on the 6 November date.", weight: 1.5 },
          { id: "ask", label: "Clear decision request", description: "Asks one clear question about guest checkout with a date for the answer.", weight: 1 },
        ],
        sampleAnswer:
          "Subject: E-commerce app – Week 4 status: Amber (payment keys needed by Friday)\n\nHi Sara,\n\nOverall: Amber. We are on track for the 6 November UAT drop if the payment sandbox keys arrive by Friday.\n\nDone\n- Product listing, cart and wishlist are on staging.\n- 11 of 14 Sprint 4 stories closed; the other 3 move to Sprint 5.\n\nNext (Sprint 5)\n- Checkout and order history.\n\nRisk\n- We requested the payment gateway sandbox keys on 1 October. Checkout work starts Monday and cannot be tested without them. Could your team share them by Friday 16 October? If they arrive later, the UAT date moves.\n\nDecision needed\n- Is guest checkout in or out of the first release? The SOW does not say. An answer by Monday lets us plan Sprint 5.\n\nThanks,\nPriya",
      },
    },
  },
  {
    id: "pm-fill-rag-status-report",
    departmentId: "pm",
    title: "Fill the RAG status report template",
    statement: "Can fill the weekly RAG status report from a board export, setting scope, schedule and budget RAG from evidence rather than feel.",
    skillIds: ["pm-status-reporting", "pm-proc-templates"],
    level: 3,
    aliases: ["rag report", "status report template", "red amber green"],
    capstone: topic("Fill the RAG status report", "pmp-e02-status-report"),
  },
  {
    id: "pm-rag-by-formula",
    departmentId: "pm",
    title: "Set RAG status by formula in a tracker",
    statement: "Can build a status sheet where RAG comes from a formula on days late, and count the red rows for the summary.",
    skillIds: ["pm-excel-for-pms", "pm-status-reporting", "pm-spreadsheets"],
    level: 3,
    aliases: ["rag formula", "rag in excel", "status sheet"],
    capstone: topic("Build the RAG column in Excel", "pma-rag-status"),
  },
  {
    id: "pm-maintain-raid-log",
    departmentId: "pm",
    title: "Maintain a RAID log for a client project",
    statement: "Can sort project events into risks, assumptions, issues and dependencies and keep the RAID log current with owners and actions.",
    skillIds: ["pm-raid-log", "pm-proc-templates", "pm-risk-management"],
    level: 3,
    aliases: ["raid log", "risk register", "risks and issues", "raid"],
    capstone: topic("Sort entries into the RAID log", "pmp-e02-raid-log"),
  },
  {
    id: "pm-audit-raid-log",
    departmentId: "pm",
    title: "Audit a RAID log and fix the weak entries",
    statement: "Can review someone else's RAID log and mark risks with no owner, issues logged as risks, stale dates and missing mitigations.",
    skillIds: ["pm-raid-log", "pm-risk-management", "pm-dependency-management"],
    level: 4,
    aliases: ["raid review", "risk log audit", "review risks"],
    capstone: topic("Spot the weak entries in a RAID log", "pm-i-raid-risk-management"),
  },

  // -------------------------------------------------------------------------
  // Excel for PMs
  // -------------------------------------------------------------------------
  {
    id: "pm-excel-dropdown-tracker",
    departmentId: "pm",
    title: "Build a clean tracker with dropdowns in Excel",
    statement: "Can build a tracker with a table, filters, frozen headers and data-validation dropdowns so statuses stay consistent.",
    skillIds: ["pm-excel-for-pms", "pm-spreadsheets"],
    level: 1,
    aliases: ["excel dropdown", "data validation", "excel tracker basics"],
    capstone: topic("Add validation dropdowns to a tracker", "pma-excel-data-validation"),
  },
  {
    id: "pm-excel-lookup-sumifs",
    departmentId: "pm",
    title: "Answer delivery questions with SUMIFS, COUNTIF and XLOOKUP",
    statement: "Can answer questions such as hours by project or open bugs by owner with SUMIFS, COUNTIF and XLOOKUP instead of manual counting.",
    skillIds: ["pm-excel-for-pms", "pm-spreadsheets"],
    level: 2,
    aliases: ["sumifs", "xlookup", "countif", "excel formulas"],
    capstone: topic("Fill the formulas in the delivery sheet", "pma-excel-core-functions"),
  },
  {
    id: "pm-excel-budget-variance",
    departmentId: "pm",
    title: "Track budget vs actual hours with variance and RAG",
    statement: "Can build a budget-vs-actuals sheet that calculates variance per phase, flags overruns with a RAG formula and totals the variance.",
    skillIds: ["pm-excel-for-pms", "pm-budget-basics", "pm-time-tracking"],
    level: 3,
    aliases: ["budget vs actuals", "hours variance", "burn tracking", "budget tracker"],
    capstone: {
      kind: "task",
      title: "Fill the budget-vs-actuals sheet",
      task: {
        kind: "excel",
        prompt:
          "This sheet compares budgeted and actual hours per phase. Fill D2:D4 with the variance (actual minus budget), E2:E4 with a RAG formula (more than 10% over budget is \"Red\", over budget by 10% or less is \"Amber\", on or under budget is \"Green\"), and D5 with the total variance using SUM.",
        grid: [
          ["Phase", "Budget hours", "Actual hours", "Variance", "RAG"],
          ["Discovery", "80", "92", "", ""],
          ["Design", "120", "110", "", ""],
          ["Development", "400", "430", "", ""],
          ["Total", "", "", "", ""],
        ],
        editable: ["D2", "D3", "D4", "E2", "E3", "E4", "D5"],
        checks: [
          { cell: "D2", expected: 12, tolerance: 0.01, requireFormula: true, functions: [] },
          { cell: "D3", expected: -10, tolerance: 0.01, requireFormula: true, functions: [] },
          { cell: "D4", expected: 30, tolerance: 0.01, requireFormula: true, functions: [] },
          { cell: "E2", expected: "Red", tolerance: 0.01, requireFormula: true, functions: ["IF"] },
          { cell: "E3", expected: "Green", tolerance: 0.01, requireFormula: true, functions: ["IF"] },
          { cell: "E4", expected: "Amber", tolerance: 0.01, requireFormula: true, functions: ["IF"] },
          { cell: "D5", expected: 32, tolerance: 0.01, requireFormula: true, functions: ["SUM"] },
        ],
        solution: {
          D2: "=C2-B2",
          D3: "=C3-B3",
          D4: "=C4-B4",
          E2: '=IF(D2/B2>0.1,"Red",IF(D2>0,"Amber","Green"))',
          E3: '=IF(D3/B3>0.1,"Red",IF(D3>0,"Amber","Green"))',
          E4: '=IF(D4/B4>0.1,"Red",IF(D4>0,"Amber","Green"))',
          D5: "=SUM(D2:D4)",
        },
        explanation:
          "Variance is actual minus budget, so overruns are positive. Discovery is 12 h over on 80 h (15%, Red); Development is 30 h over on 400 h (7.5%, Amber); Design is under budget (Green). The total variance is 12 − 10 + 30 = 32 h over.",
      },
    },
  },
  {
    id: "pm-excel-networkdays",
    departmentId: "pm",
    title: "Plan dates with NETWORKDAYS and holidays",
    statement: "Can calculate working days between milestones with NETWORKDAYS, excluding weekends and holidays, and use them to check a plan.",
    skillIds: ["pm-excel-for-pms", "pm-schedule-basics"],
    level: 3,
    aliases: ["networkdays", "working days", "excel dates"],
    capstone: topic("Calculate working days in the plan", "pma-excel-dates-networkdays"),
  },
  {
    id: "pm-excel-pivot-hours",
    departmentId: "pm",
    title: "Summarise timesheet hours with a pivot table",
    statement: "Can build a pivot table and chart of hours by project and person from a timesheet export to answer billing and utilisation questions.",
    skillIds: ["pm-excel-for-pms", "pm-time-tracking"],
    level: 3,
    aliases: ["pivot table", "excel pivot", "hours by project"],
    capstone: topic("Summarise hours with a pivot", "pma-excel-pivot-tables-charts"),
  },
  {
    id: "pm-excel-project-tracker",
    departmentId: "pm",
    title: "Build a project tracker with Gantt, resources and budget vs actuals",
    statement: "Can build a working project tracker in Excel with a simple Gantt, a resource view, budget vs actuals and a RAID tab driven by formulas.",
    skillIds: ["pm-excel-for-pms", "pm-spreadsheets", "pm-schedule-basics"],
    level: 4,
    aliases: ["excel tracker", "project tracker", "gantt in excel", "excel project plan"],
    capstone: topic("Build the project tracker", "pma-excel-trackers"),
  },

  // -------------------------------------------------------------------------
  // Resourcing
  // -------------------------------------------------------------------------
  {
    id: "pm-calc-utilisation",
    departmentId: "pm",
    title: "Calculate capacity, allocation, utilisation and billable %",
    statement: "Can calculate each person's capacity, allocation, utilisation and billable percentage from hours, and explain the difference between them.",
    skillIds: ["pm-agency-resourcing", "pm-resource-planning"],
    level: 1,
    aliases: ["utilisation", "billable percentage", "capacity vs allocation", "billability"],
    capstone: topic("Calculate the team's utilisation", "pma-capacity-allocation-utilisation"),
  },
  {
    id: "pm-plan-around-leave",
    departmentId: "pm",
    title: "Plan delivery around leave and public holidays",
    statement: "Can calculate the capacity lost to leave and holidays across a release and adjust the plan before it hits the client date.",
    skillIds: ["pm-agency-resourcing", "pm-resource-planning", "pm-keka"],
    level: 2,
    aliases: ["leave planning", "holiday planning", "capacity loss"],
    capstone: topic("Work out capacity after leave", "pma-leave-holiday-planning"),
  },
  {
    id: "pm-rebalance-allocation",
    departmentId: "pm",
    title: "Rebalance people across projects without over-allocating anyone",
    statement: "Can allocate hours across several projects so no one is over-allocated, no one works on a project they are blocked from, and every project is staffed.",
    skillIds: ["pm-agency-resourcing", "pm-resource-planning", "pm-multi-project"],
    level: 3,
    aliases: ["resource allocation", "over-allocation", "staffing", "multi-project allocation"],
    capstone: topic("Allocate the team across projects", "pma-multi-project-over-under-allocation"),
  },
  {
    id: "pm-run-resource-meeting",
    departmentId: "pm",
    title: "Run the weekly resource meeting",
    statement: "Can run the weekly resource meeting: review allocations against new demand, resolve clashes and publish next week's allocation.",
    skillIds: ["pm-agency-resourcing", "pm-resource-planning", "pm-proc-meetings"],
    level: 3,
    aliases: ["resource meeting", "weekly resourcing", "allocation meeting"],
    capstone: topic("Settle next week's allocation", "pma-weekly-resource-meeting"),
  },
  {
    id: "pm-forecast-from-pipeline",
    departmentId: "pm",
    title: "Forecast hiring and bench from the BD pipeline",
    statement: "Can turn the BD pipeline into a weighted resource forecast and say where the team will be short or on the bench in the coming months.",
    skillIds: ["pm-agency-resourcing", "pm-resource-planning", "pm-portfolio-management"],
    level: 4,
    aliases: ["pipeline forecast", "resource forecast", "bench forecast", "hiring forecast"],
    capstone: topic("Forecast resourcing from the pipeline", "pma-forecasting-from-pipeline"),
  },
  {
    id: "pm-resource-plan-excel-keka",
    departmentId: "pm",
    title: "Keep the resource plan in Excel and Keka PSA in step",
    statement: "Can maintain a resource plan in Excel and mirror it in Keka PSA allocations, catching where the two disagree.",
    skillIds: ["pm-agency-resourcing", "pm-excel-for-pms", "pm-keka"],
    level: 5,
    aliases: ["resource plan", "keka allocation", "resource sheet"],
    capstone: topic("Reconcile the resource plan", "pma-resource-plan-in-excel-and-keka"),
  },

  // -------------------------------------------------------------------------
  // Jira / ClickUp
  // -------------------------------------------------------------------------
  {
    id: "pm-jira-clickup-board-basics",
    departmentId: "pm",
    title: "Keep a Jira or ClickUp board clean for agency delivery",
    statement: "Can spot and fix board hygiene problems in Jira or ClickUp: missing assignees, wrong issue types, stale statuses and tickets with no acceptance criteria.",
    skillIds: ["pm-jira", "pm-clickup"],
    level: 1,
    aliases: ["jira basics", "clickup basics", "board hygiene", "ticket hygiene"],
    capstone: topic("Spot the board hygiene problems", "pm-b-jira-clickup-basics"),
  },
  {
    id: "pm-clickup-hierarchy",
    departmentId: "pm",
    title: "Structure client work in ClickUp's hierarchy",
    statement: "Can place agency work in the right ClickUp level (Space, Folder, List, Task) so each client and project stays separate and reportable.",
    skillIds: ["pm-clickup", "pm-work-management-tools"],
    level: 2,
    aliases: ["clickup setup", "clickup spaces", "clickup lists", "clickup structure"],
    capstone: {
      kind: "task",
      title: "Place the work in ClickUp",
      task: {
        kind: "categorize",
        mode: "generic",
        prompt:
          "You are setting up ClickUp for the delivery team. Each client has its own area, each client project groups its sprints, and each sprint holds the work. Put each item at the right ClickUp level.",
        categories: [
          { id: "space", label: "Space" },
          { id: "folder", label: "Folder" },
          { id: "list", label: "List" },
          { id: "task", label: "Task" },
        ],
        items: [
          { id: "c1", text: "Acme Retail (a client with three projects)", explanation: "One Space per client keeps permissions and reporting separate." },
          { id: "c2", text: "Acme Retail: customer mobile app project", explanation: "A project inside a client's Space is a Folder." },
          { id: "c3", text: "Sprint 3 of the customer app", explanation: "Sprints are Lists inside the project Folder." },
          { id: "c4", text: "Add Apple Pay to checkout", explanation: "A single piece of work is a Task." },
          { id: "c5", text: "Fix: order history shows the wrong currency", explanation: "A bug is a Task (with a bug type or tag)." },
          { id: "c6", text: "Brightline Clinics (a new client)", explanation: "A new client gets its own Space." },
          { id: "c7", text: "Product backlog for the customer app", explanation: "The backlog is a List the sprints pull from." },
        ],
        answer: { c1: "space", c2: "folder", c3: "list", c4: "task", c5: "task", c6: "space", c7: "list" },
      },
    },
  },
  {
    id: "pm-jira-jql-filters",
    departmentId: "pm",
    title: "Write and check JQL filters for delivery questions",
    statement: "Can read JQL filters and spot the ones that do not return what their purpose says, such as wrong date operators or currentUser() misuse.",
    skillIds: ["pm-jira", "pm-tool-automation"],
    level: 3,
    aliases: ["jql", "jira filters", "jira search", "jira queries"],
    capstone: {
      kind: "task",
      title: "Find the broken JQL filters",
      task: {
        kind: "spot",
        prompt:
          "A PM saved these JQL filters for a client dashboard, with the purpose in brackets. Mark every filter that does NOT do what its purpose says.",
        segments: [
          { id: "j1", text: "[My open work] assignee = currentUser() AND resolution = Unresolved", issue: null },
          { id: "j2", text: "[Bugs in the active sprint] project = SHOP AND issuetype = Bug AND sprint in openSprints()", issue: null },
          { id: "j3", text: "[Created in the last 7 days] project = SHOP AND created <= -7d", issue: "created <= -7d returns issues created more than 7 days ago; it needs created >= -7d." },
          { id: "j4", text: "[Unassigned stories] project = SHOP AND issuetype = Story AND assignee = currentUser()", issue: "currentUser() returns the PM's own issues; unassigned needs assignee is EMPTY." },
          { id: "j5", text: "[Release 2.1 scope] project = SHOP AND fixVersion = \"2.1\"", issue: null },
          { id: "j6", text: "[Open highest-priority first] project = SHOP AND resolution = Unresolved ORDER BY priority DESC", issue: null },
          { id: "j7", text: "[Client-reported bugs still open] project = SHOP AND issuetype = Bug AND labels = client-reported AND status = Done", issue: "status = Done returns closed bugs; open ones need statusCategory != Done or resolution = Unresolved." },
          { id: "j8", text: "[Stories with no estimate] project = SHOP AND issuetype = Story AND \"Story Points\" is EMPTY", issue: null },
        ],
        askExplanation: false,
      },
    },
  },
  {
    id: "pm-link-tickets-to-prs",
    departmentId: "pm",
    title: "Trace tickets to pull requests and releases",
    statement: "Can check that tickets are linked to their PRs and releases, and spot work marked done in Jira that never reached the release branch.",
    skillIds: ["pm-github-for-pms", "pm-jira", "pm-git-flow"],
    level: 3,
    aliases: ["link jira to github", "ticket to pr", "traceability"],
    capstone: topic("Spot the broken ticket-to-PR links", "pma-linking-tickets-to-prs"),
  },
  {
    id: "pm-check-pr-before-release",
    departmentId: "pm",
    title: "Read a pull request's status and ask the right pre-release questions",
    statement: "Can read a PR's reviews, checks and target branch and ask the questions that decide whether a release is safe to ship.",
    skillIds: ["pm-github-for-pms", "pm-git-flow", "pm-release-management"],
    level: 4,
    aliases: ["read a pr", "pull request review", "release questions", "github pr"],
    capstone: topic("Check the release PR", "pma-pre-release-questions"),
  },

  // -------------------------------------------------------------------------
  // Keka
  // -------------------------------------------------------------------------
  {
    id: "pm-approve-keka-timesheets",
    departmentId: "pm",
    title: "Review and approve the team's Keka timesheets",
    statement: "Can review a week of team timesheets in Keka and flag entries on the wrong project, missing hours or hours logged on leave before approving.",
    skillIds: ["pm-keka", "pm-time-tracking"],
    level: 1,
    aliases: ["keka timesheets", "timesheet approval", "approve hours"],
    capstone: topic("Approve this week's timesheets", "pma-keka-timesheets"),
  },
  {
    id: "pm-keka-leave-impact",
    departmentId: "pm",
    title: "Read leave and attendance in Keka for delivery impact",
    statement: "Can read team leave and attendance in Keka and say which deliveries are affected before the week starts.",
    skillIds: ["pm-keka", "pm-agency-resourcing"],
    level: 2,
    aliases: ["keka leave", "attendance", "leave impact"],
    capstone: topic("Check leave against delivery", "pma-keka-leave-attendance"),
  },
  {
    id: "pm-keka-psa-billing-setup",
    departmentId: "pm",
    title: "Set up projects with the right billing type in Keka PSA",
    statement: "Can check that each client project in Keka PSA has the right billing type (time and material, milestone or non-billable) for its contract.",
    skillIds: ["pm-keka", "pm-commercial-tm", "pm-commercial-fixed-bid"],
    level: 3,
    aliases: ["keka psa", "billing type", "keka projects"],
    capstone: topic("Check the billing configuration", "pma-keka-psa-billing-types"),
  },
  {
    id: "pm-keka-allocation-rate-cards",
    departmentId: "pm",
    title: "Check allocations and rate cards in Keka PSA",
    statement: "Can review a project's allocations and rate cards in Keka PSA and flag wrong rates, over-allocation and people missing from the project.",
    skillIds: ["pm-keka", "pm-agency-resourcing", "pm-profitability"],
    level: 4,
    aliases: ["rate card", "keka allocation", "allocation check"],
    capstone: topic("Review the allocation screen", "pma-keka-psa-allocation-rate-cards"),
  },
  {
    id: "pm-keka-invoice-check",
    departmentId: "pm",
    title: "Check a draft invoice against timesheets and the contract",
    statement: "Can check a draft Keka invoice against approved timesheets, billing type and rate card and catch errors before it goes to the client.",
    skillIds: ["pm-keka", "pm-commercial-tm", "pm-profitability"],
    level: 5,
    aliases: ["invoice check", "keka invoice", "billing review"],
    capstone: topic("Check the draft invoice", "pma-keka-psa-invoices"),
  },

  // -------------------------------------------------------------------------
  // Microsoft Teams
  // -------------------------------------------------------------------------
  {
    id: "pm-teams-right-place",
    departmentId: "pm",
    title: "Post in the right Teams channel, chat or meeting",
    statement: "Can choose between a channel post, a group chat and a meeting for each project message, so decisions are findable later.",
    skillIds: ["pm-ms-teams"],
    level: 1,
    aliases: ["teams channels", "teams chat", "where to post"],
    capstone: topic("Choose where each message goes", "pma-teams-channels-chats"),
  },
  {
    id: "pm-teams-mentions",
    departmentId: "pm",
    title: "Use @mentions and presence in Teams without noise",
    statement: "Can review a Teams channel and flag messages that misuse @channel, @mentions or presence, and rewrite them so the right person acts.",
    skillIds: ["pm-ms-teams", "pm-client-communication"],
    level: 2,
    aliases: ["mentions", "teams etiquette", "at mention"],
    capstone: topic("Flag the noisy messages", "pma-teams-mentions-presence"),
  },
  {
    id: "pm-teams-client-call",
    departmentId: "pm",
    title: "Run a client call in Teams with external guests",
    statement: "Can set up and run a Teams call with external client guests: lobby, permissions, recording consent, screen share and what to share afterwards.",
    skillIds: ["pm-ms-teams", "pm-client-meetings"],
    level: 3,
    aliases: ["teams meeting", "external guests", "client call in teams"],
    capstone: topic("Set up the client demo call", "pma-teams-client-calls"),
  },

  // -------------------------------------------------------------------------
  // Client email
  // -------------------------------------------------------------------------
  {
    id: "pm-write-clear-client-email",
    departmentId: "pm",
    title: "Write a clear client email with a strong subject line",
    statement: "Can write a client email whose subject says the point, whose first line gives the ask, and whose body a busy reader can act on.",
    skillIds: ["pm-email-etiquette", "pm-client-communication"],
    level: 1,
    aliases: ["client email", "email writing", "subject line", "professional email"],
    capstone: topic("Rewrite the email", "pma-email-subject-structure"),
  },
  {
    id: "pm-chase-politely",
    departmentId: "pm",
    title: "Chase a client politely for overdue inputs",
    statement: "Can write a firm, polite chaser for overdue client inputs that states the impact on the date and the next step.",
    skillIds: ["pm-email-etiquette", "pm-client-communication", "pm-dependency-management"],
    level: 2,
    aliases: ["chase client", "follow-up email", "reminder email", "overdue inputs"],
    capstone: topic("Write the chaser", "pma-chasing-politely"),
  },
  {
    id: "pm-write-for-non-native",
    departmentId: "pm",
    title: "Write emails non-native English readers understand first time",
    statement: "Can rewrite a project email in plain, literal English for a non-native reader: short sentences, no idioms, explicit dates and actions.",
    skillIds: ["pm-email-etiquette", "pm-client-communication"],
    level: 3,
    aliases: ["plain english", "non-native readers", "simple english"],
    capstone: topic("Rewrite for a non-native reader", "pma-writing-for-non-native-readers"),
  },
  {
    id: "pm-write-escalation-email",
    departmentId: "pm",
    title: "Write status, escalation and MoM emails that get action",
    statement: "Can write an escalation or status email that states the problem, impact, options and the decision needed, at the right level of the client's organisation.",
    skillIds: ["pm-email-etiquette", "pm-escalations", "pm-status-reporting"],
    level: 4,
    aliases: ["escalation email", "status email", "escalate by email"],
    capstone: topic("Write the escalation email", "pma-status-escalation-mom-emails"),
  },

  // -------------------------------------------------------------------------
  // Tech terms
  // -------------------------------------------------------------------------
  {
    id: "pm-explain-tech-terms",
    departmentId: "pm",
    title: "Explain frontend, backend and API to a client in plain words",
    statement: "Can explain a technical term such as API, backend or staging to a non-technical client accurately in two or three plain sentences.",
    skillIds: ["pm-tech-terms", "pm-client-communication"],
    level: 2,
    aliases: ["explain tech terms", "plain language", "explain api", "tech to client"],
    capstone: topic("Explain the terms to the client", "pma-frontend-backend-api"),
  },
  {
    id: "pm-explain-scale-and-caching",
    departmentId: "pm",
    title: "Explain scalability, latency and caching trade-offs to a client",
    statement: "Can explain to a client why an app is slow under load and what caching or scaling would cost and change, without jargon.",
    skillIds: ["pm-tech-terms", "pm-technical-tradeoffs"],
    level: 4,
    aliases: ["explain scalability", "performance explanation", "caching"],
    capstone: topic("Explain the performance issue", "pma-scalability-latency-caching"),
  },

  // -------------------------------------------------------------------------
  // AI for PMs
  // -------------------------------------------------------------------------
  {
    id: "pm-ai-draft-mom-status",
    departmentId: "pm",
    title: "Draft a MoM or status email with AI and catch its mistakes",
    statement: "Can use Copilot or Claude to draft a MoM or status email from notes and catch the invented facts, wrong owners and missing actions before sending.",
    skillIds: ["pm-ai-for-pms", "pm-ai-meeting-notes", "pm-ai-status-reports"],
    level: 2,
    aliases: ["ai mom", "copilot meeting notes", "ai status email", "claude for pms"],
    capstone: topic("Spot the errors in an AI-drafted MoM", "pma-ai-moms-status-emails"),
  },
  {
    id: "pm-ai-excel-formulas",
    departmentId: "pm",
    title: "Get a working Excel formula from AI and verify it",
    statement: "Can ask an AI assistant for an Excel formula, test it on known rows and fix it when it is wrong.",
    skillIds: ["pm-ai-for-pms", "pm-excel-for-pms"],
    level: 3,
    aliases: ["ai excel", "copilot excel", "formula with ai"],
    capstone: topic("Build the formula with AI and check it", "pma-ai-excel-formulas"),
  },
  {
    id: "pm-ai-prd-risk-list",
    departmentId: "pm",
    title: "Draft a PRD section and risk list with AI",
    statement: "Can prompt an AI assistant with the right context to draft a PRD section and risk list, then edit it into something the team can build from.",
    skillIds: ["pm-ai-for-pms", "pm-ai-prds", "pm-ai-risk-analysis"],
    level: 3,
    aliases: ["ai prd", "ai risk list", "claude prd", "prompting for pms"],
    capstone: topic("Draft the PRD and risks with AI", "pma-ai-prds-risk-lists"),
  },
  {
    id: "pm-ai-verify-output",
    departmentId: "pm",
    title: "Verify AI output before it reaches a client",
    statement: "Can apply verification habits to AI output (check facts against source, numbers against the sheet, promises against the contract) and decide what may be sent.",
    skillIds: ["pm-ai-for-pms", "pm-ai-risk-analysis"],
    level: 4,
    aliases: ["verify ai", "ai hallucination", "check ai output"],
    capstone: topic("Decide what AI output can be sent", "pma-ai-verification-habits"),
  },
  {
    id: "pm-ai-confidentiality",
    departmentId: "pm",
    title: "Keep client data safe when using AI tools",
    statement: "Can spot confidentiality and data-handling breaches in how a team uses AI tools on client work, and set the rules that prevent them.",
    skillIds: ["pm-ai-for-pms", "pm-ai-teams", "pm-contract-management"],
    level: 5,
    aliases: ["ai confidentiality", "ai data policy", "client data and ai", "nda and ai"],
    capstone: topic("Spot the AI data-handling breaches", "pm-x-ai-confidentiality"),
  },

  // -------------------------------------------------------------------------
  // Running the PM week
  // -------------------------------------------------------------------------
  {
    id: "pm-triage-pm-monday",
    departmentId: "pm",
    title: "Triage a PM's Monday morning across several projects",
    statement: "Can put a mixed list of PM tasks across projects in priority order, putting live-client impact and expiring commitments first.",
    skillIds: ["pm-multi-project", "pm-agency-refresh"],
    level: 2,
    aliases: ["prioritise my day", "pm triage", "multiple projects", "monday morning"],
    capstone: {
      kind: "task",
      title: "Order Monday's first hour",
      task: {
        kind: "rank",
        prompt:
          "It is 09:00 on Monday and you run three projects. Put these in the order you deal with them, first at the top.",
        items: [
          { id: "m1", label: "A live client reports the app's payments are failing for all users since 08:30" },
          { id: "m2", label: "The client going live tomorrow asks a blocking question about the DNS change window" },
          { id: "m3", label: "Send Friday's status-call MoM, which you promised the client within a day" },
          { id: "m4", label: "Approve last week's team timesheets in Keka, due by end of day" },
          { id: "m5", label: "Update the RAID log before Thursday's steering meeting" },
          { id: "m6", label: "Tidy labels and swimlanes on a project board" },
        ],
        correctOrder: ["m1", "m2", "m3", "m4", "m5", "m6"],
        explanation:
          "A live outage with money at stake comes first, then a blocker for tomorrow's go-live. The overdue MoM is a broken promise that grows each hour; timesheets have an end-of-day deadline; the RAID update has until Thursday; board tidying can wait.",
      },
    },
  },
  {
    id: "pm-follow-up-ownership",
    departmentId: "pm",
    title: "Follow up on actions until they close",
    statement: "Can track every action from meetings to closure, spot actions with no owner or date, and chase them before they become delays.",
    skillIds: ["pm-agency-refresh", "pm-meeting-facilitation"],
    level: 3,
    aliases: ["follow ups", "action tracking", "accountability"],
    capstone: topic("Spot the actions that will be dropped", "pma-follow-ups-ownership"),
  },
] satisfies PracticalOutcomeSeed[];
