import type { PracticalOutcomeSeed } from "../../../../shared/goals";

/**
 * v4.4 practical outcomes for the Soft skills area (department `soft`, `kind: "area"`). Because the
 * area's skills are usable by every department, these cases are offered to every learner:
 * `listUsableOutcomes` returns a department's own cases followed by every area's.
 *
 * Levels 1–5 climb on the same skills, so a next-level suggestion always exists. Capstones point at
 * the soft-skills topics (src/content/soft/) whose practice already proves the case, or are tasks.
 * Spoken cases use the topic capstone today; Phase 3's Speak recorder plays the topic's `speak`
 * practice, with the written practice as the fallback.
 */

const topic = (title: string, topicId: string) => ({ kind: "topic" as const, title, topicId });
const D = "soft";

export default [
  // -------------------------------------------------------------------------
  // Speaking
  // -------------------------------------------------------------------------
  {
    id: "ss-introduce-yourself",
    departmentId: D,
    title: "Introduce yourself and your work to a new teammate in English",
    statement: "Can introduce themselves, their role and their current work to a new teammate or client contact in under a minute, in English that is easy to follow.",
    skillIds: ["ss-spoken-english"],
    level: 1,
    aliases: ["introduce yourself", "self introduction", "spoken english basics", "english introduction"],
    capstone: topic("Introduce yourself to a new teammate", "soft-english-clear-at-work"),
  },
  {
    id: "ss-standup-60s",
    departmentId: D,
    title: "Give a clear 60-second stand-up update in English",
    statement: "Can give a stand-up update in under a minute that covers done, next and blockers, ties the work to the sprint goal and names who can help.",
    skillIds: ["ss-standup-updates", "ss-spoken-english"],
    level: 2,
    aliases: ["standup update", "stand-up in english", "daily standup", "daily scrum update"],
    capstone: topic("Give your stand-up update", "soft-standup-done-next-blockers"),
  },
  {
    id: "ss-explain-delay-client-call",
    departmentId: D,
    title: "Explain a delay to a client on a call",
    statement: "Can tell a client on a call that a delivery will be late: the new date first, the reason in one sentence without blame, the plan, any options and when they will hear next.",
    skillIds: ["ss-client-team-communication", "ss-spoken-english"],
    level: 3,
    aliases: ["explain a delay", "bad news to client", "deadline slip call", "delay conversation"],
    capstone: topic("Explain a delay to a client", "soft-comms-no-surprises"),
  },
  {
    id: "ss-demo-feature-3min",
    departmentId: D,
    title: "Demo a finished feature in 3 minutes",
    statement: "Can demo a finished feature to a client in about three minutes: the user's problem, the user's journey live, known limits and a clear ask.",
    skillIds: ["ss-presenting-demoing", "ss-explain-simply"],
    level: 3,
    aliases: ["feature demo", "sprint demo", "demo to client", "show a feature"],
    capstone: topic("Plan and give a 3-minute feature demo", "soft-demo-show-the-value"),
  },
  {
    id: "ss-sprint-review-present",
    departmentId: D,
    title: "Present sprint results to a client in a sprint review",
    statement: "Can open and run the client-facing part of a sprint review: goal and outcome first, live demos in a sensible order, limits stated, feedback captured and decisions confirmed.",
    skillIds: ["ss-presenting-demoing", "ss-spoken-english", "ss-client-team-communication"],
    level: 4,
    aliases: ["sprint review", "present sprint results", "client review meeting"],
    capstone: {
      kind: "task" as const,
      title: "Order the sprint review",
      task: {
        kind: "rank",
        prompt: "You are running a 30-minute sprint review with the client for a clinic booking app. Put the parts in the best order.",
        items: [
          { id: "goal", label: "The sprint goal and whether it was met, in one sentence" },
          { id: "demos", label: "Live demos of the finished features, each from the user's point of view" },
          { id: "limits", label: "What was not finished and why, with the plan for it" },
          { id: "feedback", label: "Client feedback and questions, repeated back and noted" },
          { id: "decisions", label: "Decisions needed and the next sprint's focus" },
          { id: "summary", label: "Recap of actions with owners and dates, and when the written summary will arrive" },
        ],
        correctOrder: ["goal", "demos", "limits", "feedback", "decisions", "summary"],
        explanation: "Lead with the goal so the demos have context, show the work, be honest about what slipped, take feedback, settle decisions, and end on owners and dates.",
      },
    },
  },
  {
    id: "ss-lead-client-call-english",
    departmentId: D,
    title: "Lead a client call in clear English and confirm decisions aloud",
    statement: "Can lead a client call in clear, well-structured English: set the agenda, keep turns balanced, check understanding, summarise decisions aloud and follow up in writing.",
    skillIds: ["ss-spoken-english", "ss-client-team-communication", "ss-listening-questions"],
    level: 5,
    aliases: ["lead a client call", "run a client meeting in english", "fluent english client call"],
    capstone: {
      kind: "task" as const,
      title: "Steer a client call to clear decisions",
      task: {
        kind: "scenario",
        prompt: "You are leading a 30-minute call with a client in the UK about the next release of their delivery app. Their product owner speaks quickly, and two of their team keep raising new feature ideas.",
        steps: [
          {
            id: "s1",
            question: "How do you open the call?",
            options: [
              "State the goal of the call and a three-point agenda, and ask if anything is missing",
              "Start with the newest feature idea to show enthusiasm",
              "Let the client talk until they run out of topics",
              "Read the full status report aloud",
            ],
            correctIndex: 0,
            explanation: "A stated goal and agenda give you a fair reason to steer later.",
          },
          {
            id: "s2",
            question: "The product owner says a date quickly and you are not sure you heard it. What do you do?",
            options: [
              "Repeat it back: \"Just to confirm, you need it live by the 14th?\"",
              "Guess and check the recording later",
              "Ignore it, the PM will know",
              "Ask them to email it after the call",
            ],
            correctIndex: 0,
            explanation: "Repeating back is normal and catches a costly misunderstanding on the spot.",
          },
          {
            id: "s3",
            question: "New feature ideas keep coming and time is nearly up. What do you do?",
            options: [
              "Note them in a parking list, summarise the decisions made aloud, agree how the ideas will be reviewed, and confirm everything in writing today",
              "Agree to all of them to keep the client happy",
              "End the call without a summary",
              "Debate each idea until the call overruns",
            ],
            correctIndex: 0,
            explanation: "Park new topics, close on decisions out loud, and follow up in writing so both sides have the same record.",
          },
        ],
      },
    },
  },
  // -------------------------------------------------------------------------
  // Writing
  // -------------------------------------------------------------------------
  {
    id: "ss-pr-description",
    departmentId: D,
    title: "Write a clear pull request description",
    statement: "Can write a pull request description that says what changed and why in the first lines, then how to test it and what is risky.",
    skillIds: ["ss-workplace-writing"],
    level: 1,
    aliases: ["pr description", "pull request write-up", "merge request description"],
    capstone: {
      kind: "task" as const,
      title: "Write the PR description",
      task: {
        kind: "write",
        variant: "general",
        prompt: "Write the pull request description for the change below. Start with what changed and why, then how to test it, then anything risky.",
        context: "Change: the order export now runs as a background job instead of during the web request, because exports over 5,000 rows timed out. The user gets an email with a download link when the file is ready. Test: export a large shop's orders on staging (shop id 42). Risk: the job uses the existing queue; if the queue worker is down, exports wait.",
        wordLimit: 150,
        rubric: [
          { id: "what", label: "What and why first", description: "The first lines say the export now runs in the background because large exports timed out.", weight: 1.5 },
          { id: "test", label: "How to test", description: "Gives the steps to test on staging (export shop 42's orders, check the email link).", weight: 1 },
          { id: "risk", label: "Risk", description: "Mentions the dependency on the queue worker.", weight: 1 },
          { id: "plain", label: "Short and plain", description: "Short sentences or bullets; no padding.", weight: 0.5 },
        ],
        sampleAnswer: "Moves the order export to a background job, because exports over 5,000 rows timed out during the request. Users now get an email with a download link when the file is ready.\n\nHow to test:\n1. On staging, export orders for shop 42.\n2. Check the email arrives and the link downloads the full file.\n\nRisk: the export uses the existing queue, so if the queue worker is down, exports wait until it is back.",
      },
    },
  },
  {
    id: "ss-chat-question-context",
    departmentId: D,
    title: "Ask for help in chat with the context in the first message",
    statement: "Can ask a teammate for help in chat with the problem, what was tried and the exact ask in the first message, so they can answer without a back-and-forth.",
    skillIds: ["ss-workplace-writing", "ss-listening-questions"],
    level: 1,
    aliases: ["ask for help in chat", "slack question", "teams message", "don't just say hi"],
    capstone: {
      kind: "task" as const,
      title: "Write the chat message",
      task: {
        kind: "write",
        variant: "general",
        prompt: "Write one chat message to Priya, the tech lead, asking for help with the problem below. Put everything she needs in this first message.",
        context: "Since this morning, the payment webhook on staging returns 401. You checked that the endpoint is deployed and that your code did not change. You suspect the Stripe keys on staging were rotated. You are blocked on checkout testing, which is due tomorrow.",
        wordLimit: 80,
        rubric: [
          { id: "problem", label: "The problem", description: "Says the staging payment webhook returns 401 since this morning.", weight: 1 },
          { id: "tried", label: "What was checked", description: "Says the endpoint is deployed and the code has not changed.", weight: 1 },
          { id: "ask", label: "A clear ask", description: "Asks a specific question (were the Stripe keys rotated?) and says it blocks checkout testing due tomorrow.", weight: 1.5 },
        ],
        sampleAnswer: "Hi Priya, the payment webhook on staging has returned 401 since this morning. The endpoint is deployed and our code hasn't changed, so I suspect the Stripe keys on staging were rotated. Do you know if they were, or who can check? It's blocking checkout testing, which is due tomorrow.",
      },
    },
  },
  {
    id: "ss-written-status-update",
    departmentId: D,
    title: "Post a written status update with done, next and blockers",
    statement: "Can post a short written status update in the project channel with done, next and blockers, linked to the goal, with links instead of long explanations.",
    skillIds: ["ss-standup-updates", "ss-workplace-writing"],
    level: 2,
    aliases: ["async standup", "written status update", "status message", "eod update"],
    capstone: {
      kind: "task" as const,
      title: "Write the status update",
      task: {
        kind: "write",
        variant: "general",
        prompt: "Your team works across time zones and posts written stand-ups. Write today's update from your notes: done, next and blockers.",
        context: "Notes: finished the invoice PDF layout (on staging, link: staging.app/invoices). Spent the afternoon fixing a flaky test. Tomorrow: email the invoice to the customer automatically. Blocker: need the client's SMTP sender address approved; Meera (PM) is asking them. Sprint goal: customers receive invoices automatically by Friday.",
        wordLimit: 90,
        rubric: [
          { id: "done", label: "Done", description: "Invoice PDF layout finished and on staging, with the link.", weight: 1 },
          { id: "next", label: "Next", description: "Automatic invoice emails tomorrow.", weight: 1 },
          { id: "blocker", label: "Blocker", description: "The SMTP sender address approval, with Meera named as chasing it, and the risk to Friday's goal.", weight: 1.5 },
          { id: "short", label: "Short", description: "Three short lines or bullets; the flaky test only if relevant.", weight: 0.5 },
        ],
        sampleAnswer: "Done: invoice PDF layout is finished and on staging (staging.app/invoices).\nNext: sending the invoice to the customer by email automatically.\nBlocker: we need the client to approve the SMTP sender address; Meera is asking them. Without it, Friday's goal (automatic invoices) is at risk.",
      },
    },
  },
  {
    id: "ss-handover-before-leave",
    departmentId: D,
    title: "Hand over unfinished work clearly before leave",
    statement: "Can hand over unfinished work in writing before leave: status, where the code and notes are, open questions, next steps and who owns each item now.",
    skillIds: ["ss-ownership-time", "ss-workplace-writing"],
    level: 2,
    aliases: ["handover note", "hand over work", "before leave handover", "task handover"],
    capstone: {
      kind: "task" as const,
      title: "Write the handover note",
      task: {
        kind: "write",
        variant: "general",
        prompt: "You go on leave tomorrow for a week. Write the handover note for Kiran, who takes over your task.",
        context: "Task: social login (Google done, Apple in progress). Code: branch feature/social-login, PR #212 open as draft. Apple sign-in fails on the iOS simulator; works on device. Open question for the client: do they want Facebook login too (asked on Monday, no reply). Due: next Thursday's release.",
        wordLimit: 160,
        rubric: [
          { id: "status", label: "Status", description: "Google login done, Apple in progress, due for next Thursday's release.", weight: 1 },
          { id: "where", label: "Where things are", description: "Branch name and draft PR #212.", weight: 1 },
          { id: "issues", label: "Known issues and open questions", description: "Apple sign-in fails on the simulator but works on device; Facebook question pending with the client.", weight: 1.5 },
          { id: "owner", label: "Next steps and owner", description: "Says what Kiran should do next and that Kiran now owns it (and who chases the client).", weight: 1 },
        ],
        sampleAnswer: "Hi Kiran, handing over social login while I'm on leave (back next Monday).\n\nStatus: Google login is done. Apple login is in progress. Due for next Thursday's release.\nCode: branch feature/social-login, draft PR #212.\nKnown issue: Apple sign-in fails on the iOS simulator but works on a real device, so test on a device.\nOpen question: on Monday we asked the client if they also want Facebook login; no reply yet. Could you ask Meera to chase it?\nNext steps: finish the Apple callback, then move PR #212 out of draft for review.\nYou own this now; thanks!",
      },
    },
  },
  {
    id: "ss-polite-reply-angry-client",
    departmentId: D,
    title: "Write a polite reply to an angry client email",
    statement: "Can reply to an angry client email calmly: acknowledge the frustration once, give the facts and evidence without blame, make one clear ask and offer help.",
    skillIds: ["ss-workplace-writing", "ss-client-team-communication"],
    level: 3,
    aliases: ["angry client email", "reply to a complaint", "polite email", "rewrite a rude email"],
    capstone: topic("Rewrite a rude reply into a polite one", "soft-writing-bottom-line-first"),
  },
  {
    id: "ss-flag-slip-early",
    departmentId: D,
    title: "Flag a slipping deadline early with a new date",
    statement: "Can tell the PM or client as soon as a promised date will slip, with the new date, the reason in one sentence and what is being done.",
    skillIds: ["ss-ownership-time", "ss-workplace-writing"],
    level: 3,
    aliases: ["flag a delay", "deadline slipping", "early warning", "missed deadline message"],
    capstone: {
      kind: "task" as const,
      title: "Write the early-warning message",
      task: {
        kind: "write",
        variant: "email",
        prompt: "It is Tuesday. Write the message to your PM, Meera, about the slip below. She will forward the key part to the client.",
        context: "You promised the CSV import for Friday. The client's sample files use three different date formats, which you found today. Handling them adds two days, so Tuesday next week is realistic. You have already written the parser for two formats. Option: ship Friday with one format supported and add the rest on Tuesday.",
        wordLimit: 140,
        rubric: [
          { id: "first", label: "The slip first", description: "The first line says the CSV import moves from Friday to next Tuesday.", weight: 1.5 },
          { id: "reason", label: "Reason in one sentence", description: "Three date formats in the client's files, found today; no blame.", weight: 1 },
          { id: "plan", label: "Plan and option", description: "Says two formats are done and offers the option to ship Friday with one format.", weight: 1.5 },
          { id: "ask", label: "Ask", description: "Asks Meera which option the client prefers, or by when she needs to decide.", weight: 1 },
        ],
        sampleAnswer: "Subject: CSV import moves from Friday to next Tuesday\n\nHi Meera,\n\nThe CSV import will be ready next Tuesday, not this Friday. Today I found the client's sample files use three different date formats, and handling all three adds two days.\n\nTwo formats are already done. Option: we ship on Friday with one format supported and add the other two on Tuesday.\n\nCould you check with the client which they prefer? If I know by Thursday noon, either plan works.\n\nThanks,\nArjun",
      },
    },
  },
  {
    id: "ss-call-summary-decisions",
    departmentId: D,
    title: "Summarise a client call and confirm the decisions in writing",
    statement: "Can send a short written summary after a client call with the decisions, the open questions and the actions with owners and dates, the same day.",
    skillIds: ["ss-listening-questions", "ss-workplace-writing", "ss-client-team-communication"],
    level: 3,
    aliases: ["meeting summary", "call notes", "minutes", "recap email", "summarise a meeting"],
    capstone: {
      kind: "task" as const,
      title: "Write the call summary",
      task: {
        kind: "write",
        variant: "email",
        prompt: "Write the follow-up email to the client after the call below. Keep it short and easy to scan.",
        context: "Call notes (messy): client (Laura) ok to move push notifications to phase 2. Logo files - Laura sends by Wed. We share staging build Fri. Laura asked if Apple login is possible - we said we'd check effort and reply Mon. Payment provider stays Stripe. Next call Tue 10am UK.",
        wordLimit: 170,
        rubric: [
          { id: "decisions", label: "Decisions", description: "Push notifications move to phase 2; Stripe stays as the payment provider.", weight: 1.5 },
          { id: "actions", label: "Actions with owners and dates", description: "Laura sends logo files by Wednesday; we share staging build Friday; we reply on Apple login by Monday.", weight: 1.5 },
          { id: "next", label: "Next meeting", description: "Tuesday 10 am UK time.", weight: 0.5 },
          { id: "scan", label: "Easy to scan", description: "Short sections or bullets; subject says it is a call summary.", weight: 1 },
        ],
        sampleAnswer: "Subject: Summary of today's call: decisions and next steps\n\nHi Laura,\n\nThanks for today's call. Here is what we agreed.\n\nDecisions:\n- Push notifications move to phase 2.\n- The payment provider stays Stripe.\n\nActions:\n- Laura: send the logo files by Wednesday.\n- Oyelabs: share the staging build on Friday.\n- Oyelabs: reply on the effort for Apple login by Monday.\n\nNext call: Tuesday, 10 am UK time.\n\nPlease let me know if I missed anything.\n\nBest regards,\nMeera",
      },
    },
  },
  // -------------------------------------------------------------------------
  // Explaining and listening
  // -------------------------------------------------------------------------
  {
    id: "ss-explain-term-client",
    departmentId: D,
    title: "Explain a technical term to a client in three sentences",
    statement: "Can explain a technical term or decision to a non-technical client in three plain sentences that lead with what it means for them.",
    skillIds: ["ss-explain-simply"],
    level: 2,
    aliases: ["explain an api", "explain to non-technical", "jargon-free explanation", "explain to a client"],
    capstone: topic("Explain an API to a client in three sentences", "soft-explain-for-your-audience"),
  },
  {
    id: "ss-clarify-before-estimating",
    departmentId: D,
    title: "Ask clarifying questions before estimating a task",
    statement: "Can turn a vague request into five specific clarifying questions about the goal, users, edge cases, scope and deadline before giving an estimate.",
    skillIds: ["ss-listening-questions"],
    level: 2,
    aliases: ["clarifying questions", "requirement questions", "before estimating", "vague request"],
    capstone: topic("Write the clarifying questions for a vague request", "soft-listening-clarify-first"),
  },
  {
    id: "ss-explain-incident-stakeholder",
    departmentId: D,
    title: "Explain a production bug and its fix to a non-technical stakeholder",
    statement: "Can explain a production incident to a non-technical stakeholder: impact first, cause in everyday words, the fix, and what prevents a repeat.",
    skillIds: ["ss-explain-simply", "ss-client-team-communication"],
    level: 4,
    aliases: ["incident explanation", "explain an outage", "post-incident update", "bug explanation"],
    capstone: {
      kind: "task" as const,
      title: "Explain the incident",
      task: {
        kind: "write",
        variant: "explain",
        prompt: "Write the short update to the client's operations director (not technical) about the incident below.",
        context: "Yesterday 18:00-18:40 UK time, customers could not complete orders. Cause: a database update ran during peak hours and locked the orders table. Fix: the update was stopped and orders worked again at 18:40; 37 customers saw an error, none were charged. Prevention: database updates now run only between 02:00 and 05:00 and are tested on a copy of live data first.",
        wordLimit: 140,
        rubric: [
          { id: "impact", label: "Impact first", description: "Says customers could not order for 40 minutes, 37 saw an error, nobody was charged.", weight: 1.5 },
          { id: "cause", label: "Cause in everyday words", description: "Explains the cause without jargon (no 'locked the table'; e.g. 'a maintenance update blocked new orders').", weight: 1.5 },
          { id: "fix", label: "Fix and prevention", description: "Says it was fixed at 18:40 and what changes prevent a repeat.", weight: 1 },
          { id: "tone", label: "Calm and accountable", description: "Owns the issue, no blame, no excessive apology.", weight: 1 },
        ],
        sampleAnswer: "Yesterday from 18:00 to 18:40 UK time, customers could not complete orders. 37 customers saw an error; nobody was charged.\n\nThe cause was a maintenance update we ran during your busy evening hours, which blocked new orders while it ran. We stopped it and ordering worked again at 18:40.\n\nTo stop this happening again, maintenance updates now run only between 2 am and 5 am and are tested on a copy of the live system first. We are sorry for the disruption and are happy to talk it through.",
      },
    },
  },
  {
    id: "ss-difficult-client-conversation",
    departmentId: D,
    title: "Stay calm and steer a difficult client conversation to next steps",
    statement: "Can stay calm when a client is upset, listen and reflect back the concern, separate facts from frustration and agree concrete next steps.",
    skillIds: ["ss-client-team-communication", "ss-listening-questions"],
    level: 4,
    aliases: ["difficult conversation", "upset client", "angry client call", "de-escalate"],
    capstone: {
      kind: "task" as const,
      title: "Handle the upset client",
      task: {
        kind: "scenario",
        prompt: "On a call, the client's founder says: \"Every release breaks something. I'm starting to think we chose the wrong agency.\" Two bugs reached production in the last month.",
        steps: [
          {
            id: "s1",
            question: "What do you say first?",
            options: [
              "Acknowledge it and reflect back: \"Two bugs reaching your users in a month is frustrating, and it makes you doubt the releases. Is that right?\"",
              "\"Those bugs were minor, honestly.\"",
              "\"Your team didn't test in UAT either.\"",
              "Promise there will never be another bug",
            ],
            correctIndex: 0,
            explanation: "Acknowledge and reflect back first: the founder needs to feel heard before facts land.",
          },
          {
            id: "s2",
            question: "The founder calms down a little. What next?",
            options: [
              "Separate facts from frustration: list the two bugs, their cause, and what you changed after each",
              "Move on to the next agenda item",
              "Offer a big discount immediately",
              "Ask them to put the complaint in writing",
            ],
            correctIndex: 0,
            explanation: "Specific facts and what changed rebuild trust better than general reassurance.",
          },
          {
            id: "s3",
            question: "How do you close this part of the call?",
            options: [
              "Agree concrete next steps (for example a release checklist and a smoke test on staging before each release), with owners and dates, and confirm them in writing",
              "Say you will try harder",
              "End the call early",
              "Blame the QA engineer",
            ],
            correctIndex: 0,
            explanation: "Close on owners and dates, then follow up in writing.",
          },
        ],
      },
    },
  },
  // -------------------------------------------------------------------------
  // Ownership, feedback and teamwork
  // -------------------------------------------------------------------------
  {
    id: "ss-prioritise-busy-day",
    departmentId: D,
    title: "Prioritise a busy day by urgency and importance",
    statement: "Can order a day's competing tasks by urgency and importance, unblock others early and protect time for important work that is not urgent.",
    skillIds: ["ss-ownership-time"],
    level: 2,
    aliases: ["prioritise tasks", "time management", "eisenhower", "busy day planning"],
    capstone: topic("Order a busy day's tasks", "soft-ownership-own-the-outcome"),
  },
  {
    id: "ss-receive-review-feedback",
    departmentId: D,
    title: "Respond to critical review feedback without getting defensive",
    statement: "Can respond to critical feedback on their work by listening, thanking, asking for specifics and deciding on the change, without getting defensive.",
    skillIds: ["ss-feedback"],
    level: 2,
    aliases: ["receive feedback", "respond to review comments", "take feedback well"],
    capstone: {
      kind: "task" as const,
      title: "Respond to the review",
      task: {
        kind: "scenario",
        prompt: "The tech lead leaves this comment on your PR: \"This component is hard to follow. Please restructure.\" You spent two days on it and think it is fine.",
        steps: [
          {
            id: "s1",
            question: "What is the best first reply?",
            options: [
              "\"Thanks for looking. Could you point to the part that's hardest to follow, or an example of the structure you'd prefer?\"",
              "\"It's fine, I tested it.\"",
              "Restructure everything without asking",
              "Ignore the comment and merge after another approval",
            ],
            correctIndex: 0,
            explanation: "Thank, then ask for specifics: a vague comment needs an example before you can act on it.",
          },
          {
            id: "s2",
            question: "The tech lead explains that the component mixes data fetching and display, so it is hard to test. You partly agree. What now?",
            options: [
              "Agree on the part that makes sense (split fetching into a hook), explain the part you would keep, and make the change",
              "Agree to everything to avoid conflict",
              "Refuse because it works",
              "Escalate to the PM",
            ],
            correctIndex: 0,
            explanation: "Separate the useful point from the rest, discuss with reasons, then act.",
          },
        ],
      },
    },
  },
  {
    id: "ss-pr-feedback-sbi",
    departmentId: D,
    title: "Give a teammate feedback on a PR using SBI",
    statement: "Can give PR feedback that names the situation, describes the code's behaviour, states the impact and asks about intent or suggests a fix, kindly and specifically.",
    skillIds: ["ss-feedback"],
    level: 3,
    aliases: ["sbi feedback", "pr review comment", "code review feedback", "constructive feedback"],
    capstone: topic("Write an SBI review comment", "soft-feedback-sbi"),
  },
  {
    id: "ss-working-agreement",
    departmentId: D,
    title: "Draft a team working agreement for a new project",
    statement: "Can draft a working agreement for a new project team covering core hours, response times, code review, the definition of done, decisions and how problems are raised.",
    skillIds: ["ss-teamwork"],
    level: 3,
    aliases: ["working agreement", "team agreement", "team norms", "team charter"],
    capstone: {
      kind: "task" as const,
      title: "Draft the working agreement",
      task: {
        kind: "write",
        variant: "general",
        prompt: "Draft a working agreement (6 to 8 short points) for the new project team below, to discuss in the first team meeting.",
        context: "Team: two backend developers and a QA engineer in India (IST), a designer in Poland (CET), and a client product owner in the UK. Problems so far: PRs waited three days for review, decisions were made in private chats, and nobody agreed what 'done' means.",
        wordLimit: 200,
        rubric: [
          { id: "hours", label: "Core hours", description: "Sets overlap hours that work across IST, CET and UK time.", weight: 1 },
          { id: "response", label: "Response and review times", description: "Sets chat response times and a review time limit (e.g. within one working day).", weight: 1.5 },
          { id: "done", label: "Definition of done", description: "Defines done (e.g. merged, tested on staging, ticket updated).", weight: 1 },
          { id: "decisions", label: "Decisions in the open", description: "Decisions are written in the project channel with an owner.", weight: 1 },
          { id: "problems", label: "Raising problems", description: "Problems are raised early and without blame.", weight: 1 },
        ],
        sampleAnswer: "1. Core hours: 1:30 pm to 5:30 pm IST (9 am to 1 pm UK), when everyone is online.\n2. Chat: reply within 2 hours in core hours; anything urgent goes by call.\n3. Code review: within one working day; one approval plus QA sign-off before merge.\n4. Done means merged, tested on staging by QA, and the ticket updated.\n5. Decisions go in the project channel with the owner's name, never only in private chat.\n6. Problems are raised the same day, without blame.\n7. We review this agreement at every retrospective.",
      },
    },
  },
  {
    id: "ss-handle-mistake-blameless",
    departmentId: D,
    title: "Handle a teammate's mistake without blame",
    statement: "Can respond to a teammate's mistake in a way that keeps the team safe to raise problems: focus on what happened and how to prevent it, not on who did it.",
    skillIds: ["ss-teamwork", "ss-feedback"],
    level: 4,
    aliases: ["blameless", "psychological safety", "blameless retro", "handle a mistake"],
    capstone: topic("Help a new team work together", "soft-teamwork-safety-and-agreements"),
  },
  {
    id: "ss-coach-feedback-culture",
    departmentId: D,
    title: "Coach a junior teammate to give and ask for feedback",
    statement: "Can coach a junior teammate to give SBI feedback and to ask for feedback on their own work, and model it in reviews and retrospectives.",
    skillIds: ["ss-feedback", "ss-teamwork"],
    level: 5,
    aliases: ["coach feedback", "mentor junior", "feedback culture"],
    capstone: {
      kind: "task" as const,
      title: "Coach the junior teammate",
      task: {
        kind: "write",
        variant: "general",
        prompt: "Write the message you would send a junior teammate to coach them, based on the situation below. Use SBI for your own feedback, and give them one simple way to ask for feedback themselves.",
        context: "Ravi (junior, 6 months in) left this PR comment for a peer yesterday: \"This is wrong, redo it.\" The peer was upset. Ravi also never asks for reviews early; his own PRs arrive huge on the last day of the sprint.",
        wordLimit: 200,
        rubric: [
          { id: "sbi", label: "SBI for Ravi", description: "Names the situation (yesterday's PR comment), the behaviour (the exact words), and the impact (the peer was upset and did not know what to fix).", weight: 1.5 },
          { id: "intent", label: "Intent or reframe", description: "Asks what Ravi meant or shows how the comment could be rewritten with the reason and a suggested fix.", weight: 1 },
          { id: "ask", label: "Asking for feedback", description: "Gives one simple way to ask for feedback early, e.g. open a draft PR halfway and ask one specific question.", weight: 1.5 },
          { id: "tone", label: "Supportive tone", description: "Kind, specific and encouraging; not a reprimand.", weight: 1 },
        ],
        sampleAnswer: "Hi Ravi, a quick thought on code reviews. In yesterday's review of Asha's PR, the comment \"This is wrong, redo it\" didn't say what was wrong, so she was upset and unsure what to fix. What were you seeing? If it was the date handling, something like \"Must fix: this parses dates in local time, so UK orders show the wrong day. Could we use UTC here?\" gives her the reason and a way forward.\n\nOne more idea for your own work: open a draft PR halfway through a task and ask one question, such as \"Is this structure OK before I build the rest?\" You'll get feedback while it's cheap to change. Happy to pair on the next review if useful.",
      },
    },
  },
  {
    id: "ss-client-communication-plan",
    departmentId: D,
    title: "Set up how the team and the client will communicate",
    statement: "Can set up a client communication plan at project start: who needs what, the channels, the cadence, response times, escalation and where decisions are recorded.",
    skillIds: ["ss-client-team-communication", "ss-teamwork"],
    level: 5,
    aliases: ["communication plan", "stakeholder communication", "client cadence", "escalation path"],
    capstone: {
      kind: "task" as const,
      title: "Write the communication plan",
      task: {
        kind: "write",
        variant: "general",
        prompt: "Write the communication plan you would agree with the client at kickoff for the project below (bullets are fine).",
        context: "Client: a retail chain in Australia (AEST), building a loyalty app. People: their CEO (wants a short monthly view), product owner (daily contact), IT lead (needs releases and access). Our team in India (IST). Overlap: about 3 hours a day.",
        wordLimit: 220,
        rubric: [
          { id: "who", label: "Who needs what", description: "Different content for the CEO, product owner and IT lead.", weight: 1.5 },
          { id: "channel", label: "Channels and cadence", description: "Names channels and how often (e.g. daily chat, weekly call, monthly summary for the CEO).", weight: 1 },
          { id: "response", label: "Response times and overlap", description: "Uses the overlap hours and sets reply times.", weight: 1 },
          { id: "escalation", label: "Escalation and decisions", description: "Says how urgent issues are escalated and where decisions are recorded.", weight: 1.5 },
        ],
        sampleAnswer: "- Product owner: daily updates in the shared Teams channel during the overlap (2 pm to 5 pm AEST); weekly 30-minute call on Tuesdays with demo and decisions.\n- CEO: one-page monthly summary by email: progress against milestones, risks, decisions needed.\n- IT lead: release notes two days before each release; access requests tracked in a shared list.\n- Response times: replies within 4 working hours; urgent production issues by phone to the PM at any time.\n- Escalation: PM, then delivery head, within one working day if unresolved.\n- Decisions: written in the project channel and in the weekly call notes, with an owner and date.",
      },
    },
  },
  {
    id: "ss-run-timeboxed-standup",
    departmentId: D,
    title: "Run a stand-up that stays within 15 minutes",
    statement: "Can run a team stand-up that stays within 15 minutes: each person gives done, next and blockers, side topics are parked and risks to the sprint goal are picked up.",
    skillIds: ["ss-standup-updates", "ss-teamwork"],
    level: 3,
    aliases: ["run a standup", "facilitate standup", "timebox standup", "scrum master standup"],
    capstone: {
      kind: "task" as const,
      title: "Keep the stand-up on track",
      task: {
        kind: "scenario",
        prompt: "You run today's stand-up for a team of six. It is already at minute 9 and only three people have spoken.",
        steps: [
          {
            id: "s1",
            question: "Two developers start debating a database design. What do you do?",
            options: [
              "Park it: \"Let's take that straight after stand-up with you two\" and move to the next person",
              "Let them finish; it's important",
              "Make the decision for them on the spot",
              "End the stand-up",
            ],
            correctIndex: 0,
            explanation: "Park side topics for the people involved; the rest of the team should not wait.",
          },
          {
            id: "s2",
            question: "The next person starts listing every file they touched. What do you do?",
            options: [
              "Gently ask for done, next and blockers in one line each",
              "Interrupt and skip them",
              "Let them continue",
              "Ask them to send it by email instead",
            ],
            correctIndex: 0,
            explanation: "Remind the shape kindly: results, plan, blockers.",
          },
          {
            id: "s3",
            question: "Someone mentions in passing that the client's API keys still have not arrived. What do you do after stand-up?",
            options: [
              "Treat it as a blocker to the sprint goal: take the action to chase the client today and tell the team when it is resolved",
              "Assume they will sort it out",
              "Add it to next week's retrospective",
              "Ignore it, it was said in passing",
            ],
            correctIndex: 0,
            explanation: "Listen for blockers and risks to the goal; they become your actions for the day.",
          },
        ],
      },
    },
  },
] satisfies PracticalOutcomeSeed[];
