#!/usr/bin/env node
// Checks every reference URL (topic webRefs and module refs) for HTTP status and whether the
// site allows being shown in an <iframe> (X-Frame-Options / CSP frame-ancestors), then writes
// src/content/embeds.generated.ts. The topic page only attempts inline previews for URLs marked
// embeddable here, and still falls back to a link card if the frame doesn't load in time.
//
//   npm run content:embeds
import fs from "node:fs";
import path from "node:path";
import { checkUrl } from "../research/check-urls.mjs";
import { CONTENT_DIR, loadCurriculum } from "./load.mjs";

const { loaded } = await loadCurriculum();
const urls = new Set();
for (const { mod } of loaded) {
  for (const r of mod.refs ?? []) urls.add(r.url);
  for (const t of mod.topics) for (const r of t.webRefs) urls.add(r.url);
}

const list = [...urls].sort();
const results = [];
const CONCURRENCY = 8;
for (let i = 0; i < list.length; i += CONCURRENCY) {
  results.push(...(await Promise.all(list.slice(i, i + CONCURRENCY).map(checkUrl))));
}

const broken = results.filter((r) => r.status === 0 || r.status >= 400);
const verdicts = Object.fromEntries(
  results.map((r) => [
    r.url,
    { embeddable: r.embeddable && r.status > 0 && r.status < 400, reason: r.status >= 400 || r.status === 0 ? `HTTP ${r.status}` : r.reason },
  ]),
);
const embeddableCount = Object.values(verdicts).filter((v) => v.embeddable).length;

const byHost = new Map();
for (const r of results) {
  const host = new URL(r.url).hostname.replace(/^www\./, "");
  const entry = byHost.get(host) ?? { embeddable: 0, blocked: 0, reasons: new Set() };
  if (r.embeddable) entry.embeddable++;
  else {
    entry.blocked++;
    entry.reasons.add(r.reason);
  }
  byHost.set(host, entry);
}

// Compact map shipped to the browser: 1 = the site allows framing, 0 = it blocks it (or is unreachable).
const compact = Object.fromEntries(Object.entries(verdicts).map(([url, v]) => [url, v.embeddable ? 1 : 0]));
const date = new Date().toISOString().slice(0, 10);
const out = `// AUTO-GENERATED by scripts/content/check-embeds.mjs on ${date}. Do not edit by hand.
// Whether each reference URL's site allows being shown in an iframe on another origin, based on
// X-Frame-Options and CSP frame-ancestors response headers: 1 = allowed, 0 = blocked.
// Per-site reasons are in docs/EMBEDDING.md.
export const embedVerdicts: Record<string, 0 | 1> = ${JSON.stringify(compact)};
`;
fs.writeFileSync(path.join(CONTENT_DIR, "embeds.generated.ts"), out);

const siteRows = [...byHost].sort((a, b) => a[0].localeCompare(b[0])).map(([host, e]) => {
  const verdict = e.blocked === 0 ? "allows framing" : e.embeddable === 0 ? "blocks framing" : "mixed (per page)";
  return { host, verdict, reasons: [...e.reasons].join("; ") };
});
const report = `# Reference previews: which sites allow embedding

Generated by \`npm run content:embeds\` on ${date}. ${results.length} reference URLs checked: ${embeddableCount} can be previewed inline, ${results.length - embeddableCount} can't, ${broken.length} broken.

Sites that send \`X-Frame-Options\` (DENY/SAMEORIGIN) or a restrictive CSP \`frame-ancestors\` can't be shown inside another site. Browsers still fire the iframe's \`load\` event for those blocked frames, so the app relies on this header check: blocked sites get a link card, allowed sites get an inline preview (with a timeout fallback).

| Site | Verdict | Blocking header |
| --- | --- | --- |
${siteRows.map((r) => `| ${r.host} | ${r.verdict} | ${r.reasons.replace(/\|/g, "\\|") || ""} |`).join("\n")}
`;
fs.writeFileSync(path.join(CONTENT_DIR, "..", "..", "docs", "EMBEDDING.md"), report);

console.log(`Checked ${results.length} URLs: ${embeddableCount} embeddable, ${broken.length} broken.\n`);
console.log("By site:");
for (const r of siteRows) console.log(`  ${r.host.padEnd(34)} ${r.verdict.padEnd(17)} ${r.reasons}`);
if (broken.length) {
  console.log("\nBroken or unreachable:");
  for (const b of broken) console.log(`  ${b.status}  ${b.url}  ${b.reason}`);
  process.exitCode = 1;
}
