#!/usr/bin/env node
// Checks every reference URL (topic webRefs and module refs) for HTTP status and whether the
// site allows being shown in an <iframe> (X-Frame-Options / CSP frame-ancestors), then writes
// src/content/embeds.generated.ts. The topic page only attempts inline previews for URLs marked
// embeddable here, and still falls back to a link card if the frame doesn't load in time.
//
//   npm run content:embeds
import fs from "node:fs";
import path from "node:path";
import { checkUrl } from "../research/check-urls.mjs";
import { CONTENT_DIR, loadCurriculum } from "./load.mjs";

const { loaded } = await loadCurriculum();
const urls = new Set();
for (const { mod } of loaded) {
  for (const r of mod.refs ?? []) urls.add(r.url);
  for (const t of mod.topics) for (const r of t.webRefs) urls.add(r.url);
}

const list = [...urls].sort();
const results = [];
const CONCURRENCY = 8;
for (let i = 0; i < list.length; i += CONCURRENCY) {
  results.push(...(await Promise.all(list.slice(i, i + CONCURRENCY).map(checkUrl))));
}

const broken = results.filter((r) => r.status === 0 || r.status >= 400);
const embeddable = Object.fromEntries(results.filter((r) => r.embeddable && r.status > 0 && r.status < 400).map((r) => [r.url, true]));

const byHost = new Map();
for (const r of results) {
  const host = new URL(r.url).hostname.replace(/^www\./, "");
  const entry = byHost.get(host) ?? { embeddable: 0, blocked: 0, reasons: new Set() };
  if (r.embeddable) entry.embeddable++;
  else {
    entry.blocked++;
    entry.reasons.add(r.reason);
  }
  byHost.set(host, entry);
}

const out = `// AUTO-GENERATED by scripts/content/check-embeds.mjs on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.
// URLs whose sites allow being framed by other origins (no X-Frame-Options / restrictive frame-ancestors).
export const embeddableUrls: Record<string, true> = ${JSON.stringify(embeddable, null, 2)};
`;
fs.writeFileSync(path.join(CONTENT_DIR, "embeds.generated.ts"), out);

console.log(`Checked ${results.length} URLs: ${Object.keys(embeddable).length} embeddable, ${broken.length} broken.\n`);
console.log("By site:");
for (const [host, e] of [...byHost].sort((a, b) => a[0].localeCompare(b[0]))) {
  const verdict = e.blocked === 0 ? "allows framing" : e.embeddable === 0 ? "blocks framing" : "mixed";
  console.log(`  ${host.padEnd(34)} ${verdict.padEnd(15)} ${[...e.reasons].join("; ")}`);
}
if (broken.length) {
  console.log("\nBroken or unreachable:");
  for (const b of broken) console.log(`  ${b.status}  ${b.url}  ${b.reason}`);
  process.exitCode = 1;
}
