/**
 * Writes docs/v4/CURRICULUM.md from the real sources: the skill catalog, the content trails and the
 * question bank seed (validated items only).
 *
 *   npx tsx scripts/v4/curriculum-report.ts
 */
import fs from "node:fs";
import path from "node:path";

import { BANK_MIN_PER_SKILL } from "../../shared/bank";
import { loadSeedItems, itemHash } from "../../server/src/bank/repo";
import { SEED_DEPARTMENTS, SEED_SKILLS, SEED_TRACKS } from "../../server/src/catalog/seed";

const root = path.resolve(import.meta.dirname, "../..");
const contentDir = path.join(root, "server/content");
const registry = {
  tracks: JSON.parse(fs.readFileSync(path.join(contentDir, "registry.json"), "utf8")) as { id: string; name: string; modules: { id: string; name: string }[] }[],
};

type Topic = { id: string; level: string; quiz?: unknown[]; codeChallenge?: unknown; practice?: { kind: string }; video?: unknown; webRefs?: unknown[] };
function moduleTopics(trackId: string, moduleId: string): Topic[] {
  const file = path.join(contentDir, trackId, `${moduleId}.json`);
  if (!fs.existsSync(file)) return [];
  return (JSON.parse(fs.readFileSync(file, "utf8")) as { topics: Topic[] }).topics;
}

const { items, validated } = loadSeedItems(path.join(root, "server/bank"));
const active = items.filter((item) => validated[item.id] === itemHash(item));

const lines: string[] = [];
const out = (line = "") => lines.push(line);
out("# Oyelearn v4 — curriculum and question bank");
out();
out(`Generated by \`scripts/v4/curriculum-report.ts\` on ${new Date().toISOString().slice(0, 10)}. Counts are from the repository, not estimates.`);
out();

for (const dept of SEED_DEPARTMENTS) {
  const skills = SEED_SKILLS.filter((s) => s.departmentId === dept.id);
  const tracks = SEED_TRACKS.filter((t) => t.departmentId === dept.id);
  const deptItems = active.filter((i) => i.departmentId === dept.id);
  out(`## ${dept.name}`);
  out();
  out(`- Tracks: ${tracks.map((t) => t.name).join(", ")}`);
  out(`- Skills in the catalog: **${skills.length}** (${skills.filter((s) => s.isAiSkill).length} AI-for-your-role)`);
  out(`- Active bank items: **${deptItems.length}** — ${deptItems.filter((i) => i.type === "coding").length} coding, ${deptItems.filter((i) => i.type === "task").length} tasks, ${deptItems.filter((i) => i.type === "mcq").length} MCQs`);
  out();
  out("| Level | Skills (levelMin) | Skills with bank items |");
  out("| --- | --- | --- |");
  for (const level of ["beginner", "intermediate", "advanced", "expert"] as const) {
    const atLevel = skills.filter((s) => s.levelMin === level);
    const covered = atLevel.filter((s) => deptItems.some((i) => i.skillId === s.id));
    out(`| ${level === "expert" ? "Super advanced" : level[0].toUpperCase() + level.slice(1)} | ${atLevel.length} | ${covered.length} |`);
  }
  out();

  // Courses: content trails that belong to this department.
  const trails = registry.tracks.filter((t) => (dept.id === "engineering" ? !["pm", "bd"].includes(t.id) : t.id === dept.id));
  let topics = 0;
  let questions = 0;
  let practice = 0;
  out("| Course (trail · camp) | Topics | Quiz questions | Practice tasks |");
  out("| --- | --- | --- | --- |");
  for (const trail of trails) {
    for (const mod of trail.modules) {
      const t = moduleTopics(trail.id, mod.id);
      const q = t.reduce((sum, x) => sum + (x.quiz?.length ?? 0), 0);
      const p = t.filter((x) => x.practice).length;
      topics += t.length;
      questions += q;
      practice += p;
      if (dept.id !== "engineering") out(`| ${trail.name} · ${mod.name} | ${t.length} | ${q} | ${p} |`);
    }
  }
  if (dept.id === "engineering") out(`| ${trails.length} trails, ${trails.reduce((s, t) => s + t.modules.length, 0)} camps | ${topics} | ${questions} | — |`);
  out();

  const thin = skills.filter((s) => {
    const mine = deptItems.filter((i) => i.skillId === s.id);
    const handsOn = mine.filter((i) => i.type !== "mcq").length;
    const mcq = mine.filter((i) => i.type === "mcq").length;
    return handsOn < BANK_MIN_PER_SKILL.task || mcq < BANK_MIN_PER_SKILL.mcq;
  });
  const noCourse = skills.filter((s) => s.contentModules.length === 0);
  out(`- Skills still thin in the bank (< ${BANK_MIN_PER_SKILL.task} hands-on or < ${BANK_MIN_PER_SKILL.mcq} MCQs): **${thin.length}**. The assembler gives their questions to the next skill and queues a one-off \`bank.fill\` (needs an AI credential).`);
  out(`- Skills with no catalog course module: **${noCourse.length}**${noCourse.length ? ` (${noCourse.slice(0, 12).map((s) => s.name).join(", ")}${noCourse.length > 12 ? ", …" : ""})` : ""}. The path builder matches or generates a course for these.`);
  out();
}

fs.writeFileSync(path.join(root, "docs/v4/CURRICULUM.md"), `${lines.join("\n")}\n`);
console.log(lines.slice(0, 40).join("\n"));
