// AUTO-GENERATED by scripts/content/check-embeds.mjs. Do not edit by hand.
// Whether each reference URL's site allows being shown in an iframe on another origin.
export const embedVerdicts: Record<string, { embeddable: boolean; reason: string }> = {};
