// AUTO-GENERATED by scripts/content/build-manifest.mjs. Do not edit by hand.
// Regenerate with `npm run content:manifest` (runs automatically before dev and build).
import type { TrackMeta } from "./manifest-types";

export const manifest: TrackMeta[] = [
  {
    "id": "frontend",
    "name": "Frontend",
    "tagline": "From the browser's rendering model to production React, Next.js and Vue.",
    "accentToken": "trailmark",
    "modules": [
      {
        "id": "fe-tooling",
        "trackId": "frontend",
        "name": "Dev Environment & Tooling",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "fe-html-css",
        "trackId": "frontend",
        "name": "HTML & CSS Foundations",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "fe-js-core",
        "trackId": "frontend",
        "name": "JavaScript Core",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "fe-js-advanced",
        "trackId": "frontend",
        "name": "JavaScript Advanced & Interview-Level",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "fe-typescript",
        "trackId": "frontend",
        "name": "TypeScript",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "fe-tailwind",
        "trackId": "frontend",
        "name": "Tailwind CSS",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "fe-react-fundamentals",
        "trackId": "frontend",
        "name": "React Fundamentals",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "fe-react-hooks",
        "trackId": "frontend",
        "name": "React Hooks & Advanced Patterns",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "fe-react-ecosystem",
        "trackId": "frontend",
        "name": "React Ecosystem",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "fe-react-projects",
        "trackId": "frontend",
        "name": "React Practice Projects",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "fe-nextjs",
        "trackId": "frontend",
        "name": "Next.js",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "fe-vue",
        "trackId": "frontend",
        "name": "Vue.js",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "fe-meta-mobile",
        "trackId": "frontend",
        "name": "Meta-Frameworks, Mobile & Bonus",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "fe-security-perf",
        "trackId": "frontend",
        "name": "Frontend Security & Performance",
        "description": "",
        "topics": [],
        "available": false
      }
    ]
  },
  {
    "id": "backend",
    "name": "Backend",
    "tagline": "Runtimes, APIs, data, security and the systems thinking behind them.",
    "accentToken": "summit",
    "modules": [
      {
        "id": "be-foundations",
        "trackId": "backend",
        "name": "Web & Backend Foundations",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "be-node-core",
        "trackId": "backend",
        "name": "Node.js Core",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "be-express",
        "trackId": "backend",
        "name": "Express.js",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "be-sql",
        "trackId": "backend",
        "name": "SQL & Relational Databases",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "be-nosql",
        "trackId": "backend",
        "name": "NoSQL & Caching",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "be-auth-security",
        "trackId": "backend",
        "name": "Authentication & Security",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "be-api-design",
        "trackId": "backend",
        "name": "API Design",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "be-nestjs",
        "trackId": "backend",
        "name": "NestJS",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "be-python",
        "trackId": "backend",
        "name": "Python Backend",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "be-docker",
        "trackId": "backend",
        "name": "Docker & Containers",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "be-system-design",
        "trackId": "backend",
        "name": "System Design Fundamentals",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "be-testing-ops",
        "trackId": "backend",
        "name": "Backend Testing & Ops",
        "description": "",
        "topics": [],
        "available": false
      }
    ]
  },
  {
    "id": "fullstack",
    "name": "Full-Stack",
    "tagline": "Wire frontend to backend and ship real, authenticated apps end to end.",
    "accentToken": "glacier",
    "modules": [
      {
        "id": "fs-mern",
        "trackId": "fullstack",
        "name": "MERN End-to-End",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "fs-nextjs",
        "trackId": "fullstack",
        "name": "Next.js Full-Stack",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "fs-t3",
        "trackId": "fullstack",
        "name": "The T3 Stack & End-to-End Type Safety",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "fs-graphql",
        "trackId": "fullstack",
        "name": "GraphQL Full-Stack",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "fs-capstone",
        "trackId": "fullstack",
        "name": "Full-Stack Capstone & Deployment",
        "description": "",
        "topics": [],
        "available": false
      }
    ]
  },
  {
    "id": "ai-driven",
    "name": "AI-Driven Development",
    "tagline": "Use AI coding tools deliberately, from prompts and context to RAG and agents.",
    "accentToken": "ridge",
    "modules": [
      {
        "id": "ai-tools",
        "trackId": "ai-driven",
        "name": "The AI Coding Tools Landscape",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "ai-prompting",
        "trackId": "ai-driven",
        "name": "Prompt Engineering",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "ai-context",
        "trackId": "ai-driven",
        "name": "Context Engineering & AI Pair Programming",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "ai-llm",
        "trackId": "ai-driven",
        "name": "LLM Fundamentals",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "ai-rag",
        "trackId": "ai-driven",
        "name": "Retrieval-Augmented Generation",
        "description": "",
        "topics": [],
        "available": false
      },
      {
        "id": "ai-agents",
        "trackId": "ai-driven",
        "name": "AI Agents",
        "description": "",
        "topics": [],
        "available": false
      }
    ]
  }
];
