// The curriculum's table of contents. Module content lives in src/content/<trackId>/<moduleId>.ts
// (default export `satisfies Module`); this file fixes the order of tracks and modules.
import type { AccentToken, TrackId } from "@/types/curriculum";

export interface ModuleEntry {
  id: string;
  name: string;
  /** Recommended prefix for topic ids in this module (ids must be unique across the whole curriculum). */
  idPrefix: string;
}

export interface TrackEntry {
  id: TrackId;
  name: string;
  tagline: string;
  accentToken: AccentToken;
  modules: ModuleEntry[];
}

export const registry: TrackEntry[] = [
  {
    id: "frontend",
    name: "Frontend",
    tagline: "From the browser's rendering model to production React, Next.js and Vue.",
    accentToken: "trailmark",
    modules: [
      { id: "fe-tooling", name: "Dev Environment & Tooling", idPrefix: "tooling-" },
      { id: "fe-html-css", name: "HTML & CSS Foundations", idPrefix: "html-/css-" },
      { id: "fe-js-core", name: "JavaScript Core", idPrefix: "js-" },
      { id: "fe-js-advanced", name: "JavaScript Advanced & Interview-Level", idPrefix: "js-" },
      { id: "fe-typescript", name: "TypeScript", idPrefix: "ts-" },
      { id: "fe-tailwind", name: "Tailwind CSS", idPrefix: "tw-" },
      { id: "fe-react-fundamentals", name: "React Fundamentals", idPrefix: "react-" },
      { id: "fe-react-hooks", name: "React Hooks & Advanced Patterns", idPrefix: "react-adv-" },
      { id: "fe-react-ecosystem", name: "React Ecosystem", idPrefix: "react-eco-" },
      { id: "fe-react-projects", name: "React Practice Projects", idPrefix: "react-capstone-" },
      { id: "fe-nextjs", name: "Next.js", idPrefix: "next-" },
      { id: "fe-vue", name: "Vue.js", idPrefix: "vue-" },
      { id: "fe-angular", name: "Angular", idPrefix: "ng-" },
      { id: "fe-svelte", name: "Svelte & SvelteKit", idPrefix: "svelte-" },
      { id: "fe-meta-mobile", name: "Meta-Frameworks, Mobile & Bonus", idPrefix: "bonus-" },
      { id: "fe-security-perf", name: "Frontend Security & Performance", idPrefix: "feperf-" },
    ],
  },
  {
    id: "backend",
    name: "Backend",
    tagline: "Runtimes, APIs, data, security and the systems thinking behind them.",
    accentToken: "summit",
    modules: [
      { id: "be-foundations", name: "Web & Backend Foundations", idPrefix: "web-" },
      { id: "be-node-core", name: "Node.js Core", idPrefix: "node-" },
      { id: "be-express", name: "Express.js", idPrefix: "express-" },
      { id: "be-sql", name: "SQL & Relational Databases", idPrefix: "sql-" },
      { id: "be-nosql", name: "NoSQL & Caching", idPrefix: "nosql-" },
      { id: "be-auth-security", name: "Authentication & Security", idPrefix: "auth-" },
      { id: "be-api-design", name: "API Design", idPrefix: "api-" },
      { id: "be-nestjs", name: "NestJS", idPrefix: "nest-" },
      { id: "be-python", name: "Python Backend", idPrefix: "py-" },
      { id: "be-docker", name: "Docker & Containers", idPrefix: "docker-" },
      { id: "be-system-design", name: "System Design Fundamentals", idPrefix: "sd-" },
      { id: "be-testing-ops", name: "Backend Testing & Ops", idPrefix: "ops-" },
    ],
  },
  {
    id: "fullstack",
    name: "Full-Stack",
    tagline: "Wire frontend to backend and ship real, authenticated apps end to end.",
    accentToken: "glacier",
    modules: [
      { id: "fs-mern", name: "MERN End-to-End", idPrefix: "mern-" },
      { id: "fs-nextjs", name: "Next.js Full-Stack", idPrefix: "fsnext-" },
      { id: "fs-t3", name: "The T3 Stack & End-to-End Type Safety", idPrefix: "t3-" },
      { id: "fs-graphql", name: "GraphQL Full-Stack", idPrefix: "fsgql-" },
      { id: "fs-capstone", name: "Full-Stack Capstone & Deployment", idPrefix: "fscap-" },
    ],
  },
  {
    id: "ai-driven",
    name: "AI-Driven Development",
    tagline: "Use AI coding tools deliberately, from prompts and context to RAG and agents.",
    accentToken: "ridge",
    modules: [
      { id: "ai-tools", name: "The AI Coding Tools Landscape", idPrefix: "aitools-" },
      { id: "ai-prompting", name: "Prompt Engineering", idPrefix: "prompt-" },
      { id: "ai-context", name: "Context Engineering & AI Pair Programming", idPrefix: "ctx-" },
      { id: "ai-llm", name: "LLM Fundamentals", idPrefix: "llm-" },
      { id: "ai-rag", name: "Retrieval-Augmented Generation", idPrefix: "rag-" },
      { id: "ai-agents", name: "AI Agents", idPrefix: "agents-" },
    ],
  },
  {
    id: "php",
    name: "PHP & Laravel",
    tagline: "The stack behind most of what Oyelabs ships, from the language up to a deployed app.",
    accentToken: "canyon",
    modules: [
      { id: "php-foundations", name: "PHP Foundations", idPrefix: "php-" },
      { id: "php-oop", name: "PHP OOP", idPrefix: "php-oop-" },
      { id: "php-modern", name: "Modern PHP 8.x", idPrefix: "php-modern-" },
      { id: "php-composer-psr", name: "Composer & PSR Standards", idPrefix: "php-psr-" },
      { id: "php-web", name: "PHP on the Web", idPrefix: "php-web-" },
      { id: "laravel-foundations", name: "Laravel Foundations", idPrefix: "lv-" },
      { id: "laravel-eloquent", name: "Eloquent & Migrations", idPrefix: "lv-eloquent-" },
      { id: "laravel-auth", name: "Laravel Auth & Authorization", idPrefix: "lv-auth-" },
      { id: "laravel-apis", name: "Laravel APIs", idPrefix: "lv-api-" },
      { id: "laravel-queues-events", name: "Queues, Events & Scheduling", idPrefix: "lv-queue-" },
      { id: "laravel-testing", name: "Testing with Pest & PHPUnit", idPrefix: "lv-test-" },
      { id: "laravel-ecosystem", name: "The Laravel Ecosystem", idPrefix: "lv-eco-" },
      { id: "laravel-deploy", name: "Deploying Laravel", idPrefix: "lv-deploy-" },
      { id: "php-wordpress", name: "WordPress Development", idPrefix: "wp-" },
    ],
  },
  {
    id: "mobile",
    name: "Mobile Development",
    tagline: "Native and cross-platform, from the language up to a release on both stores.",
    accentToken: "alpenglow",
    modules: [
      { id: "mobile-foundations", name: "Mobile Foundations", idPrefix: "mob-" },
      { id: "mobile-react-native", name: "React Native & Expo", idPrefix: "rn-" },
      { id: "mobile-dart", name: "The Dart Language", idPrefix: "dart-" },
      { id: "mobile-flutter", name: "Flutter UI & State", idPrefix: "flutter-" },
      { id: "mobile-kotlin-compose", name: "Kotlin & Jetpack Compose", idPrefix: "kt-" },
      { id: "mobile-swift-swiftui", name: "Swift & SwiftUI", idPrefix: "swift-" },
      { id: "mobile-cross-cutting", name: "Mobile Cross-Cutting Concerns", idPrefix: "mob-x-" },
    ],
  },
  {
    id: "devops",
    name: "DevOps & Cloud",
    tagline: "Everything between a working build and a system that stays up.",
    accentToken: "lichen",
    modules: [
      { id: "devops-linux-shell", name: "Linux & the Shell", idPrefix: "lin-" },
      { id: "devops-networking-tls", name: "Networking, DNS & TLS", idPrefix: "net-" },
      { id: "devops-reverse-proxies", name: "Reverse Proxies", idPrefix: "proxy-" },
      { id: "devops-aws-core", name: "AWS Core", idPrefix: "aws-" },
      { id: "devops-terraform", name: "Infrastructure as Code", idPrefix: "tf-" },
      { id: "devops-kubernetes", name: "Kubernetes in Depth", idPrefix: "k8s-" },
      { id: "devops-observability", name: "Observability", idPrefix: "obs-" },
    ],
  },
  // v4: the first two non-engineering trails. Each camp is one level of the department's ladder.
  {
    id: "pm",
    name: "Project Management",
    tagline: "Delivering client software at an agency, from the first stand-up to portfolio governance.",
    accentToken: "ridge",
    modules: [
      // v4.2: the Agency PM Processes Academy — processes first for every PM.
      { id: "pmp-a00", name: "Custom lifecycle: The custom lifecycle at a glance", idPrefix: "pmp-a00-" },
      { id: "pmp-a01", name: "Custom lifecycle: BD handover to delivery", idPrefix: "pmp-a01-" },
      { id: "pmp-a02", name: "Custom lifecycle: Estimation & commercial models", idPrefix: "pmp-a02-" },
      { id: "pmp-a03", name: "Custom lifecycle: Internal kickoff", idPrefix: "pmp-a03-" },
      { id: "pmp-a04", name: "Custom lifecycle: Client kickoff", idPrefix: "pmp-a04-" },
      { id: "pmp-a05", name: "Custom lifecycle: Discovery & requirements", idPrefix: "pmp-a05-" },
      { id: "pmp-a06", name: "Custom lifecycle: UI/UX & design approval", idPrefix: "pmp-a06-" },
      { id: "pmp-a07", name: "Custom lifecycle: Architecture & Sprint 0", idPrefix: "pmp-a07-" },
      { id: "pmp-a08", name: "Custom lifecycle: Sprint execution", idPrefix: "pmp-a08-" },
      { id: "pmp-a09", name: "Custom lifecycle: Scope control: CR, enhancement, bug", idPrefix: "pmp-a09-" },
      { id: "pmp-a10", name: "Custom lifecycle: QA, UAT & sign-off", idPrefix: "pmp-a10-" },
      { id: "pmp-a11", name: "Custom lifecycle: Release & go-live", idPrefix: "pmp-a11-" },
      { id: "pmp-a12", name: "Custom lifecycle: Hypercare & warranty", idPrefix: "pmp-a12-" },
      { id: "pmp-a13", name: "Custom lifecycle: Handover & KT", idPrefix: "pmp-a13-" },
      { id: "pmp-a14", name: "Custom lifecycle: Support, AMC & retainers", idPrefix: "pmp-a14-" },
      { id: "pmp-a15", name: "Custom lifecycle: Closure", idPrefix: "pmp-a15-" },
      { id: "pmp-b01", name: "White-label lifecycle: What white-label means", idPrefix: "pmp-b01-" },
      { id: "pmp-b02", name: "White-label lifecycle: Demo & requirement call", idPrefix: "pmp-b02-" },
      { id: "pmp-b03", name: "White-label lifecycle: Gap analysis", idPrefix: "pmp-b03-" },
      { id: "pmp-b04", name: "White-label lifecycle: Collecting the brand kit", idPrefix: "pmp-b04-" },
      { id: "pmp-b05", name: "White-label lifecycle: Client-owned accounts", idPrefix: "pmp-b05-" },
      { id: "pmp-b06", name: "White-label lifecycle: Configuration & custom modules", idPrefix: "pmp-b06-" },
      { id: "pmp-b07", name: "White-label lifecycle: Rebranded builds, QA & UAT", idPrefix: "pmp-b07-" },
      { id: "pmp-b08", name: "White-label lifecycle: Store listing preparation", idPrefix: "pmp-b08-" },
      { id: "pmp-b09", name: "White-label lifecycle: Submission, rejection & resubmission", idPrefix: "pmp-b09-" },
      { id: "pmp-b10", name: "White-label lifecycle: Go-live, licence & support plan", idPrefix: "pmp-b10-" },
      { id: "pmp-b11", name: "White-label lifecycle: Core product upgrades", idPrefix: "pmp-b11-" },
      { id: "pmp-b12", name: "White-label lifecycle: Running many white-label clients", idPrefix: "pmp-b12-" },
      { id: "pmp-c01", name: "Terminology: Commercial & contract terms", idPrefix: "pmp-c01-" },
      { id: "pmp-c02", name: "Terminology: Scope terms", idPrefix: "pmp-c02-" },
      { id: "pmp-c03", name: "Terminology: Delivery terms", idPrefix: "pmp-c03-" },
      { id: "pmp-c04", name: "Terminology: Quality & support terms", idPrefix: "pmp-c04-" },
      { id: "pmp-c05", name: "Terminology: Warranty, support & maintenance", idPrefix: "pmp-c05-" },
      { id: "pmp-c06", name: "Terminology: Communication & governance", idPrefix: "pmp-c06-" },
      { id: "pmp-c07", name: "Terminology: White-label terms", idPrefix: "pmp-c07-" },
      { id: "pmp-c08", name: "Terminology: Drills", idPrefix: "pmp-c08-" },
      { id: "pmp-d01", name: "Client meetings: Starting a project", idPrefix: "pmp-d01-" },
      { id: "pmp-d02", name: "Client meetings: Running delivery", idPrefix: "pmp-d02-" },
      { id: "pmp-d03", name: "Client meetings: Hard conversations", idPrefix: "pmp-d03-" },
      { id: "pmp-d04", name: "Client meetings: Releasing & closing", idPrefix: "pmp-d04-" },
      { id: "pmp-d05", name: "Client meetings: Meeting craft", idPrefix: "pmp-d05-" },
      { id: "pmp-e01", name: "Templates: Scope & sign-off templates", idPrefix: "pmp-e01-" },
      { id: "pmp-e02", name: "Templates: Running-the-project templates", idPrefix: "pmp-e02-" },
      { id: "pmp-e03", name: "Templates: Release & close templates", idPrefix: "pmp-e03-" },
      // v4.1: agency PM work first — practical, tool-level, client-facing.
      { id: "pma-refresh", name: "Improving your existing PM skills", idPrefix: "pma-" },
      { id: "pma-client", name: "Client management", idPrefix: "pma-" },
      { id: "pma-meetings", name: "Client update meetings & presenting", idPrefix: "pma-" },
      { id: "pma-email", name: "Email etiquette & professional writing", idPrefix: "pma-" },
      { id: "pma-excel", name: "Excel for PMs", idPrefix: "pma-" },
      { id: "pma-resource", name: "Agency resource management", idPrefix: "pma-" },
      { id: "pma-tech-terms", name: "Tech terms in plain language", idPrefix: "pma-" },
      { id: "pma-sdlc", name: "The SDLC in an agency", idPrefix: "pma-" },
      { id: "pma-teams", name: "Microsoft Teams for PMs", idPrefix: "pma-" },
      { id: "pma-word-ppt", name: "Word & PowerPoint for PMs", idPrefix: "pma-" },
      { id: "pma-keka", name: "Keka for PMs", idPrefix: "pma-" },
      { id: "pma-github", name: "Git & GitHub for PMs", idPrefix: "pma-" },
      { id: "pma-ai", name: "AI for PMs (Copilot & Claude)", idPrefix: "pma-" },
      // The generic PM theory: still useful, now last on the trail.
      { id: "pm-beginner", name: "PM foundations and advanced theory: Foundations", idPrefix: "pm-b-" },
      { id: "pm-intermediate", name: "PM foundations and advanced theory: Running delivery", idPrefix: "pm-i-" },
      { id: "pm-advanced", name: "PM foundations and advanced theory: Advanced delivery", idPrefix: "pm-a-" },
      { id: "pm-expert", name: "PM foundations and advanced theory: Programme & portfolio", idPrefix: "pm-x-" },
      { id: "pm-ai", name: "AI in Project Delivery", idPrefix: "pm-x-ai-" },
    ],
  },
  {
    id: "bd",
    name: "Business Development",
    tagline: "Winning and growing agency work: from the first cold email to strategic accounts.",
    accentToken: "canyon",
    modules: [
      { id: "bd-beginner", name: "BD Foundations", idPrefix: "bd-b-" },
      { id: "bd-intermediate", name: "Winning Deals", idPrefix: "bd-i-" },
      { id: "bd-advanced", name: "Complex Sales & Accounts", idPrefix: "bd-a-" },
      { id: "bd-expert", name: "Strategic BD & AI-Powered Selling", idPrefix: "bd-x-" },
      { id: "bd-ai", name: "AI-Powered Business Development", idPrefix: "bd-x-ai-" },
    ],
  },
  // v4.4: the Soft skills area. One camp per soft skill (catalog `ss-*` → `soft-*`), usable by every
  // department; each camp is one full lesson with a hands-on practice.
  {
    id: "soft",
    name: "Soft skills",
    tagline: "Speaking, writing and working with people: the skills every engineer, PM and BD person uses daily.",
    accentToken: "alpenglow",
    modules: [
      { id: "soft-spoken-english", name: "Spoken English at work", idPrefix: "soft-english-" },
      { id: "soft-workplace-writing", name: "Workplace writing (email, chat, docs)", idPrefix: "soft-writing-" },
      { id: "soft-explain-simply", name: "Explaining technical work simply", idPrefix: "soft-explain-" },
      { id: "soft-standup-updates", name: "Stand-ups and status updates", idPrefix: "soft-standup-" },
      { id: "soft-client-team-communication", name: "Client and team communication", idPrefix: "soft-comms-" },
      { id: "soft-listening-questions", name: "Listening and asking good questions", idPrefix: "soft-listening-" },
      { id: "soft-presenting-demoing", name: "Presenting and demoing", idPrefix: "soft-demo-" },
      { id: "soft-ownership-time", name: "Ownership and time management", idPrefix: "soft-ownership-" },
      { id: "soft-feedback", name: "Giving and receiving feedback", idPrefix: "soft-feedback-" },
      { id: "soft-teamwork", name: "Teamwork and collaboration", idPrefix: "soft-teamwork-" },
    ],
  },
];
