import type { SeedDepartment, SeedSkill, SeedStack, SeedTrack } from "./types";

export const BD_DEPARTMENT: SeedDepartment = {
  id: "bd",
  name: "Business Development",
  slug: "bd",
  icon: "Handshake",
  colour: "#0F766E",
  assessmentFormat: "tasks",
  position: 2,
  practiceNoun: "Task workspace",
};

const D = "bd";

export const BD_TRACKS: SeedTrack[] = [
  { id: "bd-agency", departmentId: D, name: "Agency BD (Upwork/inbound)", description: "Winning projects from Upwork, Clutch and inbound leads with sharp proposals.", position: 0 },
  { id: "bd-outbound", departmentId: D, name: "Outbound & Partnerships", description: "Prospecting, sequencing, enterprise deals and white-label partnerships.", position: 1 },
  { id: "bd-account", departmentId: D, name: "Account Management", description: "Growing, retaining and expanding existing client relationships.", position: 2 },
];

export const BD_STACKS: SeedStack[] = [
  { id: "bd-tool-hubspot", departmentId: D, name: "HubSpot", kind: "tool", aliases: ["hubspot crm"], position: 0 },
  { id: "bd-tool-zoho", departmentId: D, name: "Zoho CRM", kind: "tool", aliases: ["zoho"], position: 1 },
  { id: "bd-tool-pipedrive", departmentId: D, name: "Pipedrive", kind: "tool", aliases: [], position: 2 },
  { id: "bd-tool-salesforce", departmentId: D, name: "Salesforce", kind: "tool", aliases: ["sfdc"], position: 3 },
  { id: "bd-tool-sales-navigator", departmentId: D, name: "LinkedIn Sales Navigator", kind: "tool", aliases: ["sales nav", "linkedin"], position: 4 },
  { id: "bd-tool-upwork", departmentId: D, name: "Upwork", kind: "tool", aliases: ["upwork agency"], position: 5 },
  { id: "bd-tool-apollo", departmentId: D, name: "Apollo", kind: "tool", aliases: ["apollo.io"], position: 6 },
  { id: "bd-tool-clutch", departmentId: D, name: "Clutch", kind: "tool", aliases: ["clutch.co"], position: 7 },
  { id: "bd-tool-lemlist", departmentId: D, name: "Lemlist", kind: "tool", aliases: [], position: 8 },
  { id: "bd-tool-loom", departmentId: D, name: "Loom", kind: "tool", aliases: [], position: 9 },
  { id: "bd-tool-calendly", departmentId: D, name: "Calendly", kind: "tool", aliases: [], position: 10 },
  { id: "bd-tool-pandadoc", departmentId: D, name: "PandaDoc", kind: "tool", aliases: ["e-signature"], position: 11 },
];

const ALL = ["bd-agency", "bd-outbound", "bd-account"];
const CRMS = ["bd-tool-hubspot", "bd-tool-zoho", "bd-tool-pipedrive", "bd-tool-salesforce"];

export const BD_SKILLS: SeedSkill[] = [
  // Market & offering
  { id: "bd-agency-services", departmentId: D, name: "Agency services & offerings", area: "Market & offering", aliases: ["services", "what we sell", "service catalogue", "capabilities"], tags: ["offering", "foundations"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["bd-beginner"] },
  { id: "bd-white-label-offering", departmentId: D, name: "White-label & AI platform offerings", area: "Market & offering", aliases: ["white label", "reseller", "turnkey apps", "clone apps", "ai platforms"], tags: ["offering", "white-label", "ai"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: ["bd-agency-services"], stackIds: [], contentModules: ["bd-beginner"] },
  { id: "bd-icp", departmentId: D, name: "Ideal customer profile (ICP)", area: "Market & offering", aliases: ["icp", "ideal customer", "target market", "firmographics"], tags: ["targeting", "strategy"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["bd-beginner"] },
  { id: "bd-personas", departmentId: D, name: "Buyer personas", area: "Market & offering", aliases: ["personas", "decision makers", "founder vs cto", "buyer roles"], tags: ["targeting"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: ["bd-icp"], stackIds: [], contentModules: ["bd-beginner"] },
  { id: "bd-value-proposition", departmentId: D, name: "Value proposition & positioning", area: "Market & offering", aliases: ["usp", "positioning", "differentiation", "elevator pitch"], tags: ["messaging", "strategy"], levelMin: "beginner", levelMax: "advanced", trackIds: ALL, prerequisites: ["bd-agency-services"], stackIds: [], contentModules: ["bd-beginner"] },
  { id: "bd-competitor-awareness", departmentId: D, name: "Competitor & market awareness", area: "Market & offering", aliases: ["competitors", "market research", "battlecards"], tags: ["strategy", "research"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["bd-outbound", "bd-agency"], prerequisites: ["bd-icp"], stackIds: [], contentModules: ["bd-intermediate"] },

  // Lead generation
  { id: "bd-lead-upwork", departmentId: D, name: "Upwork as a lead source", area: "Lead generation", aliases: ["upwork", "freelance marketplace", "upwork agency"], tags: ["leads", "upwork"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["bd-agency"], prerequisites: [], stackIds: ["bd-tool-upwork"], contentModules: ["bd-beginner"] },
  { id: "bd-lead-linkedin", departmentId: D, name: "LinkedIn as a lead source", area: "Lead generation", aliases: ["linkedin leads", "social selling", "linkedin content"], tags: ["leads", "linkedin"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["bd-outbound", "bd-agency"], prerequisites: [], stackIds: ["bd-tool-sales-navigator"], contentModules: ["bd-beginner"] },
  { id: "bd-lead-clutch", departmentId: D, name: "Clutch & directory listings", area: "Lead generation", aliases: ["clutch", "goodfirms", "directories", "agency listings"], tags: ["leads", "inbound"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["bd-agency"], prerequisites: [], stackIds: ["bd-tool-clutch"], contentModules: ["bd-beginner"] },
  { id: "bd-lead-referrals", departmentId: D, name: "Referrals", area: "Lead generation", aliases: ["referral", "word of mouth", "client referrals", "introductions"], tags: ["leads", "relationships"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["bd-account", "bd-outbound"], prerequisites: [], stackIds: [], contentModules: ["bd-beginner"] },
  { id: "bd-lead-inbound", departmentId: D, name: "Inbound leads & website enquiries", area: "Lead generation", aliases: ["inbound", "contact form", "seo leads", "lead response time"], tags: ["leads", "inbound"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["bd-agency"], prerequisites: [], stackIds: ["bd-tool-hubspot", "bd-tool-calendly"], contentModules: ["bd-beginner"] },
  { id: "bd-prospect-research", departmentId: D, name: "Prospect research", area: "Lead generation", aliases: ["research", "lead research", "account research", "trigger events"], tags: ["research", "outbound"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["bd-outbound", "bd-agency"], prerequisites: ["bd-icp"], stackIds: ["bd-tool-sales-navigator", "bd-tool-apollo"], contentModules: ["bd-beginner"] },
  { id: "bd-crm-hygiene", departmentId: D, name: "CRM hygiene", area: "Lead generation", aliases: ["crm", "data hygiene", "deal stages", "logging activities", "hubspot"], tags: ["crm", "process"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: CRMS, contentModules: ["bd-beginner"] },
  { id: "bd-pipeline-management", departmentId: D, name: "Pipeline management", area: "Lead generation", aliases: ["pipeline", "deal stages", "sales funnel", "deal reviews"], tags: ["crm", "pipeline"], levelMin: "intermediate", levelMax: "advanced", trackIds: ALL, prerequisites: ["bd-crm-hygiene"], stackIds: CRMS, contentModules: ["bd-intermediate"] },

  // Outreach
  { id: "bd-cold-email", departmentId: D, name: "Cold email", area: "Outreach", aliases: ["cold outreach", "email prospecting", "subject lines", "deliverability"], tags: ["outreach", "email"], levelMin: "beginner", levelMax: "advanced", trackIds: ["bd-outbound"], prerequisites: ["bd-personas"], stackIds: ["bd-tool-lemlist", "bd-tool-apollo"], contentModules: ["bd-beginner"] },
  { id: "bd-linkedin-outreach", departmentId: D, name: "LinkedIn outreach", area: "Outreach", aliases: ["connection requests", "linkedin dms", "inmail", "sales navigator"], tags: ["outreach", "linkedin"], levelMin: "beginner", levelMax: "advanced", trackIds: ["bd-outbound"], prerequisites: ["bd-personas"], stackIds: ["bd-tool-sales-navigator"], contentModules: ["bd-beginner"] },
  { id: "bd-business-writing", departmentId: D, name: "Professional business writing", area: "Outreach", aliases: ["business emails", "writing", "grammar", "tone"], tags: ["writing", "communication"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["bd-beginner"] },
  { id: "bd-meeting-prep", departmentId: D, name: "Booking & preparing for sales calls", area: "Outreach", aliases: ["call prep", "meeting booking", "calendly", "agenda"], tags: ["meetings", "process"], levelMin: "beginner", levelMax: "beginner", trackIds: ALL, prerequisites: [], stackIds: ["bd-tool-calendly"], contentModules: ["bd-beginner"] },
  { id: "bd-follow-up-cadences", departmentId: D, name: "Follow-up cadences", area: "Outreach", aliases: ["follow ups", "cadence", "touchpoints", "nurturing"], tags: ["outreach", "process"], levelMin: "intermediate", levelMax: "advanced", trackIds: ALL, prerequisites: ["bd-cold-email"], stackIds: ["bd-tool-lemlist", "bd-tool-hubspot"], contentModules: ["bd-intermediate"] },
  { id: "bd-sequencing-tools", departmentId: D, name: "Outbound sequencing tools", area: "Outreach", aliases: ["lemlist", "apollo sequences", "hubspot sequences", "email warmup"], tags: ["outreach", "tools", "automation"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["bd-outbound"], prerequisites: ["bd-cold-email"], stackIds: ["bd-tool-lemlist", "bd-tool-apollo", "bd-tool-hubspot"], contentModules: ["bd-intermediate"] },

  // Tech literacy for BD
  { id: "bd-tech-web-mobile-ai", departmentId: D, name: "Web vs mobile vs AI products", area: "Tech literacy for BD", aliases: ["web app", "mobile app", "native vs cross-platform", "ai app", "saas"], tags: ["technical", "product"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["bd-beginner"] },
  { id: "bd-tech-mvp", departmentId: D, name: "MVPs & phased delivery", area: "Tech literacy for BD", aliases: ["mvp", "minimum viable product", "phase 1", "prototype", "poc"], tags: ["technical", "product"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: ["bd-tech-web-mobile-ai"], stackIds: [], contentModules: ["bd-beginner"] },
  { id: "bd-tech-apis", departmentId: D, name: "APIs & integrations for BD", area: "Tech literacy for BD", aliases: ["api", "integrations", "third-party services", "payment gateway"], tags: ["technical"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["bd-agency", "bd-outbound"], prerequisites: ["bd-tech-web-mobile-ai"], stackIds: [], contentModules: ["bd-beginner"] },
  { id: "bd-tech-estimation", departmentId: D, name: "Estimation basics for BD", area: "Tech literacy for BD", aliases: ["ballpark estimate", "rough order of magnitude", "rom", "effort estimate"], tags: ["technical", "estimation"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["bd-agency", "bd-outbound"], prerequisites: ["bd-tech-mvp"], stackIds: [], contentModules: ["bd-beginner"] },
  { id: "bd-tech-stacks", departmentId: D, name: "Explaining tech stacks to clients", area: "Tech literacy for BD", aliases: ["react vs flutter", "laravel vs node", "cloud hosting", "tech stack"], tags: ["technical", "communication"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["bd-agency", "bd-outbound"], prerequisites: ["bd-tech-web-mobile-ai"], stackIds: [], contentModules: ["bd-beginner"] },
  { id: "bd-tech-delivery-process", departmentId: D, name: "How the delivery process works", area: "Tech literacy for BD", aliases: ["agile for sales", "sprints", "qa", "handoff", "maintenance"], tags: ["technical", "delivery"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["bd-beginner"] },

  // Upwork & proposals
  { id: "bd-upwork-job-selection", departmentId: D, name: "Upwork job selection", area: "Upwork & proposals", aliases: ["job filtering", "client quality", "payment verified", "red flags"], tags: ["upwork", "qualification"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["bd-agency"], prerequisites: ["bd-lead-upwork"], stackIds: ["bd-tool-upwork"], contentModules: ["bd-intermediate"] },
  { id: "bd-upwork-connects", departmentId: D, name: "Upwork Connects strategy", area: "Upwork & proposals", aliases: ["connects", "boosted proposals", "bid budget", "connects roi"], tags: ["upwork", "budget"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["bd-agency"], prerequisites: ["bd-upwork-job-selection"], stackIds: ["bd-tool-upwork"], contentModules: ["bd-intermediate"] },
  { id: "bd-upwork-proposals", departmentId: D, name: "Upwork proposals", area: "Upwork & proposals", aliases: ["cover letter", "bids", "proposal writing", "screening questions"], tags: ["upwork", "proposals", "writing"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["bd-agency"], prerequisites: ["bd-lead-upwork", "bd-business-writing"], stackIds: ["bd-tool-upwork"], contentModules: ["bd-intermediate"] },
  { id: "bd-upwork-profile", departmentId: D, name: "Upwork profile optimisation", area: "Upwork & proposals", aliases: ["agency profile", "portfolio", "jss", "top rated", "profile seo"], tags: ["upwork", "positioning"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["bd-agency"], prerequisites: ["bd-lead-upwork"], stackIds: ["bd-tool-upwork"], contentModules: ["bd-intermediate"] },
  { id: "bd-loom-proposals", departmentId: D, name: "Loom video proposals", area: "Upwork & proposals", aliases: ["loom", "video proposal", "screen recording"], tags: ["proposals", "video"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["bd-agency", "bd-outbound"], prerequisites: ["bd-upwork-proposals"], stackIds: ["bd-tool-loom"], contentModules: ["bd-intermediate"] },
  { id: "bd-proposals-sows", departmentId: D, name: "Proposals & SOWs with engineering", area: "Upwork & proposals", aliases: ["proposal", "sow", "statement of work", "scope document", "pandadoc"], tags: ["proposals", "scope"], levelMin: "intermediate", levelMax: "advanced", trackIds: ALL, prerequisites: ["bd-tech-estimation", "bd-business-writing"], stackIds: ["bd-tool-pandadoc"], contentModules: ["bd-intermediate"] },
  { id: "bd-sales-handoff", departmentId: D, name: "Sales-to-delivery handoff", area: "Upwork & proposals", aliases: ["handoff", "handover", "kickoff brief", "deal notes"], tags: ["process", "delivery"], levelMin: "intermediate", levelMax: "intermediate", trackIds: ALL, prerequisites: ["bd-proposals-sows"], stackIds: [], contentModules: ["bd-intermediate"] },

  // Discovery & qualification
  { id: "bd-discovery-calls", departmentId: D, name: "Running discovery calls", area: "Discovery & qualification", aliases: ["discovery", "first call", "needs analysis", "intro call"], tags: ["discovery", "calls"], levelMin: "intermediate", levelMax: "advanced", trackIds: ALL, prerequisites: ["bd-meeting-prep"], stackIds: [], contentModules: ["bd-intermediate"] },
  { id: "bd-spin", departmentId: D, name: "SPIN questioning", area: "Discovery & qualification", aliases: ["spin selling", "situation problem implication need-payoff"], tags: ["discovery", "methodology"], levelMin: "intermediate", levelMax: "advanced", trackIds: ALL, prerequisites: ["bd-discovery-calls"], stackIds: [], contentModules: ["bd-intermediate"] },
  { id: "bd-bant", departmentId: D, name: "BANT qualification", area: "Discovery & qualification", aliases: ["bant", "budget authority need timeline", "lead qualification"], tags: ["qualification", "methodology"], levelMin: "intermediate", levelMax: "intermediate", trackIds: ALL, prerequisites: ["bd-discovery-calls"], stackIds: [], contentModules: ["bd-intermediate"] },
  { id: "bd-meddic", departmentId: D, name: "MEDDIC / MEDDPICC qualification", area: "Discovery & qualification", aliases: ["meddic", "meddpicc", "champion", "economic buyer"], tags: ["qualification", "enterprise"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["bd-outbound", "bd-account"], prerequisites: ["bd-bant"], stackIds: [], contentModules: ["bd-intermediate"] },
  { id: "bd-demos", departmentId: D, name: "Running demos", area: "Discovery & qualification", aliases: ["product demo", "portfolio walkthrough", "demo script"], tags: ["calls", "presentation"], levelMin: "intermediate", levelMax: "advanced", trackIds: ALL, prerequisites: ["bd-discovery-calls"], stackIds: ["bd-tool-loom"], contentModules: ["bd-intermediate"] },
  { id: "bd-objection-handling", departmentId: D, name: "Objection handling", area: "Discovery & qualification", aliases: ["objections", "too expensive", "price objection", "competitor objection"], tags: ["calls", "closing"], levelMin: "intermediate", levelMax: "advanced", trackIds: ALL, prerequisites: ["bd-discovery-calls"], stackIds: [], contentModules: ["bd-intermediate"] },
  { id: "bd-closing", departmentId: D, name: "Closing deals", area: "Discovery & qualification", aliases: ["closing", "asking for the business", "mutual action plan", "trial close"], tags: ["closing"], levelMin: "intermediate", levelMax: "advanced", trackIds: ALL, prerequisites: ["bd-objection-handling"], stackIds: ["bd-tool-pandadoc"], contentModules: ["bd-intermediate"] },

  // Pricing & commercials
  { id: "bd-pricing-fixed", departmentId: D, name: "Fixed-price pricing", area: "Pricing & commercials", aliases: ["fixed price", "fixed bid", "project quote"], tags: ["pricing", "commercial"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["bd-agency", "bd-outbound"], prerequisites: ["bd-tech-estimation"], stackIds: [], contentModules: ["bd-intermediate"] },
  { id: "bd-pricing-tm", departmentId: D, name: "Time & materials pricing", area: "Pricing & commercials", aliases: ["t&m", "hourly", "rate card"], tags: ["pricing", "commercial"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["bd-agency", "bd-outbound"], prerequisites: ["bd-tech-estimation"], stackIds: [], contentModules: ["bd-intermediate"] },
  { id: "bd-pricing-retainer", departmentId: D, name: "Retainer pricing", area: "Pricing & commercials", aliases: ["retainer", "monthly retainer", "maintenance contract", "support plan"], tags: ["pricing", "recurring"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["bd-account", "bd-agency"], prerequisites: ["bd-agency-services"], stackIds: [], contentModules: ["bd-intermediate"] },
  { id: "bd-pricing-dedicated-team", departmentId: D, name: "Dedicated team pricing", area: "Pricing & commercials", aliases: ["dedicated team", "staff augmentation", "team extension", "monthly per developer"], tags: ["pricing", "recurring"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["bd-outbound", "bd-account"], prerequisites: ["bd-agency-services"], stackIds: [], contentModules: ["bd-intermediate"] },
  { id: "bd-pricing-strategy", departmentId: D, name: "Pricing strategy", area: "Pricing & commercials", aliases: ["value-based pricing", "price positioning", "discounting policy"], tags: ["pricing", "strategy"], levelMin: "expert", levelMax: "expert", trackIds: ALL, prerequisites: ["bd-pricing-fixed", "bd-pricing-tm"], stackIds: [], contentModules: ["bd-expert"] },
  { id: "bd-margins", departmentId: D, name: "Deal margins & profitability", area: "Pricing & commercials", aliases: ["margin", "gross margin", "blended rate", "cost of delivery"], tags: ["finance", "pricing"], levelMin: "expert", levelMax: "expert", trackIds: ["bd-account", "bd-outbound"], prerequisites: ["bd-pricing-strategy"], stackIds: [], contentModules: ["bd-expert"] },

  // Selling methodologies
  { id: "bd-consultative-selling", departmentId: D, name: "Consultative selling", area: "Selling methodologies", aliases: ["consultative", "trusted advisor", "needs-based selling"], tags: ["methodology"], levelMin: "advanced", levelMax: "expert", trackIds: ALL, prerequisites: ["bd-spin"], stackIds: [], contentModules: ["bd-advanced"] },
  { id: "bd-solution-selling", departmentId: D, name: "Solution selling", area: "Selling methodologies", aliases: ["solution selling", "pain-driven selling"], tags: ["methodology"], levelMin: "advanced", levelMax: "expert", trackIds: ["bd-outbound", "bd-agency"], prerequisites: ["bd-discovery-calls"], stackIds: [], contentModules: ["bd-advanced"] },
  { id: "bd-challenger", departmentId: D, name: "Challenger selling", area: "Selling methodologies", aliases: ["challenger sale", "teach tailor take control", "commercial insight"], tags: ["methodology"], levelMin: "advanced", levelMax: "expert", trackIds: ["bd-outbound"], prerequisites: ["bd-consultative-selling"], stackIds: [], contentModules: ["bd-advanced"] },
  { id: "bd-negotiation", departmentId: D, name: "Negotiation & BATNA", area: "Selling methodologies", aliases: ["negotiation", "batna", "zopa", "anchoring"], tags: ["negotiation", "closing"], levelMin: "advanced", levelMax: "expert", trackIds: ALL, prerequisites: ["bd-objection-handling"], stackIds: [], contentModules: ["bd-advanced"] },
  { id: "bd-concessions", departmentId: D, name: "Trading concessions", area: "Selling methodologies", aliases: ["concessions", "discount requests", "give-get", "scope for price"], tags: ["negotiation", "pricing"], levelMin: "advanced", levelMax: "expert", trackIds: ALL, prerequisites: ["bd-negotiation"], stackIds: [], contentModules: ["bd-advanced"] },

  // Enterprise & partnerships
  { id: "bd-rfp", departmentId: D, name: "RFP responses", area: "Enterprise & partnerships", aliases: ["rfp", "rfi", "rfq", "tender", "bid response"], tags: ["enterprise", "proposals"], levelMin: "advanced", levelMax: "expert", trackIds: ["bd-outbound"], prerequisites: ["bd-proposals-sows"], stackIds: [], contentModules: ["bd-advanced"] },
  { id: "bd-enterprise-procurement", departmentId: D, name: "Enterprise deals & procurement", area: "Enterprise & partnerships", aliases: ["procurement", "vendor onboarding", "security questionnaire", "legal review"], tags: ["enterprise"], levelMin: "advanced", levelMax: "expert", trackIds: ["bd-outbound", "bd-account"], prerequisites: ["bd-meddic"], stackIds: ["bd-tool-salesforce"], contentModules: ["bd-advanced"] },
  { id: "bd-white-label-partnerships", departmentId: D, name: "White-label partnerships", area: "Enterprise & partnerships", aliases: ["white label partners", "reseller agreements", "agency partners", "channel partners"], tags: ["partnerships", "white-label"], levelMin: "advanced", levelMax: "expert", trackIds: ["bd-outbound"], prerequisites: ["bd-white-label-offering"], stackIds: [], contentModules: ["bd-advanced"] },
  { id: "bd-referral-partners", departmentId: D, name: "Referral & technology partner programmes", area: "Enterprise & partnerships", aliases: ["partner program", "affiliate", "technology partners", "aws partner"], tags: ["partnerships"], levelMin: "advanced", levelMax: "expert", trackIds: ["bd-outbound"], prerequisites: ["bd-lead-referrals"], stackIds: [], contentModules: ["bd-advanced"] },
  { id: "bd-case-studies", departmentId: D, name: "Case studies", area: "Enterprise & partnerships", aliases: ["case study", "success stories", "portfolio pieces"], tags: ["social-proof", "marketing"], levelMin: "advanced", levelMax: "advanced", trackIds: ALL, prerequisites: ["bd-business-writing"], stackIds: [], contentModules: ["bd-advanced"] },
  { id: "bd-social-proof", departmentId: D, name: "Reviews & social proof", area: "Enterprise & partnerships", aliases: ["clutch reviews", "testimonials", "upwork feedback", "references"], tags: ["social-proof"], levelMin: "advanced", levelMax: "advanced", trackIds: ["bd-agency", "bd-account"], prerequisites: ["bd-lead-clutch"], stackIds: ["bd-tool-clutch"], contentModules: ["bd-advanced"] },

  // Account growth
  { id: "bd-account-management", departmentId: D, name: "Account management", area: "Account growth", aliases: ["client success", "account manager", "relationship management"], tags: ["accounts", "relationships"], levelMin: "advanced", levelMax: "expert", trackIds: ["bd-account"], prerequisites: ["bd-sales-handoff"], stackIds: CRMS, contentModules: ["bd-advanced"] },
  { id: "bd-qbrs", departmentId: D, name: "Quarterly business reviews", area: "Account growth", aliases: ["qbr", "business review", "account review"], tags: ["accounts", "meetings"], levelMin: "advanced", levelMax: "expert", trackIds: ["bd-account"], prerequisites: ["bd-account-management"], stackIds: [], contentModules: ["bd-advanced"] },
  { id: "bd-upselling", departmentId: D, name: "Upselling", area: "Account growth", aliases: ["upsell", "phase 2", "expansion revenue"], tags: ["accounts", "expansion"], levelMin: "advanced", levelMax: "expert", trackIds: ["bd-account"], prerequisites: ["bd-account-management"], stackIds: [], contentModules: ["bd-advanced"] },
  { id: "bd-cross-selling", departmentId: D, name: "Cross-selling", area: "Account growth", aliases: ["cross-sell", "additional services", "bundle"], tags: ["accounts", "expansion"], levelMin: "advanced", levelMax: "expert", trackIds: ["bd-account"], prerequisites: ["bd-account-management"], stackIds: [], contentModules: ["bd-advanced"] },
  { id: "bd-retention", departmentId: D, name: "Client retention & churn prevention", area: "Account growth", aliases: ["churn", "retention", "renewals", "at-risk accounts"], tags: ["accounts", "retention"], levelMin: "advanced", levelMax: "expert", trackIds: ["bd-account"], prerequisites: ["bd-account-management"], stackIds: [], contentModules: ["bd-advanced"] },
  { id: "bd-strategic-accounts", departmentId: D, name: "Strategic account planning", area: "Account growth", aliases: ["key accounts", "account plan", "whitespace analysis", "kam"], tags: ["accounts", "strategy"], levelMin: "expert", levelMax: "expert", trackIds: ["bd-account"], prerequisites: ["bd-upselling", "bd-qbrs"], stackIds: [], contentModules: ["bd-expert"] },

  // Metrics & leadership
  { id: "bd-pipeline-metrics", departmentId: D, name: "Pipeline metrics", area: "Metrics & leadership", aliases: ["conversion rate", "win rate", "sales velocity", "deal cycle"], tags: ["metrics", "pipeline"], levelMin: "advanced", levelMax: "expert", trackIds: ALL, prerequisites: ["bd-pipeline-management"], stackIds: CRMS, contentModules: ["bd-advanced"] },
  { id: "bd-forecasting", departmentId: D, name: "Sales forecasting", area: "Metrics & leadership", aliases: ["forecast", "weighted pipeline", "commit vs best case"], tags: ["metrics", "forecasting"], levelMin: "advanced", levelMax: "expert", trackIds: ["bd-outbound", "bd-account"], prerequisites: ["bd-pipeline-metrics"], stackIds: CRMS, contentModules: ["bd-advanced"] },
  { id: "bd-new-regions", departmentId: D, name: "Expanding into new regions", area: "Metrics & leadership", aliases: ["new markets", "geo expansion", "us market", "gcc", "europe"], tags: ["strategy", "expansion"], levelMin: "expert", levelMax: "expert", trackIds: ["bd-outbound"], prerequisites: ["bd-icp"], stackIds: [], contentModules: ["bd-expert"] },
  { id: "bd-new-verticals", departmentId: D, name: "Expanding into new verticals", area: "Metrics & leadership", aliases: ["verticals", "industries", "healthtech", "fintech", "niche"], tags: ["strategy", "expansion"], levelMin: "expert", levelMax: "expert", trackIds: ["bd-outbound", "bd-agency"], prerequisites: ["bd-icp"], stackIds: [], contentModules: ["bd-expert"] },
  { id: "bd-playbooks", departmentId: D, name: "BD playbooks", area: "Metrics & leadership", aliases: ["playbook", "sales process", "templates", "sop"], tags: ["process", "leadership"], levelMin: "expert", levelMax: "expert", trackIds: ALL, prerequisites: ["bd-pipeline-management"], stackIds: [], contentModules: ["bd-expert"] },
  { id: "bd-team-leadership", departmentId: D, name: "Leading a BD team", area: "Metrics & leadership", aliases: ["sales management", "quotas", "coaching sdrs", "team targets"], tags: ["leadership"], levelMin: "expert", levelMax: "expert", trackIds: ALL, prerequisites: ["bd-pipeline-metrics", "bd-playbooks"], stackIds: [], contentModules: ["bd-expert"] },

  // Contracts
  { id: "bd-msa", departmentId: D, name: "Master service agreements (MSA)", area: "Contracts", aliases: ["msa", "master agreement", "terms and conditions"], tags: ["contracts", "legal"], levelMin: "expert", levelMax: "expert", trackIds: ["bd-outbound", "bd-account"], prerequisites: ["bd-proposals-sows"], stackIds: ["bd-tool-pandadoc"], contentModules: ["bd-expert"] },
  { id: "bd-nda", departmentId: D, name: "NDAs", area: "Contracts", aliases: ["nda", "non-disclosure agreement", "confidentiality"], tags: ["contracts", "legal"], levelMin: "expert", levelMax: "expert", trackIds: ALL, prerequisites: [], stackIds: ["bd-tool-pandadoc"], contentModules: ["bd-expert"] },
  { id: "bd-ip-clauses", departmentId: D, name: "IP ownership & liability clauses", area: "Contracts", aliases: ["ip", "intellectual property", "source code ownership", "liability cap", "indemnity"], tags: ["contracts", "legal"], levelMin: "expert", levelMax: "expert", trackIds: ["bd-outbound", "bd-account"], prerequisites: ["bd-msa"], stackIds: [], contentModules: ["bd-expert"] },

  // AI-powered BD
  { id: "bd-ai-research", departmentId: D, name: "AI-powered prospect research", area: "AI-powered BD", aliases: ["ai research", "claude research", "account intelligence", "clay"], tags: ["ai", "research"], levelMin: "beginner", levelMax: "advanced", trackIds: ["bd-outbound", "bd-agency"], prerequisites: ["bd-prospect-research"], stackIds: ["bd-tool-apollo"], contentModules: ["bd-beginner"], isAiSkill: true },
  { id: "bd-ai-personalisation", departmentId: D, name: "AI personalisation at scale", area: "AI-powered BD", aliases: ["ai personalization", "personalised outreach", "ai cold email"], tags: ["ai", "outreach"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["bd-outbound"], prerequisites: ["bd-cold-email", "bd-ai-research"], stackIds: ["bd-tool-lemlist", "bd-tool-apollo"], contentModules: ["bd-intermediate"], isAiSkill: true },
  { id: "bd-ai-proposals", departmentId: D, name: "Drafting proposals with Claude", area: "AI-powered BD", aliases: ["ai proposals", "claude proposals", "ai upwork bids", "ai sow"], tags: ["ai", "proposals"], levelMin: "intermediate", levelMax: "advanced", trackIds: ALL, prerequisites: ["bd-upwork-proposals"], stackIds: [], contentModules: ["bd-intermediate"], isAiSkill: true },
  { id: "bd-ai-call-notes", departmentId: D, name: "AI call notes & CRM updates", area: "AI-powered BD", aliases: ["ai notes", "call summaries", "hubspot ai", "gong"], tags: ["ai", "crm"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: ["bd-crm-hygiene"], stackIds: CRMS, contentModules: ["bd-beginner"], isAiSkill: true },
  { id: "bd-ai-ethics", departmentId: D, name: "AI ethics & accuracy checks in sales", area: "AI-powered BD", aliases: ["hallucinations", "fact checking", "ai disclosure", "client data privacy"], tags: ["ai", "ethics"], levelMin: "intermediate", levelMax: "expert", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["bd-intermediate"], isAiSkill: true },
  { id: "bd-ai-selling-ai", departmentId: D, name: "Selling AI projects", area: "AI-powered BD", aliases: ["ai use cases", "ai roi", "chatbot projects", "ai readiness"], tags: ["ai", "offering"], levelMin: "advanced", levelMax: "expert", trackIds: ALL, prerequisites: ["bd-tech-web-mobile-ai", "bd-consultative-selling"], stackIds: [], contentModules: ["bd-advanced"], isAiSkill: true },
];
