import type { SeedDepartment, SeedSkill, SeedStack, SeedTrack } from "./types";

export const PM_DEPARTMENT: SeedDepartment = {
  id: "pm",
  name: "Project Management",
  slug: "pm",
  icon: "KanbanSquare",
  colour: "#7C3AED",
  assessmentFormat: "tasks",
  position: 1,
  practiceNoun: "Task workspace",
};

const D = "pm";

export const PM_TRACKS: SeedTrack[] = [
  { id: "pm-agile", departmentId: D, name: "Agile Delivery PM", description: "Running sprints, backlogs and client delivery for agency projects.", position: 0 },
  { id: "pm-technical", departmentId: D, name: "Technical PM", description: "Bridging engineering and clients: requirements, environments, releases and QA.", position: 1 },
  { id: "pm-program", departmentId: D, name: "Program/Portfolio", description: "Governing many projects, resources, contracts and business value at once.", position: 2 },
];

export const PM_STACKS: SeedStack[] = [
  { id: "pm-tool-jira", departmentId: D, name: "Jira", kind: "tool", aliases: ["jira software", "atlassian"], position: 0 },
  { id: "pm-tool-clickup", departmentId: D, name: "ClickUp", kind: "tool", aliases: ["click up"], position: 1 },
  { id: "pm-tool-asana", departmentId: D, name: "Asana", kind: "tool", aliases: [], position: 2 },
  { id: "pm-tool-notion", departmentId: D, name: "Notion", kind: "tool", aliases: [], position: 3 },
  { id: "pm-tool-linear", departmentId: D, name: "Linear", kind: "tool", aliases: [], position: 4 },
  { id: "pm-tool-ms-project", departmentId: D, name: "MS Project", kind: "tool", aliases: ["microsoft project", "project online"], position: 5 },
  { id: "pm-tool-miro", departmentId: D, name: "Miro", kind: "tool", aliases: ["whiteboard", "figjam"], position: 6 },
  { id: "pm-tool-confluence", departmentId: D, name: "Confluence", kind: "tool", aliases: ["wiki"], position: 7 },
  { id: "pm-tool-trello", departmentId: D, name: "Trello", kind: "tool", aliases: [], position: 8 },
  { id: "pm-tool-monday", departmentId: D, name: "Monday.com", kind: "tool", aliases: ["monday"], position: 9 },
  { id: "pm-tool-google-workspace", departmentId: D, name: "Google Workspace", kind: "tool", aliases: ["google sheets", "google docs", "gsuite"], position: 10 },
  { id: "pm-tool-slack", departmentId: D, name: "Slack", kind: "tool", aliases: [], position: 11 },
];

const ALL = ["pm-agile", "pm-technical", "pm-program"];

export const PM_SKILLS: SeedSkill[] = [
  // Foundations (beginner)
  { id: "pm-project-lifecycle", departmentId: D, name: "Project lifecycle & phases", area: "Project foundations", aliases: ["initiation planning execution closure", "project phases", "plc"], tags: ["lifecycle", "foundations"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["pm-beginner"] },
  { id: "pm-roles", departmentId: D, name: "Project roles & agency team structure", area: "Project foundations", aliases: ["roles", "project sponsor", "ba qa dev", "team structure"], tags: ["roles", "foundations", "team"], levelMin: "beginner", levelMax: "beginner", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["pm-beginner"] },
  { id: "pm-scope-basics", departmentId: D, name: "Scope definition & WBS", area: "Project foundations", aliases: ["scope", "work breakdown structure", "wbs", "deliverables", "triple constraint"], tags: ["scope", "planning"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: ["pm-project-lifecycle"], stackIds: [], contentModules: ["pm-beginner"] },
  { id: "pm-schedule-basics", departmentId: D, name: "Schedules, milestones & Gantt charts", area: "Project foundations", aliases: ["gantt", "timeline", "milestones", "critical path", "scheduling"], tags: ["schedule", "planning"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["pm-technical", "pm-program"], prerequisites: ["pm-scope-basics"], stackIds: ["pm-tool-ms-project", "pm-tool-monday"], contentModules: ["pm-beginner"] },
  { id: "pm-budget-basics", departmentId: D, name: "Project budgets & cost basics", area: "Project foundations", aliases: ["budget", "cost tracking", "burn rate", "cost baseline"], tags: ["cost", "finance"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["pm-program", "pm-agile"], prerequisites: ["pm-scope-basics"], stackIds: ["pm-tool-google-workspace"], contentModules: ["pm-beginner"] },
  { id: "pm-requirements-gathering", departmentId: D, name: "Requirements gathering", area: "Project foundations", aliases: ["requirements", "elicitation", "brd", "client brief", "discovery"], tags: ["requirements", "analysis"], levelMin: "beginner", levelMax: "advanced", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["pm-beginner"] },
  { id: "pm-workshops", departmentId: D, name: "Workshops & whiteboarding", area: "Project foundations", aliases: ["miro boards", "user journey mapping", "story mapping", "workshop facilitation"], tags: ["facilitation", "requirements"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["pm-agile", "pm-technical"], prerequisites: ["pm-requirements-gathering"], stackIds: ["pm-tool-miro"], contentModules: ["pm-beginner"] },

  // Agile delivery
  { id: "pm-scrum-accountabilities", departmentId: D, name: "Scrum accountabilities", area: "Agile delivery", aliases: ["scrum master", "product owner", "developers", "scrum roles"], tags: ["scrum", "agile"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["pm-agile", "pm-technical"], prerequisites: [], stackIds: [], contentModules: ["pm-beginner"] },
  { id: "pm-scrum-events", departmentId: D, name: "Scrum events", area: "Agile delivery", aliases: ["sprint", "sprint review", "daily scrum", "ceremonies"], tags: ["scrum", "agile"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["pm-agile", "pm-technical"], prerequisites: ["pm-scrum-accountabilities"], stackIds: [], contentModules: ["pm-beginner"] },
  { id: "pm-scrum-artifacts", departmentId: D, name: "Scrum artifacts & Definition of Done", area: "Agile delivery", aliases: ["product backlog", "sprint backlog", "increment", "dod", "definition of done", "sprint goal"], tags: ["scrum", "agile"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["pm-agile", "pm-technical"], prerequisites: ["pm-scrum-accountabilities"], stackIds: [], contentModules: ["pm-beginner"] },
  { id: "pm-kanban", departmentId: D, name: "Kanban basics", area: "Agile delivery", aliases: ["kanban", "wip limits", "kanban board", "pull system"], tags: ["kanban", "agile", "flow"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["pm-agile", "pm-technical"], prerequisites: [], stackIds: ["pm-tool-trello", "pm-tool-jira"], contentModules: ["pm-beginner"] },
  { id: "pm-user-stories", departmentId: D, name: "Writing user stories", area: "Agile delivery", aliases: ["user story", "as a user", "invest", "epics", "story splitting"], tags: ["backlog", "requirements", "agile"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["pm-beginner"] },
  { id: "pm-acceptance-criteria", departmentId: D, name: "Acceptance criteria", area: "Agile delivery", aliases: ["gherkin", "given when then", "ac", "definition of ready"], tags: ["backlog", "requirements", "qa"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: ["pm-user-stories"], stackIds: [], contentModules: ["pm-beginner"] },
  { id: "pm-standups", departmentId: D, name: "Running daily stand-ups", area: "Agile delivery", aliases: ["standup", "daily scrum", "stand up", "blockers"], tags: ["meetings", "agile"], levelMin: "beginner", levelMax: "beginner", trackIds: ["pm-agile", "pm-technical"], prerequisites: ["pm-scrum-events"], stackIds: ["pm-tool-slack"], contentModules: ["pm-beginner"] },
  { id: "pm-sprint-planning", departmentId: D, name: "Sprint planning", area: "Agile delivery", aliases: ["sprint planning", "sprint goal", "commitment", "iteration planning"], tags: ["scrum", "planning"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["pm-agile", "pm-technical"], prerequisites: ["pm-scrum-events", "pm-user-stories"], stackIds: ["pm-tool-jira", "pm-tool-clickup"], contentModules: ["pm-intermediate"] },
  { id: "pm-backlog-refinement", departmentId: D, name: "Backlog refinement", area: "Agile delivery", aliases: ["grooming", "backlog grooming", "refinement", "story splitting"], tags: ["backlog", "agile"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["pm-agile", "pm-technical"], prerequisites: ["pm-acceptance-criteria"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-estimation", departmentId: D, name: "Estimation with story points", area: "Agile delivery", aliases: ["story points", "planning poker", "t-shirt sizing", "fibonacci"], tags: ["estimation", "agile"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["pm-agile", "pm-technical"], prerequisites: ["pm-user-stories"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-velocity-capacity", departmentId: D, name: "Velocity & sprint capacity", area: "Agile delivery", aliases: ["velocity", "capacity", "focus factor", "availability"], tags: ["estimation", "metrics", "agile"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["pm-agile", "pm-technical"], prerequisites: ["pm-estimation"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-retrospectives", departmentId: D, name: "Running retrospectives", area: "Agile delivery", aliases: ["retro", "retrospective", "start stop continue", "lessons learned"], tags: ["meetings", "continuous-improvement"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["pm-agile"], prerequisites: ["pm-scrum-events"], stackIds: ["pm-tool-miro"], contentModules: ["pm-intermediate"] },
  { id: "pm-hybrid-delivery", departmentId: D, name: "Hybrid delivery (agile inside fixed scope)", area: "Agile delivery", aliases: ["hybrid", "water-scrum-fall", "agile fixed price", "phased agile"], tags: ["methodology", "agile", "waterfall"], levelMin: "advanced", levelMax: "expert", trackIds: ALL, prerequisites: ["pm-sprint-planning", "pm-schedule-basics"], stackIds: [], contentModules: ["pm-advanced"] },
  { id: "pm-delivery-metrics", departmentId: D, name: "Burndown & burnup charts", area: "Agile delivery", aliases: ["burndown", "burnup", "sprint report", "release burnup"], tags: ["metrics", "reporting"], levelMin: "advanced", levelMax: "advanced", trackIds: ["pm-agile", "pm-technical"], prerequisites: ["pm-velocity-capacity"], stackIds: ["pm-tool-jira"], contentModules: ["pm-advanced"] },
  { id: "pm-flow-metrics", departmentId: D, name: "Flow metrics (cycle time, throughput)", area: "Agile delivery", aliases: ["cycle time", "lead time", "throughput", "cumulative flow diagram", "wip age"], tags: ["metrics", "kanban", "flow"], levelMin: "advanced", levelMax: "expert", trackIds: ["pm-agile", "pm-program"], prerequisites: ["pm-kanban"], stackIds: ["pm-tool-jira", "pm-tool-linear"], contentModules: ["pm-advanced"] },
  { id: "pm-delivery-forecasting", departmentId: D, name: "Delivery forecasting", area: "Agile delivery", aliases: ["monte carlo", "release forecast", "probabilistic forecasting", "when will it be done"], tags: ["forecasting", "metrics"], levelMin: "advanced", levelMax: "expert", trackIds: ["pm-agile", "pm-program"], prerequisites: ["pm-flow-metrics"], stackIds: [], contentModules: ["pm-advanced"] },

  // Tools
  { id: "pm-jira", departmentId: D, name: "Jira for delivery", area: "PM tools", aliases: ["jira", "jql", "jira boards", "jira workflows"], tags: ["tools", "jira"], levelMin: "beginner", levelMax: "advanced", trackIds: ALL, prerequisites: [], stackIds: ["pm-tool-jira"], contentModules: ["pm-beginner"] },
  { id: "pm-clickup", departmentId: D, name: "ClickUp for delivery", area: "PM tools", aliases: ["clickup", "click up", "clickup spaces"], tags: ["tools", "clickup"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: ["pm-tool-clickup"], contentModules: ["pm-beginner"] },
  { id: "pm-work-management-tools", departmentId: D, name: "Asana, Trello, Monday & Linear", area: "PM tools", aliases: ["asana", "trello", "monday.com", "linear"], tags: ["tools"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: ["pm-tool-asana", "pm-tool-trello", "pm-tool-monday", "pm-tool-linear"], contentModules: ["pm-beginner"] },
  { id: "pm-documentation-tools", departmentId: D, name: "Project documentation in Notion & Confluence", area: "PM tools", aliases: ["notion", "confluence", "wiki", "project docs"], tags: ["tools", "documentation"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: ["pm-tool-notion", "pm-tool-confluence"], contentModules: ["pm-beginner"] },
  { id: "pm-spreadsheets", departmentId: D, name: "Spreadsheets for PMs", area: "PM tools", aliases: ["google sheets", "excel", "trackers", "pivot tables"], tags: ["tools", "reporting"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["pm-program", "pm-agile"], prerequisites: [], stackIds: ["pm-tool-google-workspace"], contentModules: ["pm-beginner"] },
  { id: "pm-time-tracking", departmentId: D, name: "Time tracking & timesheets", area: "PM tools", aliases: ["timesheets", "harvest", "toggl", "billable hours", "utilisation"], tags: ["time", "commercial"], levelMin: "intermediate", levelMax: "intermediate", trackIds: ["pm-agile", "pm-program"], prerequisites: ["pm-budget-basics"], stackIds: ["pm-tool-clickup", "pm-tool-jira"], contentModules: ["pm-intermediate"] },
  { id: "pm-tool-automation", departmentId: D, name: "Workflow automation in PM tools", area: "PM tools", aliases: ["jira automation", "clickup automations", "zapier", "integrations"], tags: ["tools", "automation"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["pm-technical", "pm-program"], prerequisites: ["pm-jira"], stackIds: ["pm-tool-jira", "pm-tool-clickup", "pm-tool-slack"], contentModules: ["pm-intermediate"] },

  // Communication & stakeholders
  { id: "pm-status-reporting", departmentId: D, name: "Status reporting", area: "Communication & stakeholders", aliases: ["status report", "weekly update", "rag status", "project dashboard"], tags: ["reporting", "communication"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: ["pm-tool-google-workspace"], contentModules: ["pm-beginner"] },
  { id: "pm-client-communication", departmentId: D, name: "Client communication", area: "Communication & stakeholders", aliases: ["client updates", "client emails", "client calls", "account communication"], tags: ["communication", "client"], levelMin: "beginner", levelMax: "advanced", trackIds: ALL, prerequisites: [], stackIds: ["pm-tool-slack"], contentModules: ["pm-beginner"] },
  { id: "pm-meeting-facilitation", departmentId: D, name: "Meeting facilitation & minutes", area: "Communication & stakeholders", aliases: ["agendas", "meeting notes", "minutes", "action items", "mom"], tags: ["meetings", "communication"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["pm-beginner"] },
  { id: "pm-kickoff", departmentId: D, name: "Project kickoff", area: "Communication & stakeholders", aliases: ["kickoff meeting", "onboarding a client", "project charter"], tags: ["communication", "planning", "client"], levelMin: "intermediate", levelMax: "advanced", trackIds: ALL, prerequisites: ["pm-client-communication", "pm-scope-basics"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-stakeholder-mapping", departmentId: D, name: "Stakeholder mapping", area: "Communication & stakeholders", aliases: ["power interest grid", "stakeholder analysis", "stakeholder register"], tags: ["stakeholders", "communication"], levelMin: "intermediate", levelMax: "advanced", trackIds: ALL, prerequisites: ["pm-roles"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-raci", departmentId: D, name: "RACI matrices", area: "Communication & stakeholders", aliases: ["raci", "responsibility matrix", "rasci", "daci"], tags: ["stakeholders", "roles"], levelMin: "intermediate", levelMax: "intermediate", trackIds: ALL, prerequisites: ["pm-roles"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-expectation-management", departmentId: D, name: "Managing client expectations", area: "Communication & stakeholders", aliases: ["expectations", "saying no", "under promise over deliver", "client trust"], tags: ["client", "communication"], levelMin: "intermediate", levelMax: "advanced", trackIds: ALL, prerequisites: ["pm-client-communication"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-escalations", departmentId: D, name: "Escalation management", area: "Communication & stakeholders", aliases: ["escalations", "escalation path", "issue escalation"], tags: ["client", "issues"], levelMin: "advanced", levelMax: "expert", trackIds: ALL, prerequisites: ["pm-expectation-management"], stackIds: [], contentModules: ["pm-advanced"] },
  { id: "pm-difficult-conversations", departmentId: D, name: "Difficult conversations", area: "Communication & stakeholders", aliases: ["bad news", "conflict resolution", "delivering bad news", "negotiating with clients"], tags: ["communication", "conflict"], levelMin: "advanced", levelMax: "expert", trackIds: ALL, prerequisites: ["pm-expectation-management"], stackIds: [], contentModules: ["pm-advanced"] },
  { id: "pm-team-leadership", departmentId: D, name: "Leading cross-functional teams", area: "Communication & stakeholders", aliases: ["team leadership", "motivation", "servant leadership", "one on ones"], tags: ["leadership", "team"], levelMin: "advanced", levelMax: "expert", trackIds: ALL, prerequisites: ["pm-roles"], stackIds: [], contentModules: ["pm-advanced"] },

  // Technical literacy
  { id: "pm-sdlc", departmentId: D, name: "Software development lifecycle for PMs", area: "Technical literacy", aliases: ["sdlc", "design to deployment", "how software gets built"], tags: ["technical", "foundations"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["pm-technical", "pm-agile"], prerequisites: [], stackIds: [], contentModules: ["pm-beginner"] },
  { id: "pm-environments", departmentId: D, name: "Environments: dev, staging & production", area: "Technical literacy", aliases: ["staging", "production", "qa environment", "uat environment"], tags: ["technical", "environments"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["pm-technical", "pm-agile"], prerequisites: ["pm-sdlc"], stackIds: [], contentModules: ["pm-beginner"] },
  { id: "pm-apis-for-pms", departmentId: D, name: "APIs & integrations for PMs", area: "Technical literacy", aliases: ["api", "rest", "third-party integrations", "postman", "webhooks"], tags: ["technical", "api"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["pm-technical"], prerequisites: ["pm-sdlc"], stackIds: [], contentModules: ["pm-beginner"] },
  { id: "pm-git-flow", departmentId: D, name: "Git flow & code review for PMs", area: "Technical literacy", aliases: ["git", "branches", "pull requests", "merge"], tags: ["technical", "git"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["pm-technical"], prerequisites: ["pm-sdlc"], stackIds: [], contentModules: ["pm-beginner"] },
  { id: "pm-deployment-basics", departmentId: D, name: "How deployments & releases work", area: "Technical literacy", aliases: ["deployment", "ci/cd", "hotfix", "rollback", "app store review"], tags: ["technical", "release"], levelMin: "beginner", levelMax: "intermediate", trackIds: ["pm-technical", "pm-agile"], prerequisites: ["pm-environments"], stackIds: [], contentModules: ["pm-beginner"] },
  { id: "pm-prd-writing", departmentId: D, name: "Writing PRDs & functional specs", area: "Technical literacy", aliases: ["prd", "product requirements document", "functional spec", "srs"], tags: ["requirements", "documentation"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["pm-technical", "pm-agile"], prerequisites: ["pm-requirements-gathering", "pm-user-stories"], stackIds: ["pm-tool-notion", "pm-tool-confluence"], contentModules: ["pm-intermediate"] },
  { id: "pm-technical-tradeoffs", departmentId: D, name: "Technical trade-offs & tech debt", area: "Technical literacy", aliases: ["tech debt", "architecture decisions", "build vs buy", "non-functional requirements"], tags: ["technical", "decisions"], levelMin: "advanced", levelMax: "expert", trackIds: ["pm-technical"], prerequisites: ["pm-sdlc"], stackIds: [], contentModules: ["pm-advanced"] },

  // Scope, risk & quality
  { id: "pm-prioritisation-moscow", departmentId: D, name: "Prioritisation with MoSCoW", area: "Scope, risk & quality", aliases: ["moscow", "must should could wont", "prioritization"], tags: ["prioritisation", "backlog"], levelMin: "intermediate", levelMax: "intermediate", trackIds: ALL, prerequisites: ["pm-user-stories"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-prioritisation-rice", departmentId: D, name: "Prioritisation with RICE", area: "Scope, risk & quality", aliases: ["rice", "reach impact confidence effort", "scoring"], tags: ["prioritisation", "backlog"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["pm-agile", "pm-technical"], prerequisites: ["pm-user-stories"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-prioritisation-wsjf", departmentId: D, name: "Prioritisation with WSJF", area: "Scope, risk & quality", aliases: ["wsjf", "cost of delay", "weighted shortest job first"], tags: ["prioritisation", "safe"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["pm-program", "pm-agile"], prerequisites: ["pm-user-stories"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-change-requests", departmentId: D, name: "Change requests", area: "Scope, risk & quality", aliases: ["cr", "change request", "change control", "variation order"], tags: ["scope", "commercial"], levelMin: "intermediate", levelMax: "advanced", trackIds: ALL, prerequisites: ["pm-scope-basics"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-scope-control", departmentId: D, name: "Scope control & preventing scope creep", area: "Scope, risk & quality", aliases: ["scope creep", "gold plating", "out of scope", "scope baseline"], tags: ["scope", "client"], levelMin: "intermediate", levelMax: "advanced", trackIds: ALL, prerequisites: ["pm-change-requests"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-raid-log", departmentId: D, name: "RAID logs", area: "Scope, risk & quality", aliases: ["raid", "risks assumptions issues dependencies", "issue log"], tags: ["risk", "governance"], levelMin: "intermediate", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: ["pm-tool-google-workspace", "pm-tool-confluence"], contentModules: ["pm-intermediate"] },
  { id: "pm-risk-management", departmentId: D, name: "Risk management", area: "Scope, risk & quality", aliases: ["risk register", "probability impact", "mitigation", "risk response"], tags: ["risk"], levelMin: "intermediate", levelMax: "expert", trackIds: ALL, prerequisites: ["pm-raid-log"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-dependency-management", departmentId: D, name: "Dependency management", area: "Scope, risk & quality", aliases: ["dependencies", "blockers", "third-party dependencies", "client dependencies"], tags: ["risk", "planning"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["pm-technical", "pm-program"], prerequisites: ["pm-raid-log"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-qa-coordination", departmentId: D, name: "QA coordination & bug triage", area: "Scope, risk & quality", aliases: ["qa", "bug triage", "test plan", "severity priority", "regression testing"], tags: ["quality", "qa"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["pm-technical", "pm-agile"], prerequisites: ["pm-acceptance-criteria"], stackIds: ["pm-tool-jira"], contentModules: ["pm-intermediate"] },
  { id: "pm-uat", departmentId: D, name: "UAT & client sign-off", area: "Scope, risk & quality", aliases: ["uat", "user acceptance testing", "sign-off", "acceptance"], tags: ["quality", "client"], levelMin: "intermediate", levelMax: "advanced", trackIds: ALL, prerequisites: ["pm-qa-coordination"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-release-management", departmentId: D, name: "Release management", area: "Scope, risk & quality", aliases: ["release plan", "go-live", "launch checklist", "release notes", "cutover"], tags: ["release", "technical"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["pm-technical", "pm-agile"], prerequisites: ["pm-deployment-basics"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-project-recovery", departmentId: D, name: "Project recovery", area: "Scope, risk & quality", aliases: ["failing project", "red project", "turnaround", "rescue project"], tags: ["risk", "recovery"], levelMin: "advanced", levelMax: "expert", trackIds: ALL, prerequisites: ["pm-risk-management", "pm-difficult-conversations"], stackIds: [], contentModules: ["pm-advanced"] },

  // Commercial & contracts
  { id: "pm-commercial-fixed-bid", departmentId: D, name: "Fixed-bid projects", area: "Commercial & contracts", aliases: ["fixed price", "fixed bid", "fixed scope"], tags: ["commercial", "contracts"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["pm-agile", "pm-program"], prerequisites: ["pm-budget-basics"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-commercial-tm", departmentId: D, name: "Time & materials projects", area: "Commercial & contracts", aliases: ["t&m", "time and materials", "hourly billing"], tags: ["commercial", "contracts"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["pm-agile", "pm-program"], prerequisites: ["pm-budget-basics"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-commercial-retainer", departmentId: D, name: "Retainers & dedicated teams", area: "Commercial & contracts", aliases: ["retainer", "monthly retainer", "dedicated team", "support contract"], tags: ["commercial", "contracts"], levelMin: "intermediate", levelMax: "advanced", trackIds: ["pm-agile", "pm-program"], prerequisites: ["pm-budget-basics"], stackIds: [], contentModules: ["pm-intermediate"] },
  { id: "pm-sow", departmentId: D, name: "Statements of work", area: "Commercial & contracts", aliases: ["sow", "statement of work", "scope document", "milestone payments"], tags: ["contracts", "scope"], levelMin: "advanced", levelMax: "expert", trackIds: ["pm-program", "pm-technical"], prerequisites: ["pm-scope-basics", "pm-commercial-fixed-bid"], stackIds: [], contentModules: ["pm-advanced"] },
  { id: "pm-contract-management", departmentId: D, name: "Contract management", area: "Commercial & contracts", aliases: ["contracts", "slas", "warranty period", "invoicing milestones"], tags: ["contracts", "governance"], levelMin: "advanced", levelMax: "expert", trackIds: ["pm-program"], prerequisites: ["pm-sow"], stackIds: [], contentModules: ["pm-advanced"] },
  { id: "pm-evm", departmentId: D, name: "Earned value management (CPI, SPI)", area: "Commercial & contracts", aliases: ["evm", "cpi", "spi", "earned value", "eac"], tags: ["metrics", "finance"], levelMin: "advanced", levelMax: "expert", trackIds: ["pm-program"], prerequisites: ["pm-budget-basics", "pm-schedule-basics"], stackIds: ["pm-tool-ms-project"], contentModules: ["pm-advanced"] },
  { id: "pm-vendor-management", departmentId: D, name: "Vendor & subcontractor management", area: "Commercial & contracts", aliases: ["vendors", "subcontractors", "freelancers", "outsourcing"], tags: ["vendors", "governance"], levelMin: "advanced", levelMax: "expert", trackIds: ["pm-program"], prerequisites: ["pm-contract-management"], stackIds: [], contentModules: ["pm-advanced"] },
  { id: "pm-profitability", departmentId: D, name: "Project profitability & margins", area: "Commercial & contracts", aliases: ["margin", "profitability", "write-offs", "utilisation rate"], tags: ["finance", "commercial"], levelMin: "advanced", levelMax: "expert", trackIds: ["pm-program"], prerequisites: ["pm-time-tracking"], stackIds: [], contentModules: ["pm-advanced"] },

  // Programme & portfolio
  { id: "pm-multi-project", departmentId: D, name: "Managing multiple projects", area: "Programme & portfolio", aliases: ["multi-project", "juggling projects", "context switching", "portfolio view"], tags: ["planning", "portfolio"], levelMin: "advanced", levelMax: "expert", trackIds: ["pm-program", "pm-agile"], prerequisites: ["pm-status-reporting"], stackIds: [], contentModules: ["pm-advanced"] },
  { id: "pm-resource-planning", departmentId: D, name: "Resource & capacity planning", area: "Programme & portfolio", aliases: ["resource allocation", "capacity planning", "bench", "resource leveling"], tags: ["resources", "planning"], levelMin: "advanced", levelMax: "expert", trackIds: ["pm-program"], prerequisites: ["pm-velocity-capacity"], stackIds: ["pm-tool-google-workspace", "pm-tool-ms-project"], contentModules: ["pm-advanced"] },
  { id: "pm-programme-governance", departmentId: D, name: "Programme governance", area: "Programme & portfolio", aliases: ["programme management", "program management", "steering committee", "stage gates"], tags: ["governance", "program"], levelMin: "expert", levelMax: "expert", trackIds: ["pm-program"], prerequisites: ["pm-multi-project"], stackIds: [], contentModules: ["pm-expert"] },
  { id: "pm-portfolio-management", departmentId: D, name: "Portfolio management", area: "Programme & portfolio", aliases: ["portfolio", "ppm", "project selection", "portfolio prioritisation"], tags: ["governance", "portfolio"], levelMin: "expert", levelMax: "expert", trackIds: ["pm-program"], prerequisites: ["pm-programme-governance"], stackIds: [], contentModules: ["pm-expert"] },
  { id: "pm-business-case", departmentId: D, name: "Business cases", area: "Programme & portfolio", aliases: ["business case", "roi", "cost benefit analysis", "npv"], tags: ["finance", "strategy"], levelMin: "expert", levelMax: "expert", trackIds: ["pm-program"], prerequisites: ["pm-budget-basics"], stackIds: [], contentModules: ["pm-expert"] },
  { id: "pm-value-realisation", departmentId: D, name: "Benefits & value realisation", area: "Programme & portfolio", aliases: ["benefits realisation", "outcomes", "okrs", "value tracking"], tags: ["strategy", "value"], levelMin: "expert", levelMax: "expert", trackIds: ["pm-program"], prerequisites: ["pm-business-case"], stackIds: [], contentModules: ["pm-expert"] },
  { id: "pm-safe", departmentId: D, name: "Scaling agile with SAFe", area: "Programme & portfolio", aliases: ["safe", "scaled agile", "pi planning", "agile release train", "art"], tags: ["scaling", "agile"], levelMin: "expert", levelMax: "expert", trackIds: ["pm-program", "pm-agile"], prerequisites: ["pm-sprint-planning"], stackIds: [], contentModules: ["pm-expert"] },
  { id: "pm-less-nexus", departmentId: D, name: "LeSS, Nexus & Scrum of Scrums", area: "Programme & portfolio", aliases: ["less", "large scale scrum", "nexus", "scrum of scrums"], tags: ["scaling", "agile"], levelMin: "expert", levelMax: "expert", trackIds: ["pm-program", "pm-agile"], prerequisites: ["pm-sprint-planning"], stackIds: [], contentModules: ["pm-expert"] },

  // Certification & growth
  { id: "pm-pmp", departmentId: D, name: "PMP exam alignment", area: "Certification & growth", aliases: ["pmp", "pmbok", "pmi", "project management professional"], tags: ["certification", "pmi"], levelMin: "expert", levelMax: "expert", trackIds: ["pm-program", "pm-technical"], prerequisites: ["pm-risk-management", "pm-evm"], stackIds: [], contentModules: ["pm-expert"] },
  { id: "pm-pmi-acp", departmentId: D, name: "PMI-ACP exam alignment", area: "Certification & growth", aliases: ["pmi-acp", "agile certified practitioner", "psm", "csm"], tags: ["certification", "agile"], levelMin: "expert", levelMax: "expert", trackIds: ["pm-agile"], prerequisites: ["pm-sprint-planning", "pm-flow-metrics"], stackIds: [], contentModules: ["pm-expert"] },
  { id: "pm-coaching", departmentId: D, name: "Coaching & mentoring PMs", area: "Certification & growth", aliases: ["mentoring", "coaching", "pm career ladder", "agile coaching"], tags: ["leadership", "coaching"], levelMin: "expert", levelMax: "expert", trackIds: ALL, prerequisites: ["pm-team-leadership"], stackIds: [], contentModules: ["pm-expert"] },

  // AI in project delivery
  { id: "pm-ai-meeting-notes", departmentId: D, name: "AI meeting notes & summaries", area: "AI in project delivery", aliases: ["ai notes", "fireflies", "otter", "meeting summaries", "ai minutes"], tags: ["ai", "meetings"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: ["pm-meeting-facilitation"], stackIds: [], contentModules: ["pm-beginner"], isAiSkill: true },
  { id: "pm-ai-status-reports", departmentId: D, name: "AI-assisted status reports & client updates", area: "AI in project delivery", aliases: ["ai status report", "ai client email", "chatgpt for pms"], tags: ["ai", "reporting"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: ["pm-status-reporting"], stackIds: [], contentModules: ["pm-beginner"], isAiSkill: true },
  { id: "pm-ai-prds", departmentId: D, name: "Writing PRDs & user stories with Claude", area: "AI in project delivery", aliases: ["ai prd", "claude prd", "ai user stories", "ai acceptance criteria"], tags: ["ai", "requirements"], levelMin: "intermediate", levelMax: "advanced", trackIds: ALL, prerequisites: ["pm-prd-writing"], stackIds: [], contentModules: ["pm-intermediate"], isAiSkill: true },
  { id: "pm-ai-risk-analysis", departmentId: D, name: "AI risk analysis", area: "AI in project delivery", aliases: ["ai risk register", "ai pre-mortem", "ai raid"], tags: ["ai", "risk"], levelMin: "advanced", levelMax: "expert", trackIds: ALL, prerequisites: ["pm-risk-management"], stackIds: [], contentModules: ["pm-advanced"], isAiSkill: true },
  { id: "pm-ai-estimating", departmentId: D, name: "Estimating AI-assisted development work", area: "AI in project delivery", aliases: ["ai velocity", "estimating with copilot", "ai productivity"], tags: ["ai", "estimation"], levelMin: "advanced", levelMax: "expert", trackIds: ["pm-technical", "pm-agile", "pm-program"], prerequisites: ["pm-estimation"], stackIds: [], contentModules: ["pm-advanced"], isAiSkill: true },
  { id: "pm-ai-teams", departmentId: D, name: "Managing AI-assisted teams", area: "AI in project delivery", aliases: ["ai teams", "ai adoption", "ai governance", "ai policy"], tags: ["ai", "leadership"], levelMin: "expert", levelMax: "expert", trackIds: ALL, prerequisites: ["pm-team-leadership", "pm-ai-estimating"], stackIds: [], contentModules: ["pm-expert"], isAiSkill: true },
  { id: "pm-ai-tool-automation", departmentId: D, name: "AI features in Jira, ClickUp & Notion", area: "AI in project delivery", aliases: ["atlassian intelligence", "clickup brain", "notion ai", "rovo"], tags: ["ai", "tools"], levelMin: "intermediate", levelMax: "advanced", trackIds: ALL, prerequisites: ["pm-jira"], stackIds: ["pm-tool-jira", "pm-tool-clickup", "pm-tool-notion"], contentModules: ["pm-intermediate"], isAiSkill: true },
];
