import type { SeedSkill } from "./types";

/**
 * v4.1: the agency PM catalog — practical, tool-level, client-facing skills first.
 *
 * `defaultSlider` is what the Setup screen pre-selects for a new PM learner (the admin can move
 * every slider): Critical for client management, client update meetings and email; High for Excel,
 * resource management, tech terms and the SDLC; Medium for Teams, Word & PowerPoint, Keka and
 * GitHub; Low for the generic PM theory, which moves to the end of the trail.
 */
const D = "pm";
const ALL = ["pm-agile", "pm-technical", "pm-program"];

export const PM_AGENCY_SKILLS: SeedSkill[] = [
  { id: "pm-agency-refresh", departmentId: D, name: "Improving your existing PM skills", area: "Agency PM essentials", aliases: ["diagnostic refresh", "planning a week", "follow-ups", "ownership", "tracking"], tags: ["pm", "refresh", "ownership"], levelMin: "beginner", levelMax: "advanced", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["pma-refresh"] },
  { id: "pm-client-management", departmentId: D, name: "Client management", area: "Agency PM essentials", aliases: ["client onboarding", "kickoff", "scope conversations", "saying no", "unhappy client", "bad news", "time zones", "client relationship"], tags: ["client", "communication"], levelMin: "beginner", levelMax: "advanced", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["pma-client"], defaultSlider: 5 },
  { id: "pm-client-meetings", departmentId: D, name: "Client update meetings & presenting", area: "Agency PM essentials", aliases: ["status meeting", "rag status", "demo", "mom", "minutes of meeting", "presenting progress", "teams meeting"], tags: ["client", "meetings", "presenting"], levelMin: "beginner", levelMax: "advanced", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["pma-meetings"], defaultSlider: 5 },
  { id: "pm-email-etiquette", departmentId: D, name: "Email etiquette & professional writing", area: "Agency PM essentials", aliases: ["email", "outlook", "status email", "escalation email", "cc bcc", "reply all", "writing for non-native readers"], tags: ["email", "writing", "client"], levelMin: "beginner", levelMax: "advanced", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["pma-email"], defaultSlider: 5 },
  { id: "pm-excel-for-pms", departmentId: D, name: "Excel for PMs", area: "Agency PM tools", aliases: ["excel", "spreadsheets", "sumif", "xlookup", "pivot table", "gantt in excel", "tracker", "google sheets", "conditional formatting"], tags: ["excel", "tools", "tracking"], levelMin: "beginner", levelMax: "advanced", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["pma-excel"], defaultSlider: 4 },
  { id: "pm-agency-resourcing", departmentId: D, name: "Agency resource management", area: "Agency PM essentials", aliases: ["capacity", "allocation", "utilisation", "billable %", "bench", "skill matrix", "over-allocation", "resource forecast"], tags: ["resources", "capacity", "billable"], levelMin: "intermediate", levelMax: "advanced", trackIds: ALL, prerequisites: ["pm-excel-for-pms"], stackIds: [], contentModules: ["pma-resource"], defaultSlider: 4 },
  { id: "pm-tech-terms", departmentId: D, name: "Tech terms in plain language", area: "Agency PM essentials", aliases: ["glossary", "api", "dns", "ssl", "ci/cd", "technical debt", "explain to a client", "llm", "hallucination"], tags: ["technical", "client", "glossary"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["pma-tech-terms"], defaultSlider: 4 },
  { id: "pm-agency-sdlc", departmentId: D, name: "The SDLC in an agency", area: "Agency PM essentials", aliases: ["sdlc", "discovery to maintenance", "uat", "hotfix", "app store review", "definition of done", "support sla"], tags: ["technical", "delivery"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["pma-sdlc"], defaultSlider: 4 },
  { id: "pm-ms-teams", departmentId: D, name: "Microsoft Teams for PMs", area: "Agency PM tools", aliases: ["teams", "channels", "teams meeting", "recording", "transcript", "planner", "loop", "sharepoint"], tags: ["teams", "tools"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["pma-teams"], defaultSlider: 3 },
  { id: "pm-word-powerpoint", departmentId: D, name: "Word & PowerPoint for PMs", area: "Agency PM tools", aliases: ["word", "track changes", "comments", "styles", "table of contents", "powerpoint", "status deck"], tags: ["word", "powerpoint", "tools"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["pma-word-ppt"], defaultSlider: 3 },
  { id: "pm-keka", departmentId: D, name: "Keka for PMs", area: "Agency PM tools", aliases: ["keka", "timesheets", "timesheet approval", "leave", "attendance", "keka psa", "billing types", "utilisation report"], tags: ["keka", "timesheets", "tools"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["pma-keka"], defaultSlider: 3 },
  { id: "pm-github-for-pms", departmentId: D, name: "Git & GitHub for PMs", area: "Agency PM tools", aliases: ["github", "pull request", "pr review", "branches", "releases", "tags", "github issues", "github projects"], tags: ["github", "technical", "tools"], levelMin: "beginner", levelMax: "intermediate", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["pma-github"], defaultSlider: 3 },
  { id: "pm-ai-for-pms", departmentId: D, name: "AI for PMs (Copilot & Claude)", area: "AI in project delivery", aliases: ["copilot", "claude", "ai mom", "ai status email", "ai excel formulas", "ai prd"], tags: ["ai", "productivity"], levelMin: "beginner", levelMax: "advanced", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["pma-ai"], isAiSkill: true },
  { id: "pm-foundations-theory", departmentId: D, name: "PM foundations and advanced theory", area: "PM foundations and theory", aliases: ["pm theory", "agile theory", "scrum", "evm", "governance", "pmp"], tags: ["theory", "foundations"], levelMin: "beginner", levelMax: "expert", trackIds: ALL, prerequisites: [], stackIds: [], contentModules: ["pm-beginner", "pm-intermediate"], defaultSlider: 2 },
];
