import type { Module } from "@/types/curriculum";

export default {
  id: "pma-sdlc",
  trackId: "pm",
  name: "The SDLC in an agency",
  description:
    "How a client project really moves from discovery to maintenance at an agency: environments, sprints, QA and UAT, what done means, hotfixes, app store reviews and the handover to support.",
  refs: [
    { label: "Atlassian: What is Software Development Life Cycle (SDLC)? Complete Guide", url: "https://www.atlassian.com/agile/software-development/sdlc", kind: "article", verifiedAt: "2026-10-02T09:35:20Z" },
    { label: "Scrum Guides: Scrum Guide", url: "https://scrumguides.org/scrum-guide.html", kind: "spec", verifiedAt: "2026-10-02T09:35:44Z" },
  ],
  topics: [
    // ---------------------------------------------------------------- beginner
    {
      id: "pma-sdlc-phases",
      moduleId: "pma-sdlc",
      trackId: "pm",
      title: "Discovery to maintenance: the phases",
      summary:
        "Every client project goes through the same phases, even when nobody names them: discovery, requirements, design, development, QA, UAT, release and maintenance. A US client asks for a Laravel booking portal. In discovery you learn the business goal and the users. In requirements you write down what the system must do. Design turns that into screens and an architecture. Development builds it. QA is our own testing, UAT is the client's testing, release puts it live, and maintenance keeps it running.\n\nWhy does a PM care about the names? Because each phase has an exit. Discovery ends with an agreed scope. Requirements end with signed-off user stories or a PRD. Design ends with approved screens. If you skip an exit, the cost moves to a later phase, where it is far more expensive. A missing requirement found in design costs an hour. The same gap found in UAT costs a sprint and an awkward call.\n\nHow to use the phases day to day:\n\n1. Know which phase each part of the project is in. Phases overlap in agile work: sprint 3 can be in development while sprint 4 is still in design.\n2. Name the exit for each phase and who signs it off, usually the client's product owner.\n3. Tell the client what you need from them in each phase: answers in discovery, approvals in design, testers in UAT.\n\nA common mistake is to treat \"agile\" as a reason to skip discovery and requirements. Agile changes how often you go round the loop, not whether the steps exist. Another mistake is to forget that maintenance is a phase too: a project that ends at launch, with no plan for support, leaves the client stranded on day two.",
      level: "beginner",
      estMinutes: 25,
      webRefs: [
        { label: "AWS: What is SDLC?", url: "https://aws.amazon.com/what-is/sdlc/", kind: "article", verifiedAt: "2026-10-02T09:35:29Z" },
        { label: "Atlassian: What is Software Development Life Cycle (SDLC)? Complete Guide", url: "https://www.atlassian.com/agile/software-development/sdlc", kind: "article", verifiedAt: "2026-10-02T09:35:20Z" },
        { label: "IBM: What is the Software Development Lifecycle (SDLC)?", url: "https://www.ibm.com/think/topics/sdlc", kind: "article", verifiedAt: "2026-10-02T09:35:26Z" },
        { label: "Scrum Guides: Scrum Guide", url: "https://scrumguides.org/scrum-guide.html", kind: "spec", verifiedAt: "2026-10-02T09:35:44Z" },
      ],
      video: {
        title: "Software Development Life Cycle: Explained",
        channel: "AltexSoft",
        url: "https://www.youtube.com/watch?v=SaCYkPD4_K0",
        videoId: "SaCYkPD4_K0",
        verifiedAt: "2026-10-02T09:35:53Z",
      },
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-sdlc-phases-q1",
          prompt: "What is the difference between QA and UAT on a client project?",
          options: [
            "QA is our team testing against the requirements; UAT is the client testing that it meets their business needs",
            "QA and UAT are the same thing with different names",
            "UAT is done by our developers before QA starts",
            "QA happens after release; UAT happens before",
          ],
          correctIndex: 0,
          explanation: "QA is the agency's own testing. UAT is the client's acceptance, and its sign-off is what allows release.",
        },
        {
          id: "pma-sdlc-phases-q2",
          prompt:
            "During UAT, the client of a React dashboard says: \"Where is the CSV export? We always needed that.\" Nobody wrote it down in discovery. Which phase failed?",
          options: ["Requirements (and discovery before it)", "Development", "QA", "Release"],
          correctIndex: 0,
          explanation: "The need existed but was never captured. Development and QA built and tested what was written, so the gap goes back to requirements.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-sdlc-phases-q3",
          prompt: "Which are things the client must give you during the project phases? (Select all that apply.)",
          options: [
            "Answers and access to users during discovery",
            "Approval of designs before development of those screens",
            "Testers and sign-off during UAT",
            "Code reviews of every pull request",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "The client owns answers, approvals and acceptance. Code review is the agency's internal job.",
        },
        {
          id: "pma-sdlc-phases-q4",
          prompt: "A client says \"We're agile, so let's skip discovery and start coding on Monday.\" What is the best response?",
          options: [
            "Agree to a short, focused discovery: agile changes how often we loop, not whether we understand the goal first",
            "Start coding: agile means no planning",
            "Refuse to start until a 50-page specification is signed",
            "Let developers decide the scope as they go",
          ],
          correctIndex: 0,
          explanation: "A short discovery protects both sides. Skipping it moves the cost of misunderstanding into later, more expensive phases; a huge spec is the opposite extreme.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-sdlc-phases-q5",
          prompt: "Why should maintenance be planned before launch?",
          options: [
            "Because bugs, OS updates and security patches keep coming after go-live, and the client needs to know who handles them and how",
            "Because maintenance is always free",
            "Because the code will stop working the day after launch",
            "It shouldn't: maintenance is discussed only when something breaks",
          ],
          correctIndex: 0,
          explanation: "Software keeps needing care after launch. Agreeing the support model early avoids a stranded client and unbilled work.",
        },
      ],
      practice: {
        kind: "rank",
        prompt:
          "A UK client signs for a Laravel + React booking portal. Put the phases of the project in the order their exits normally happen.",
        items: [
          { id: "discovery", label: "Discovery: business goal, users and scope agreed" },
          { id: "requirements", label: "Requirements: user stories and acceptance criteria signed off" },
          { id: "design", label: "Design: screens and architecture approved" },
          { id: "dev", label: "Development: features built and code reviewed" },
          { id: "qa", label: "QA: our team tests against the acceptance criteria" },
          { id: "uat", label: "UAT: the client tests and signs off" },
          { id: "release", label: "Release: deployed to production" },
          { id: "maintenance", label: "Maintenance: bug fixes, updates and support" },
        ],
        correctOrder: ["discovery", "requirements", "design", "dev", "qa", "uat", "release", "maintenance"],
        explanation:
          "In agile work these loop per sprint and overlap, but each piece of work still passes the same exits in this order. UAT always comes after our own QA, and release only after UAT sign-off.",
      },
    },
    {
      id: "pma-dev-staging-prod",
      moduleId: "pma-sdlc",
      trackId: "pm",
      title: "Dev, staging and prod",
      summary:
        "Most agency projects run on three environments. Dev (or local) is where developers build and break things. Staging is a copy of the live system where QA and the client test. Production, or prod, is the live system real users touch. A Canadian client's React Native app with a Laravel API will usually have a staging API and a production API, and test builds point at staging.\n\nWhy it matters to a PM: the environment tells you who can see a change and how risky it is. \"It's done\" from a developer may mean \"done on my laptop\". The client cannot see it until it is on staging, and users cannot see it until it is on prod. When you report progress, say which environment: \"The checkout fix is on staging for your review\" is precise; \"the checkout fix is done\" is not.\n\nHow to work with environments:\n\n1. Keep a simple list: each environment's URL, which branch deploys there, and who has access.\n2. Send clients only staging links for review, never a developer's local or a temporary tunnel.\n3. Ask the team to keep staging close to prod: same PHP and database versions, similar configuration, realistic but not real data. The Twelve-Factor App calls this dev/prod parity.\n4. Never let clients test with real customer data on staging unless that has been agreed and secured.\n\nA common mistake is to treat a pass on staging as a guarantee for prod. If staging uses a different payment key, a smaller database or a missing queue worker, things that worked there can fail live. When a bug appears only in prod, the first question is: \"What is different between staging and prod?\"",
      level: "beginner",
      estMinutes: 25,
      webRefs: [
        { label: "Twelve-Factor App: Dev/prod parity", url: "https://12factor.net/dev-prod-parity", kind: "article", verifiedAt: "2026-10-02T09:35:30Z" },
        { label: "GitHub Docs: Managing environments for deployment", url: "https://docs.github.com/en/actions/how-tos/deploy/configure-and-manage-deployments/manage-environments", kind: "docs", verifiedAt: "2026-10-02T09:35:34Z" },
        { label: "Atlassian: Continuous integration vs. delivery vs. deployment", url: "https://www.atlassian.com/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment", kind: "article", verifiedAt: "2026-10-02T09:35:45Z" },
      ],
      video: {
        title: "Difference Between Development, Staging, and Prod Environment?",
        channel: "CodeWithHarry",
        url: "https://www.youtube.com/watch?v=H2p4wowlD3Q",
        videoId: "H2p4wowlD3Q",
        verifiedAt: "2026-10-02T09:35:54Z",
      },
      alternateVideos: [
        {
          title: "💻 Staging vs Production Environments : How Tech Startups Deploy?",
          channel: "Mehul Mohan",
          url: "https://www.youtube.com/watch?v=A1E6P7U_nrk",
          videoId: "A1E6P7U_nrk",
          verifiedAt: "2026-10-02T09:35:59Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-dev-staging-prod-q1",
          prompt: "A developer says the new invoice PDF is \"done\". The client wants to see it today. What should you ask first?",
          options: [
            "Is it deployed to staging, and what is the staging link?",
            "Is it in production yet?",
            "How many lines of code did it take?",
            "Can you send the client your local URL?",
          ],
          correctIndex: 0,
          explanation: "Clients review on staging. \"Done\" may mean done locally; production is not where a client should review unreleased work.",
        },
        {
          id: "pma-dev-staging-prod-q2",
          prompt:
            "A Stripe payment flow passes every test on staging but fails for real users in prod. What is the most useful first question?",
          options: [
            "What is different between staging and prod: keys, configuration, data or services?",
            "Who wrote the code?",
            "Should we delete staging since it didn't help?",
            "Can the client test in prod instead from now on?",
          ],
          correctIndex: 0,
          explanation: "Prod-only bugs usually come from differences between environments, such as live API keys or missing services. Blame and abandoning staging do not find the cause.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-dev-staging-prod-q3",
          prompt: "Which keep staging useful as a rehearsal for prod? (Select all that apply.)",
          options: [
            "The same PHP, Node and database versions as prod",
            "Similar configuration, queues and scheduled jobs",
            "Realistic test data that is not real customer data",
            "Letting developers hot-edit files on staging directly",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Parity makes staging results trustworthy. Manual edits on the server make staging drift away from what will actually be deployed.",
        },
        {
          id: "pma-dev-staging-prod-q4",
          prompt: "The client asks to copy the live customer database to staging so their testers see real data. What is the right response?",
          options: [
            "Raise it as a data-protection question: use anonymised or test data unless a secure, agreed process exists",
            "Do it immediately: real data finds more bugs",
            "Email the database export to the testers",
            "Let the developers decide quietly",
          ],
          correctIndex: 0,
          explanation: "Real personal data on a less-protected environment is a privacy and contract risk. It needs an explicit, secure decision, usually anonymised data.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-dev-staging-prod-q5",
          prompt: "Which status line is the most precise for a client?",
          options: [
            "\"The booking reminder emails are on staging for your review; we plan to release them to production on Thursday after your sign-off.\"",
            "\"The reminders are done.\"",
            "\"The reminders are mostly working.\"",
            "\"The reminders were merged.\"",
          ],
          correctIndex: 0,
          explanation: "It says where the change is, what the client should do and what happens next. \"Merged\" is jargon and does not say where it is visible.",
        },
      ],
      practice: {
        kind: "scenario",
        prompt:
          "You manage a React Native app and Laravel API for an Australian fitness client. The team has fixed a bug in the class-booking screen. The client's CEO wants to try it on her phone before the weekend.",
        steps: [
          {
            id: "s1",
            question: "Where should the CEO try the fix?",
            options: [
              "A test build (TestFlight / internal testing) that points at the staging API",
              "The production app from the store, pointed at staging",
              "A developer's laptop over a screen share",
              "Production, with real member data",
            ],
            correctIndex: 0,
            explanation: "A test build on staging lets her try it on her own phone without touching live users or data.",
          },
          {
            id: "s2",
            question: "She approves the fix on staging. A day after release, a member reports the same bug in production. What do you ask the team first?",
            options: [
              "What differs between staging and prod for this flow: data, configuration or the app version the member has?",
              "Why the CEO approved a broken fix",
              "Whether we can skip staging next time",
              "Whether the member is lying",
            ],
            correctIndex: 0,
            explanation: "Mobile adds a twist: the member may still run an old app version. Environment and version differences are the first suspects.",
          },
          {
            id: "s3",
            question: "How do you update the client?",
            options: [
              "Say what you know, what you are checking and when the next update comes, and ask the member's app version if support has it",
              "Wait until the team has a full answer before saying anything",
              "Tell her it works on staging so it is not our problem",
              "Promise a fix within an hour",
            ],
            correctIndex: 0,
            explanation: "Early, factual updates with a next-update time build trust. Silence or promises you cannot keep do the opposite.",
          },
        ],
      },
    },
    // ---------------------------------------------------------------- intermediate
    {
      id: "pma-sprints-in-practice",
      moduleId: "pma-sdlc",
      trackId: "pm",
      title: "Sprints in practice",
      summary:
        "A sprint is a fixed timebox, usually one or two weeks, in which the team commits to a sprint goal and a set of backlog items. The Scrum Guide defines the events: sprint planning, the daily scrum, the sprint review and the retrospective. In an agency, a sprint is also a commercial rhythm: it is how a US client paying time and materials sees steady progress, and how a fixed-bid project shows it is on track.\n\nWhy sprints matter to a PM: they turn a long project into short promises you can keep. The sprint goal is the promise, not the full list of tickets. \"Customers can pay by card on the Laravel checkout\" is a goal. Twelve tickets are the plan to reach it, and the plan can flex.\n\nHow to run sprints well with a client:\n\n1. Before planning, make sure the top of the backlog is ready: clear stories, acceptance criteria and designs. Unready stories are the most common cause of a failed sprint.\n2. In planning, size the work against real capacity: leave, public holidays in India and in the client's country, and support time on other projects.\n3. Protect the sprint. When the client sends a new request mid-sprint, log it in the backlog and agree whether it replaces something. Do not quietly add it.\n4. In the sprint review, demo working software on staging, not slides. Then agree what goes next.\n5. In the retro, pick one or two improvements and actually do them.\n\nScrum is not the only option. Kanban, with a continuous flow and work-in-progress limits, fits support and maintenance work better, where requests arrive daily. Many agencies use sprints for build projects and Kanban for retainers.\n\nA common mistake is to measure success by ticket count. A sprint that closes 15 small tickets but misses the goal has failed the client; one that meets the goal and moves two minor tickets has not.",
      level: "intermediate",
      estMinutes: 35,
      webRefs: [
        { label: "Scrum Guides: Scrum Guide", url: "https://scrumguides.org/scrum-guide.html", kind: "spec", verifiedAt: "2026-10-02T09:35:44Z" },
        { label: "Atlassian: Scrum sprints", url: "https://www.atlassian.com/agile/scrum/sprints", kind: "article", verifiedAt: "2026-10-02T09:35:36Z" },
        { label: "Atlassian: Sprint Planning", url: "https://www.atlassian.com/agile/scrum/sprint-planning", kind: "article", verifiedAt: "2026-10-02T09:35:22Z" },
        { label: "Atlassian: Kanban vs scrum", url: "https://www.atlassian.com/agile/kanban/kanban-vs-scrum", kind: "article", verifiedAt: "2026-10-02T09:35:30Z" },
      ],
      video: {
        title: "Sprint Planning in Scrum: How It Really Works",
        channel: "Mountain Goat Software: Agile & Scrum Mastery",
        url: "https://www.youtube.com/watch?v=bT30zGIfaW8",
        videoId: "bT30zGIfaW8",
        verifiedAt: "2026-10-02T09:35:53Z",
      },
      alternateVideos: [
        {
          title: "Scrum vs Kanban - What's the Difference?",
          channel: "Development That Pays",
          url: "https://www.youtube.com/watch?v=rIaz-l1Kf8w",
          videoId: "rIaz-l1Kf8w",
          verifiedAt: "2026-10-02T09:35:56Z",
        },
        {
          title: "Scrum in 20 mins... (with examples)",
          channel: "Codex Community",
          url: "https://www.youtube.com/watch?v=SWDhGSZNF9M",
          videoId: "SWDhGSZNF9M",
          verifiedAt: "2026-10-02T09:35:56Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-sprints-in-practice-q1",
          prompt: "Which is the best sprint goal for a two-week sprint on a Laravel e-commerce site?",
          options: [
            "Customers can pay by card and receive an order confirmation email",
            "Finish tickets ECOM-101 to ECOM-115",
            "Work on payments",
            "Keep the developers busy",
          ],
          correctIndex: 0,
          explanation: "A goal describes an outcome the client can see and test. A ticket range is a plan, and \"work on payments\" cannot be judged done.",
        },
        {
          id: "pma-sprints-in-practice-q2",
          prompt:
            "On day 4 of a sprint, the client emails: \"Small thing, can you add Apple Pay this sprint?\" What do you do?",
          options: [
            "Log it in the backlog, explain the effect, and offer to swap it for something of similar size or plan it next sprint",
            "Add it quietly; it's small",
            "Refuse to discuss it until the next quarter",
            "Ask the developers to work the weekend",
          ],
          correctIndex: 0,
          explanation: "Protecting the sprint means changes are visible trade-offs, not silent additions. The client keeps control by choosing what moves.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-sprints-in-practice-q3",
          prompt: "Which must you account for when planning sprint capacity for an offshore team and a US client? (Select all that apply.)",
          options: [
            "Planned leave and public holidays in India",
            "US public holidays when the client cannot give approvals",
            "Time developers spend supporting other live projects",
            "The number of tickets closed in the previous company's sprints",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Real capacity is hours actually available for this project, including when the client can respond. Another company's numbers mean nothing here.",
        },
        {
          id: "pma-sprints-in-practice-q4",
          prompt: "What is the most common reason a sprint fails at an agency?",
          options: [
            "Stories entered the sprint without clear acceptance criteria, designs or client answers",
            "The sprint was two weeks instead of one",
            "The daily scrum lasted 15 minutes",
            "The team used Jira instead of GitHub Projects",
          ],
          correctIndex: 0,
          explanation: "Unready work stalls mid-sprint while the team waits for answers. Sprint length and tools matter much less.",
        },
        {
          id: "pma-sprints-in-practice-q5",
          prompt: "What should the client see in a sprint review?",
          options: [
            "Working software on staging, then a discussion of what to do next",
            "A slide deck of tickets closed",
            "Developers' code changes",
            "Only the burndown chart",
          ],
          correctIndex: 0,
          explanation: "The review inspects the increment and adapts the backlog. Slides and charts describe work; a demo proves it.",
        },
        {
          id: "pma-sprints-in-practice-q6",
          prompt: "A client pays a monthly retainer for support and small changes, with requests arriving every day. Which way of working usually fits best?",
          options: [
            "Kanban: continuous flow with work-in-progress limits",
            "Four-week sprints with no changes allowed",
            "A waterfall plan signed once a year",
            "No process: do requests in the order they arrive",
          ],
          correctIndex: 0,
          explanation: "Kanban handles a steady stream of small items without forcing them into fixed timeboxes. Doing items with no prioritisation ignores urgency.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-sprints-in-practice-q7",
          prompt:
            "Sprint A closed 15 of 16 tickets but customers still cannot pay. Sprint B closed 9 of 11 and payments work. Which sprint met its goal of \"customers can pay\"?",
          options: ["Sprint B", "Sprint A", "Both", "Neither: all tickets must close"],
          correctIndex: 0,
          explanation: "Success is the goal, not the count. Moving two minor tickets is fine if the promised outcome is delivered.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-sprints-in-practice-q8",
          prompt: "Which are healthy uses of the retrospective? (Select all that apply.)",
          options: [
            "Choosing one or two concrete improvements with an owner",
            "Checking whether last retro's actions were done",
            "Discussing why client approvals kept arriving late, and what to change",
            "Naming and blaming the developer who caused a bug",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Retros improve the process. Blame makes people hide problems, which makes the next sprint worse.",
        },
      ],
      practice: {
        kind: "scenario",
        prompt:
          "You run two-week sprints on a React + Laravel learning platform for a UK client. Sprint 7's goal: \"Teachers can create and publish a quiz.\" On day 6 the client's product owner asks for a new reporting dashboard \"as soon as possible\", and one developer is unexpectedly on sick leave for three days.",
        steps: [
          {
            id: "s1",
            question: "What do you do about the dashboard request?",
            options: [
              "Add it to the backlog, ask what problem it solves and when they need it, and plan it in sprint 8 planning unless they choose to swap the goal",
              "Start it now in parallel with the quiz work",
              "Tell the client it is out of scope forever",
              "Ignore the email until the sprint ends",
            ],
            correctIndex: 0,
            explanation: "The sprint is protected, but the client still decides priorities. Asking about the need often reveals a smaller first version.",
          },
          {
            id: "s2",
            question: "With three days of capacity lost, how do you protect the sprint goal?",
            options: [
              "Check with the team which quiz stories are essential to the goal and move non-essential ones out, then tell the client",
              "Keep the full plan and hope",
              "Ask the remaining developers to work double hours",
              "Change the goal to \"work on quizzes\"",
            ],
            correctIndex: 0,
            explanation: "Cut scope, not the goal or people's evenings. Tell the client early what moved.",
          },
          {
            id: "s3",
            question: "At the sprint review, publishing works but the quiz timer is moved to sprint 8. How do you present it?",
            options: [
              "Demo creating and publishing on staging, say clearly that the timer moved and why, and confirm it in sprint 8 planning",
              "Show slides only, to avoid questions",
              "Hide the timer and hope nobody asks",
              "Apologise that the sprint failed",
            ],
            correctIndex: 0,
            explanation: "The goal was met. Being upfront about what moved keeps trust; hiding it guarantees an awkward conversation later.",
          },
        ],
      },
    },
    {
      id: "pma-qa-uat",
      moduleId: "pma-sdlc",
      trackId: "pm",
      title: "QA and UAT",
      summary:
        "QA (quality assurance) is our own testing. Our testers and automated checks confirm the software meets the acceptance criteria and does not break what worked before. UAT (user acceptance testing) is the client's testing. Their people try the software on staging and decide whether it is fit for their business. QA asks \"did we build it right?\" UAT asks \"did we build the right thing?\"\n\nWhy it matters: UAT sign-off is usually the gate for release, and on fixed-bid projects it is often tied to a milestone payment. A messy UAT drags on for weeks, mixes bugs with new ideas, and delays both the launch and the invoice. A well-run UAT is short and decisive.\n\nHow to run UAT with an overseas client:\n\n1. Do not send anything to UAT that has not passed QA. Every bug the client finds that QA should have caught costs credibility.\n2. Agree the UAT plan up front: who tests, what scenarios, on which devices, for how many days, and what counts as a blocker.\n3. Give testers a staging link, test accounts and a short script based on the acceptance criteria.\n4. Collect feedback in one place, such as a shared sheet or the ticket board, not in scattered WhatsApp messages.\n5. Triage every item: a bug (it does not match the agreed criteria), a change request (it works as agreed, but they want something different), or a question.\n6. Close with a written sign-off.\n\nAutomated checks also matter. On GitHub, status checks show whether tests passed on a pull request. A PM does not need to read the tests, but should ask: \"Did the checks pass before this went to staging?\"\n\nThe most common mistake is to accept every UAT comment as a bug. When \"make the button blue\" sits in the same list as \"payment fails\", scope creeps and the release slips. Classify each item against the acceptance criteria, and route change requests through the change process.",
      level: "intermediate",
      estMinutes: 35,
      webRefs: [
        { label: "TechTarget: What is User Acceptance Testing (UAT)?", url: "https://www.techtarget.com/it-infrastructure/definition/What-is-user-acceptance-testing-UAT", kind: "article", verifiedAt: "2026-10-02T09:35:21Z" },
        { label: "Atlassian: The different types of testing in software", url: "https://www.atlassian.com/continuous-delivery/software-testing/types-of-software-testing", kind: "article", verifiedAt: "2026-10-02T09:35:41Z" },
        { label: "Atlassian: What is Acceptance Criteria? Definition, Examples, & Tips", url: "https://www.atlassian.com/work-management/project-management/acceptance-criteria", kind: "article", verifiedAt: "2026-10-02T09:35:24Z" },
        { label: "GitHub Docs: Status checks", url: "https://docs.github.com/en/pull-requests/reference/status-checks", kind: "docs", verifiedAt: "2026-10-02T09:35:22Z" },
      ],
      video: {
        title: "Software Testing Process Guide: What is User Acceptance Testing - UAT?",
        channel: "Online PM Courses - Mike Clayton",
        url: "https://www.youtube.com/watch?v=sGwm4p9sGPI",
        videoId: "sGwm4p9sGPI",
        verifiedAt: "2026-10-02T09:35:53Z",
      },
      alternateVideos: [
        {
          title: "What is UAT (User Acceptance Testing) ? How Does Business Analyst Drive UAT?",
          channel: "BA Professional",
          url: "https://www.youtube.com/watch?v=PzoD3FtzIbY",
          videoId: "PzoD3FtzIbY",
          verifiedAt: "2026-10-02T09:35:54Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-qa-uat-q1",
          prompt: "Which question does UAT answer?",
          options: [
            "Did we build the right thing for the client's business?",
            "Is the code well formatted?",
            "Did the server deploy without errors?",
            "Are the developers following the style guide?",
          ],
          correctIndex: 0,
          explanation: "UAT is the client's acceptance against business needs. QA and code review cover correctness and code quality.",
        },
        {
          id: "pma-qa-uat-q2",
          prompt:
            "In UAT on a Laravel CRM, the client logs: \"The lead form should also ask for company size.\" The signed acceptance criteria list name, email and phone only. What is it?",
          options: ["A change request", "A bug", "A blocker for release", "A QA failure"],
          correctIndex: 0,
          explanation: "The form works as agreed. Wanting something different is a change request, to be estimated and prioritised, not fixed for free inside UAT.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-qa-uat-q3",
          prompt: "Which belong in a UAT plan agreed with the client before UAT starts? (Select all that apply.)",
          options: [
            "Who will test and how many days they have",
            "The scenarios to test, based on the acceptance criteria",
            "Devices and browsers in scope",
            "What counts as a release blocker",
            "The developers' hourly rates",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 3],
          explanation: "These make UAT short and decisive. Rates belong in the commercial agreement, not the test plan.",
        },
        {
          id: "pma-qa-uat-q4",
          prompt: "The client finds that the login page crashes on Safari during UAT. Safari was in scope. What does this tell you?",
          options: [
            "QA missed an in-scope case, so tighten QA coverage as well as fixing the bug",
            "Nothing: clients are meant to find all bugs",
            "Safari should be removed from scope",
            "UAT should be cancelled",
          ],
          correctIndex: 0,
          explanation: "UAT should not be the first place in-scope bugs show up. Fix it and add the case to QA so it does not repeat.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-qa-uat-q5",
          prompt: "The client's testers send feedback by WhatsApp, email and calls. What is the best fix?",
          options: [
            "Agree one place to log UAT feedback, such as a shared sheet or the ticket board, and move existing items there",
            "Let each tester use whatever they like",
            "Ask testers to call the developers directly",
            "Stop UAT until they learn Jira",
          ],
          correctIndex: 0,
          explanation: "One list makes triage and status possible. Scattered feedback gets lost, and direct developer calls bypass prioritisation.",
        },
        {
          id: "pma-qa-uat-q6",
          prompt: "Why ask whether GitHub status checks passed before a build goes to staging for UAT?",
          options: [
            "Failed or missing checks mean automated tests did not confirm the change, so the client may test broken work",
            "Because status checks show the client's approval",
            "Because checks replace UAT",
            "Because checks show developer hours",
          ],
          correctIndex: 0,
          explanation: "Status checks report automated test results. They support QA but never replace the client's acceptance.",
        },
        {
          id: "pma-qa-uat-q7",
          prompt: "UAT has been open for four weeks with new comments every day. What is the most likely cause?",
          options: [
            "No agreed end date, scope or blocker definition, so UAT turned into an ongoing wish list",
            "The software has too many features",
            "The client is testing too carefully",
            "The staging server is slow",
          ],
          correctIndex: 0,
          explanation: "Without a timebox and criteria, UAT never ends. Agree them before it starts and route new ideas to change requests.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-qa-uat-q8",
          prompt: "What should close UAT?",
          options: [
            "A written sign-off from the client's named approver, listing any accepted known issues",
            "A verbal \"looks fine\" on a call",
            "The developers deciding it is good enough",
            "The end of the month",
          ],
          correctIndex: 0,
          explanation: "Written sign-off protects both sides, especially when a milestone payment depends on it. A verbal OK is easy to dispute later.",
        },
      ],
      practice: {
        kind: "spot",
        prompt:
          "Here is a UAT plan a junior PM drafted for a US client's React booking app. Mark the lines that will cause trouble.",
        segments: [
          { id: "l1", text: "Scope: booking, payment and cancellation flows from the signed acceptance criteria.", issue: null },
          { id: "l2", text: "Testers: the client's operations manager and two front-desk staff.", issue: null },
          { id: "l3", text: "Environment: testers will use the production site so they see real bookings.", issue: "UAT must run on staging with test data; testing on production touches real customers and payments." },
          { id: "l4", text: "Duration: open-ended, until the client is happy.", issue: "No timebox: UAT will drift into an endless wish list. Agree an end date." },
          { id: "l5", text: "Devices: latest Chrome and Safari on desktop, iOS and Android phones.", issue: null },
          { id: "l6", text: "Feedback: send comments any way you like, and developers will pick them up.", issue: "Feedback needs one agreed place and PM triage, not scattered channels straight to developers." },
          { id: "l7", text: "All feedback will be treated as bugs and fixed before release.", issue: "Each item must be triaged as bug, change request or question; change requests go through the change process." },
          { id: "l8", text: "Test accounts and a short test script will be shared on day one.", issue: null },
          { id: "l9", text: "Our QA will run its full regression on staging before UAT starts.", issue: null },
          { id: "l10", text: "Sign-off: written approval from the operations manager, listing any accepted known issues.", issue: null },
        ],
        askExplanation: true,
      },
    },
    {
      id: "pma-definition-of-done",
      moduleId: "pma-sdlc",
      trackId: "pm",
      title: "Definition of done",
      summary:
        "\"Done\" is the most misused word in software. To a developer it can mean \"I wrote the code\". To QA it means \"tested\". To the client it means \"live and working\". A definition of done (DoD) is the team's shared checklist of what must be true before any item counts as done. The Scrum Guide describes it as a formal description of the state of the increment when it meets the quality measures required for the product.\n\nThe DoD is different from acceptance criteria. Acceptance criteria are specific to one story: \"A teacher can export grades as CSV.\" The DoD applies to every story: code reviewed, tests passing, QA'd on staging, and so on. A story is done only when it meets both.\n\nWhy it matters to a PM: your status reports depend on it. If \"done\" means different things to different people, your burndown lies and the client is surprised at UAT. A clear DoD also protects the team from pressure to cut corners: \"It's not done until it's reviewed and tested\" is easier to say when it is written down and the client has seen it.\n\nHow to use it:\n\n1. Agree the DoD with the team at the start of the project, and share a client-friendly version with the client. Your team's SOP below sets the baseline the DoD must include.\n2. Make it a checklist on every ticket or pull request, not a page nobody reads.\n3. Report progress only on items that meet it. \"Code complete\" is not done.\n4. Review it in retros, for example adding \"release notes written\" after a confusing launch.\n\nA common mistake is a DoD that stops at \"merged\". On an agency project, work the client cannot see on staging, or that has not passed QA, is not done. The opposite mistake is a DoD so long the team ignores it. Keep it short, specific and enforced.",
      level: "intermediate",
      estMinutes: 30,
      webRefs: [
        { label: "Scrum Guides: Scrum Guide", url: "https://scrumguides.org/scrum-guide.html", kind: "spec", verifiedAt: "2026-10-02T09:35:44Z" },
        { label: "Atlassian: What is the Definition of Done (DoD) in Agile?", url: "https://www.atlassian.com/agile/project-management/definition-of-done", kind: "article", verifiedAt: "2026-10-02T09:35:34Z" },
        { label: "Atlassian: What is Acceptance Criteria? Definition, Examples, & Tips", url: "https://www.atlassian.com/work-management/project-management/acceptance-criteria", kind: "article", verifiedAt: "2026-10-02T09:35:24Z" },
      ],
      video: {
        title: "Definition of Done - Agile Software Development",
        channel: "freeCodeCamp.org",
        url: "https://www.youtube.com/watch?v=pYOJyQoBT3U",
        videoId: "pYOJyQoBT3U",
        verifiedAt: "2026-10-02T09:35:57Z",
      },
      alternateVideos: [
        {
          title: "Crafting a Definition of Done",
          channel: "Scrum.org",
          url: "https://www.youtube.com/watch?v=2MD5onpE6jg",
          videoId: "2MD5onpE6jg",
          verifiedAt: "2026-10-02T09:35:55Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-definition-of-done-q1",
          prompt: "What is the difference between acceptance criteria and the definition of done?",
          options: [
            "Acceptance criteria are specific to one story; the DoD is a quality checklist that applies to every story",
            "They are the same thing",
            "The DoD is written by the client; acceptance criteria by developers",
            "Acceptance criteria apply only to bugs",
          ],
          correctIndex: 0,
          explanation: "A story is done only when it meets its own acceptance criteria and the shared DoD.",
        },
        {
          id: "pma-definition-of-done-q2",
          prompt: "A developer says the Laravel invoice export is \"done\": the code is merged, but QA has not tested it and it is not on staging. How do you report it to the client?",
          options: [
            "As in progress: code complete, QA and staging still to do",
            "As done, since the code is merged",
            "As done, with a note that it might have bugs",
            "Don't mention it",
          ],
          correctIndex: 0,
          explanation: "If it does not meet the DoD, it is not done. Reporting merged work as done is how clients get surprised in UAT.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-definition-of-done-q3",
          prompt: "Which are typical items in an agency team's definition of done? (Select all that apply.)",
          options: [
            "Code reviewed by another developer",
            "Automated checks passing",
            "Tested by QA on staging",
            "Client has paid the invoice",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "The DoD is about quality of the work. Payment is a commercial matter, not a quality criterion.",
        },
        {
          id: "pma-definition-of-done-q4",
          prompt: "The client pushes: \"Skip the code review this week, we need speed.\" What is the best answer?",
          options: [
            "Explain that review is part of the agreed definition of done because it prevents costly bugs, and offer to cut scope instead",
            "Agree and skip it silently",
            "Skip it but don't tell the team lead",
            "Refuse without explanation",
          ],
          correctIndex: 0,
          explanation: "A written DoD makes it easier to hold the quality line. Trading scope for speed is the honest lever; cutting quality creates hidden debt.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-definition-of-done-q5",
          prompt: "Why share a client-friendly version of the DoD with the client?",
          options: [
            "So they know what \"done\" means in your reports and why some items take longer than \"just coding\"",
            "So they can approve each developer's code",
            "Because the contract requires them to write it",
            "So they can skip UAT",
          ],
          correctIndex: 0,
          explanation: "Shared meaning prevents surprises. The client does not approve code, and the DoD does not replace their UAT.",
        },
        {
          id: "pma-definition-of-done-q6",
          prompt: "After a confusing launch where support did not know what changed, what is a sensible DoD update?",
          options: [
            "Add \"release notes written for the client and support\"",
            "Remove QA to release faster",
            "Add a second code review for every change",
            "Nothing: the DoD should never change",
          ],
          correctIndex: 0,
          explanation: "The DoD should evolve from retros to fix real problems. It is not fixed forever.",
        },
        {
          id: "pma-definition-of-done-q7",
          prompt: "A team's DoD has 25 items and nobody follows it. What is the best fix?",
          options: [
            "Cut it to a short, specific list the team agrees to enforce, and put it as a checklist on tickets or PRs",
            "Add more items so nothing is missed",
            "Keep it as it is: it looks thorough to the client",
            "Delete it and trust everyone",
          ],
          correctIndex: 0,
          explanation: "An ignored DoD is worse than a short one. A visible checklist makes it part of the daily flow.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-definition-of-done-q8",
          prompt: "Which status statements are consistent with a DoD that includes QA on staging? (Select all that apply.)",
          options: [
            "\"Done: tested by QA on staging, ready for your UAT.\"",
            "\"Code complete; QA starts tomorrow.\"",
            "\"In review: waiting for code review.\"",
            "\"Done: merged, QA will test next week.\"",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Only work that meets every DoD item is called done. The last line calls untested work done.",
        },
      ],
      practice: {
        kind: "spot",
        prompt:
          "This is the Friday status a PM sent to a Canadian client for a React Native + Laravel delivery app. The team's DoD is: code reviewed, checks passing, QA'd on staging. Mark the lines that misuse \"done\" or misreport status.",
        segments: [
          { id: "l1", text: "Driver login: done — reviewed, QA'd on staging, ready for your UAT.", issue: null },
          { id: "l2", text: "Order tracking map: done — merged this afternoon, QA will look at it Monday.", issue: "Merged but not QA'd: it does not meet the DoD, so it is in progress." },
          { id: "l3", text: "Push notifications: in progress — waiting for your Apple Developer account access.", issue: null },
          { id: "l4", text: "Admin reports: done on Ravi's laptop, will deploy next week.", issue: "Local-only work is not done; it is not reviewed, tested or visible on staging." },
          { id: "l5", text: "Payment refunds: in review — code review in progress.", issue: null },
          { id: "l6", text: "Ratings screen: done — reviewed and QA'd on staging.", issue: null },
          { id: "l7", text: "Overall: 5 of 6 features done, we are ahead of plan.", issue: "Only two items meet the DoD; the overall claim overstates progress." },
          { id: "l8", text: "Next update: Tuesday, after QA finishes the tracking map.", issue: null },
        ],
        askExplanation: true,
      },
      sop: [
        {
          title: "Our definition of done",
          prompt:
            "[Oyelabs SOP – admin to fill] The baseline definition of done every Oyelabs project must include: code review rules (who reviews, how many approvals), automated tests and checks that must pass, QA sign-off on staging, deployment to staging, client UAT sign-off before release, and documentation or release notes. Note any extra items for mobile apps.",
        },
      ],
    },
    // ---------------------------------------------------------------- advanced
    {
      id: "pma-app-store-play-review",
      moduleId: "pma-sdlc",
      trackId: "pm",
      title: "App Store and Play Store review times",
      summary:
        "A web release is under your control: the team deploys and it is live. A mobile release is not. Every iOS build goes through Apple's App Review, and Google Play reviews new apps and updates too. Neither store promises a fixed time. Apple says most submissions are reviewed quickly, and they often clear within a day or two, but new apps, first submissions and anything sensitive can take longer. So can a rejection, which restarts the clock.\n\nWhy it matters to a PM: a Flutter or React Native app for a US client with a launch event on a fixed date can miss it because of a review delay you did not plan for. The client will not care whose fault it is. Store review is a dependency outside your team, so it goes in the plan and in the risk log.\n\nHow to plan mobile releases:\n\n1. Add a buffer for review and a possible rejection and resubmission before any public date. Never promise a go-live day for a first submission.\n2. Check early who owns the developer accounts. The client usually should, and getting access often takes days.\n3. Prepare store assets in parallel: screenshots, description, privacy policy URL, data-safety and privacy details, and a demo account for the reviewer if login is required. A missing demo login is a classic rejection reason.\n4. Read the App Review Guidelines for anything risky: payments for digital goods, user-generated content, health data or account deletion.\n5. Use phased or staged rollouts where it makes sense, so a bad build reaches a small share of users first.\n6. Remember that a hotfix for a mobile app also goes through review. You cannot patch a mobile crash in ten minutes like a web bug.\n\nA common mistake is to release the Laravel API change and the app update on the same day without checking compatibility. Users update apps slowly, so the live API must keep working with the old app version for weeks.",
      level: "advanced",
      estMinutes: 35,
      webRefs: [
        { label: "Apple Developer: App Review", url: "https://developer.apple.com/distribute/app-review/", kind: "docs", verifiedAt: "2026-10-02T09:35:28Z" },
        { label: "Apple Developer: App Review Guidelines", url: "https://developer.apple.com/app-store/review/guidelines/", kind: "spec", verifiedAt: "2026-10-02T09:35:22Z" },
        { label: "Google Play Console Help: Publish your app", url: "https://support.google.com/googleplay/android-developer/answer/9859751", kind: "docs", verifiedAt: "2026-10-02T09:35:39Z" },
        { label: "Google Play Console Help: Prepare and roll out a release", url: "https://support.google.com/googleplay/android-developer/answer/9859348", kind: "docs", verifiedAt: "2026-10-02T09:35:30Z" },
      ],
      video: {
        title: "App Store Review Rejections - 8 Point Checklist Before You Submit",
        channel: "Marcin Kaczmarzyk",
        url: "https://www.youtube.com/watch?v=pn4RkSAF6f8",
        videoId: "pn4RkSAF6f8",
        verifiedAt: "2026-10-02T09:35:57Z",
      },
      alternateVideos: [
        {
          title: "Why My App Was Rejected and How I Got It Approved | App Store Review Process Explained",
          channel: "Think Like an Engineer",
          url: "https://www.youtube.com/watch?v=gvQiTtUU_LE",
          videoId: "gvQiTtUU_LE",
          verifiedAt: "2026-10-02T09:36:05Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-app-store-play-review-q1",
          prompt: "A US client wants their new React Native app live in the App Store on the morning of their launch event. When should the first submission go in?",
          options: [
            "Well ahead, with buffer for review plus at least one rejection and resubmission, then release manually on the day",
            "The night before, since review usually takes a day",
            "On launch morning",
            "Whenever development finishes, without a plan",
          ],
          correctIndex: 0,
          explanation: "Review time is not guaranteed and rejections restart it. Submitting early and releasing manually on the day removes the risk.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-app-store-play-review-q2",
          prompt: "Which are common reasons for App Store rejection a PM can prevent? (Select all that apply.)",
          options: [
            "No demo account for the reviewer when the app needs a login",
            "Missing or broken privacy policy link",
            "Placeholder text or screens that crash",
            "The app uses a Laravel backend",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Reviewers need to get in and see a complete app with required policies. The backend technology is irrelevant.",
        },
        {
          id: "pma-app-store-play-review-q3",
          prompt: "A crash in the live iOS app affects 20% of users. Why can't you promise the client a fix \"in the next hour\"?",
          options: [
            "The fixed build still has to pass App Review before users get it, and users must then update",
            "Because iOS bugs can't be fixed",
            "Because Apple only accepts updates monthly",
            "Because the API must be rewritten",
          ],
          correctIndex: 0,
          explanation: "Mobile fixes depend on review and on users updating. You can request an expedited review in urgent cases, but it is not guaranteed.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-app-store-play-review-q4",
          prompt: "Who should normally own the Apple Developer and Google Play accounts for a client's app?",
          options: [
            "The client, with the agency given team access",
            "The developer who built the app, personally",
            "Nobody until launch day",
            "Any free account the team can create",
          ],
          correctIndex: 0,
          explanation: "The app belongs to the client. Agency-owned or personal accounts cause painful transfers later. Sort access out early.",
        },
        {
          id: "pma-app-store-play-review-q5",
          prompt:
            "The team plans to release a breaking change to the Laravel API on the same day the new app version is submitted. What is the risk?",
          options: [
            "Users still on the old app version break, since the update is not approved or installed yet",
            "There is no risk if both are released together",
            "Apple will reject the app because the API changed",
            "The API will be slower",
          ],
          correctIndex: 0,
          explanation: "Old app versions stay in use for weeks. The API must stay backward compatible, or versioned, until old versions are retired.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-app-store-play-review-q6",
          prompt: "What is the benefit of a staged rollout on Google Play?",
          options: [
            "The update reaches a percentage of users first, so a bad build affects fewer people and can be halted",
            "It skips Google's review",
            "It makes review faster",
            "It releases to iOS at the same time",
          ],
          correctIndex: 0,
          explanation: "Staged rollouts limit the damage of a bad release. They do not bypass review.",
        },
        {
          id: "pma-app-store-play-review-q7",
          prompt: "Which store items can be prepared in parallel with development, instead of at the end? (Select all that apply.)",
          options: [
            "Screenshots and app description",
            "Privacy policy URL and privacy / data-safety details",
            "Reviewer demo account",
            "The approved review result",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Assets and declarations can be ready early. The review result only comes after submission.",
        },
        {
          id: "pma-app-store-play-review-q8",
          prompt: "How should a mobile launch date appear in your risk log?",
          options: [
            "Store review delay or rejection as a risk, with buffer and an owner for store submission",
            "It should not: store review is the client's problem",
            "Only after the app is rejected",
            "As an issue that has already happened",
          ],
          correctIndex: 0,
          explanation: "Review is a known external dependency. Logging it with a mitigation before it bites is the PM's job.",
        },
      ],
      practice: {
        kind: "calculate",
        prompt:
          "A UK client's Flutter app must be live in both stores by working day 30 of the plan. Working back from launch, the team estimates these steps in working days. Calculate the total days needed after code freeze, and the latest working day code freeze can happen.",
        table: {
          columns: ["Step after code freeze", "Working days"],
          rows: [
            ["Final QA regression on release build", "3"],
            ["Client UAT on TestFlight / internal testing", "4"],
            ["Fixes from UAT and new build", "2"],
            ["Store review buffer", "3"],
            ["Buffer for one rejection and resubmission", "3"],
          ],
        },
        fields: [
          { id: "total", label: "Total working days after code freeze", unit: "days", answer: 15, tolerance: 0, expression: "T[0][1] + T[1][1] + T[2][1] + T[3][1] + T[4][1]" },
          { id: "freeze", label: "Latest code-freeze day if launch is day 30", unit: "day", answer: 15, tolerance: 0, expression: "30 - (T[0][1] + T[1][1] + T[2][1] + T[3][1] + T[4][1])" },
        ],
        explanation:
          "3 + 4 + 2 + 3 + 3 = 15 working days, so code must freeze by day 15. Dropping the rejection buffer to save three days is exactly the bet that misses launch events.",
      },
    },
    {
      id: "pma-hotfix-vs-release",
      moduleId: "pma-sdlc",
      trackId: "pm",
      title: "Hotfix vs release",
      summary:
        "A release is a planned bundle of changes that has gone through the normal flow: sprint, QA, UAT, then a scheduled deployment. A hotfix is an urgent, minimal fix to production that skips the queue because the problem cannot wait. In Gitflow terms, a hotfix branch comes off the production branch, gets the smallest possible fix, and is merged back to both production and the development branch. In semantic versioning, a release might be 2.4.0 and a hotfix 2.4.1.\n\nWhy it matters: a hotfix is a trade. You buy speed with risk, because the fix gets less testing than a normal release. A PM's job is to make sure that trade is worth it. A Laravel checkout that charges customers twice at 2 a.m. in the client's time zone is a hotfix. A typo on the About page, or a feature the client forgot to ask for, is not, however loudly it is requested.\n\nHow to handle a hotfix request:\n\n1. Confirm the impact: who is affected, how many users, is money or data at risk, and is there a workaround?\n2. Decide with the tech lead, and the client where needed, whether it is a hotfix or the next release. Your team's SOP below sets who may approve a hotfix.\n3. Keep it minimal: fix only the problem. No \"while we're in there\" extras.\n4. Test it as much as time allows, at least on staging, and have a rollback plan.\n5. Communicate before, during and after: what happened, what you did, and what you will do to prevent it.\n6. Make sure the fix is merged back to the development branch, or the next release will bring the bug back.\n\nFor mobile apps, remember a hotfix still goes through store review, so a server-side fix or a feature flag may be faster.\n\nA common mistake is letting \"hotfix\" become the normal way of shipping. If every client request goes out as a hotfix, testing erodes, prod breaks more often, and you create more hotfixes. Watch for the pattern and fix the process.",
      level: "advanced",
      estMinutes: 40,
      isMilestone: true,
      webRefs: [
        { label: "Atlassian Git tutorial: Gitflow Workflow", url: "https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow", kind: "article", verifiedAt: "2026-10-02T09:35:29Z" },
        { label: "SemVer: Semantic Versioning 2.0.0", url: "https://semver.org/", kind: "spec", verifiedAt: "2026-10-02T09:35:21Z" },
        { label: "Atlassian: Incident Management: Processes, Best Practices & Tools", url: "https://www.atlassian.com/incident-management", kind: "article", verifiedAt: "2026-10-02T09:35:41Z" },
        { label: "GitHub Docs: About releases", url: "https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases", kind: "docs", verifiedAt: "2026-10-02T09:35:38Z" },
      ],
      video: {
        title: "Hotfix Branches: Essential Tips for Software Developers and DevOps | Hotfix from a Release Branch",
        channel: "LogicOps Lab",
        url: "https://www.youtube.com/watch?v=gpxvoPETVMo",
        videoId: "gpxvoPETVMo",
        verifiedAt: "2026-10-02T09:35:57Z",
      },
      alternateVideos: [
        {
          title: "What is Hotfix in Software Development / Testing | Incident Management | SoftwaretestingbyMKT",
          channel: "SoftwaretestingbyMKT",
          url: "https://www.youtube.com/watch?v=b9xlIC3qFYw",
          videoId: "b9xlIC3qFYw",
          verifiedAt: "2026-10-02T09:35:53Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-hotfix-vs-release-q1",
          prompt: "Which of these justifies a hotfix on a live Laravel e-commerce site?",
          options: [
            "Some customers are being charged twice at checkout",
            "The client wants a new banner for next month's sale",
            "A typo on the About page",
            "A developer wants to refactor the cart code",
          ],
          correctIndex: 0,
          explanation: "Money is being lost right now, and every hour makes it worse. The others can wait for the next planned release.",
        },
        {
          id: "pma-hotfix-vs-release-q2",
          prompt: "Which questions decide whether something is a hotfix? (Select all that apply.)",
          options: [
            "How many users are affected?",
            "Is money, data or security at risk?",
            "Is there a workaround users can use until the next release?",
            "How senior is the person asking?",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Impact and urgency decide. Seniority of the requester does not change the risk of an under-tested change.",
        },
        {
          id: "pma-hotfix-vs-release-q3",
          prompt: "The current version is 3.2.0. The team ships a hotfix for a bug. Under semantic versioning, what should the version be?",
          options: ["3.2.1", "3.3.0", "4.0.0", "3.2.0-hotfix"],
          correctIndex: 0,
          explanation: "A backward-compatible bug fix increments the patch number. Minor is for new features, major for breaking changes.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-hotfix-vs-release-q4",
          prompt:
            "A hotfix went to production last week. This week's planned release reintroduces the same bug. What most likely went wrong?",
          options: [
            "The hotfix was not merged back into the development branch",
            "The client tested badly",
            "Semantic versioning was not used",
            "The server cached the old code",
          ],
          correctIndex: 0,
          explanation: "In Gitflow, hotfixes merge into both the production branch and the development branch. Missing the second merge brings the bug back.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-hotfix-vs-release-q5",
          prompt: "While fixing the double-charge bug, a developer also wants to tidy the payment code and add a small feature. What do you say?",
          options: [
            "Keep the hotfix minimal; put the tidy-up and feature in the normal release",
            "Fine, since we're in there anyway",
            "Only add the feature, skip the tidy-up",
            "Delay the hotfix until everything is done",
          ],
          correctIndex: 0,
          explanation: "Every extra line in a hotfix is untested risk. Minimal fixes are faster to verify and easier to roll back.",
        },
        {
          id: "pma-hotfix-vs-release-q6",
          prompt: "A crash affects the live iOS app. Which options can get relief to users faster than a new store build? (Select all that apply.)",
          options: [
            "A server-side fix in the API if the crash is caused by the data it returns",
            "Turning off the faulty feature with a feature flag",
            "Requesting an expedited App Review for the fixed build",
            "Editing the app directly on users' phones",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Server fixes and flags avoid review, and an expedited review can shorten it. You cannot change installed apps directly.",
        },
        {
          id: "pma-hotfix-vs-release-q7",
          prompt: "Over two months, a project has shipped 14 hotfixes and 2 planned releases. What does this most likely mean?",
          options: [
            "Hotfix has become the normal delivery path, so testing is being bypassed and the process needs fixing",
            "The team is very fast",
            "The client is very happy",
            "Nothing: hotfix counts are not meaningful",
          ],
          correctIndex: 0,
          explanation: "Frequent hotfixes are a symptom of weak QA, poor planning or urgent requests treated as emergencies. Find the cause in a retro.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-hotfix-vs-release-q8",
          prompt: "What should the client hear after a hotfix is deployed?",
          options: [
            "What happened, who was affected, what was fixed, how it was verified, and what will prevent it recurring",
            "Nothing, to avoid worrying them",
            "Only that \"it's fixed\"",
            "The developer's name who caused it",
          ],
          correctIndex: 0,
          explanation: "A short, factual follow-up builds trust. Silence or blame both damage it.",
        },
      ],
      practice: {
        kind: "scenario",
        prompt:
          "Friday 6 p.m. IST. You manage a React + Laravel subscription platform for a US client. Their support lead messages: since this morning's release, new sign-ups get an error at the payment step. Existing subscribers are fine. The client's marketing campaign goes live on Monday.",
        steps: [
          {
            id: "s1",
            question: "What is your first move?",
            options: [
              "Get the tech lead to confirm the impact and cause, and decide between a rollback and a minimal hotfix",
              "Wait until Monday's planned release",
              "Tell the client it's probably their payment provider",
              "Ask the whole team to start rewriting the sign-up flow",
            ],
            correctIndex: 0,
            explanation: "New revenue is blocked and a campaign is coming. Assess quickly, and compare rollback with a minimal fix.",
          },
          {
            id: "s2",
            question: "The tech lead says a one-line config fix will solve it, tested on staging in 30 minutes. The client also asks to add a promo-code field \"while you're at it\". What do you do?",
            options: [
              "Ship only the config fix as a hotfix; plan the promo-code field in the next release",
              "Add the promo-code field to the hotfix",
              "Delay the fix until the promo-code field is ready",
              "Ship both straight to production without staging",
            ],
            correctIndex: 0,
            explanation: "Keep hotfixes minimal. The promo-code field is a feature request and goes through the normal flow.",
          },
          {
            id: "s3",
            question: "The fix is live and verified. What else must happen before you close it?",
            options: [
              "Merge the fix back to the development branch and send the client a short incident summary with prevention steps",
              "Nothing: the bug is fixed",
              "Delete the hotfix branch without merging",
              "Tell the client only if they ask",
            ],
            correctIndex: 0,
            explanation: "Merge-back prevents the bug returning in the next release, and a follow-up closes the loop with the client.",
          },
        ],
      },
      sop: [
        {
          title: "Our hotfix approval process",
          prompt:
            "[Oyelabs SOP – admin to fill] Who can approve a hotfix (tech lead, delivery head, client), the minimum testing before a hotfix goes to production, out-of-hours contacts, how the client is informed, and whether hotfix time is billable under each contract type.",
        },
      ],
    },
    {
      id: "pma-handover-support-sla",
      moduleId: "pma-sdlc",
      trackId: "pm",
      title: "Handover and support SLAs",
      summary:
        "Launch is not the end of a client project. After go-live, the work moves from the build team to support or maintenance, and the relationship moves from a project to a service. A service-level agreement (SLA) is the promise that governs it: how fast we respond to and resolve issues of each severity, during which hours, and through which channel. Behind an SLA sit SLOs, the internal targets, and SLIs, the measurements.\n\nWhy it matters: most client disputes after launch come from mismatched expectations. A US client emails at 9 p.m. their time, which is morning in India, expecting a fix \"today\". Another assumes every new idea is covered under \"support\". Without a clear SLA, a severity scheme and a handover, every request becomes a negotiation, and goodwill runs out.\n\nHow to hand over and run support well:\n\n1. Agree the support model before launch: tier or package, hours and time zones, channels, and severity definitions. Use your team's SOP below for Oyelabs' actual tiers and times; never improvise them on a call.\n2. Define severity in plain language: P1 means the app is down or money or data is at risk; P4 is a cosmetic issue. Response time and resolution time are different promises.\n3. Run a proper handover: credentials and accounts transferred to the client, documentation, known issues, the release notes, and who to contact.\n4. Separate bugs from change requests. A bug is something that does not work as agreed. A new feature or a change of mind is a change request, estimated and billed under the agreed model.\n5. Track SLA performance and share it monthly. It builds trust and supports renewals.\n\nA common mistake is promising a response time the team cannot staff, such as a one-hour response at weekends with no on-call rota. Another is a handover that lives in one developer's head. When that person leaves, support collapses. Write it down and test it with someone who did not build the project.",
      level: "advanced",
      estMinutes: 40,
      isMilestone: true,
      webRefs: [
        { label: "Atlassian: What Is an SLA? Service Level Agreements Explained", url: "https://www.atlassian.com/itsm/service-request-management/slas", kind: "article", verifiedAt: "2026-10-02T09:35:35Z" },
        { label: "Atlassian: What are Service-Level Objectives (SLOs)?", url: "https://www.atlassian.com/incident-management/kpis/sla-vs-slo-vs-sli", kind: "article", verifiedAt: "2026-10-02T09:35:25Z" },
        { label: "Atlassian: Understanding incident severity levels", url: "https://www.atlassian.com/incident-management/kpis/severity-levels", kind: "article", verifiedAt: "2026-10-02T09:35:47Z" },
        { label: "Atlassian: The Atlassian Incident Management Handbook", url: "https://www.atlassian.com/incident-management/handbook", kind: "docs", verifiedAt: "2026-10-02T09:35:44Z" },
      ],
      video: {
        title: "What is a Service-Level Agreement (SLA)?",
        channel: "Metroun Quantity Surveying",
        url: "https://www.youtube.com/watch?v=V-ypx6Rmu_k",
        videoId: "V-ypx6Rmu_k",
        verifiedAt: "2026-10-02T09:35:53Z",
      },
      alternateVideos: [
        {
          title: "Do you need a Software Maintenance Agreement?",
          channel: "Martisz",
          url: "https://www.youtube.com/watch?v=rLEUmJ0g_8U",
          videoId: "rLEUmJ0g_8U",
          verifiedAt: "2026-10-02T09:35:55Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-handover-support-sla-q1",
          prompt: "What is the difference between response time and resolution time in an SLA?",
          options: [
            "Response is when we acknowledge and start working on the issue; resolution is when it is fixed or worked around",
            "They mean the same thing",
            "Response is for bugs; resolution is for features",
            "Resolution is always one hour after response",
          ],
          correctIndex: 0,
          explanation: "Clients often hear \"one-hour response\" as \"one-hour fix\". Make the difference explicit in the SLA and in conversation.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-handover-support-sla-q2",
          prompt: "Which issue on a live Laravel booking platform is the highest severity?",
          options: [
            "No customer can complete a booking or payment",
            "The admin report export is slow",
            "A button colour is off-brand",
            "A client wants a new loyalty feature",
          ],
          correctIndex: 0,
          explanation: "Core business flow down means a top-severity incident. A new feature is not an incident at all; it is a change request.",
        },
        {
          id: "pma-handover-support-sla-q3",
          prompt:
            "Three months after handover, the client logs a \"bug\": the app should let users book for a friend. This was never in scope. How do you treat it?",
          options: [
            "As a change request: acknowledge it, explain it is new functionality, and offer an estimate under the agreed model",
            "As a P1 bug, fixed for free",
            "Ignore it, since the project is closed",
            "Fix it quietly to keep the client happy",
          ],
          correctIndex: 0,
          explanation: "Support covers things not working as agreed. New functionality is a change request; handling it politely and clearly protects the relationship and the margin.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-handover-support-sla-q4",
          prompt: "Which belong in a handover pack for a client's React Native app and Laravel API? (Select all that apply.)",
          options: [
            "Accounts and credentials transferred to the client (stores, hosting, domains)",
            "Architecture overview and deployment steps",
            "Known issues and the release notes for the live version",
            "Support contacts, hours and how to raise an issue",
            "Developers' personal phone numbers for any problem",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 3],
          explanation: "A handover lets someone who did not build the project support it. Personal numbers bypass the support process and the severity triage.",
        },
        {
          id: "pma-handover-support-sla-q5",
          prompt: "A UK client's SLA promises support in UK business hours, but your team is in India. What does a PM need to check before signing?",
          options: [
            "That the team's working hours and on-call cover actually overlap with the promised support window",
            "Nothing: time zones don't matter for support",
            "Only that the contract is signed",
            "That the client has a fast internet connection",
          ],
          correctIndex: 0,
          explanation: "An SLA is only as good as the staffing behind it. Check overlap and on-call cover against the SOP before promising.",
        },
        {
          id: "pma-handover-support-sla-q6",
          prompt: "How do SLA, SLO and SLI relate?",
          options: [
            "SLI is what you measure, SLO is your internal target for it, SLA is the promise to the client with consequences",
            "They are three names for the same thing",
            "SLA is internal; SLO is the contract",
            "SLI is the client's satisfaction survey",
          ],
          correctIndex: 0,
          explanation: "Teams set SLOs stricter than the SLA so they have a margin before a contractual breach.",
        },
        {
          id: "pma-handover-support-sla-q7",
          prompt: "A sales rep wants to promise a 30-minute response, 24/7, to close a deal. There is no on-call rota. What is the right response?",
          options: [
            "Flag that it cannot be staffed today, and offer the standard tier or price a real on-call arrangement",
            "Agree: it closes the deal",
            "Agree, and ask developers to watch their phones at night unpaid",
            "Say nothing and deal with it later",
          ],
          correctIndex: 0,
          explanation: "Promises without staffing become broken SLAs and damaged trust. Make the cost visible before it is signed.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-handover-support-sla-q8",
          prompt: "Why share monthly SLA performance with a support client? (Select all that apply.)",
          options: [
            "It shows the value they are paying for",
            "It surfaces patterns, such as repeated issues in one area, that justify improvement work",
            "It supports renewal and upsell conversations",
            "It removes the need to respond to tickets",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Reporting turns invisible support work into evidence. It never replaces actually handling tickets.",
        },
      ],
      practice: {
        kind: "write",
        variant: "email",
        prompt:
          "Write a reply to the client. Acknowledge the urgency, separate the real bug from the new request, say what happens next with each, and keep the relationship warm. Do not quote specific SLA times or rates; refer to \"the support terms we agreed\".",
        context:
          "From: Laura Bennett (Operations Director, client, Chicago)\nTo: You (PM, Oyelabs)\nSubject: URGENT – app problems\n\nHi,\n\nTwo things, both urgent. First, since yesterday some customers can't upload their profile photo; it just spins. Second, we need the app to support booking for multiple people at once. Our competitors have it. This is under our support contract, right? Need both fixed this week.\n\nLaura",
        wordLimit: 220,
        rubric: [
          { id: "separate", label: "Separates bug from change request", description: "Treats the photo upload as a bug handled under support and the group booking as new functionality needing an estimate, without sounding dismissive.", weight: 3 },
          { id: "next", label: "Clear next steps", description: "Says what the team is doing on the bug now and when the next update comes, and offers a concrete next step (estimate or call) for the new feature.", weight: 2 },
          { id: "tone", label: "Professional, warm tone", description: "Acknowledges urgency and the competitive concern; no blame, no jargon.", weight: 1 },
          { id: "commitments", label: "No invented commitments", description: "Does not promise both by Friday or quote SLA times/rates not given; refers to the agreed support terms.", weight: 2 },
        ],
        sampleAnswer:
          "Subject: RE: URGENT – app problems\n\nHi Laura,\n\nThanks for flagging these quickly. I understand both matter for your customers.\n\n1. Profile photo upload: this is a bug, and it's covered by your support terms. The team has already started investigating. I'll send you an update by 10 a.m. your time tomorrow with the cause and when the fix will be live.\n\n2. Booking for multiple people: this is new functionality rather than a fix, so it sits outside support and works as a change request. It's a good idea, and I'd like to scope it properly. Could we have a 20-minute call this week to go through how it should work? I'll then send an estimate and the earliest release date.\n\nI'll keep you posted on the upload issue.\n\nBest regards,\n[Name]",
      },
      sop: [
        {
          title: "Our support SLAs and tiers",
          prompt:
            "[Oyelabs SOP – admin to fill] Our support tiers or packages; severity definitions P1–P4 with examples; response and resolution times per severity and tier; support hours and the time zones covered; channels for raising issues; the escalation path; how to tell a bug from a change request after handover; and the warranty period after go-live.",
        },
      ],
    },
  ],
} satisfies Module;
