import type { Module } from "@/types/curriculum";

export default {
  id: "pma-meetings",
  trackId: "pm",
  name: "Client update meetings & presenting",
  description:
    "Running the weekly client update well: a tight agenda, honest RAG status, done / next / risks / decisions, demos that work, presenting progress, handling tough questions, timeboxing, and the minutes-of-meeting email within 24 hours, all run in Microsoft Teams.",
  topics: [
    {
      id: "pma-meeting-agenda",
      moduleId: "pma-meetings",
      trackId: "pm",
      title: "Agenda for a client update",
      summary:
        "Your weekly call with a client in London or Sydney is often the only hour they spend on the project all week. If it drifts, they leave without knowing whether the Laravel release is on track, and they fill the gap with worry. A short written agenda turns that hour into a decision meeting instead of a chat.\n\nA good client update agenda has a fixed shape so the client learns where to look. Start with the overall status in one line (the RAG colour). Then what was done since last time, what is next, risks and blockers, and the decisions you need from the client. End with a recap of action items. Put a time next to each item, and put the decisions slot early enough that it never gets squeezed out.\n\nHow to do it step by step. First, send the agenda at least one working day before the call, in the Teams invite or as a short email, so the client can bring the right people. Second, list the decisions you need as questions, for example \"Approve the new checkout copy, yes or no?\". Third, attach or link the status report so nobody waits for you to read it aloud. Fourth, open the call by confirming the agenda and asking if anything urgent must be added.\n\nThe common mistake is an agenda that is just \"Weekly sync\". It tells the client nothing, so they cannot prepare, and the meeting becomes a long demo of tickets. Another mistake is putting \"any other business\" at the end with no time, where a surprise change request eats the last fifteen minutes.\n\nHow often you meet, who attends from our side and the standard agenda we use are in your team's SOP below. Follow it so every client gets the same quality of meeting.",
      level: "beginner",
      estMinutes: 20,
      webRefs: [
        { label: "Microsoft Support: Schedule a meeting in Microsoft Teams", url: "https://support.microsoft.com/en-us/teams/meetings/schedule-a-meeting-in-microsoft-teams", kind: "docs", verifiedAt: "2026-10-02T09:35:24Z" },
        { label: "Asana: Meeting Agenda Templates & Examples for Better Meetings", url: "https://asana.com/resources/meeting-agenda", kind: "article", verifiedAt: "2026-10-02T09:38:34Z" },
        { label: "Asana: How Project Status Reports Work: 8 Steps + Template", url: "https://asana.com/resources/how-project-status-reports", kind: "article", verifiedAt: "2026-10-02T10:07:41Z" },
        { label: "Asana: Want Fewer, Better Meetings? Try Meeting Management", url: "https://asana.com/resources/meeting-management", kind: "article", verifiedAt: "2026-10-02T10:07:52Z" },
      ],
      video: {
        title: "How to Run Project Status Meetings",
        channel: "American Management Association",
        url: "https://www.youtube.com/watch?v=iIss0K-W9UQ",
        videoId: "iIss0K-W9UQ",
        verifiedAt: "2026-10-02T09:35:56Z",
      },
      alternateVideos: [
        {
          title: "How to Lead a Meeting as a Project Manager | Explained in 8 Minutes",
          channel: "Max Mao",
          url: "https://www.youtube.com/watch?v=XsDSoWKroTk",
          videoId: "XsDSoWKroTk",
          verifiedAt: "2026-10-02T09:35:54Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-meeting-agenda-q1",
          prompt: "Your weekly call with a US client is tomorrow. When should the agenda reach them?",
          options: [
            "At least one working day before, in the invite or a short email",
            "At the start of the call, shared on screen",
            "After the call, together with the minutes",
            "Only if the client asks for it",
          ],
          correctIndex: 0,
          explanation: "Sending it ahead lets the client prepare and bring the person who can make the decision you need.",
        },
        {
          id: "pma-meeting-agenda-q2",
          prompt: "Which items belong in a standard client update agenda? (Select all that apply.)",
          options: [
            "Overall status (RAG) in one line",
            "Done since last call and next steps",
            "Risks, blockers and decisions needed from the client",
            "A walkthrough of every Jira ticket closed this week",
            "Recap of action items with owners",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 4],
          explanation: "The client needs status, progress, risks, decisions and actions. A ticket-by-ticket tour wastes their time; link the board instead.",
        },
        {
          id: "pma-meeting-agenda-q3",
          prompt: "You need the client to approve a payment-gateway choice this week. Where should that go on the agenda?",
          options: [
            "Early, as a clear yes/no question with its own time slot",
            "Under 'any other business' at the end",
            "Leave it off and email it later",
            "Mention it only if there is time left",
          ],
          correctIndex: 0,
          explanation: "Decisions slip when they sit at the end. Put them early and phrase them as a question the client can answer.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-meeting-agenda-q4",
          prompt: "Your invite just says 'Weekly sync'. What is the main problem?",
          options: [
            "The client cannot tell what to prepare or whom to bring",
            "The title is too short for Teams",
            "Clients dislike the word 'sync'",
            "There is no problem if the call is recurring",
          ],
          correctIndex: 0,
          explanation: "A vague invite produces a vague meeting. The agenda is how you get the right people and the right answers.",
        },
        {
          id: "pma-meeting-agenda-q5",
          prompt: "Ten minutes into the call, the client raises a new feature request that would take the rest of the hour. What do you do?",
          options: [
            "Note it, agree a separate slot or follow-up to assess it as a change request, and return to the agenda",
            "Drop the agenda and discuss the feature until the end",
            "Tell the client new requests are not allowed",
            "Promise to add it to the current sprint",
          ],
          correctIndex: 0,
          explanation: "Park it respectfully and route it through change control. The rest of the agenda, especially decisions, still needs the time.",
          isEdgeCaseOrInterviewQuestion: true,
        },
      ],
      practice: {
        kind: "rank",
        prompt:
          "Put this 30-minute weekly update for an Australian client's React booking app in the best order.",
        items: [
          { id: "status", label: "Overall status in one line (RAG) and confirm the agenda" },
          { id: "done", label: "Done since last call (short, with a link to the report)" },
          { id: "decisions", label: "Decisions needed from the client (checkout copy, release date)" },
          { id: "next", label: "Next steps until the next call" },
          { id: "risks", label: "Risks and blockers" },
          { id: "actions", label: "Recap action items with owners and dates" },
        ],
        correctOrder: ["status", "done", "next", "risks", "decisions", "actions"],
        explanation:
          "Status first sets the frame. Done and next are quick context. Risks lead naturally into the decisions you need, which still come well before the end. Close by reading back actions so everyone leaves with the same list.",
      },
      sop: [
        {
          title: "Our client meeting cadence",
          prompt:
            "[Oyelabs SOP – admin to fill] How often we hold client updates (weekly or fortnightly, by project type), the default length, who attends from Oyelabs (PM, tech lead, BD?), how far ahead the agenda is sent, and our standard agenda template.",
        },
      ],
    },
    {
      id: "pma-rag-status",
      moduleId: "pma-meetings",
      trackId: "pm",
      title: "RAG status",
      summary:
        "RAG means Red, Amber, Green. It is a one-word answer to the question every client asks first: \"Are we OK?\". A busy founder in New York may read nothing else in your report, so the colour has to be honest and has to mean the same thing every week.\n\nGreen means on track for scope, time and budget, with no help needed. Amber means there is a real risk to a date, budget or scope, but you have a plan to recover it. Red means a commitment will be missed without a decision or help from the client or management. Give a colour per area (schedule, budget, scope, quality) and an overall colour, and always add one line saying why.\n\nStep by step: compare plan against actual for each area. Apply the thresholds in your team's SOP below, for example how many days late turns Amber into Red. Write the reason and the recovery action next to every non-green colour. If the status changed since last week, say what changed. A simple Excel formula can apply the thresholds so the colour is not a mood.\n\nThe classic mistake is the \"watermelon\" report: green outside, red inside. A PM keeps a Laravel API release green for three weeks to avoid an awkward call, then it jumps straight to red a day before the deadline. The client loses trust in every future green. Moving to amber early, with a plan, is a sign of control, not failure.\n\nAnother mistake is amber forever. If something has been amber for a month with no recovery, it is red. Escalate it.",
      level: "beginner",
      estMinutes: 25,
      webRefs: [
        { label: "Microsoft Support: Use conditional formatting to highlight information in Excel", url: "https://support.microsoft.com/en-us/excel/use-conditional-formatting-to-highlight-information-in-excel", kind: "docs", verifiedAt: "2026-10-02T09:35:37Z" },
        { label: "ProjectManager: RAG Status in Project Management: Importance & Benefits", url: "https://www.projectmanager.com/blog/rag-status", kind: "article", verifiedAt: "2026-10-02T09:38:56Z" },
        { label: "Atlassian: Project Status Report: Tips and Templates for Success", url: "https://www.atlassian.com/agile/project-management/status-report", kind: "article", verifiedAt: "2026-10-02T09:38:53Z" },
        { label: "TeamGantt: How to Write a Weekly Project Status Report [Template]", url: "https://www.teamgantt.com/project-status-report-template", kind: "article", verifiedAt: "2026-10-02T09:39:02Z" },
      ],
      video: {
        title: "What is a RAG Report? ...or a Traffic Light Report?",
        channel: "Online PM Courses - Mike Clayton",
        url: "https://www.youtube.com/watch?v=xadyhn3GjJc",
        videoId: "xadyhn3GjJc",
        verifiedAt: "2026-10-02T09:35:57Z",
      },
      alternateVideos: [
        {
          title: "Project Status Reports: Everything you need to know and more!",
          channel: "The Digital Project Manager",
          url: "https://www.youtube.com/watch?v=U1oSjjNervA",
          videoId: "U1oSjjNervA",
          verifiedAt: "2026-10-02T09:35:56Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-rag-status-q1",
          prompt: "The release is 4 days late, but the team has a recovery plan that needs nothing from the client. Which colour fits best?",
          options: ["Amber", "Green", "Red", "No colour until the plan works"],
          correctIndex: 0,
          explanation: "Amber means a real risk with a recovery plan in hand. Red is for when you need a decision or help.",
        },
        {
          id: "pma-rag-status-q2",
          prompt: "What is a 'watermelon' status report?",
          options: [
            "Green on the surface while the project is really in trouble",
            "A report that uses too many colours",
            "A report shared only with the internal team",
            "A report split into many small sections",
          ],
          correctIndex: 0,
          explanation: "Green outside, red inside. It hides problems until it is too late to fix them cheaply, and it destroys trust.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-rag-status-q3",
          prompt: "What should sit next to every Amber or Red colour? (Select all that apply.)",
          options: [
            "One line on why",
            "The recovery action and its owner",
            "Any decision needed from the client",
            "A longer apology",
            "The names of developers who caused it",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "A colour without a reason and a plan just creates worry. Blame and apologies do not help the client decide anything.",
        },
        {
          id: "pma-rag-status-q4",
          prompt: "A workstream has been Amber for five weeks with no change. What is the honest move?",
          options: [
            "Treat it as Red and escalate, because the recovery plan is not working",
            "Keep it Amber so the client stays calm",
            "Switch it to Green since nothing got worse",
            "Remove it from the report",
          ],
          correctIndex: 0,
          explanation: "Permanent amber is a hidden red. If the plan is not recovering it, someone needs to decide something.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-rag-status-q5",
          prompt: "Why should RAG thresholds be written down (for example in a formula or SOP) rather than decided each week?",
          options: [
            "So the colour means the same thing every week and is not a matter of mood",
            "So the client cannot argue",
            "Because Excel needs it",
            "So the PM never has to explain the colour",
          ],
          correctIndex: 0,
          explanation: "Agreed thresholds make status comparable over time and between projects. You still explain each non-green colour.",
        },
      ],
      practice: {
        kind: "excel",
        prompt:
          "This is the weekly status sheet for a Laravel + React project for a UK client. Fill E2:E5 with a formula that gives the RAG status from the days late in column D: more than 5 days late is \"Red\", 1 to 5 days late is \"Amber\", 0 or less is \"Green\". Then fill E6 with a COUNTIF formula that counts the Red rows.",
        grid: [
          ["Workstream", "Planned date", "Forecast date", "Days late", "RAG"],
          ["Admin panel (Laravel)", "10 Oct", "10 Oct", "0", ""],
          ["Booking API", "14 Oct", "17 Oct", "3", ""],
          ["React web app", "21 Oct", "30 Oct", "9", ""],
          ["Payment integration", "24 Oct", "22 Oct", "-2", ""],
          ["", "", "", "Red count", ""],
        ],
        editable: ["E2", "E3", "E4", "E5", "E6"],
        checks: [
          { cell: "E2", expected: "Green", tolerance: 0.01, requireFormula: true, functions: ["IF"] },
          { cell: "E3", expected: "Amber", tolerance: 0.01, requireFormula: true, functions: ["IF"] },
          { cell: "E4", expected: "Red", tolerance: 0.01, requireFormula: true, functions: ["IF"] },
          { cell: "E5", expected: "Green", tolerance: 0.01, requireFormula: true, functions: ["IF"] },
          { cell: "E6", expected: 1, tolerance: 0.01, requireFormula: true, functions: ["COUNTIF"] },
        ],
        solution: {
          E2: '=IF(D2>5,"Red",IF(D2>0,"Amber","Green"))',
          E3: '=IF(D3>5,"Red",IF(D3>0,"Amber","Green"))',
          E4: '=IF(D4>5,"Red",IF(D4>0,"Amber","Green"))',
          E5: '=IF(D5>5,"Red",IF(D5>0,"Amber","Green"))',
          E6: '=COUNTIF(E2:E5,"Red")',
        },
        explanation:
          "A nested IF tests the worst case first: =IF(D2>5,\"Red\",IF(D2>0,\"Amber\",\"Green\")). Early delivery (negative days) is Green. COUNTIF over the RAG column gives the number of red workstreams for the summary line.",
      },
      sop: [
        {
          title: "Our RAG definitions",
          prompt:
            "[Oyelabs SOP – admin to fill] What Green, Amber and Red mean at Oyelabs for schedule, budget, scope and quality (the exact thresholds, e.g. days late or % over budget), who must be told when a project turns Red, and how fast.",
        },
      ],
    },
    {
      id: "pma-done-next-risks-decisions",
      moduleId: "pma-meetings",
      trackId: "pm",
      title: "Done / next / risks / decisions format",
      summary:
        "Clients do not want a diary of what the team did. They want to know four things: what got finished, what happens next, what could go wrong, and what they need to decide. The done / next / risks / decisions format answers exactly those, in that order, every week.\n\nDone lists outcomes the client can see, not activity. \"Stripe payments live on staging, ready for your test\" beats \"worked on payments\". Next lists what you will finish before the next update, with dates. Risks lists what might hurt the date, budget or quality, with likelihood, impact and what you are doing about it. Blockers are risks that have already happened. Decisions lists each question for the client with an owner and a needed-by date.\n\nStep by step: pull the facts from Jira or the sprint board, not from memory. Rewrite each item in the client's language. Keep each section to three to five bullets. Make the decisions section specific: \"Choose between option A (ship 20 Oct without Apple Pay) and option B (ship 27 Oct with it). Needed by Thursday so we keep the slot.\" Use the same headings in the email, the slide and the meeting, so they reinforce each other.\n\nCommon mistakes: hiding a risk in the done section (\"done, except the API still times out\"), listing risks with no response, and writing decisions as vague statements (\"we need feedback\") with no owner or deadline. Another one is letting \"next\" be a copy of last week's \"next\". If items keep rolling forward, say so and explain why.",
      level: "intermediate",
      estMinutes: 30,
      webRefs: [
        { label: "Atlassian Team Playbook: DACI: A Decision-Making Framework", url: "https://www.atlassian.com/team-playbook/plays/daci", kind: "docs", verifiedAt: "2026-10-02T09:35:27Z" },
        { label: "Asana: How Project Status Reports Work: 8 Steps + Template", url: "https://asana.com/resources/how-project-status-reports", kind: "article", verifiedAt: "2026-10-02T10:07:41Z" },
        { label: "ProjectManager: Project Status Reports (Example & Template Included)", url: "https://www.projectmanager.com/guides/status-report", kind: "article", verifiedAt: "2026-10-02T09:38:48Z" },
        { label: "Atlassian: Project Status Report: Tips and Templates for Success", url: "https://www.atlassian.com/agile/project-management/status-report", kind: "article", verifiedAt: "2026-10-02T09:38:53Z" },
      ],
      video: {
        title: "How to Write a Status Report - PPP methodology (Plans, Progress, Problems) with Weekdone",
        channel: "Weekdone",
        url: "https://www.youtube.com/watch?v=a77p1Dx0JHQ",
        videoId: "a77p1Dx0JHQ",
        verifiedAt: "2026-10-02T09:35:58Z",
      },
      alternateVideos: [
        {
          title: "Project Management Status Reports [WHAT TO INCLUDE]",
          channel: "Adriana Girdler",
          url: "https://www.youtube.com/watch?v=8C1PBSs_cMI",
          videoId: "8C1PBSs_cMI",
          verifiedAt: "2026-10-02T09:35:58Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-done-next-risks-decisions-q1",
          prompt: "Which 'Done' line is best for a client update?",
          options: [
            "Stripe payments live on staging, ready for your test",
            "Worked on payments all week",
            "Closed tickets OYE-412, OYE-415 and OYE-419",
            "Developers were very busy on the payment module",
          ],
          correctIndex: 0,
          explanation: "Done means an outcome the client can see or use, in their words.",
        },
        {
          id: "pma-done-next-risks-decisions-q2",
          prompt: "What makes a decision item actionable? (Select all that apply.)",
          options: [
            "A clear question or set of options",
            "Who on the client side decides",
            "The date by which it is needed and why",
            "A long technical background section",
            "The phrase 'we need feedback'",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Options, an owner and a needed-by date turn a request into a decision. Vague asks get vague answers.",
        },
        {
          id: "pma-done-next-risks-decisions-q3",
          prompt: "What is the difference between a risk and a blocker?",
          options: [
            "A risk might happen; a blocker has already happened and is stopping work",
            "A risk is technical; a blocker is commercial",
            "Blockers are for the internal team only",
            "There is no difference",
          ],
          correctIndex: 0,
          explanation: "Blockers need action now. Risks need a response plan before they turn into blockers.",
        },
        {
          id: "pma-done-next-risks-decisions-q4",
          prompt: "Your 'Done' section says: 'Login done, except social sign-in still fails on iOS.' What is wrong?",
          options: [
            "A known problem is hidden inside Done; it belongs in risks or blockers, and login is not done",
            "Nothing, it is honest",
            "It is too short",
            "Social sign-in should not be mentioned to clients",
          ],
          correctIndex: 0,
          explanation: "Burying issues in Done makes the client think it is finished. Report it as not done, with the issue under blockers.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-done-next-risks-decisions-q5",
          prompt: "The same three items have appeared in 'Next' for three weeks. What should the update do?",
          options: [
            "Call it out, explain why they keep slipping and what changes now",
            "Quietly keep listing them",
            "Remove them so the report looks better",
            "Move them to 'Done' to show progress",
          ],
          correctIndex: 0,
          explanation: "Rolling items are a signal. Clients notice; say it first and give the reason and the fix.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-done-next-risks-decisions-q6",
          prompt: "A good risk entry includes:",
          options: [
            "Description, likelihood, impact, response and owner",
            "Only the description",
            "The name of whoever made the mistake",
            "A note that it is probably fine",
          ],
          correctIndex: 0,
          explanation: "Without a response and an owner, a risk list is just a worry list.",
        },
        {
          id: "pma-done-next-risks-decisions-q7",
          prompt: "Where should the done/next/risks/decisions content come from?",
          options: [
            "The sprint board and team facts, checked before writing",
            "The PM's memory on the morning of the call",
            "Last week's report with dates changed",
            "Whatever the client asked about last time",
          ],
          correctIndex: 0,
          explanation: "Status built from the board is accurate and defensible. Memory and copy-paste produce errors clients catch.",
        },
        {
          id: "pma-done-next-risks-decisions-q8",
          prompt: "The client must choose between shipping on 20 Oct without Apple Pay or 27 Oct with it. How do you write it?",
          options: [
            "Decision needed by Thursday: A) 20 Oct without Apple Pay, B) 27 Oct with it. We recommend A because…",
            "Please let us know your thoughts on Apple Pay",
            "Apple Pay may cause a delay",
            "We will decide internally and inform you",
          ],
          correctIndex: 0,
          explanation: "Options, a recommendation and a deadline make it easy for the client to say yes.",
        },
        {
          id: "pma-done-next-risks-decisions-q9",
          prompt: "Why keep the same four headings in the email, the slide and the meeting?",
          options: [
            "The client learns where to look, and each channel reinforces the others",
            "It saves the PM from writing anything new",
            "Teams requires it",
            "So the meeting can be skipped",
          ],
          correctIndex: 0,
          explanation: "Consistency reduces reading effort and makes missing items obvious.",
        },
      ],
      practice: {
        kind: "spot",
        prompt:
          "A PM drafted this weekly update for a US client's React + Laravel marketplace. Mark the lines that break the done / next / risks / decisions format.",
        segments: [
          { id: "l1", text: "Overall status: Amber. The search release moves from 14 to 18 Oct; recovery plan below.", issue: null },
          { id: "l2", text: "Done: Seller onboarding flow live on staging, ready for your review.", issue: null },
          { id: "l3", text: "Done: Search page finished, except filters still return wrong results.", issue: "Hides a defect inside Done; search is not done and the filter bug is a blocker." },
          { id: "l4", text: "Done: Team worked hard on many tickets this week.", issue: "Activity, not an outcome the client can see." },
          { id: "l5", text: "Next: Fix search filters and release search to staging by 16 Oct.", issue: null },
          { id: "l6", text: "Risk: Payment provider sandbox is unstable. Impact: payment testing slips. Response: daily retry plus vendor ticket, owner Ravi.", issue: null },
          { id: "l7", text: "Risk: Things might get delayed.", issue: "No specific cause, impact, response or owner." },
          { id: "l8", text: "Decision: We need your feedback.", issue: "No question, no decision owner, no needed-by date." },
          { id: "l9", text: "Decision needed by Wed 15 Oct from Sarah: approve the commission rate table so we can finish payouts.", issue: null },
          { id: "l10", text: "Next call: Thursday 9am EST.", issue: null },
        ],
        askExplanation: true,
      },
    },
    {
      id: "pma-demo-prep-flow",
      moduleId: "pma-meetings",
      trackId: "pm",
      title: "Demo preparation and flow",
      summary:
        "A demo is where the client sees their money turn into software. A good one builds trust faster than any report. A broken one, with a login error on screen in front of the client's CEO, can undo weeks of good work. The difference is almost always preparation.\n\nThe Scrum sprint review is a useful model: it is not a show, it is a working session where the client inspects what was built and you adapt the plan together. So the demo should show finished work against the client's goals, and leave time for feedback.\n\nStep by step. One or two days before: agree the stories to show with the tech lead, deploy them to a stable staging build, and freeze it. Prepare test data that looks real (sensible names, prices in the client's currency). Write a short script: the user story, the click path, what the client should notice. Do a dry run with the person driving. On the day: join early, close other apps and notifications, and have screenshots or a recording as a backup. During the demo, start with the goal (\"a guest can book and pay in under a minute\"), show the happy path, then the important edge cases. Pause for questions after each story, and write feedback down as you go.\n\nCommon mistakes: demoing from a developer's laptop with live code, showing unfinished work without saying so, and letting the developer scroll through code. Do not hide known bugs; say \"you will see X, it is fixed in the next build\". Feedback becomes backlog items or change requests, never a promise made on the spot.\n\nWhich environment we demo from and the rules for preparing it are in your team's SOP below.",
      level: "intermediate",
      estMinutes: 30,
      webRefs: [
        { label: "Scrum Guides: Scrum Guide", url: "https://scrumguides.org/scrum-guide.html", kind: "spec", verifiedAt: "2026-10-02T09:35:44Z" },
        { label: "Atlassian: What is a Sprint Review in Agile?", url: "https://www.atlassian.com/agile/scrum/sprint-reviews", kind: "article", verifiedAt: "2026-10-02T09:35:25Z" },
        { label: "Mountain Goat Software: Sprint Review Meeting in Scrum", url: "https://www.mountaingoatsoftware.com/agile/scrum/meetings/sprint-review", kind: "article", verifiedAt: "2026-10-02T09:35:30Z" },
      ],
      video: {
        title: "How to Facilitate the Sprint Review",
        channel: "Scrum.org",
        url: "https://www.youtube.com/watch?v=Fbp9eLbcf7A",
        videoId: "Fbp9eLbcf7A",
        verifiedAt: "2026-10-02T09:35:54Z",
      },
      alternateVideos: [
        {
          title: "Sprint Review: More Than Just a Demo",
          channel: "Mountain Goat Software: Agile & Scrum Mastery",
          url: "https://www.youtube.com/watch?v=9WzoYrtXR-A",
          videoId: "9WzoYrtXR-A",
          verifiedAt: "2026-10-02T09:35:58Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-demo-prep-flow-q1",
          prompt: "Where should a client demo run from?",
          options: [
            "A stable, frozen staging build prepared for the demo",
            "The developer's laptop with the latest code",
            "Production, with real customer data",
            "Whichever environment is up at the time",
          ],
          correctIndex: 0,
          explanation: "A frozen staging build avoids surprises from fresh commits and keeps real customer data out of a screen share.",
        },
        {
          id: "pma-demo-prep-flow-q2",
          prompt: "What should you prepare before a demo? (Select all that apply.)",
          options: [
            "A short script per story: goal, click path, what to notice",
            "Realistic test data in the client's currency and language",
            "A dry run with the person driving",
            "Backup screenshots or a recording",
            "A walkthrough of the source code",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 3],
          explanation: "Script, data, rehearsal and backup make the demo reliable. Clients rarely want code.",
        },
        {
          id: "pma-demo-prep-flow-q3",
          prompt: "According to the Scrum Guide, what is the sprint review mainly for?",
          options: [
            "Inspecting the outcome with stakeholders and adapting what comes next",
            "Approving the developers' performance",
            "Presenting slides only",
            "Signing off the whole project",
          ],
          correctIndex: 0,
          explanation: "It is a working session, not just a presentation. Feedback shapes the backlog.",
        },
        {
          id: "pma-demo-prep-flow-q4",
          prompt: "During the demo, the client says 'Can we also add a referral programme? Should be quick.' What do you say?",
          options: [
            "Note it and say you will come back with an estimate and impact on the plan",
            "Yes, we'll add it this sprint",
            "No, that is out of scope",
            "Ask the developer to estimate it live on the call",
          ],
          correctIndex: 0,
          explanation: "Capture, then assess through change control. On-the-spot promises and live estimates both backfire.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-demo-prep-flow-q5",
          prompt: "There is a known display bug in one screen you must show. What is the best approach?",
          options: [
            "Say up front what they will see and when the fix lands",
            "Skip the screen and hope they do not ask",
            "Show it and say nothing",
            "Cancel the demo",
          ],
          correctIndex: 0,
          explanation: "Naming it first keeps trust. Discovering it by surprise makes the client wonder what else is hidden.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-demo-prep-flow-q6",
          prompt: "How should you open each story in the demo?",
          options: [
            "With the user goal, e.g. 'a guest can book and pay in under a minute'",
            "With the ticket number",
            "With the technology used",
            "With how many hours it took",
          ],
          correctIndex: 0,
          explanation: "The goal tells the client what to judge. Ticket numbers and tech choices do not.",
        },
        {
          id: "pma-demo-prep-flow-q7",
          prompt: "Should you demo a feature that is 80% complete?",
          options: [
            "Only if you clearly label it as work in progress and explain what is missing",
            "Yes, present it as done",
            "Never mention it",
            "Yes, but only the parts that work, without comment",
          ],
          correctIndex: 0,
          explanation: "Showing unfinished work as finished creates false expectations. Labelled previews can be useful for early feedback.",
        },
        {
          id: "pma-demo-prep-flow-q8",
          prompt: "Staging goes down 10 minutes before the demo. What do you do?",
          options: [
            "Switch to the prepared recording or screenshots, and offer a live follow-up once staging is back",
            "Ask the developer to deploy a fix live during the call",
            "Cancel without explanation",
            "Demo from production with real data",
          ],
          correctIndex: 0,
          explanation: "That is exactly what the backup is for. Live fixes under pressure and production data both create bigger risks.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-demo-prep-flow-q9",
          prompt: "What happens to feedback captured during the demo?",
          options: [
            "It becomes backlog items or change requests, confirmed in the minutes",
            "The developer fixes it the same night",
            "It is noted only if the client repeats it",
            "Nothing until the next demo",
          ],
          correctIndex: 0,
          explanation: "Feedback goes into the normal process and is confirmed in writing, so nothing is lost or silently promised.",
        },
      ],
      practice: {
        kind: "rank",
        prompt: "Order the steps for a Friday demo of a booking flow to a UK client.",
        items: [
          { id: "agree", label: "Agree with the tech lead which stories are demo-ready" },
          { id: "freeze", label: "Deploy those stories to staging and freeze the build" },
          { id: "data", label: "Load realistic test data (GBP prices, real-looking names)" },
          { id: "dry", label: "Dry run the script with the person driving, and record a backup" },
          { id: "show", label: "On the call: state the goal, show the happy path, then key edge cases" },
          { id: "capture", label: "Capture feedback and confirm it in the MoM as backlog items or change requests" },
        ],
        correctOrder: ["agree", "freeze", "data", "dry", "show", "capture"],
        explanation:
          "Scope first, then a stable build, then data on that build, then rehearsal on the real setup. The call itself follows, and feedback is captured in writing afterwards.",
      },
      sop: [
        {
          title: "Our demo environment rules",
          prompt:
            "[Oyelabs SOP – admin to fill] Which environment we demo from (staging/UAT URL convention), when the build is frozen before a demo, test-data rules (no real client customer data), who drives the demo, and the backup we keep.",
        },
      ],
    },
    {
      id: "pma-presenting-progress",
      moduleId: "pma-meetings",
      trackId: "pm",
      title: "Presenting progress: slides or live demo",
      summary:
        "Not every update needs a demo, and not every update needs slides. Picking the wrong one wastes the client's time. A live demo is best when there is new, working software the client can react to. Slides (or a one-page status) are best when the story is about plans, dates, budget or a decision, for example a two-week delay on a React Native release and the options to recover.\n\nSenior stakeholders want the answer first. Start with one slide or one screen that says the overall status, the key message and the decision you need. Then give the supporting detail. For a sponsor on a monthly steering call, that may be three slides: status and headline, timeline against plan, risks and decisions. For a product owner in a weekly call, a five-minute demo plus the status doc may be enough.\n\nStep by step: decide the one thing the client must leave knowing. Choose the format that shows it best. Keep slides simple: one message per slide in the title, a chart or table, no paragraphs. In Teams, share a single window or the PowerPoint Live option rather than your whole screen, so no private chat pops up. Hand over control to the developer for the demo part, and take it back for decisions.\n\nCommon mistakes: reading slides aloud, burying a delay on slide nine, and switching to a demo when the client really needs to decide on scope. Mixing both is fine; a short demo followed by a decision slide often works best. Whatever the format, send the material afterwards so people who missed the call get the same message.",
      level: "intermediate",
      estMinutes: 30,
      webRefs: [
        { label: "Microsoft Support: Present content in Microsoft Teams meetings", url: "https://support.microsoft.com/en-us/teams/meetings/present-content-in-microsoft-teams-meetings", kind: "docs", verifiedAt: "2026-10-02T09:35:40Z" },
        { label: "Microsoft Support: PowerPoint for Windows training", url: "https://support.microsoft.com/en-us/powerpoint/powerpoint-for-windows-training", kind: "docs", verifiedAt: "2026-10-02T09:35:29Z" },
        { label: "Atlassian: Project Status Report: Tips and Templates for Success", url: "https://www.atlassian.com/agile/project-management/status-report", kind: "article", verifiedAt: "2026-10-02T09:38:53Z" },
        { label: "TeamGantt: How to Write a Weekly Project Status Report [Template]", url: "https://www.teamgantt.com/project-status-report-template", kind: "article", verifiedAt: "2026-10-02T09:39:02Z" },
      ],
      video: {
        title: "How To Create Executive Status Reports",
        channel: "Your Project Leadership Coach",
        url: "https://www.youtube.com/watch?v=MJyYxuKtUaQ",
        videoId: "MJyYxuKtUaQ",
        verifiedAt: "2026-10-02T09:35:55Z",
      },
      alternateVideos: [
        {
          title: "Project Status Reports: Everything you need to know and more!",
          channel: "The Digital Project Manager",
          url: "https://www.youtube.com/watch?v=U1oSjjNervA",
          videoId: "U1oSjjNervA",
          verifiedAt: "2026-10-02T09:35:56Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-presenting-progress-q1",
          prompt: "The release slipped two weeks and the client must choose between two recovery options. Which format fits best?",
          options: [
            "A short slide deck or one-pager: status, timeline, options and the decision needed",
            "A 30-minute live demo of the current build",
            "A walkthrough of the Jira board",
            "No presentation; just discuss",
          ],
          correctIndex: 0,
          explanation: "The message is a decision about dates and scope. Slides show options clearly; a demo would distract.",
        },
        {
          id: "pma-presenting-progress-q2",
          prompt: "What should the first slide or first minute contain?",
          options: [
            "Overall status, the key message and the decision needed",
            "The team introduction",
            "A detailed list of completed tickets",
            "The project history since kickoff",
          ],
          correctIndex: 0,
          explanation: "Answer first. Busy sponsors may only stay for the first few minutes.",
        },
        {
          id: "pma-presenting-progress-q3",
          prompt: "Which are good slide habits for a client status deck? (Select all that apply.)",
          options: [
            "The slide title states the message, e.g. 'Release moves to 27 Oct'",
            "One message per slide, supported by a chart or table",
            "Full paragraphs so nothing is missed",
            "Reading each slide aloud word for word",
            "Bad news on the first slides, not hidden at the end",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 4],
          explanation: "Message titles, one idea per slide and early bad news respect the client's time. Paragraphs and reading aloud do not.",
        },
        {
          id: "pma-presenting-progress-q4",
          prompt: "Why share a single window (or PowerPoint Live) in Teams instead of your whole screen?",
          options: [
            "So private chats, emails and other clients' data do not appear on screen",
            "Because whole-screen sharing is not allowed for guests",
            "It makes the slides bigger",
            "It turns on recording",
          ],
          correctIndex: 0,
          explanation: "Whole-screen sharing leaks notifications and other clients' information. Share only what you mean to show.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-presenting-progress-q5",
          prompt: "A weekly call with a product owner who tests every build. What usually works?",
          options: [
            "A short live demo of new work plus the status doc for dates and risks",
            "A 20-slide deck every week",
            "No agenda, just questions",
            "Sending a video instead of meeting",
          ],
          correctIndex: 0,
          explanation: "Hands-on product owners want to see the software, with status handled in writing.",
        },
        {
          id: "pma-presenting-progress-q6",
          prompt: "The client's CEO joins a demo call unexpectedly. What do you adjust?",
          options: [
            "Open with a one-minute summary of status and the big decision before the demo",
            "Carry on exactly as planned",
            "Switch to technical detail to impress",
            "Ask the CEO to leave and join the next steering call",
          ],
          correctIndex: 0,
          explanation: "Adapt to the most senior person present. They want the headline, then they can watch.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-presenting-progress-q7",
          prompt: "Your deck mentions the delay only on slide 9 of 10. What is the risk?",
          options: [
            "The client feels misled and you may run out of time before the key topic",
            "None, as long as it is in the deck",
            "Teams may not show slide 9",
            "The client may not like the colour",
          ],
          correctIndex: 0,
          explanation: "Burying bad news damages trust and leaves no time to discuss it.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-presenting-progress-q8",
          prompt: "After the presentation, what should you send?",
          options: [
            "The slides or status doc with the minutes, so absentees get the same message",
            "Nothing; the recording is enough",
            "Only the slides that went well",
            "A new deck with different numbers",
          ],
          correctIndex: 0,
          explanation: "Written follow-up keeps everyone aligned and gives a record of what was presented.",
        },
        {
          id: "pma-presenting-progress-q9",
          prompt: "How do you hand the demo part to a developer cleanly in Teams?",
          options: [
            "Make them presenter or give control, introduce what they will show, take back control for decisions",
            "Let them share their whole screen with IDE open",
            "Ask the client to share instead",
            "Leave the meeting while they present",
          ],
          correctIndex: 0,
          explanation: "A clear handover keeps the flow, and the PM leads the decision part.",
        },
      ],
      practice: {
        kind: "scenario",
        prompt:
          "You manage a React Native + Laravel delivery app for an Australian client. This week: two new screens are working on staging, but the App Store submission is delayed by 10 days because Apple rejected the build for a missing privacy disclosure. Tomorrow's 30-minute call includes the client's operations head and, for the first 10 minutes, their CEO.",
        steps: [
          {
            id: "s1",
            question: "How do you open the call?",
            options: [
              "Status Amber, the 10-day App Store delay with cause and recovery plan, and the decision needed, then the demo",
              "Start with the demo of the two new screens to build goodwill",
              "Introduce the team and the agenda for five minutes",
              "Wait for the CEO to ask about the store release",
            ],
            correctIndex: 0,
            explanation: "The CEO is only there for 10 minutes. Lead with the headline and the decision.",
          },
          {
            id: "s2",
            question: "What format do you use for the delay?",
            options: [
              "One slide: old date, new date, cause, fix and the option to release Android first",
              "A live look at the App Store Connect rejection screen",
              "A ten-slide deck on Apple's review process",
              "Just mention it verbally",
            ],
            correctIndex: 0,
            explanation: "A single clear slide with options supports the decision without drowning the client in detail.",
          },
          {
            id: "s3",
            question: "After the CEO leaves, how do you show the new screens?",
            options: [
              "The developer drives a short scripted demo from frozen staging, sharing only the app window",
              "Share your whole screen and click around freely",
              "Skip the demo since the delay is the main news",
              "Send the build link and end the call",
            ],
            correctIndex: 0,
            explanation: "The operations head still needs to see and react to the new screens; keep it scripted and safe.",
          },
        ],
      },
    },
    {
      id: "pma-client-meetings-in-teams",
      moduleId: "pma-meetings",
      trackId: "pm",
      title: "Running client meetings in Teams",
      summary:
        "Most of our client calls run in Microsoft Teams, and clients judge us by how smooth they are. A client in Toronto stuck in the lobby for five minutes, a recording started without anyone being told, or a PM sharing their whole screen with another client's chat visible: each one makes us look careless.\n\nKnow the basics. Schedule from Outlook or Teams with a clear title and the agenda in the body. External clients can join from a link, even without a Teams account. Meeting options control who can bypass the lobby, who can present, and whether attendees can unmute or use chat. Recording and transcription can be started from the meeting controls; Teams shows a notice to everyone, but you should still say it out loud and ask for agreement.\n\nStep by step: before the call, set meeting options (lobby, presenters), attach the agenda, and test your audio and the window you will share. Join five minutes early to admit people. At the start, confirm the agenda and ask \"Is it OK if we record and transcribe for the minutes?\". Share only the window you need. Use chat for links, not side conversations. At the end, stop recording, and use the transcript to check your minutes, not to replace them.\n\nCommon mistakes: letting everyone be a presenter in a large client meeting, forgetting the time zone in the invite, starting recording silently, and treating the transcript as the minutes. Transcripts are long and nobody reads them; the client wants a short MoM. Recordings may also hold confidential information, so they must be stored where your team's SOP below says, with the right access.\n\nThe Teams settings we use for client meetings and where recordings live are in your team's SOP below.",
      level: "intermediate",
      estMinutes: 30,
      webRefs: [
        { label: "Microsoft Support: Schedule a meeting in Microsoft Teams", url: "https://support.microsoft.com/en-us/teams/meetings/schedule-a-meeting-in-microsoft-teams", kind: "docs", verifiedAt: "2026-10-02T09:35:24Z" },
        { label: "Microsoft Support: Start, stop, and find meeting recordings in Microsoft Teams", url: "https://support.microsoft.com/en-us/teams/meetings/start-stop-and-find-meeting-recordings-in-microsoft-teams", kind: "docs", verifiedAt: "2026-10-02T09:41:14Z" },
        { label: "Microsoft Support: Start, stop, and download live transcripts in Microsoft Teams meetings", url: "https://support.microsoft.com/en-us/teams/meetings/start-stop-and-download-live-transcripts-in-microsoft-teams-meetings", kind: "docs", verifiedAt: "2026-10-02T09:35:42Z" },
        { label: "Microsoft Support: Join a meeting without an account in Microsoft Teams", url: "https://support.microsoft.com/en-us/teams/meetings/join-a-meeting-without-an-account-in-microsoft-teams", kind: "docs", verifiedAt: "2026-10-02T09:35:19Z" },
      ],
      video: {
        title: "How to Use Microsoft Teams (Full Tutorial)",
        channel: "Kevin Stratvert",
        url: "https://www.youtube.com/watch?v=vaeFzrIc9HU",
        videoId: "vaeFzrIc9HU",
        verifiedAt: "2026-10-02T09:35:53Z",
      },
      alternateVideos: [
        {
          title: "How to use Microsoft Teams Lobby",
          channel: "Kevin Stratvert",
          url: "https://www.youtube.com/watch?v=dooaJNiSarc",
          videoId: "dooaJNiSarc",
          verifiedAt: "2026-10-02T09:35:54Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-client-meetings-in-teams-q1",
          prompt: "Your client does not have a Teams account. Can they join your meeting?",
          options: [
            "Yes, from the meeting link in a browser or the app, as a guest",
            "No, they must buy a licence",
            "Only by phone",
            "Only if you add them to your company tenant",
          ],
          correctIndex: 0,
          explanation: "Teams supports joining without an account from the meeting link.",
        },
        {
          id: "pma-client-meetings-in-teams-q2",
          prompt: "Before you start recording a client call, what should you do?",
          options: [
            "Say it out loud and ask if everyone agrees, even though Teams shows a notice",
            "Nothing; Teams notifies people automatically",
            "Record silently and delete it later if anyone objects",
            "Ask only your own team",
          ],
          correctIndex: 0,
          explanation: "Asking openly is courteous and protects consent. The banner alone is easy to miss.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-client-meetings-in-teams-q3",
          prompt: "Which meeting options matter most for a client call? (Select all that apply.)",
          options: [
            "Who can bypass the lobby",
            "Who can present",
            "Whether recording and transcription will be used",
            "The background image of each attendee",
            "The font of the invite",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Lobby, presenter rights and recording affect security and control. Backgrounds and fonts do not.",
        },
        {
          id: "pma-client-meetings-in-teams-q4",
          prompt: "Is the Teams transcript a substitute for minutes of meeting?",
          options: [
            "No, it is source material; the client still needs a short MoM with decisions and actions",
            "Yes, just forward the transcript",
            "Yes, if it is downloaded as a Word file",
            "Only for internal meetings",
          ],
          correctIndex: 0,
          explanation: "Transcripts are long and include errors. Use them to check your MoM, not to replace it.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-client-meetings-in-teams-q5",
          prompt: "The client is in Toronto and you are in India. What must the invite make clear?",
          options: [
            "The time in the client's time zone (Teams shows each person their local time, but say it in the agenda too)",
            "Only IST",
            "Only UTC",
            "No time, the link is enough",
          ],
          correctIndex: 0,
          explanation: "Stating the client's local time avoids confusion, especially around daylight-saving changes.",
        },
        {
          id: "pma-client-meetings-in-teams-q6",
          prompt: "A large client meeting has 15 attendees. Who should be a presenter?",
          options: [
            "Only the people who need to share or run the meeting",
            "Everyone, to be friendly",
            "Nobody",
            "Only the client's CEO",
          ],
          correctIndex: 0,
          explanation: "Limiting presenters avoids accidental screen shares and removals.",
        },
        {
          id: "pma-client-meetings-in-teams-q7",
          prompt: "You need to share a link to the staging build during the call. Where?",
          options: [
            "In the meeting chat, so it stays with the meeting",
            "By reading it aloud",
            "In a private WhatsApp message",
            "Only in the minutes next week",
          ],
          correctIndex: 0,
          explanation: "Meeting chat keeps links with the meeting for everyone, including later.",
        },
        {
          id: "pma-client-meetings-in-teams-q8",
          prompt: "Your developer posts 'this client never reads the docs lol' in the meeting chat by mistake. What is the lesson?",
          options: [
            "The meeting chat is visible to the client; internal comments go in an internal chat, and you apologise if needed",
            "Delete it and say nothing",
            "It is fine, clients do not read chat",
            "Turn off chat for all meetings",
          ],
          correctIndex: 0,
          explanation: "Meeting chat includes external guests. Brief the team on this before client calls.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-client-meetings-in-teams-q9",
          prompt: "Why join a client meeting five minutes early?",
          options: [
            "To admit guests from the lobby, check audio and the shared window",
            "To start recording before the client arrives",
            "Because Teams requires it",
            "To finish other work",
          ],
          correctIndex: 0,
          explanation: "Being early means no client waits in the lobby and no tech fumbling on the hour.",
        },
      ],
      practice: {
        kind: "sim",
        app: "teams",
        prompt:
          "It is 9:00 EST. You are hosting the weekly update with a US client for their Laravel portal. Review the meeting panel and flag every row that needs action before you start.",
        title: "Weekly update – Acme Portal (Teams meeting)",
        columns: ["Item", "Detail", "Status"],
        rows: [
          { id: "r1", cells: ["Participant", "Sarah Lee (Acme, guest)", "Joined, admitted from lobby"], issue: null },
          { id: "r2", cells: ["Participant", "Unknown guest 'jd-test'", "Bypassed lobby"], issue: "An unidentified external person is in a client meeting; confirm who it is or remove them." },
          { id: "r3", cells: ["Meeting option", "Who can present", "Everyone"], issue: "Limit presenters to the PM and the developer doing the demo." },
          { id: "r4", cells: ["Recording", "Started 8:58 by Arjun", "Not announced to attendees"], issue: "Recording must be announced and agreed with the client." },
          { id: "r5", cells: ["Transcript", "Live transcript", "On"], issue: null },
          { id: "r6", cells: ["Shared screen", "Arjun – entire screen (Slack and email visible)", "Sharing"], issue: "Share only the browser window; whole-screen sharing exposes other chats." },
          { id: "r7", cells: ["Meeting chat", "Link to staging build posted", "Visible to all"], issue: null },
          { id: "r8", cells: ["Agenda", "Attached to invite", "Sent yesterday"], issue: null },
          { id: "r9", cells: ["Participant", "Raj (Oyelabs tech lead)", "Joined"], issue: null },
        ],
        questions: [
          {
            id: "q1",
            question: "Sarah says she would rather the call is not recorded today. What do you do?",
            options: [
              "Stop the recording, delete it, and take notes for the MoM manually",
              "Keep recording but promise not to share it",
              "Continue; the company policy is to record everything",
              "End the meeting",
            ],
            correctIndex: 0,
            explanation: "Consent matters more than convenience. You can still write a good MoM from notes.",
          },
          {
            id: "q2",
            question: "Where do the decisions from this call end up?",
            options: [
              "In a short MoM email sent within 24 hours, checked against the transcript",
              "Only in the transcript",
              "Only in the recording",
            ],
            correctIndex: 0,
            explanation: "The MoM is the record the client reads and confirms; the transcript is just a source.",
          },
        ],
      },
      sop: [
        {
          title: "Our Teams settings for client meetings",
          prompt:
            "[Oyelabs SOP – admin to fill] Default meeting options for client calls (lobby, who can present, chat), our rule for recording and transcription consent, where recordings and transcripts are stored and who can access them, and how long we keep them.",
        },
      ],
    },
    {
      id: "pma-timeboxing-decisions-actions",
      moduleId: "pma-meetings",
      trackId: "pm",
      title: "Timeboxing, decisions and action items",
      summary:
        "A client call that overruns by 20 minutes is not a sign of a thorough PM. It usually means the important item came last, the client had to leave, and the decision you needed is now a week late. Timeboxing, explicit decisions and clear action items are what make a meeting worth the client's hour.\n\nTimeboxing means giving each agenda item a fixed time and holding to it. The Scrum Guide uses timeboxes for every event for the same reason: they force focus. When time is up, you either decide, park the topic for a separate session with the right people, or agree what extra information is needed and who will get it.\n\nA decision is only a decision when it is stated out loud and agreed. Use a simple pattern: \"So we are agreeing to ship Android first on 20 Oct and iOS on 27 Oct. Sarah, you are OK with that?\" Frameworks like DACI help on bigger choices: who drives, who approves, who is consulted, who is informed. If the approver is not in the room, it is not decided yet.\n\nAn action item needs three parts: a specific task, one named owner, and a due date. \"Look into the payment issue\" is not an action. \"Ravi to send the Stripe error logs to Acme's IT by Wed 15 Oct\" is. Read the actions back in the last five minutes so everyone hears their own name.\n\nCommon mistakes: no one watching the clock, owners like \"team\" or \"client\", decisions inferred later from vague talk, and action items nobody checks next week. Open every update by reviewing last week's actions.",
      level: "advanced",
      estMinutes: 35,
      webRefs: [
        { label: "Scrum Guides: Scrum Guide", url: "https://scrumguides.org/scrum-guide.html", kind: "spec", verifiedAt: "2026-10-02T09:35:44Z" },
        { label: "Asana: Free Meeting Minutes Template (Examples + Tips)", url: "https://asana.com/templates/meeting-minutes", kind: "docs", verifiedAt: "2026-10-02T10:07:03Z" },
        { label: "Atlassian Team Playbook: DACI: A Decision-Making Framework", url: "https://www.atlassian.com/team-playbook/plays/daci", kind: "article", verifiedAt: "2026-10-02T09:35:27Z" },
        { label: "Asana: Action Items: Definition, How to Write, and Examples", url: "https://asana.com/resources/action-items", kind: "article", verifiedAt: "2026-10-02T09:38:38Z" },
      ],
      video: {
        title: "A Simple Way to Track Action Items in a Meeting",
        channel: "North Star Facilitators",
        url: "https://www.youtube.com/watch?v=mmTZbH-zWkM",
        videoId: "mmTZbH-zWkM",
        verifiedAt: "2026-10-02T09:35:55Z",
      },
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-timeboxing-decisions-actions-q1",
          prompt: "Which is a properly written action item?",
          options: [
            "Ravi to send the Stripe error logs to Acme IT by Wed 15 Oct",
            "Look into the payment issue",
            "Team to fix bugs ASAP",
            "Client to share feedback",
          ],
          correctIndex: 0,
          explanation: "A specific task, one named owner and a date. The others miss at least one of the three.",
        },
        {
          id: "pma-timeboxing-decisions-actions-q2",
          prompt: "The timebox for the scope discussion ends with no agreement. What are good options? (Select all that apply.)",
          options: [
            "Park it for a separate session with the right people",
            "Agree what information is missing and who gets it by when",
            "Make a decision now if the approver is present and has enough information",
            "Keep discussing until the end of the call regardless of the agenda",
            "Pretend it was agreed and write it in the minutes",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Decide, park, or define the next step. Running over squeezes everything else; inventing agreement is worse.",
        },
        {
          id: "pma-timeboxing-decisions-actions-q3",
          prompt: "The product owner says 'Sounds good' about shipping Android first, but the CEO is the approver and is not on the call. Is it decided?",
          options: [
            "No; record it as recommended, pending the CEO's approval, with an action to get it",
            "Yes, the product owner agreed",
            "Yes, silence from the CEO means yes",
            "No, so do not mention it in the minutes",
          ],
          correctIndex: 0,
          explanation: "Without the approver it is a recommendation. Write it down as pending, with an owner to close it.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-timeboxing-decisions-actions-q4",
          prompt: "How do you confirm a decision in the meeting?",
          options: [
            "State it out loud and ask the decision-maker to confirm",
            "Assume it from the discussion",
            "Wait for the minutes to see if anyone objects",
            "Ask the developer if it sounds right",
          ],
          correctIndex: 0,
          explanation: "A spoken summary and explicit 'yes' prevent the 'I never agreed to that' email later.",
        },
        {
          id: "pma-timeboxing-decisions-actions-q5",
          prompt: "Why review last week's action items at the start of each update?",
          options: [
            "It builds accountability and catches anything that slipped",
            "It fills time",
            "Clients expect a long recap",
            "To blame people who missed them",
          ],
          correctIndex: 0,
          explanation: "Open actions that are never checked quietly die. A quick review keeps both sides accountable.",
        },
        {
          id: "pma-timeboxing-decisions-actions-q6",
          prompt: "An action is assigned to 'Client'. What is the problem?",
          options: [
            "No single person owns it, so nobody does it",
            "Clients cannot have action items",
            "It should be assigned to the PM instead",
            "Nothing, it is clear enough",
          ],
          correctIndex: 0,
          explanation: "Name a person on the client side. Group owners are a common reason actions are missed.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-timeboxing-decisions-actions-q7",
          prompt: "In DACI, who makes the final call?",
          options: ["The Approver", "The Driver", "The Contributors", "The Informed"],
          correctIndex: 0,
          explanation: "The Driver runs the process; the Approver decides; Contributors advise; Informed are told after.",
        },
        {
          id: "pma-timeboxing-decisions-actions-q8",
          prompt: "Fifteen minutes before the end, you still have three agenda items including the release date decision. What do you do?",
          options: [
            "Jump to the release date decision now and move the other items to email or next call",
            "Go through the items in order and run over",
            "End on time and skip everything",
            "Speed-read all three items",
          ],
          correctIndex: 0,
          explanation: "Protect the decision. Information items can move to writing.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-timeboxing-decisions-actions-q9",
          prompt: "When should action items be read back?",
          options: [
            "In the last few minutes of the call, so everyone hears their own name and date",
            "Only in the MoM",
            "Only if someone asks",
            "At the next meeting",
          ],
          correctIndex: 0,
          explanation: "Reading back catches misunderstandings while everyone is still there.",
        },
      ],
      practice: {
        kind: "spot",
        prompt:
          "These are the decisions and actions a PM captured from a call with a UK client about a delayed Laravel release. Mark the lines that would not hold up as a decision or an action item.",
        segments: [
          { id: "l1", text: "Decision: Release v2.1 moves to 24 Oct. Approved by Emma (client sponsor) on the call.", issue: null },
          { id: "l2", text: "Decision: Client is happy with the new dashboard design.", issue: "Not a decision; vague impression, nobody approved anything specific." },
          { id: "l3", text: "Action: Ravi to share the load-test report with Emma by Fri 17 Oct.", issue: null },
          { id: "l4", text: "Action: Team to look into performance.", issue: "No named owner, no specific task, no date." },
          { id: "l5", text: "Action: Emma to confirm the new VAT rules with her finance team by Tue 21 Oct.", issue: null },
          { id: "l6", text: "Decision: Add multi-currency support (Tom suggested it; Emma to check budget).", issue: "Pending budget approval from Emma; it is an open question, not a decision." },
          { id: "l7", text: "Action: Client to send content soon.", issue: "Group owner and no date." },
          { id: "l8", text: "Parked: Reporting module scope, separate 30-min call booked for Thu 16 Oct with Emma and Raj.", issue: null },
          { id: "l9", text: "Action: Priya to update the Jira board with the new release date by today 6pm IST.", issue: null },
          { id: "l10", text: "Next call: Tue 21 Oct, 10:00 BST.", issue: null },
        ],
        askExplanation: true,
      },
    },
    {
      id: "pma-tough-questions",
      moduleId: "pma-meetings",
      trackId: "pm",
      title: "Handling tough questions",
      summary:
        "Sooner or later a client asks the question you hoped they would not: \"Why is this late again?\", \"Why are we paying for bugs?\", \"Can your team actually do this?\". How you answer in that moment matters more than the slide you prepared. A calm, honest answer builds trust. A defensive or vague one makes the client start checking everything you say.\n\nPrepare for it. Before each update, list the three questions you would least like to hear and draft short answers with facts. Know the numbers: original date, new date, hours used against estimate, open defects. Bring the tech lead if a deep technical question is likely.\n\nIn the moment, use a simple flow. Listen to the whole question without interrupting. Acknowledge the concern (\"I understand the delay affects your launch plans\"). Answer with facts, briefly. If it is our fault, say so plainly. Then move to what happens next and what you need. If you do not know, say \"I don't know yet; I will confirm by tomorrow 5pm your time\" and put it in the minutes. Never guess a date to make the moment pass.\n\nWatch for hidden questions. \"Is this still on track for the board meeting?\" may really mean \"Can I trust your dates?\". Answer both. If the question opens a commercial topic (\"Will you cover the extra hours?\"), do not decide on the call unless you have authority. Say you will come back after checking with your account lead.\n\nCommon mistakes: blaming the developers or a third party in front of the client, over-explaining technical detail, promising a fix date the team has not agreed, and arguing. Stay factual and keep the conversation on the plan.",
      level: "advanced",
      estMinutes: 35,
      webRefs: [
        { label: "Atlassian Team Playbook: Stakeholder Project Communication: Atlassian Plays", url: "https://www.atlassian.com/team-playbook/plays/stakeholder-communications-plan", kind: "docs", verifiedAt: "2026-10-02T09:38:59Z" },
        { label: "Asana: Effective communication workplace: 12 tips & styles", url: "https://asana.com/resources/effective-communication-workplace", kind: "article", verifiedAt: "2026-10-02T10:08:00Z" },
        { label: "Asana: Project Stakeholder: Definition, Analysis & Mapping", url: "https://asana.com/resources/project-stakeholder", kind: "article", verifiedAt: "2026-10-02T10:07:41Z" },
        { label: "ProjectManager: What Is Stakeholder Management?", url: "https://www.projectmanager.com/guides/stakeholder-management", kind: "article", verifiedAt: "2026-10-02T09:38:55Z" },
      ],
      video: {
        title: "Answering Tough Questions",
        channel: "Stanford Graduate School of Business",
        url: "https://www.youtube.com/watch?v=hSeAGSPDG4w",
        videoId: "hSeAGSPDG4w",
        verifiedAt: "2026-10-02T09:35:55Z",
      },
      alternateVideos: [
        {
          title: "From Fear to Fabulous: Expert Tips for Answering Difficult Questions During a Presentation",
          channel: "Carl Kwan",
          url: "https://www.youtube.com/watch?v=cQMO3Z7lWPA",
          videoId: "cQMO3Z7lWPA",
          verifiedAt: "2026-10-02T09:35:54Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-tough-questions-q1",
          prompt: "The client asks 'When will the fix be live?' and you do not know. What do you say?",
          options: [
            "'I don't know yet. I'll confirm with the team and reply by 5pm your time tomorrow.'",
            "'Probably Friday.'",
            "'The developers are slow, so hard to say.'",
            "'It depends on many technical factors.'",
          ],
          correctIndex: 0,
          explanation: "An honest 'I don't know' with a firm follow-up time beats a guess you later miss.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-tough-questions-q2",
          prompt: "Which steps belong in answering a tough question well? (Select all that apply.)",
          options: [
            "Listen to the whole question",
            "Acknowledge the concern",
            "Answer briefly with facts",
            "Move to the plan and what you need",
            "Explain the full technical history in detail",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 3],
          explanation: "Listen, acknowledge, answer, move forward. Long technical detail sounds like an excuse.",
        },
        {
          id: "pma-tough-questions-q3",
          prompt: "The delay is caused by your team's estimate being too low. How do you say it?",
          options: [
            "Plainly: 'We underestimated the integration work. Here is the new plan and what we changed in how we estimate.'",
            "'The third-party API was harder than expected' (without mentioning the estimate)",
            "'The junior developer made mistakes'",
            "Avoid the question and move on",
          ],
          correctIndex: 0,
          explanation: "Owning it as a team, with a fix, keeps trust. Blaming individuals or vendors in front of the client does not.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-tough-questions-q4",
          prompt: "'Will you cover the extra hours for this?' You do not have authority to decide. What do you do?",
          options: [
            "Acknowledge it, say you will confirm with your account lead and come back by a set date",
            "Say yes to keep the client happy",
            "Say no, the contract is clear",
            "Ignore the question",
          ],
          correctIndex: 0,
          explanation: "Commercial commitments need the right authority. A dated follow-up shows you take it seriously.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-tough-questions-q5",
          prompt: "'Is this still on track for my board meeting?' What is the client probably also asking?",
          options: [
            "Whether they can trust your dates",
            "Whether you know when their board meets",
            "Whether you will attend the board meeting",
            "Nothing else",
          ],
          correctIndex: 0,
          explanation: "Answer the hidden question too: give the evidence behind your date and the risks to it.",
        },
        {
          id: "pma-tough-questions-q6",
          prompt: "How should you prepare for tough questions before an update?",
          options: [
            "List the three questions you would least like to hear and draft factual answers",
            "Hope they do not come up",
            "Prepare a long technical appendix",
            "Ask the client to send questions in writing only",
          ],
          correctIndex: 0,
          explanation: "Preparation turns a stressful moment into a calm, factual answer.",
        },
        {
          id: "pma-tough-questions-q7",
          prompt: "The client gets angry and raises their voice. What helps most?",
          options: [
            "Stay calm, let them finish, acknowledge the impact, and steer to facts and next steps",
            "Raise your voice to match",
            "End the call immediately",
            "Defend the team point by point",
          ],
          correctIndex: 0,
          explanation: "Calm acknowledgement lowers the temperature; then facts and the plan can be heard.",
        },
        {
          id: "pma-tough-questions-q8",
          prompt: "A deep technical question comes up that you cannot answer well. What is best?",
          options: [
            "Bring in the tech lead if present, or note it and arrange a short follow-up with them",
            "Make up a plausible answer",
            "Say it is not important",
            "Tell the client to read the documentation",
          ],
          correctIndex: 0,
          explanation: "Use the right expert; a wrong technical answer costs more trust than a short wait.",
        },
        {
          id: "pma-tough-questions-q9",
          prompt: "After a tough call, where should your promised follow-ups go?",
          options: [
            "Into the MoM as action items with your name and date",
            "Into your memory",
            "Only into the internal chat",
            "Nowhere; the client will remind you",
          ],
          correctIndex: 0,
          explanation: "Writing them in the MoM makes your promise visible and trackable.",
        },
      ],
      practice: {
        kind: "scenario",
        prompt:
          "You run a fixed-price React + Laravel e-commerce build for an Australian retailer. The go-live moved from 1 Nov to 15 Nov, the second slip this quarter. Mid-call, the client's founder says: \"Honestly, I'm starting to wonder if your team can deliver this at all.\"",
        steps: [
          {
            id: "s1",
            question: "What do you say first?",
            options: [
              "Acknowledge it: 'I understand, two slips is not what you expected from us, and it affects your launch plans.'",
              "'Our team is very experienced, I assure you.'",
              "'The delays were caused by your late content.'",
              "'Let's move to the next agenda item.'",
            ],
            correctIndex: 0,
            explanation: "Acknowledging the real concern opens the door to a factual conversation.",
          },
          {
            id: "s2",
            question: "The founder asks why it slipped again. The main cause was our underestimate of the shipping integration. How do you answer?",
            options: [
              "Own it briefly, give the facts, and show what changed: integration now tested end to end, daily build checks, and the new date's buffer",
              "Explain the full API documentation of the shipping provider",
              "Say the provider's API was badly documented and leave it there",
              "Promise it will never happen again",
            ],
            correctIndex: 0,
            explanation: "Ownership plus concrete changes rebuilds confidence; vague promises and blame do not.",
          },
          {
            id: "s3",
            question: "The founder asks: 'Will you give us a discount for the delay?' You are not authorised to decide.",
            options: [
              "Say you understand the request, will discuss it with your account lead, and reply by Thursday; add it to the MoM",
              "Offer 10% to calm things down",
              "Refuse because the contract is fixed-price",
              "Ignore it and close the call",
            ],
            correctIndex: 0,
            explanation: "Commercial decisions need authority. A clear, dated follow-up in writing shows respect.",
          },
        ],
      },
    },
    {
      id: "pma-mom-follow-up-24h",
      moduleId: "pma-meetings",
      trackId: "pm",
      title: "Minutes of meeting and follow-up within 24h",
      summary:
        "The minutes of meeting (MoM) email is the real output of a client call. Memories fade within a day, and a client in another time zone may have joined tired at the end of their evening. If decisions and actions are not in writing quickly, they get reopened, forgotten, or remembered differently. A change request agreed on Tuesday and disputed three weeks later is a typical result of a missing MoM.\n\nThat is why the MoM goes out within 24 hours, ideally the same day. Keep it short and scannable. A good structure: a clear subject line with project, meeting and date; attendees; a one-line status; decisions made; action items in a table with owner and due date; open questions or items pending approval; next meeting date in the client's time zone; and a line asking for corrections by a set date. Link the slides, recording or status doc instead of pasting them in.\n\nStep by step: take notes in the agenda during the call, marking D for decisions and A for actions. Right after the call, spend ten minutes turning them into the template in your team's SOP below. Check names, dates and numbers against the transcript if you recorded. Send to all attendees, CC whoever your SOP says, and save it in the project folder. Then put the actions into Jira or your tracker so they are followed up.\n\nCommon mistakes: sending a transcript or a long narrative instead of minutes, writing things nobody agreed (\"client approved the design\" when they said \"looks nice\"), vague owners like \"team\", and sending it three days later. Another one is staying silent when the client replies with a correction. Reply, fix the record, and confirm the change.\n\nOur MoM template, email format and signature are in your team's SOP below.",
      level: "advanced",
      estMinutes: 40,
      isMilestone: true,
      webRefs: [
        { label: "Asana: Meeting Notes Tips: How to Take Notes & Track Actions", url: "https://asana.com/resources/meeting-notes-tips", kind: "docs", verifiedAt: "2026-10-02T10:06:59Z" },
        { label: "Asana: Free Meeting Minutes Template (Examples + Tips)", url: "https://asana.com/templates/meeting-minutes", kind: "article", verifiedAt: "2026-10-02T10:07:03Z" },
        { label: "ProjectManager: Meeting Minutes Template", url: "https://www.projectmanager.com/templates/meeting-minutes-template", kind: "article", verifiedAt: "2026-10-02T09:38:50Z" },
      ],
      video: {
        title: "How to write meeting minutes LIKE A PRO [With meeting minutes example!]",
        channel: "Emelie Lindström - Productivity & Work Skills",
        url: "https://www.youtube.com/watch?v=cST_Q5VpLRw",
        videoId: "cST_Q5VpLRw",
        verifiedAt: "2026-10-02T09:35:55Z",
      },
      alternateVideos: [
        {
          title: "How To Write a Follow Up Email After a Meeting | Mindmaven",
          channel: "Mindmaven",
          url: "https://www.youtube.com/watch?v=s7FK_iCrL1U",
          videoId: "s7FK_iCrL1U",
          verifiedAt: "2026-10-02T09:35:57Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-mom-follow-up-24h-q1",
          prompt: "When should the MoM for a client update go out?",
          options: [
            "Within 24 hours, ideally the same day",
            "Within a week",
            "Before the next meeting",
            "Only if the client asks",
          ],
          correctIndex: 0,
          explanation: "Fast minutes lock in decisions while memories are fresh.",
        },
        {
          id: "pma-mom-follow-up-24h-q2",
          prompt: "Which sections belong in a client MoM? (Select all that apply.)",
          options: [
            "Decisions made",
            "Action items with owner and due date",
            "Open questions or items pending approval",
            "Next meeting date in the client's time zone",
            "A full word-for-word transcript",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 3],
          explanation: "The MoM is a short record of outcomes. Link the transcript or recording if needed; do not paste it.",
        },
        {
          id: "pma-mom-follow-up-24h-q3",
          prompt: "The client said 'the design looks nice'. Can the MoM say 'Client approved the design'?",
          options: [
            "No; record it as positive feedback and, if approval is needed, ask for it explicitly",
            "Yes, that is what they meant",
            "Yes, if the PM thinks so",
            "Only if the designer agrees",
          ],
          correctIndex: 0,
          explanation: "Overstating agreement in minutes causes disputes later. Approval must be explicit.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-mom-follow-up-24h-q4",
          prompt: "Which subject line is best?",
          options: [
            "MoM – Acme Portal weekly update – 14 Oct 2026",
            "Notes",
            "Re: Re: Weekly sync",
            "Important!!",
          ],
          correctIndex: 0,
          explanation: "Project, meeting type and date make it findable and clear.",
        },
        {
          id: "pma-mom-follow-up-24h-q5",
          prompt: "The client replies: 'Small correction, I said we'd decide on Apple Pay next week, not that we'd drop it.' What do you do?",
          options: [
            "Thank them, correct the MoM, reply-all with the corrected line, and update the tracker",
            "Ignore it; the transcript shows otherwise",
            "Argue using the recording",
            "Fix it silently in your own copy",
          ],
          correctIndex: 0,
          explanation: "The MoM is a shared record. Corrections must be visible to everyone who received the original.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-mom-follow-up-24h-q6",
          prompt: "Why end the MoM with 'Please reply with any corrections by Thursday'?",
          options: [
            "It invites the client to confirm or fix the record while it is fresh",
            "It is a polite filler line",
            "It legally binds the client",
            "It replaces the need for action items",
          ],
          correctIndex: 0,
          explanation: "A correction window turns the MoM into an agreed record rather than your private version.",
        },
        {
          id: "pma-mom-follow-up-24h-q7",
          prompt: "A change request (extra admin report) was agreed on the call. What should the MoM say?",
          options: [
            "That it was raised, that Oyelabs will send an estimate and impact by a date, and that work starts only after written approval",
            "That it is approved and in this sprint",
            "Nothing, change requests go in a separate email only",
            "That it is free because it is small",
          ],
          correctIndex: 0,
          explanation: "Record the CR and its next step without implying scope, cost or timing was already agreed.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-mom-follow-up-24h-q8",
          prompt: "After sending the MoM, what else should you do?",
          options: [
            "Put the action items into Jira or the tracker and save the MoM in the project folder",
            "Delete your notes",
            "Nothing else",
            "Send the recording to everyone at the company",
          ],
          correctIndex: 0,
          explanation: "Actions must live where they are tracked, and the MoM where the team can find it.",
        },
        {
          id: "pma-mom-follow-up-24h-q9",
          prompt: "How should action items appear in the MoM?",
          options: [
            "A short table: action, owner, due date",
            "Mixed into paragraphs",
            "As a list of names only",
            "As links to the recording timestamps",
          ],
          correctIndex: 0,
          explanation: "A table is scannable, and each person can find their own tasks quickly.",
        },
        {
          id: "pma-mom-follow-up-24h-q10",
          prompt: "You recorded the call. How should you use the transcript for the MoM?",
          options: [
            "To check names, numbers and decisions in your draft",
            "Paste it in as the MoM",
            "Ignore it",
            "Forward it to the client instead of minutes",
          ],
          correctIndex: 0,
          explanation: "Transcripts are good for checking facts; minutes are the short, agreed summary.",
        },
      ],
      practice: {
        kind: "write",
        variant: "email",
        prompt:
          "Write the MoM email for this call. It must go out within 24 hours. Include a clear subject line, the decisions, the action items with owner and date, open questions, the next meeting, and a request for corrections.",
        context:
          "Your rough notes, Tue 14 Oct 2026, 30-min weekly update, Acme Portal (Laravel admin + React customer app). Attendees: Sarah Lee (Acme, product owner), Tom Reed (Acme, ops), Priya (Oyelabs PM), Raj (Oyelabs tech lead).\n- Status amber: customer app release slips from 17 Oct to 24 Oct, booking API timeouts under load. Raj: fix in progress, load test Thu.\n- D: Sarah OK to release admin panel on 17 Oct as planned, customer app on 24 Oct.\n- Tom asked for an extra CSV export of bookings. Priya: will estimate. Not agreed yet.\n- Apple Pay: Sarah to check with CFO, decide next week.\n- A: Raj load test results to Sarah by Thu 16 Oct. Tom to send sample CSV format by Wed 15 Oct. Priya estimate for CSV export by Fri 17 Oct.\n- Next call Tue 21 Oct 9:00 EDT.",
        wordLimit: 300,
        rubric: [
          { id: "subject", label: "Clear subject line", description: "Subject names the project, meeting and date, e.g. 'MoM – Acme Portal weekly update – 14 Oct 2026'.", weight: 1 },
          { id: "decisions", label: "Decisions recorded accurately", description: "States the agreed split release (admin 17 Oct, customer app 24 Oct) and does not overstate anything as decided.", weight: 2 },
          { id: "actions", label: "Action items with owner and date", description: "Lists all three actions (Raj load test by 16 Oct, Tom CSV sample by 15 Oct, Priya estimate by 17 Oct), each with one owner and a due date, ideally as a short list or table.", weight: 2 },
          { id: "open", label: "Open questions and change request handled", description: "Shows Apple Pay as pending Sarah/CFO decision next week, and the CSV export as a change request to be estimated, not approved.", weight: 2 },
          { id: "close", label: "Next meeting and corrections request", description: "Gives the next call in the client's time zone and asks for corrections by a set date. Polite, short, scannable.", weight: 1 },
        ],
        sampleAnswer:
          "Subject: MoM – Acme Portal weekly update – 14 Oct 2026\n\nHi Sarah, Tom,\n\nThanks for today's call. Summary below.\n\nAttendees: Sarah Lee, Tom Reed (Acme); Priya, Raj (Oyelabs)\nStatus: Amber. The customer app release moves from 17 Oct to 24 Oct because of booking API timeouts under load. A fix is in progress.\n\nDecisions\n- Admin panel releases on 17 Oct as planned.\n- Customer app releases on 24 Oct.\n\nAction items\n- Raj: share load-test results with Sarah – Thu 16 Oct\n- Tom: send a sample CSV format for the bookings export – Wed 15 Oct\n- Priya: send the estimate and timeline impact for the CSV export – Fri 17 Oct\n\nOpen items\n- Apple Pay: Sarah to confirm with the CFO; decision expected next week.\n- Bookings CSV export: new request. We will start only after you approve the estimate.\n\nNext call: Tue 21 Oct, 9:00 EDT.\n\nPlease reply with any corrections by Thu 16 Oct.\n\nBest regards,\nPriya",
      },
      sop: [
        {
          title: "Our MoM template",
          prompt:
            "[Oyelabs SOP – admin to fill] The exact MoM template (sections and order), the subject-line format, who is in To and CC (e.g. account manager, tech lead), where the MoM is saved, and the deadline for sending it after a call.",
        },
        {
          title: "Our client email template and signature",
          prompt:
            "[Oyelabs SOP – admin to fill] The standard opening and closing for client emails, the email signature format (name, role, phone, time zone, company links), and any disclaimer we include.",
        },
      ],
    },
  ],
} satisfies Module;
