import type { Module } from "@/types/curriculum";

export default {
  id: "pma-client",
  trackId: "pm",
  name: "Client management",
  description:
    "Running the client side of an agency project well: kickoff, owning scope and change requests, saying no, bad news, escalations, time zones and cultures, satisfaction check-ins, long-term trust and a clean handover to support.",
  topics: [
    {
      id: "pma-client-onboarding-kickoff",
      moduleId: "pma-client",
      trackId: "pm",
      title: "Client onboarding and kickoff",
      summary:
        "The kickoff is the first time the client sees how Oyelabs works. A US founder who signed for a Laravel and React marketplace has only seen a proposal and a sales call. In the kickoff they decide whether we are organised. Most later problems, such as a disputed feature, a slow approval or a missed demo, can be traced back to something the kickoff never settled.\n\nPrepare before the call. Read the signed proposal or SOW, the estimate and the sales notes. List what is in scope and what is out. Find out who on the client side decides, who approves designs and who pays invoices. If a white-label reseller sits between us and the end client, agree with the reseller who speaks to whom.\n\nRun the call in a fixed order. Introduce people and roles. Restate the goal and how success will be measured. Walk through scope, including what is not included. Show the milestones and the first two weeks in detail. Agree the communication plan: channels, meeting cadence, the hours both sides overlap, and the response time each side can expect. Then list the client's dependencies, like store accounts, API keys, brand assets and test data, each with an owner and a date. Close with action items.\n\nSend the notes and the welcome pack within a day, using your team's SOP below for the checklist and template. Ask the client to confirm the scope summary and the dependency list in writing.\n\nThe common mistake is treating kickoff as a friendly introduction and skipping the boring parts. If you never asked who approves designs, you will find out in week five, when the CEO rejects screens the product manager already signed off.",
      level: "beginner",
      estMinutes: 30,
      webRefs: [
        { label: "Atlassian Team Playbook: Planning Project Kickoff Meetings: Steps & Example Agenda", url: "https://www.atlassian.com/team-playbook/plays/project-kickoff", kind: "docs", verifiedAt: "2026-10-02T09:35:38Z" },
        { label: "The Digital Project Manager: Project Kickoff Guide: 15 Steps For Success In 2026", url: "https://thedigitalprojectmanager.com/project-management/project-kickoff-guide/", kind: "article", verifiedAt: "2026-10-02T10:07:46Z" },
        { label: "ProjectManager: Project Kickoff Meeting: How to Write a Project Kickoff Agenda", url: "https://www.projectmanager.com/blog/write-project-kickoff-meeting", kind: "article", verifiedAt: "2026-10-02T09:38:38Z" },
        { label: "Asana: Project Kickoff Meeting: 10-Step Guide for Success", url: "https://asana.com/resources/project-kickoff-meeting", kind: "article", verifiedAt: "2026-10-02T10:07:04Z" },
      ],
      video: {
        title: "Kickoff Best Practices | How to Run a Client Kickoff Meeting Successfully",
        channel: "The Digital Project Manager",
        url: "https://www.youtube.com/watch?v=4ESb9qoXVyo",
        videoId: "4ESb9qoXVyo",
        verifiedAt: "2026-10-02T09:35:54Z",
      },
      alternateVideos: [
        {
          title: "Project Kickoff Meetings | 5-Minute Guide",
          channel: "TeamGantt",
          url: "https://www.youtube.com/watch?v=Bu84BEkN2e4",
          videoId: "Bu84BEkN2e4",
          verifiedAt: "2026-10-02T09:35:57Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-client-onboarding-kickoff-q1",
          prompt: "You are preparing the kickoff for a React web app for a UK retailer. Which documents should you read before the call?",
          options: [
            "The signed proposal or SOW, the estimate and the sales handover notes",
            "Only the client's website",
            "Only the developers' task board",
            "Nothing: the kickoff is for listening",
          ],
          correctIndex: 0,
          explanation: "The SOW and estimate define what was sold. Sales notes tell you what was promised in conversation. You cannot recap scope or spot gaps without them.",
        },
        {
          id: "pma-client-onboarding-kickoff-q2",
          prompt: "Which of these should be agreed in the kickoff? (Select all that apply.)",
          options: [
            "Who on the client side approves designs and accepts releases",
            "Meeting cadence and the hours both sides are online",
            "Client dependencies such as store accounts and API keys, with owners and dates",
            "The exact database table names",
            "The developers' personal phone numbers",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Approvers, communication rhythm and client dependencies are what block projects later. Table names are a team decision, and personal numbers are not a client channel.",
        },
        {
          id: "pma-client-onboarding-kickoff-q3",
          prompt: "A white-label reseller sold your Laravel app to their end client. In the kickoff, the end client asks to message your developers directly on WhatsApp. What is the best response?",
          options: [
            "Agree a channel plan with the reseller first, and keep communication through the agreed channel",
            "Say yes, it will be faster",
            "Share the developers' numbers but ask them not to reply",
            "Ignore the request",
          ],
          correctIndex: 0,
          explanation: "In a white-label deal the reseller owns the end-client relationship. Direct developer chats bypass both the reseller and the PM, so scope and promises leak out of control.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-client-onboarding-kickoff-q4",
          prompt: "Why should the kickoff walk through what is out of scope, not only what is in?",
          options: [
            "Clients often assume features they never asked for are included, and saying it early prevents disputes later",
            "To make the proposal look smaller",
            "Because it is a legal requirement",
            "It is not useful; only scope matters",
          ],
          correctIndex: 0,
          explanation: "Assumed features like an admin panel, push notifications or multi-language support cause most scope arguments. Naming exclusions early is cheap.",
        },
        {
          id: "pma-client-onboarding-kickoff-q5",
          prompt: "The kickoff went well, but the client says, \"No need to send notes, we all heard it.\" What do you do?",
          options: [
            "Send a short written summary anyway and ask them to confirm scope and dependencies",
            "Skip the notes to respect their wish",
            "Send notes only to your own team",
            "Record the call and send nothing else",
          ],
          correctIndex: 0,
          explanation: "Memories differ within days. A short written summary that the client confirms is your reference when scope or dates are questioned.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-client-onboarding-kickoff-q6",
          prompt: "Two weeks after kickoff, the team is blocked because the client has not shared App Store Connect access. What kickoff step would have prevented this?",
          options: [
            "Listing client dependencies with an owner and a due date, then tracking them",
            "Inviting more developers to the kickoff",
            "Making the kickoff longer",
            "Skipping the communication plan",
          ],
          correctIndex: 0,
          explanation: "Dependencies only get done when someone owns them by a date. A tracked list turns \"we'll send it\" into an action you can chase.",
        },
      ],
      practice: {
        kind: "rank",
        prompt: "You are running the kickoff for a Laravel and React booking platform for an Australian clinic group. Put the agenda items in the order you would run them.",
        items: [
          { id: "intro", label: "Introductions: who is who, roles and decision makers on both sides" },
          { id: "goals", label: "Project goals and how success will be measured" },
          { id: "scope", label: "Scope recap: what is in, and what is explicitly out" },
          { id: "plan", label: "Delivery approach, milestones and the first two weeks in detail" },
          { id: "comms", label: "Communication plan: channels, meeting cadence, overlap hours, response times" },
          { id: "deps", label: "Client dependencies, risks and assumptions, each with an owner" },
          { id: "next", label: "Action items, owners and dates, and when notes will arrive" },
        ],
        correctOrder: ["intro", "goals", "scope", "plan", "comms", "deps", "next"],
        explanation: "People first, then why (goals), then what (scope), then how and when (plan), then how we talk (comms). Dependencies and risks need the plan as context. Always close on actions so the call ends with owners.",
      },
      sop: [
        {
          title: "Our kickoff checklist and client welcome pack",
          prompt: "[Oyelabs SOP – admin to fill] The internal pre-kickoff checklist (documents to read, sales handover), the standard kickoff agenda and deck, what goes in the client welcome pack (contacts, channels, cadence, tools, access requests), and when it must be sent.",
        },
      ],
    },
    {
      id: "pma-expectations-scope-change-requests",
      moduleId: "pma-client",
      trackId: "pm",
      title: "Expectations, scope and change requests",
      summary:
        "Scope creep rarely arrives as a big request. It arrives as \"one small thing\": an extra filter, a second login method, a tweak to the checkout. On a fixed-bid React Native app each small thing is unpaid work. Ten of them can wipe out the margin and push the release. On a time-and-materials (T&M) project the money is less risky, but the date still slips, and the client is surprised by the invoice.\n\nYour job is to own the scope conversation, not to refuse change. Change is normal. Clients learn as they see the product. The goal is that every change is visible, sized and agreed before the team builds it.\n\nThe process is simple. First, write the request down in the client's words. Second, check it against the signed scope. Is it new, or is it a clarification of something already included? Third, ask the tech lead to size it in hours and to name the impact on dates, testing and other features. Fourth, send the client a change request with the description, cost, schedule impact and options: add it now, swap it for something else, or move it to phase two. Fifth, start work only after written approval. Then update the plan and the backlog. Your team's SOP below gives the change-request template and the billing rules.\n\nSetting expectations early makes this easier. In kickoff, explain how changes work, so the first CR is not a surprise.\n\nThe common mistake is saying \"sure, we'll look at it\" in a meeting. The client hears yes. The developer starts building. Two weeks later you are asking for money for work the client thinks was agreed.",
      level: "intermediate",
      estMinutes: 40,
      webRefs: [
        { label: "Atlassian Team Playbook: Project Poster Template to Guide Your Work", url: "https://www.atlassian.com/team-playbook/plays/project-poster", kind: "docs", verifiedAt: "2026-10-02T09:35:21Z" },
        { label: "TeamGantt: What Is Scope Creep and How to Avoid It", url: "https://www.teamgantt.com/project-management-guide/taming-scope-creep", kind: "article", verifiedAt: "2026-10-02T09:35:33Z" },
        { label: "ProjectManager: Change Request Form (Free Word Template)", url: "https://www.projectmanager.com/templates/change-request-form", kind: "article", verifiedAt: "2026-10-02T09:39:03Z" },
      ],
      video: {
        title: "How to Control Change Requests on Projects - Project Management Training",
        channel: "ProjectManager",
        url: "https://www.youtube.com/watch?v=WWdgFFVkPgA",
        videoId: "WWdgFFVkPgA",
        verifiedAt: "2026-10-02T09:35:57Z",
      },
      alternateVideos: [
        {
          title: "Managing Change: How To Manage Project Scope Change",
          channel: "ProjectManager",
          url: "https://www.youtube.com/watch?v=tMR7jVefRIQ",
          videoId: "tMR7jVefRIQ",
          verifiedAt: "2026-10-02T09:35:59Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-expectations-scope-change-requests-q1",
          prompt: "During a demo of a fixed-bid Laravel portal, the client says, \"Can we also export these reports to PDF? Should be quick.\" What is the best reply in the meeting?",
          options: [
            "\"Good idea. I'll check it against scope with the team and send you the effort and options by Thursday.\"",
            "\"Sure, we'll add it.\"",
            "\"No, that's out of scope.\"",
            "\"The developer can do it tonight.\"",
          ],
          correctIndex: 0,
          explanation: "Acknowledge, don't commit, and give a date for the answer. \"Sure\" is heard as a yes, and a flat no closes a conversation that may be a paid change.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-expectations-scope-change-requests-q2",
          prompt: "What should a change request sent to the client contain? (Select all that apply.)",
          options: [
            "A description of the change in plain words",
            "Cost or hours, and the schedule impact",
            "Options: add now, swap for another item, or defer to a later phase",
            "A request for written approval before work starts",
            "The developer's hourly salary",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 3],
          explanation: "The client needs to know what, how much, what it does to the date, and what their choices are. Internal salaries are never shared.",
        },
        {
          id: "pma-expectations-scope-change-requests-q3",
          prompt: "The client says the new \"forgot password\" flow is a change request. The SOW lists \"user authentication including password reset\". What is it?",
          options: [
            "A clarification of existing scope, so it is included",
            "A paid change request",
            "Out of scope entirely",
            "Something to defer to phase two",
          ],
          correctIndex: 0,
          explanation: "Always check the request against the signed scope. Charging for something already included damages trust fast.",
        },
        {
          id: "pma-expectations-scope-change-requests-q4",
          prompt: "Why does scope creep hurt a fixed-bid project more than a T&M project?",
          options: [
            "On fixed bid, unpaid extra work comes straight out of the agency's margin",
            "T&M projects never change",
            "Fixed-bid clients can't request changes",
            "It doesn't: they are the same",
          ],
          correctIndex: 0,
          explanation: "On T&M the client pays for extra hours, though the date still moves. On fixed bid, every unapproved extra is free work.",
        },
        {
          id: "pma-expectations-scope-change-requests-q5",
          prompt: "A developer quietly added a small feature the client asked for in a Slack message. What is the main risk?",
          options: [
            "It sets a precedent that unapproved requests get built, and the time is unplanned and untested",
            "None: the client is happy",
            "The developer will get bored",
            "The feature will be too good",
          ],
          correctIndex: 0,
          explanation: "Side-channel changes skip sizing, testing and approval. The next ask will come the same way, and the plan stops being true.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-expectations-scope-change-requests-q6",
          prompt: "When is the best moment to explain to a client how change requests work?",
          options: ["At kickoff, before any change comes up", "At the first change request", "At final invoice", "Never; it sounds negative"],
          correctIndex: 0,
          explanation: "Explaining the process up front makes the first CR feel routine instead of a surprise charge.",
        },
        {
          id: "pma-expectations-scope-change-requests-q7",
          prompt: "The client approves a change request by email. What must you do next? (Select all that apply.)",
          options: [
            "Update the plan and milestone dates",
            "Add the work to the backlog with acceptance criteria",
            "Tell the team and the client what moved",
            "Keep the old plan so the dates look better",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "An approved change only helps if the plan, backlog and everyone's expectations change with it.",
        },
        {
          id: "pma-expectations-scope-change-requests-q8",
          prompt: "The client wants a new feature but cannot increase budget or move the date on a fixed-bid project. What is the most useful option to offer?",
          options: [
            "A swap: drop or defer an item of similar size to make room",
            "Ask the team to work weekends for free",
            "Add it and hope it fits",
            "Refuse to discuss it",
          ],
          correctIndex: 0,
          explanation: "When money and time are fixed, scope is the only lever. A like-for-like swap keeps the deal fair.",
        },
        {
          id: "pma-expectations-scope-change-requests-q9",
          prompt: "Many tiny changes each take one to two hours. The client says they are too small to need a CR. What is a good approach?",
          options: [
            "Log them all, and bundle them into a periodic CR or count them against an agreed small-change allowance",
            "Do them free forever",
            "Write a full CR for every two-hour item and stop work until signed",
            "Ignore them",
          ],
          correctIndex: 0,
          explanation: "Small changes add up. Bundling keeps the paperwork light but keeps the total visible and agreed.",
          isEdgeCaseOrInterviewQuestion: true,
        },
      ],
      practice: {
        kind: "calculate",
        prompt: "A US client asks to add Apple Pay to the checkout of a fixed-bid React Native app with a Laravel API. Your tech lead sized the change below. Rates are illustrative; use your rate card from the SOP in real life. Work out the numbers for the change request.",
        table: {
          columns: ["Work item", "Hours", "Rate (USD/h)"],
          rows: [
            ["Apple Pay in the app checkout", "32", "40"],
            ["Laravel payment API changes", "18", "40"],
            ["QA and regression testing", "10", "35"],
          ],
        },
        fields: [
          { id: "hours", label: "Total effort", unit: "h", answer: 60, tolerance: 0, expression: "T[0][1] + T[1][1] + T[2][1]" },
          { id: "cost", label: "Change request cost", unit: "USD", answer: 2350, tolerance: 1, expression: "T[0][1]*T[0][2] + T[1][1]*T[1][2] + T[2][1]*T[2][2]" },
          { id: "days", label: "Schedule impact if one developer does it at 6 focused hours a day", unit: "days", answer: 10, tolerance: 0.1, expression: "(T[0][1] + T[1][1] + T[2][1]) / 6" },
        ],
        explanation: "Total hours 32 + 18 + 10 = 60. Cost 32×40 + 18×40 + 10×35 = 1,280 + 720 + 350 = 2,350 USD. At 6 focused hours a day, 60 hours is 10 working days, so the release moves unless the client swaps something out.",
      },
      sop: [
        {
          title: "Our change-request process and billing rules",
          prompt: "[Oyelabs SOP – admin to fill] The CR template and where CRs are logged, who sizes and who approves internally, the rate card and minimum billing unit for CRs, any small-change allowance, and how fixed-bid vs T&M changes are billed.",
        },
      ],
    },
    {
      id: "pma-saying-no-not-now",
      moduleId: "pma-client",
      trackId: "pm",
      title: "Saying no or not now",
      summary:
        "A PM who always says yes is not being helpful. They are borrowing against the release date. When a UK client asks for a live chat feature a week before launch, a yes means one of three things. Quality drops, the date slips, or the team burns out. The client pays for all three later.\n\nSaying no well is a skill, and most of the time the answer is really \"not now\" or \"yes, if\". You are not refusing the client. You are showing them the trade-off so they can choose.\n\nUse a simple structure. First, show you understand why they want it. Second, state the constraint plainly: the date, the budget or the risk. Third, give options. They can do it after launch in the next sprint. They can swap it for something of similar size. Or they can add it as a paid change and move the date. Fourth, recommend one option and say why. Fifth, ask for a decision by a date. Keep the tone warm and the facts firm.\n\nSome requests deserve a real no. These include anything that breaks App Store rules, skips security work, or asks the team to cut testing before a release. Say no clearly and explain the risk in business terms, such as a store rejection or a data leak.\n\nThe common mistakes are opposites. Some PMs give a vague \"we'll try\", which the client hears as yes. Others give a cold \"out of scope\" with no options, which makes the client feel blocked. Both damage trust. A clear \"not now, and here's when\" usually builds it.",
      level: "intermediate",
      estMinutes: 35,
      webRefs: [
        { label: "Atlassian Team Playbook: Project Trade-Off Analysis", url: "https://www.atlassian.com/team-playbook/plays/trade-offs", kind: "docs", verifiedAt: "2026-10-02T09:35:28Z" },
        { label: "Harvard Business Review: How to Say No to Taking on More Work", url: "https://hbr.org/2015/12/how-to-say-no-to-taking-on-more-work", kind: "article", verifiedAt: "2026-10-02T09:35:37Z" },
        { label: "ProjectManager: What Is Stakeholder Management?", url: "https://www.projectmanager.com/guides/stakeholder-management", kind: "article", verifiedAt: "2026-10-02T09:38:55Z" },
      ],
      video: {
        title: "When to Push Back with Project Stakeholders - Leadership Training",
        channel: "ProjectManager",
        url: "https://www.youtube.com/watch?v=FEUTaNgqvgk",
        videoId: "FEUTaNgqvgk",
        verifiedAt: "2026-10-02T09:35:55Z",
      },
      alternateVideos: [
        {
          title: "How to Say No to Bad Clients",
          channel: "Michael Janda",
          url: "https://www.youtube.com/watch?v=n_M3AVPuf1c",
          videoId: "n_M3AVPuf1c",
          verifiedAt: "2026-10-02T09:35:56Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-saying-no-not-now-q1",
          prompt: "A client asks for a new dashboard widget four days before a fixed release. Which reply is best?",
          options: [
            "Explain the release risk, offer to add it in the first sprint after launch, and ask them to confirm",
            "\"We'll try our best to squeeze it in.\"",
            "\"That's out of scope.\" and nothing more",
            "Agree and ask the team to stay late",
          ],
          correctIndex: 0,
          explanation: "\"Not now, and here's when\" protects the release and still gives the client a path. \"We'll try\" is heard as yes.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-saying-no-not-now-q2",
          prompt: "Which elements make a \"no\" constructive? (Select all that apply.)",
          options: [
            "Showing you understand why they want it",
            "Stating the real constraint: date, budget or risk",
            "Offering options and recommending one",
            "Asking for a decision by a date",
            "Blaming the development team",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 3],
          explanation: "Empathy, the constraint, options and a decision request turn a refusal into a choice. Blaming the team makes Oyelabs look disorganised.",
        },
        {
          id: "pma-saying-no-not-now-q3",
          prompt: "The client asks the team to skip QA so a React web app can go live tomorrow. What should you do?",
          options: [
            "Say no clearly and explain the business risk, then offer the fastest safe option such as a reduced-scope release",
            "Agree, because the client is paying",
            "Agree but secretly test anyway and slip the date",
            "Escalate to your manager without replying",
          ],
          correctIndex: 0,
          explanation: "Some requests need a firm no. Explain the risk in business terms (broken payments, bad reviews) and give a safe alternative.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-saying-no-not-now-q4",
          prompt: "Why does a vague \"we'll see\" cause trouble later?",
          options: [
            "The client usually hears it as a yes and plans around it",
            "It is too short",
            "It sounds too formal",
            "It forces a change request",
          ],
          correctIndex: 0,
          explanation: "Ambiguity defaults to the hopeful reading. Be clear about what will and will not happen.",
        },
        {
          id: "pma-saying-no-not-now-q5",
          prompt: "On a fixed-bid project, money and date are fixed. The client insists on a new feature. Which option keeps the project healthy?",
          options: [
            "Offer a swap with a backlog item of similar size that the client cares less about",
            "Add it with no other change",
            "Reduce testing to make time",
            "Refuse to discuss scope",
          ],
          correctIndex: 0,
          explanation: "When time and budget are fixed, scope is the lever. A swap respects the contract and the client's priorities.",
        },
        {
          id: "pma-saying-no-not-now-q6",
          prompt: "Who should normally deliver a \"not now\" to the client?",
          options: [
            "The PM, with the tech lead's input on effort and risk",
            "A junior developer in a chat",
            "The finance team",
            "Nobody; let the request fade",
          ],
          correctIndex: 0,
          explanation: "The PM owns the client conversation. The tech lead provides the facts behind it.",
        },
        {
          id: "pma-saying-no-not-now-q7",
          prompt: "A white-label reseller asks you to promise their end client a feature you have not sized. What is the right move?",
          options: [
            "Tell the reseller you will size it first, and give them a date for an answer they can pass on",
            "Promise it to keep the reseller happy",
            "Contact the end client directly to say no",
            "Ignore the reseller",
          ],
          correctIndex: 0,
          explanation: "Never promise unsized work, and respect the reseller's ownership of the end client. Give them a dated answer.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-saying-no-not-now-q8",
          prompt: "What tone works best when you push back on a client?",
          options: ["Warm in tone and firm on facts", "Apologetic and uncertain", "Cold and contractual", "Humorous to soften it"],
          correctIndex: 0,
          explanation: "Warmth keeps the relationship; firm facts keep the decision clear.",
        },
        {
          id: "pma-saying-no-not-now-q9",
          prompt: "Which are good ways to phrase a \"not now\"? (Select all that apply.)",
          options: [
            "\"We can add this in the first sprint after launch on 14 June.\"",
            "\"If we add this now, launch moves by a week. Which matters more to you?\"",
            "\"We can swap it for the reports page, which is the same size.\"",
            "\"That's impossible.\"",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Good phrasing gives a when, a trade-off or a swap. \"Impossible\" is rarely true and closes the conversation.",
        },
      ],
      practice: {
        kind: "write",
        variant: "email",
        prompt: "Reply to the client email below. You cannot add the feature before launch without risking the date. Say \"not now\" professionally: acknowledge the request, explain the constraint, give options with a recommendation, and ask for a decision by a date.",
        context: "From: Sarah Mitchell (COO, BrightCare, UK)\nSubject: Live chat before launch\n\nHi,\nOur board saw the app yesterday and loved it. They'd really like a live chat with our support staff in the patient app before we go live next Friday. It should be a small addition, right? Can you confirm it'll be in?\nThanks,\nSarah",
        wordLimit: 220,
        rubric: [
          { id: "ack", label: "Acknowledges the request", description: "Shows the PM understands why the board wants live chat and responds positively to the idea.", weight: 1 },
          { id: "constraint", label: "States the constraint clearly", description: "Explains plainly that adding chat now would risk next Friday's launch (build, testing, store review), without jargon or blame.", weight: 1.5 },
          { id: "options", label: "Gives options and recommends one", description: "Offers at least two options (e.g. add after launch in the next sprint, add now as a change with a new date) and recommends one with a reason.", weight: 2 },
          { id: "ask", label: "Clear ask with a deadline", description: "Asks Sarah for a decision by a specific day so the team can plan.", weight: 1 },
          { id: "tone", label: "Professional, warm tone", description: "Polite, confident, concise; no vague 'we'll try' and no flat refusal.", weight: 1 },
        ],
        sampleAnswer: "Subject: RE: Live chat before launch\n\nHi Sarah,\n\nGreat to hear the board liked the app, and live chat is a sensible next step for patients.\n\nAdding it before next Friday would put the launch at risk. Chat needs a new screen, a connection to your support team's inbox, and full testing on iOS and Android. It also has to pass Apple's review again.\n\nTwo options:\n1. Launch on Friday as planned, and build live chat in the first sprint after launch. It would be live by 28 June.\n2. Add live chat now as a change request. The launch would move to around 21 June, and we'd send you the cost by Tuesday.\n\nI recommend option 1. Patients get the app on time, and chat follows three weeks later without risk to the launch.\n\nCould you let me know your choice by Monday 5 pm UK time? Then we can plan the next sprint.\n\nBest regards,\nPriya",
      },
    },
    {
      id: "pma-time-zones-cultures",
      moduleId: "pma-client",
      trackId: "pm",
      title: "Time zones and cultures",
      summary:
        "Most Oyelabs clients are in the US, UK, Europe or Australia. The team works from India. That means every client project runs on a small window of shared hours, and on different habits about directness, silence and deadlines. A question asked at the wrong time can cost a full day. A blunt message can read as rude, and a polite hint can be missed completely.\n\nStart with the clock. Work out the overlap hours for each client and put them in the kickoff notes. Use the overlap for things that need a live answer: decisions, demos and blockers. Everything else should be asynchronous, meaning it does not need both sides online at once. Write status updates, questions and handovers so the client can act on them while you sleep. Always say which time zone a date or time is in, and watch for daylight saving changes in March, October and November.\n\nPlan the daily handoff. Before your day ends, send the client what was done, what you need from them, and what happens next. Then their morning is productive, and you wake up to answers instead of questions.\n\nCulture matters too. Some clients are very direct and expect the same. Others will say \"interesting idea\" when they mean no. Some read silence as agreement; some read it as a problem. Ask early how they like to receive bad news and how fast they expect replies. Write in simple English with short sentences, because many clients and team members are not native speakers. Follow your team's SOP below for overlap rules and response times.\n\nThe common mistake is assuming the client works like you. A \"yes\" from a team member may mean \"I heard you\", not \"I agree and it will be done\". Confirm in writing.",
      level: "intermediate",
      estMinutes: 35,
      webRefs: [
        { label: "Asana: Synchronous vs Asynchronous Communication", url: "https://asana.com/resources/synchronous-vs-asynchronous-communication", kind: "docs", verifiedAt: "2026-10-02T10:07:06Z" },
        { label: "Asana: Why Managers Need Cultural Intelligence", url: "https://asana.com/resources/cultural-intelligence", kind: "docs", verifiedAt: "2026-10-02T10:07:49Z" },
        { label: "Harvard Business Review: Navigating the Cultural Minefield", url: "https://hbr.org/2014/05/navigating-the-cultural-minefield", kind: "article", verifiedAt: "2026-10-02T09:35:46Z" },
        { label: "Asana: 7 Tips To Help Manage Your Distributed Team", url: "https://asana.com/resources/managing-distributed-teams", kind: "article", verifiedAt: "2026-10-02T10:06:44Z" },
      ],
      video: {
        title: "4 Rules to Manage Remote Teams in Different Time Zones [GIVEAWAY FINISHED]",
        channel: "ScrumMastered",
        url: "https://www.youtube.com/watch?v=Yr1pOCvcfW4",
        videoId: "Yr1pOCvcfW4",
        verifiedAt: "2026-10-02T09:35:56Z",
      },
      alternateVideos: [
        {
          title: "Managing Cross Cultural Remote Teams | Ricardo Fernandez | TEDxIESEBarcelona",
          channel: "TEDx Talks",
          url: "https://www.youtube.com/watch?v=QIoAkFpN8wQ",
          videoId: "QIoAkFpN8wQ",
          verifiedAt: "2026-10-02T09:35:56Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-time-zones-cultures-q1",
          prompt: "Your US client in New York has almost no overlap with your team in India. Which work should use the small overlap window?",
          options: [
            "Decisions, demos and urgent blockers that need a live conversation",
            "Routine status updates",
            "Reading documents together",
            "Nothing; avoid live calls entirely",
          ],
          correctIndex: 0,
          explanation: "Shared hours are scarce. Spend them on things that need real-time discussion and move everything else to written, asynchronous updates.",
        },
        {
          id: "pma-time-zones-cultures-q2",
          prompt: "Which habits help a project run across time zones? (Select all that apply.)",
          options: [
            "An end-of-day handoff note: done, needed from the client, next",
            "Writing every date and time with its time zone",
            "Checking daylight saving dates for the client's country",
            "Waiting for the next call to ask blocking questions",
            "Assuming the client works your hours",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Clear handoffs, explicit time zones and DST awareness keep work moving. Waiting for calls wastes days.",
        },
        {
          id: "pma-time-zones-cultures-q3",
          prompt: "A UK client's meeting is set for \"3 pm\" in an email. In late March the meeting suddenly seems to be an hour off. What most likely happened?",
          options: [
            "The UK switched to summer time, changing the offset to India",
            "The client made a typo",
            "Teams has a bug",
            "India changed its time zone",
          ],
          correctIndex: 0,
          explanation: "India has no daylight saving, but the UK, US, EU and parts of Australia do, on different dates. The overlap moves twice a year.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-time-zones-cultures-q4",
          prompt: "An Australian client replies to your proposal with \"Interesting, we'll think about it.\" Nothing follows for a week. What is the best next step?",
          options: [
            "Follow up politely and ask a direct question about their concerns or decision date",
            "Treat it as approval and start work",
            "Treat it as a rejection and close the project",
            "Wait silently for another month",
          ],
          correctIndex: 0,
          explanation: "Polite phrases can hide doubts. Neither assume yes nor no; ask a clear, friendly question.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-time-zones-cultures-q5",
          prompt: "A developer says \"yes, okay\" when you ask if the API will be ready tomorrow. Why should you confirm further?",
          options: [
            "\"Yes\" may mean \"I heard you\" rather than \"I commit to this date\"",
            "Developers always lie about dates",
            "It is not necessary",
            "Because the client asked",
          ],
          correctIndex: 0,
          explanation: "In many cultures saying no to a manager is uncomfortable. Ask an open question, like \"what could stop it being ready?\"",
        },
        {
          id: "pma-time-zones-cultures-q6",
          prompt: "What does asynchronous communication mean on a client project?",
          options: [
            "Messages and updates that do not need both sides online at the same time",
            "Communication that is always slow",
            "Only video calls",
            "Messages sent without a subject",
          ],
          correctIndex: 0,
          explanation: "Async work (written updates, recorded demos, tickets) lets each side act in its own day.",
        },
        {
          id: "pma-time-zones-cultures-q7",
          prompt: "How should you write for a client who is not a native English speaker?",
          options: [
            "Short sentences, simple words, no idioms, one request per paragraph",
            "Long formal paragraphs",
            "Lots of slang to sound friendly",
            "Abbreviations to save time",
          ],
          correctIndex: 0,
          explanation: "Plain English is easier to read and to translate. Idioms like \"ballpark\" or \"circle back\" often confuse readers.",
        },
        {
          id: "pma-time-zones-cultures-q8",
          prompt: "A German client gives very direct feedback: \"This design is wrong.\" A newer team member is upset. How do you handle it?",
          options: [
            "Explain that directness is normal in that business culture, and focus the team on the specific feedback",
            "Ask the client to be nicer",
            "Ignore the feedback",
            "Reply equally bluntly",
          ],
          correctIndex: 0,
          explanation: "Direct feedback is often a sign of engagement, not anger. Translate it into concrete changes.",
        },
        {
          id: "pma-time-zones-cultures-q9",
          prompt: "Which are good ways to protect the team from late-night client calls? (Select all that apply.)",
          options: [
            "Agree fixed meeting slots in the overlap window at kickoff",
            "Rotate late calls instead of one person always taking them",
            "Use recorded demos for non-decision updates",
            "Accept every ad-hoc call at any hour",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Fixed slots, rotation and recordings keep the client served without burning out one person.",
          isEdgeCaseOrInterviewQuestion: true,
        },
      ],
      practice: {
        kind: "calculate",
        prompt: "Your team in India works 10:00 to 19:00 IST (UTC+5:30). Work out the overlap with two clients in summer. Times are on a 24-hour decimal clock (17.5 means 17:30). Hint: convert the client's start time to IST by adding the difference in UTC offsets.",
        table: {
          columns: ["Location", "Start (local)", "End (local)", "UTC offset (h)"],
          rows: [
            ["Oyelabs team, India", "10", "19", "5.5"],
            ["Client, London (summer)", "9", "17.5", "1"],
            ["Client, New York (summer)", "9", "17.5", "-4"],
          ],
        },
        fields: [
          { id: "london", label: "Overlap with London", unit: "h", answer: 5.5, tolerance: 0.01, expression: "T[0][2] - (T[1][1] + T[0][3] - T[1][3])" },
          { id: "ny", label: "Overlap with New York", unit: "h", answer: 0.5, tolerance: 0.01, expression: "T[0][2] - (T[2][1] + T[0][3] - T[2][3])" },
        ],
        explanation: "London 09:00 is 13:30 IST (5.5 − 1 = 4.5 h ahead), so the overlap runs 13:30–19:00: 5.5 hours. New York 09:00 is 18:30 IST (5.5 − (−4) = 9.5 h ahead), so the overlap is only 18:30–19:00: half an hour. That is why US projects need strong async handoffs and an agreed late slot for decisions.",
      },
      sop: [
        {
          title: "Our time-zone overlap rules and response times",
          prompt: "[Oyelabs SOP – admin to fill] Minimum overlap hours the PM must keep per client region, who covers late or early calls and how they are compensated, expected response times to client messages (in and out of overlap), and the end-of-day handoff format.",
        },
      ],
    },
    {
      id: "pma-satisfaction-check-ins",
      moduleId: "pma-client",
      trackId: "pm",
      title: "Client satisfaction check-ins",
      summary:
        "Most unhappy clients do not complain. They go quiet, approve things slowly, and then do not renew the maintenance contract. By the time a client says \"we're not happy\", the problem is weeks old. A satisfaction check-in is how you find out early, while it is still cheap to fix.\n\nA check-in is different from a status meeting. The status meeting is about the project. The check-in is about the relationship: how the client feels about working with Oyelabs. Keep it short and separate. Run one at key moments: after the first sprint, after each major release, and at a regular rhythm set in your team's SOP below.\n\nUse two tools together. The first is a short survey. A common choice is Net Promoter Score (NPS): \"How likely are you to recommend us, from 0 to 10?\" Scores of 9–10 are promoters, 7–8 are passives, and 0–6 are detractors. NPS is the percentage of promoters minus the percentage of detractors. Add one open question: \"What is one thing we should do differently?\" The second tool is a 15-minute conversation, ideally with someone senior from Oyelabs. Ask open questions. Listen more than you talk.\n\nThen act. Thank the client, tell them what you will change, and show the change in the next weeks. A survey with no visible action makes things worse, because the client learns that feedback is ignored.\n\nThe common mistakes are surveying only at the end of the project, and treating a 7 as good. A 7 is a passive. Passives leave quietly when a cheaper agency calls. Ask what would make it a 9.",
      level: "intermediate",
      estMinutes: 30,
      webRefs: [
        { label: "Microsoft Support: Microsoft Forms help & learning", url: "https://support.microsoft.com/en-us/forms/", kind: "docs", verifiedAt: "2026-10-02T10:06:42Z" },
        { label: "Qualtrics: Net Promoter Score (NPS): The Ultimate Guide", url: "https://www.qualtrics.com/articles/customer-experience/net-promoter-score/", kind: "article", verifiedAt: "2026-10-02T09:35:34Z" },
        { label: "Atlassian Team Playbook: Sprint Retrospective: How to Hold an Effective Meeting", url: "https://www.atlassian.com/team-playbook/plays/retrospective", kind: "article", verifiedAt: "2026-10-02T09:35:20Z" },
      ],
      video: {
        title: "Customer Satisfaction Survey: Proven Tips for HONEST Answers",
        channel: "HubSpot Marketing",
        url: "https://www.youtube.com/watch?v=Oivm_UFVj08",
        videoId: "Oivm_UFVj08",
        verifiedAt: "2026-10-02T09:35:55Z",
      },
      alternateVideos: [
        {
          title: "How to Measure Customer Satisfaction like a Pro?",
          channel: "SurveySparrow",
          url: "https://www.youtube.com/watch?v=WSJzNtdMqkk",
          videoId: "WSJzNtdMqkk",
          verifiedAt: "2026-10-02T09:35:56Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-satisfaction-check-ins-q1",
          prompt: "How is a satisfaction check-in different from a weekly status meeting?",
          options: [
            "It is about how the client feels about working with us, not about task progress",
            "It is longer and covers every ticket",
            "It is only for internal staff",
            "There is no difference",
          ],
          correctIndex: 0,
          explanation: "Status covers the project; the check-in covers the relationship. Mixing them means the relationship questions get skipped.",
        },
        {
          id: "pma-satisfaction-check-ins-q2",
          prompt: "A client scores you 7 out of 10 on \"How likely are you to recommend us?\". How should you read it?",
          options: [
            "As a passive: not unhappy, but not loyal, so ask what would make it a 9",
            "As a strong result",
            "As a detractor needing escalation",
            "As meaningless",
          ],
          correctIndex: 0,
          explanation: "In NPS, 7–8 are passives. They rarely complain but leave easily. The follow-up question is where the value is.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-satisfaction-check-ins-q3",
          prompt: "When are good moments for a check-in? (Select all that apply.)",
          options: [
            "After the first sprint or first demo",
            "After each major release",
            "At a regular rhythm during long projects",
            "Only after the final invoice is paid",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Early and regular check-ins catch problems while they are cheap to fix. End-only surveys are too late to change anything.",
        },
        {
          id: "pma-satisfaction-check-ins-q4",
          prompt: "How is NPS calculated?",
          options: [
            "Percentage of promoters (9–10) minus percentage of detractors (0–6)",
            "The average score out of 10",
            "Promoters divided by passives",
            "The number of 10s",
          ],
          correctIndex: 0,
          explanation: "NPS ranges from −100 to +100. Passives count in the total but not in either group.",
        },
        {
          id: "pma-satisfaction-check-ins-q5",
          prompt: "A client gives honest feedback that demos feel rushed. What should happen next?",
          options: [
            "Thank them, agree a specific change, and show it in the next demo",
            "Explain why demos are rushed",
            "Log it and do nothing",
            "Ask the team to defend the demos",
          ],
          correctIndex: 0,
          explanation: "Visible action is what makes clients keep giving feedback. Defending or ignoring teaches them not to bother.",
        },
        {
          id: "pma-satisfaction-check-ins-q6",
          prompt: "A client has gone quiet: approvals are slow and they skipped the last demo, but they say \"all good\" when asked. What is the most likely situation?",
          options: [
            "There may be hidden dissatisfaction or a change on their side, worth a direct, senior check-in",
            "They are very happy",
            "They are on holiday",
            "Nothing worth acting on",
          ],
          correctIndex: 0,
          explanation: "Behaviour is a better signal than words. Slow approvals and skipped demos often come before a complaint or a cancelled contract.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-satisfaction-check-ins-q7",
          prompt: "Why can it help if someone senior from Oyelabs, not only the PM, joins a check-in?",
          options: [
            "Clients may share concerns about the PM or team more openly with someone else",
            "To make the call longer",
            "Because the PM cannot ask questions",
            "To sell more services in every call",
          ],
          correctIndex: 0,
          explanation: "If the problem is the PM, the client may not say so to the PM. A second voice opens that door.",
        },
        {
          id: "pma-satisfaction-check-ins-q8",
          prompt: "Which survey questions are useful in a short client check-in? (Select all that apply.)",
          options: [
            "\"How likely are you to recommend us to a colleague, 0–10?\"",
            "\"What is one thing we should do differently?\"",
            "\"How clear are our updates, 1–5?\"",
            "\"Don't you agree we are doing a great job?\"",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Neutral scales and an open question give honest data. Leading questions get polite, useless answers.",
        },
        {
          id: "pma-satisfaction-check-ins-q9",
          prompt: "Only one person at the client answers the survey, and they are your friendly day-to-day contact. What is the risk?",
          options: [
            "The decision maker who renews the contract may feel differently and is not represented",
            "There is no risk",
            "The score will be too low",
            "The survey tool will fail",
          ],
          correctIndex: 0,
          explanation: "Ask the budget holder too. The friendly contact is rarely the one who decides whether to renew.",
          isEdgeCaseOrInterviewQuestion: true,
        },
      ],
      practice: {
        kind: "calculate",
        prompt: "After the release of a Laravel and React portal, ten people across the client's team answered \"How likely are you to recommend Oyelabs, 0–10?\". The answers are grouped below. Calculate the results.",
        table: {
          columns: ["Group", "Responses"],
          rows: [
            ["Promoters (9–10)", "6"],
            ["Passives (7–8)", "3"],
            ["Detractors (0–6)", "1"],
          ],
        },
        fields: [
          { id: "promoters", label: "Promoters as a percentage", unit: "%", answer: 60, tolerance: 0.1, expression: "T[0][1] / (T[0][1] + T[1][1] + T[2][1]) * 100" },
          { id: "nps", label: "Net Promoter Score", unit: "", answer: 50, tolerance: 0.1, expression: "(T[0][1] - T[2][1]) / (T[0][1] + T[1][1] + T[2][1]) * 100" },
        ],
        explanation: "Total responses: 6 + 3 + 1 = 10. Promoters 60%, detractors 10%, so NPS = 60 − 10 = 50. The three passives and the one detractor are the people to talk to next.",
      },
      sop: [
        {
          title: "Our client check-in cadence and survey",
          prompt: "[Oyelabs SOP – admin to fill] When check-ins happen (after which milestones, and how often on long projects), who from Oyelabs joins, which survey tool and questions we use, where results are recorded, and what score triggers escalation.",
        },
      ],
    },
    {
      id: "pma-bad-news-early",
      moduleId: "pma-client",
      trackId: "pm",
      title: "Delivering bad news early",
      summary:
        "Every project has bad news. A third-party API changes, a key developer falls ill, App Store review rejects the build. The news itself rarely ends a client relationship. Hearing it late does. A client told on Monday that Friday's release will slip can move a marketing launch. A client told on Thursday night cannot, and they will remember it.\n\nThe rule is: as soon as you know something is likely, not when it is certain, tell the client. Waiting a few days \"to see if we can recover\" feels kind, but it removes the client's options. Clients judge you less on the problem than on how early you told them and how clearly you handled it.\n\nUse a clear structure, by call for big news and always confirmed in writing. First, state the news in one sentence, at the top. Do not bury it under a long background. Second, explain the cause briefly and honestly, without blaming the client or your team. Third, give the impact: what moves, by how much, and what does not change. Fourth, give your recovery plan and options, such as a phased release, extra people or reduced scope. Recommend one. Fifth, say what you need from the client and by when. Finally, say when you will update them next.\n\nPrepare before you speak. Have the new dates agreed with the tech lead. Have the options sized. If you are on a fixed-bid project, know whether the delay is our risk or a client dependency, because that changes who pays.\n\nThe common mistakes are softening the message until it is unclear, and giving a new date you have not checked. The second slip hurts far more than the first.",
      level: "advanced",
      estMinutes: 40,
      webRefs: [
        { label: "Atlassian Team Playbook: Stakeholder Project Communication: Atlassian Plays", url: "https://www.atlassian.com/team-playbook/plays/stakeholder-communications-plan", kind: "docs", verifiedAt: "2026-10-02T09:38:59Z" },
        { label: "Atlassian: Incident Communication Best Practices & Channels", url: "https://www.atlassian.com/incident-management/incident-communication", kind: "article", verifiedAt: "2026-10-02T09:35:19Z" },
        { label: "Atlassian: Project Status Report: Tips and Templates for Success", url: "https://www.atlassian.com/agile/project-management/status-report", kind: "article", verifiedAt: "2026-10-02T09:38:53Z" },
        { label: "ProjectManager: 10 Free Communication Plan Templates for Word and Excel", url: "https://www.projectmanager.com/blog/communication-plan-templates", kind: "article", verifiedAt: "2026-10-02T09:38:55Z" },
      ],
      video: {
        title: "How to Deliver Bad News About a Project",
        channel: "ProjectManager",
        url: "https://www.youtube.com/watch?v=WnUD1-k3B-o",
        videoId: "WnUD1-k3B-o",
        verifiedAt: "2026-10-02T09:35:56Z",
      },
      alternateVideos: [
        {
          title: "Breaking Bad News to Project Stakeholders | Coffee with Brett",
          channel: "TeamGantt",
          url: "https://www.youtube.com/watch?v=PdUKlnVTauE",
          videoId: "PdUKlnVTauE",
          verifiedAt: "2026-10-02T09:35:53Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-bad-news-early-q1",
          prompt: "On Monday your tech lead says Friday's release is 70% likely to slip because the payment provider's sandbox is down. When do you tell the client?",
          options: [
            "Today, as a risk with options, so they can adjust their plans",
            "Thursday, once the slip is certain",
            "After Friday, with a new date",
            "Never, if the team can recover with overtime",
          ],
          correctIndex: 0,
          explanation: "Tell the client when the problem is likely, not certain. Early warning keeps their options open, such as moving a marketing email.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-bad-news-early-q2",
          prompt: "Which should a bad-news message include? (Select all that apply.)",
          options: [
            "The news in the first sentence",
            "A short, honest cause",
            "The impact: what moves and what does not",
            "A recovery plan with options and a recommendation",
            "Three paragraphs of background before the news",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 3],
          explanation: "Lead with the news, then cause, impact and plan. Burying the news under background makes clients feel managed.",
        },
        {
          id: "pma-bad-news-early-q3",
          prompt: "You announce a new release date without checking it with the tech lead. It slips again. Why is this worse than the first slip?",
          options: [
            "A second slip shows the client your dates cannot be trusted",
            "It is not worse",
            "Because it costs more money",
            "Because the contract forbids two slips",
          ],
          correctIndex: 0,
          explanation: "One slip is a project problem. Two slips is a credibility problem. Only commit to dates the team has checked.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-bad-news-early-q4",
          prompt: "How should you deliver major bad news, such as a two-week delay?",
          options: [
            "On a call, then confirm in writing the same day",
            "Only by email, late at night",
            "In a chat message",
            "Through the reseller without telling them the details",
          ],
          correctIndex: 0,
          explanation: "A call shows respect and lets the client ask questions. The written follow-up records what was agreed.",
        },
        {
          id: "pma-bad-news-early-q5",
          prompt: "The delay happened because the client sent API credentials three weeks late. How do you state the cause?",
          options: [
            "Factually, with dates, and without blame: \"We received the credentials on 12 May, three weeks after the planned date.\"",
            "\"Your team caused this delay.\"",
            "Leave the cause out to be polite",
            "Say the team was slow",
          ],
          correctIndex: 0,
          explanation: "Facts with dates are fair and matter for who bears the cost, especially on fixed bid. Blame language starts an argument.",
        },
        {
          id: "pma-bad-news-early-q6",
          prompt: "Which recovery options can you offer for a late release? (Select all that apply.)",
          options: [
            "A phased release: ship the core flows on time, the rest later",
            "Reduce scope for this release by agreement",
            "Add people if they can be useful quickly",
            "Skip testing to hold the date",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Phasing, scope trade-offs and extra capacity are real options. Skipping testing only moves the problem to production.",
        },
        {
          id: "pma-bad-news-early-q7",
          prompt: "Why is \"we're facing some minor challenges\" a weak way to report a two-week slip?",
          options: [
            "It is so soft that the client does not realise the date has moved",
            "It is too long",
            "It uses passive voice",
            "It is too technical",
          ],
          correctIndex: 0,
          explanation: "Softening until the message is unclear means the client hears it later anyway, and feels misled.",
        },
        {
          id: "pma-bad-news-early-q8",
          prompt: "What should you always end a bad-news message with?",
          options: [
            "What you need from the client and when you will update them next",
            "An apology only",
            "A discount offer",
            "Nothing; keep it short",
          ],
          correctIndex: 0,
          explanation: "A clear next step and next update time give the client control back.",
        },
        {
          id: "pma-bad-news-early-q9",
          prompt: "You work through a white-label reseller. The delay affects their end client. What is the right approach?",
          options: [
            "Tell the reseller first, early, with facts and options they can pass on",
            "Email the end client directly",
            "Wait until the reseller notices",
            "Let the team explain it in the next demo",
          ],
          correctIndex: 0,
          explanation: "The reseller owns the end-client relationship and needs time to manage it. Give them a clear package of facts and options.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-bad-news-early-q10",
          prompt: "Before you tell the client about a slip, what should you prepare?",
          options: [
            "A checked new date, sized options, and whether the cause is our risk or a client dependency",
            "A list of who to blame",
            "A new contract",
            "Nothing; speed matters more than preparation",
          ],
          correctIndex: 0,
          explanation: "Speed matters, but an hour of preparation makes the call useful. Know the date, the options and who carries the cost.",
        },
      ],
      practice: {
        kind: "write",
        variant: "email",
        prompt: "Write the email that confirms bad news to the client after a short call this morning. Lead with the news, give the cause without blame, state the impact, give a recovery plan with a recommendation, say what you need from the client, and say when you will update them next.",
        context: "Project: React Native food-ordering app with a Laravel API, for a US restaurant group (client: Daniel Ortiz, Head of Digital). Planned launch: Friday 20 June. Facts: Apple rejected the build yesterday because the in-app account deletion option is missing (guideline 5.1.1). The fix takes 3 days of development and testing. Resubmission and review take 1–3 days. Android is approved and ready. New realistic date for iOS: Thursday 26 June. Option: launch Android on 20 June as planned and iOS when approved. You need Daniel to confirm whether to launch Android first, by Wednesday.",
        wordLimit: 250,
        rubric: [
          { id: "lead", label: "News first", description: "The first one or two sentences state that iOS launch moves from 20 June to around 26 June.", weight: 1.5 },
          { id: "cause", label: "Clear, blame-free cause", description: "Explains the Apple rejection (account deletion option missing) simply and honestly, owning the fix without blaming anyone.", weight: 1 },
          { id: "impact", label: "Impact and what is unchanged", description: "States what moves (iOS date) and what does not (Android ready on 20 June).", weight: 1 },
          { id: "plan", label: "Recovery plan with recommendation", description: "Gives the fix plan and the option to launch Android first, with a recommendation and reason.", weight: 1.5 },
          { id: "ask", label: "Ask and next update", description: "Asks Daniel to confirm the Android-first choice by Wednesday and says when the next update will come.", weight: 1 },
        ],
        sampleAnswer: "Subject: iOS launch moves to 26 June – Android still ready for 20 June\n\nHi Daniel,\n\nThanks for the call this morning. As discussed, the iOS app will now launch around Thursday 26 June instead of Friday 20 June.\n\nWhy: Apple rejected the build yesterday because the app does not yet let users delete their account from inside the app. This is a required Apple rule, and we should have included it. We are adding it now.\n\nImpact:\n- iOS: fix takes 3 days, then Apple review takes 1–3 days. Realistic launch: 26 June.\n- Android: already approved and ready for 20 June.\n- Nothing else in scope changes.\n\nOur recommendation: launch Android on 20 June as planned, and iOS as soon as Apple approves. Your customers on Android get the app on time, and your launch announcement can go out with a short \"iPhone coming next week\" note.\n\nWhat we need: please confirm by Wednesday whether you want the Android-first launch.\n\nI'll update you on Tuesday by 6 pm Eastern with the fix status and the resubmission time.\n\nBest regards,\nAnkit",
      },
    },
    {
      id: "pma-escalations-unhappy-clients",
      moduleId: "pma-client",
      trackId: "pm",
      title: "Escalations and unhappy clients",
      summary:
        "Sooner or later a client will be angry. A Laravel admin panel goes down during their sales event. A demo breaks in front of their investors. They email your CEO with \"unacceptable\" in the subject line. How you handle the next 48 hours often decides whether the client stays for five more years or leaves this month.\n\nFirst, separate the emotion from the problem. An angry client needs to feel heard before they can listen to a plan. On the first call, listen fully. Do not interrupt or defend. Repeat back what you heard: \"So the main issue is that orders failed for three hours during your launch, and nobody told you.\" Acknowledge the impact on their business, and apologise for what is ours to own. Do not argue facts in this call.\n\nSecond, act fast and visibly. If something is broken, fix or work around it first. Agree an update rhythm, such as every two hours until resolved, and keep to it even when there is no news. Bring in the right people through your team's internal escalation path, described in the SOP below. Tell the client who owns the issue now.\n\nThird, close properly. Once things are stable, send a short incident summary: what happened, why, what we fixed, and what we will change so it does not happen again. Then check in a week later.\n\nNot every escalation is about one incident. Sometimes it is many small things: slow replies, missed notes, changing dates. Then the fix is a reset meeting with a clear plan, not an apology.\n\nThe common mistakes are defending the team in the first call, promising a date before you know the cause, and going quiet while you investigate. Silence makes an angry client angrier.",
      level: "advanced",
      estMinutes: 45,
      isMilestone: true,
      webRefs: [
        { label: "Atlassian: Escalation Policies for Incidents: Types & Tips", url: "https://www.atlassian.com/incident-management/on-call/escalation-policies", kind: "docs", verifiedAt: "2026-10-02T09:35:38Z" },
        { label: "Atlassian Team Playbook: Stakeholder Project Communication: Atlassian Plays", url: "https://www.atlassian.com/team-playbook/plays/stakeholder-communications-plan", kind: "article", verifiedAt: "2026-10-02T09:38:59Z" },
        { label: "ProjectManager: What Is Stakeholder Management?", url: "https://www.projectmanager.com/guides/stakeholder-management", kind: "article", verifiedAt: "2026-10-02T09:38:55Z" },
      ],
      video: {
        title: "8 Steps To Manage Client Escalations Like a PRO",
        channel: "VenuMuvvala",
        url: "https://www.youtube.com/watch?v=fTGJMYcLVR0",
        videoId: "fTGJMYcLVR0",
        verifiedAt: "2026-10-02T09:35:58Z",
      },
      alternateVideos: [
        {
          title: "How to Manage Difficult Clients as a Project Manager (Without Losing Your Cool)",
          channel: "Haile Solutions",
          url: "https://www.youtube.com/watch?v=PRpR-2x9mN4",
          videoId: "PRpR-2x9mN4",
          verifiedAt: "2026-10-02T09:35:54Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-escalations-unhappy-clients-q1",
          prompt: "An angry client calls: their app's checkout failed for three hours during a sale. What should you do first on the call?",
          options: [
            "Listen fully, repeat back the problem and its impact, and acknowledge it",
            "Explain that the payment provider caused it",
            "Give a precise fix time straight away",
            "Ask them to email instead",
          ],
          correctIndex: 0,
          explanation: "People need to feel heard before they can hear a plan. Explaining causes in the first minute sounds like defending.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-escalations-unhappy-clients-q2",
          prompt: "Which actions help during an active client escalation? (Select all that apply.)",
          options: [
            "Agree an update rhythm and keep it, even with no news",
            "Name who owns the issue now",
            "Bring in the right people through the internal escalation path",
            "Go quiet until you have a full root cause",
            "Promise a fix time before the cause is known",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Visible ownership and regular updates calm a crisis. Silence and guessed dates make it worse.",
        },
        {
          id: "pma-escalations-unhappy-clients-q3",
          prompt: "The client emails your CEO directly, copying you, with \"unacceptable\" in the subject. What is the best first move?",
          options: [
            "Brief your CEO quickly with facts, then reply to the client with ownership and a plan, as agreed internally",
            "Reply-all defending the team",
            "Ignore it because the CEO will answer",
            "Ask the CEO to remove you from the thread",
          ],
          correctIndex: 0,
          explanation: "Your leadership must not be surprised, and the client needs one clear voice. Align internally fast, then respond.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-escalations-unhappy-clients-q4",
          prompt: "What should the incident summary after an escalation contain?",
          options: [
            "What happened, why, what was fixed, and what will change to prevent a repeat",
            "Only an apology",
            "The names of the developers at fault",
            "A discount offer and nothing else",
          ],
          correctIndex: 0,
          explanation: "A blameless, factual summary with prevention steps rebuilds confidence. Naming individuals damages the team and helps no one.",
        },
        {
          id: "pma-escalations-unhappy-clients-q5",
          prompt: "A client is unhappy, but there was no single incident: slow replies, missed meeting notes and dates that shifted. What fixes this?",
          options: [
            "A reset meeting that admits the pattern and agrees a clear plan: cadence, response times, owners",
            "A long apology email",
            "Waiting for it to pass",
            "Changing the developers",
          ],
          correctIndex: 0,
          explanation: "Pattern problems need process fixes. Show the client exactly what will be different, then deliver it.",
        },
        {
          id: "pma-escalations-unhappy-clients-q6",
          prompt: "During the escalation call the client says something factually wrong: \"You never told us about the API change.\" You did, in an email. What do you do?",
          options: [
            "Note it and correct it gently later, with the email, once the crisis is under control",
            "Interrupt and forward the email during the call",
            "Accept it as true",
            "End the call",
          ],
          correctIndex: 0,
          explanation: "Winning the argument in the heat of the moment loses the client. Correct the record calmly later, and ask how to make warnings more visible.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-escalations-unhappy-clients-q7",
          prompt: "How often should you update an angry client while a production issue is open?",
          options: [
            "At a fixed, agreed rhythm (for example every 2 hours), even if there is nothing new",
            "Only when it is fixed",
            "Once a day",
            "Whenever the client asks",
          ],
          correctIndex: 0,
          explanation: "A predictable rhythm stops the client chasing you and shows control. \"No change yet, next update at 4 pm\" is still an update.",
        },
        {
          id: "pma-escalations-unhappy-clients-q8",
          prompt: "Which phrases help calm an unhappy client? (Select all that apply.)",
          options: [
            "\"I understand this hit your sale, and I'm sorry.\"",
            "\"I own this until it's fixed. Next update at 3 pm.\"",
            "\"Here is what we're doing right now.\"",
            "\"That's not our fault.\"",
            "\"Calm down.\"",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Empathy, ownership and action calm people. Blame and \"calm down\" do the opposite.",
        },
        {
          id: "pma-escalations-unhappy-clients-q9",
          prompt: "A week after the incident is resolved, what should you do?",
          options: [
            "Check in with the client to confirm things feel stable and the prevention steps are done",
            "Nothing; the ticket is closed",
            "Send an invoice for the fix",
            "Ask for a testimonial",
          ],
          correctIndex: 0,
          explanation: "A follow-up shows the fix was real and the relationship matters. It is often what turns an escalation into loyalty.",
        },
        {
          id: "pma-escalations-unhappy-clients-q10",
          prompt: "When should you escalate a client issue internally rather than handle it alone?",
          options: [
            "When it affects production, money, the contract or the relationship, or you cannot resolve it within the agreed time",
            "Never; escalating looks weak",
            "Only after the client threatens to leave",
            "For every small question",
          ],
          correctIndex: 0,
          explanation: "Escalating early with facts is a professional move. Waiting until the client threatens to leave is too late.",
        },
      ],
      practice: {
        kind: "scenario",
        prompt: "It is 9 pm IST. A UK client's Laravel e-commerce site has been returning errors at checkout for 40 minutes during their weekend promotion. The client, Tom (Managing Director), calls you, very angry. Your on-call developer is investigating and thinks a payment webhook change deployed today is the cause.",
        steps: [
          {
            id: "s1",
            question: "Tom is shouting that this is costing him thousands. What do you say first?",
            options: [
              "\"I hear you, Tom. Checkout failing during your promotion is serious, and I'm sorry. Our developer is on it now, and I'll stay with this until it's fixed.\"",
              "\"It might be the payment provider, not us.\"",
              "\"It'll be fixed in 10 minutes.\"",
              "\"Can you send this by email so we can log it?\"",
            ],
            correctIndex: 0,
            explanation: "Acknowledge impact, apologise for what is ours, and show ownership. Do not guess causes or times.",
          },
          {
            id: "s2",
            question: "The developer confirms today's deployment caused it. Rolling back takes 15 minutes; a proper fix needs 2 hours. What do you agree with Tom?",
            options: [
              "Roll back now to restore checkout, update him every 30 minutes, and do the proper fix tomorrow with testing",
              "Do the 2-hour fix now so it's done properly",
              "Wait until morning when the full team is in",
              "Ask Tom to choose the technical approach",
            ],
            correctIndex: 0,
            explanation: "Restore service first, then fix properly. A regular update rhythm keeps Tom informed while you work.",
          },
          {
            id: "s3",
            question: "Checkout is restored. The next day, what do you send Tom?",
            options: [
              "A short incident summary: what happened, cause, fix, and changes such as testing webhooks before weekend releases",
              "A note naming the developer who deployed the change",
              "Nothing; it's fixed",
              "An invoice for the overtime",
            ],
            correctIndex: 0,
            explanation: "A blameless summary with prevention steps rebuilds trust. Blaming individuals or billing for our mistake does not.",
          },
        ],
      },
      sop: [
        {
          title: "Our internal escalation path",
          prompt: "[Oyelabs SOP – admin to fill] Who the PM escalates to and when (production down, client threatens to leave, payment dispute), how fast leadership must be informed, who may speak to the client during an incident, and the incident summary template.",
        },
      ],
    },
    {
      id: "pma-trust-long-term-relationships",
      moduleId: "pma-client",
      trackId: "pm",
      title: "Trust and long-term client relationships",
      summary:
        "For an agency, the first project is often the cheapest one to win and the least profitable. The value is in what comes next: phase two, the mobile app, the maintenance retainer, and the referral to the founder's friend. All of that depends on trust. Clients who trust you approve faster, argue less over change requests and forgive the occasional slip.\n\nTrust is built from small, repeated proofs. You do what you said, when you said. Updates arrive on the same day every week. Bad news comes early. Meeting notes arrive the next day. Over months, the client stops checking your work and starts asking your opinion. That is the goal.\n\nSome habits help a lot. Learn the client's business, not just the project. Know their customers, their busy season and what their boss measures them on. Then make suggestions that help the business: \"Your sign-up drop-off is at the phone verification step; we could test email sign-up.\" Be honest when something is a bad idea, even if it is paid work. Keep a short record of each client's preferences and key dates. Plan a quarterly review for long accounts, looking back at results and forward at what they need next.\n\nDo not confuse trust with friendliness. A client can like you and still not trust your dates. And do not over-promise to please. One missed promise undoes many on-time ones.\n\nThe common mistake is to only contact the client when you need something: an approval, an invoice or an access key. Long relationships are built in the calm weeks, with useful updates and ideas, not only during deadlines.",
      level: "advanced",
      estMinutes: 35,
      webRefs: [
        { label: "Atlassian Team Playbook: Stakeholder Project Communication: Atlassian Plays", url: "https://www.atlassian.com/team-playbook/plays/stakeholder-communications-plan", kind: "docs", verifiedAt: "2026-10-02T09:38:59Z" },
        { label: "Asana: Project Stakeholder: Definition, Analysis & Mapping", url: "https://asana.com/resources/project-stakeholder", kind: "article", verifiedAt: "2026-10-02T10:07:41Z" },
        { label: "ProjectManager: What Is Stakeholder Management?", url: "https://www.projectmanager.com/guides/stakeholder-management", kind: "article", verifiedAt: "2026-10-02T09:38:55Z" },
        { label: "Asana: Effective communication workplace: 12 tips & styles", url: "https://asana.com/resources/effective-communication-workplace", kind: "article", verifiedAt: "2026-10-02T10:08:00Z" },
      ],
      video: {
        title: "Project Stakeholder Management Plan: Managing Expectations!",
        channel: "ProjectManager",
        url: "https://www.youtube.com/watch?v=0EkufUCo5qI",
        videoId: "0EkufUCo5qI",
        verifiedAt: "2026-10-02T09:35:56Z",
      },
      alternateVideos: [
        {
          title: "Improving Your Communication With Clients - Robyn Birkedal",
          channel: "The Digital Project Manager",
          url: "https://www.youtube.com/watch?v=KA-7T8zCDt4",
          videoId: "KA-7T8zCDt4",
          verifiedAt: "2026-10-02T09:35:58Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-trust-long-term-relationships-q1",
          prompt: "What builds client trust most reliably over months?",
          options: [
            "Doing what you said, when you said, over and over",
            "Big discounts",
            "Frequent social chats",
            "Saying yes to every request",
          ],
          correctIndex: 0,
          explanation: "Trust is the record of kept promises. Discounts and friendliness do not replace reliability.",
        },
        {
          id: "pma-trust-long-term-relationships-q2",
          prompt: "Which habits build a long-term client relationship? (Select all that apply.)",
          options: [
            "Learning the client's business goals and busy seasons",
            "Suggesting improvements that help their business",
            "Quarterly reviews on long accounts",
            "Contacting them only when you need approvals or payments",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Clients value a partner who understands and improves their business. Contact only when you need something feels transactional.",
        },
        {
          id: "pma-trust-long-term-relationships-q3",
          prompt: "A client on a T&M retainer asks for a feature you believe will hurt their conversion rate. It is paid work. What builds the most trust?",
          options: [
            "Explain your concern with evidence, suggest an alternative or a test, and respect their final decision",
            "Build it without comment since it is billable",
            "Refuse to build it",
            "Build it badly so it gets removed",
          ],
          correctIndex: 0,
          explanation: "Honest advice, even against short-term revenue, is what makes a client see you as a partner.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-trust-long-term-relationships-q4",
          prompt: "A client likes you personally but double-checks every date you give. What does this tell you?",
          options: [
            "They like you but do not yet trust your delivery commitments",
            "They trust you fully",
            "They are being rude",
            "Nothing important",
          ],
          correctIndex: 0,
          explanation: "Liking and trusting are different. Fix it with a run of small, on-time commitments.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-trust-long-term-relationships-q5",
          prompt: "Why is over-promising so damaging to trust?",
          options: [
            "One missed promise can undo many kept ones",
            "It makes projects cheaper",
            "Clients never remember promises",
            "It is only a problem on fixed bid",
          ],
          correctIndex: 0,
          explanation: "People weigh broken promises more heavily than kept ones. Promise what you can keep, then beat it.",
        },
        {
          id: "pma-trust-long-term-relationships-q6",
          prompt: "What is a good agenda for a quarterly review with a long-term client?",
          options: [
            "Results delivered against their goals, what went well and badly, and what they need next quarter",
            "A list of all tickets closed",
            "A sales pitch for new services only",
            "Team birthdays",
          ],
          correctIndex: 0,
          explanation: "Tie the review to the client's business outcomes and their next needs. Ticket lists bore executives.",
        },
        {
          id: "pma-trust-long-term-relationships-q7",
          prompt: "Your main contact at the client is leaving. What should you do? (Select all that apply.)",
          options: [
            "Ask for an introduction to their replacement and meet early",
            "Share a short project summary so the new person catches up",
            "Strengthen links with other people at the client",
            "Wait until the new person contacts you",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Relationships tied to one person are fragile. A planned transition protects the account.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-trust-long-term-relationships-q8",
          prompt: "Which update is most likely to build trust?",
          options: [
            "\"Your sign-up drop-off is at phone verification. We could test email sign-up next sprint; it's about 2 days of work.\"",
            "\"All good this week.\"",
            "\"We closed 23 tickets.\"",
            "\"Let us know if you need anything.\"",
          ],
          correctIndex: 0,
          explanation: "A specific, business-focused insight with a clear next step shows you care about their outcome, not just tasks.",
        },
        {
          id: "pma-trust-long-term-relationships-q9",
          prompt: "Why keep a short record of each client's preferences and key dates?",
          options: [
            "So anyone at Oyelabs can serve the client consistently, and you remember what matters to them",
            "For billing",
            "Because it is a legal requirement",
            "It is not useful",
          ],
          correctIndex: 0,
          explanation: "Knowing that a client hates calls on Mondays or has a busy season in December prevents friction and shows care.",
        },
      ],
      practice: {
        kind: "spot",
        prompt: "A PM drafted this plan for growing a 14-month relationship with a US client whose React and Laravel platform Oyelabs built. Mark the lines that would damage trust or the long-term relationship.",
        segments: [
          { id: "l1", text: "Send the weekly status update every Friday by 5 pm Eastern, as we have done all year.", issue: null },
          { id: "l2", text: "Hold a quarterly review covering results against their sign-up goals and what they need next quarter.", issue: null },
          { id: "l3", text: "Promise the new analytics dashboard by month end to secure the phase-three contract, then work out the plan.", issue: "Committing a date before sizing the work is over-promising; a miss would undo months of trust." },
          { id: "l4", text: "Only contact the client's CEO when an invoice is overdue.", issue: "Contacting senior people only about money makes the relationship transactional." },
          { id: "l5", text: "Suggest testing email sign-up, because analytics show drop-off at phone verification.", issue: null },
          { id: "l6", text: "Ask for an introduction to the new CTO before our current contact leaves in May.", issue: null },
          { id: "l7", text: "Don't mention the slow API response times we found; they haven't noticed yet.", issue: "Hiding a known problem breaks trust when the client finds it, and they will." },
          { id: "l8", text: "Keep a client notes page with preferences, key dates and their busy season.", issue: null },
        ],
        askExplanation: true,
      },
    },
    {
      id: "pma-handover-to-support",
      moduleId: "pma-client",
      trackId: "pm",
      title: "Handover to support and maintenance",
      summary:
        "Launch is not the end of the project. For the client it is the start of real use: real users, real bugs and real questions. If the handover from the project team to support is messy, the first month after launch feels like chaos. Tickets bounce between people, nobody knows the server passwords, and the client wonders what they paid for. A clean handover protects the relationship and often turns into a paid maintenance contract.\n\nThe handover has two sides: the client and our support team. Start planning it before launch, not after.\n\nFor the client, agree in writing what support looks like. That means which channel to report issues on, what counts as critical versus minor, how fast we respond to each level, and the warranty period for defects. Also agree what is not covered, such as new features or changes to third-party services. Use your team's SOP below for SLAs, tiers and warranty terms. Do not invent them in a meeting.\n\nFor our support team, prepare a handover pack. Include the architecture overview, environments and where they run, how to deploy and roll back, access and credentials stored in the agreed vault, third-party accounts such as payment, SMS and push providers with their owners, known issues and workarounds, and contacts on the client side. Hold a walkthrough session where the developers explain the system to support, and have support do one deployment while the developers watch.\n\nClose the project formally. Get written sign-off on acceptance, transfer ownership of accounts the client should own, such as app store and domain accounts, and run a short lessons-learned review.\n\nThe common mistakes are leaving credentials in a developer's head, and letting support learn about the client's open complaints from the client.",
      level: "advanced",
      estMinutes: 40,
      isMilestone: true,
      webRefs: [
        { label: "Atlassian: The Atlassian Incident Management Handbook", url: "https://www.atlassian.com/incident-management/handbook", kind: "docs", verifiedAt: "2026-10-02T09:35:44Z" },
        { label: "ProjectManager: 7 Steps to Project Closure (Checklist Included)", url: "https://www.projectmanager.com/blog/project-closure", kind: "article", verifiedAt: "2026-10-02T09:38:35Z" },
        { label: "Atlassian: What Is an SLA? Service Level Agreements Explained", url: "https://www.atlassian.com/itsm/service-request-management/slas", kind: "article", verifiedAt: "2026-10-02T09:35:35Z" },
        { label: "Atlassian: Knowledge Base Guide: Examples, Templates & Best Practices", url: "https://www.atlassian.com/itsm/knowledge-management/what-is-a-knowledge-base", kind: "article", verifiedAt: "2026-10-02T09:35:37Z" },
      ],
      video: {
        title: "Closing the Project [5 STEPS TO PROJECT CLOSURE]",
        channel: "Adriana Girdler",
        url: "https://www.youtube.com/watch?v=Fl5BVFzigt8",
        videoId: "Fl5BVFzigt8",
        verifiedAt: "2026-10-02T09:35:53Z",
      },
      alternateVideos: [
        {
          title: "Project Handover Process: 5 Simple Steps to a Successful Project Handover",
          channel: "ProjectSkillsMentor",
          url: "https://www.youtube.com/watch?v=dOXcbx0qmIk",
          videoId: "dOXcbx0qmIk",
          verifiedAt: "2026-10-02T09:35:58Z",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pma-handover-to-support-q1",
          prompt: "When should you start planning the handover to support?",
          options: ["Before launch, while the project team is still on it", "The day after launch", "When the first bug arrives", "When the warranty ends"],
          correctIndex: 0,
          explanation: "Once developers move to new projects, knowledge leaves with them. Plan the handover while they are still available.",
        },
        {
          id: "pma-handover-to-support-q2",
          prompt: "What belongs in the internal handover pack for the support team? (Select all that apply.)",
          options: [
            "Architecture overview, environments and how to deploy and roll back",
            "Where credentials are stored in the agreed vault",
            "Third-party accounts (payment, SMS, push) and who owns them",
            "Known issues, workarounds and client contacts",
            "Passwords pasted into the handover document",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 3],
          explanation: "Support needs to run, fix and deploy the system. Credentials belong in the vault, never pasted into documents.",
        },
        {
          id: "pma-handover-to-support-q3",
          prompt: "Two weeks after launch the client reports that a button is the wrong colour on one screen and asks for a new report export. How do you classify them?",
          options: [
            "The colour is a defect, likely covered by warranty; the export is a new feature needing a change request",
            "Both are free warranty fixes",
            "Both are change requests",
            "Both should be ignored",
          ],
          correctIndex: 0,
          explanation: "Warranty covers things that do not match what was agreed. New features are new scope, even after launch.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-handover-to-support-q4",
          prompt: "What should the client know about support before launch?",
          options: [
            "How to report issues, the severity levels, response times for each, the warranty period, and what is not covered",
            "Only the support email address",
            "The support team's salaries",
            "Nothing; they will learn when they need help",
          ],
          correctIndex: 0,
          explanation: "Clear expectations stop a minor bug becoming an angry midnight call.",
        },
        {
          id: "pma-handover-to-support-q5",
          prompt: "The only developer who knows the server setup is leaving Oyelabs next week, after launch. What is the priority?",
          options: [
            "Document the setup, move credentials to the vault and have support do a deployment while he watches, this week",
            "Ask him to stay on call informally",
            "Wait until something breaks",
            "Ask the client to manage the server",
          ],
          correctIndex: 0,
          explanation: "Knowledge in one head is the biggest handover risk. Document it and prove it with a supervised deployment.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-handover-to-support-q6",
          prompt: "Which accounts should normally be owned by the client, not Oyelabs, after handover? (Select all that apply.)",
          options: [
            "Apple App Store and Google Play developer accounts",
            "The domain name registration",
            "Payment provider merchant account",
            "Oyelabs' internal Keka account",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Business-critical accounts belong to the client so they are never locked out. Oyelabs' internal tools stay internal.",
        },
        {
          id: "pma-handover-to-support-q7",
          prompt: "Why run a walkthrough session where developers explain the system to support?",
          options: [
            "Support can ask questions and learn the system while the developers are still available",
            "It is a formality",
            "To train the client",
            "To decide who gets a bonus",
          ],
          correctIndex: 0,
          explanation: "Documents miss things. A live walkthrough and a supervised deployment surface the gaps.",
        },
        {
          id: "pma-handover-to-support-q8",
          prompt: "The client has open complaints about slow load times when you hand over. What should you do?",
          options: [
            "Tell the support lead about them in the handover, with status and next steps, before the client raises them",
            "Leave them out so the handover looks clean",
            "Close them as won't fix",
            "Let the client explain them to support",
          ],
          correctIndex: 0,
          explanation: "Support should never be surprised by the client. Hand over open issues honestly.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pma-handover-to-support-q9",
          prompt: "What formally closes the project?",
          options: [
            "Written client acceptance, account ownership transferred, support handover done, and a lessons-learned review",
            "The final deployment",
            "The last invoice email",
            "The team moving to another project",
          ],
          correctIndex: 0,
          explanation: "Formal closure prevents months of \"is this still the project?\" arguments and captures lessons for next time.",
        },
        {
          id: "pma-handover-to-support-q10",
          prompt: "What is an SLA in client support?",
          options: [
            "An agreement on service levels, such as how quickly each severity of issue gets a response and a fix",
            "A software licence",
            "A type of server",
            "A sales target",
          ],
          correctIndex: 0,
          explanation: "A service level agreement sets measurable promises like response and resolution times per severity.",
        },
      ],
      practice: {
        kind: "spot",
        prompt: "Here is a PM's handover checklist for a React Native and Laravel delivery app moving to Oyelabs support. Mark the lines that are wrong or risky.",
        segments: [
          { id: "l1", text: "Architecture diagram and list of environments (staging, production) with hosting details.", issue: null },
          { id: "l2", text: "Production database password included in this document for quick access.", issue: "Credentials must live in the agreed vault, not in a shared document." },
          { id: "l3", text: "Step-by-step deploy and rollback guide, tested by the support engineer on staging.", issue: null },
          { id: "l4", text: "Apple and Google developer accounts stay under the Oyelabs developer's personal email.", issue: "Store accounts should be owned by the client, never tied to one person's personal email." },
          { id: "l5", text: "List of third-party services (Stripe, Twilio, Firebase) with account owners.", issue: null },
          { id: "l6", text: "Known issues and workarounds, including the open complaint about slow order history.", issue: null },
          { id: "l7", text: "Support response times: we will agree them with the client if something goes wrong.", issue: "SLAs and severity levels must be agreed in writing before launch, not during an incident." },
          { id: "l8", text: "Written client acceptance of the release and a lessons-learned session booked.", issue: null },
        ],
        askExplanation: true,
      },
      sop: [
        {
          title: "Our support SLAs, tiers and warranty",
          prompt: "[Oyelabs SOP – admin to fill] Support tiers or plans offered after launch, severity levels with response and resolution times, the warranty period and what it covers, the support channel clients use, the handover pack template, and where credentials are stored.",
        },
      ],
    },
  ],
} satisfies Module;
