import type { Module } from "@/types/curriculum";

export default {
  id: "pmp-e02",
  trackId: "pm",
  name: "Running-the-project templates",
  description:
    "The four documents that keep an agency project honest while it runs: minutes of meeting, the weekly RAG status report, the RAID log and the escalation matrix. For each one: when it is used, who fills, approves and receives it, a field-by-field walkthrough, and a practice task where you complete it from a real-looking scenario.",
  topics: [
    // -----------------------------------------------------------------------
    // MoM
    // -----------------------------------------------------------------------
    {
      id: "pmp-e02-mom",
      moduleId: "pmp-e02",
      trackId: "pm",
      title: "Minutes of meeting (MoM)",
      summary:
        "At an agency, the [[term:mom|minutes of meeting]] are the written memory of every client conversation. Clients forget what they agreed. Teams change. Six weeks later, a disputed feature or a missed date comes down to one question: what did we write down, and did anyone object? Good minutes turn a friendly call into a record of [[term:sign-off|decisions]], owners and dates.\n\nThe PM fills the MoM. The client [[term:spoc|SPOC]] and every attendee receive it, and internal [[term:stakeholder|stakeholders]] (tech lead, account manager) get a copy. Nobody formally signs it. Instead, the email asks attendees to reply with corrections by a set time, and silence is treated as agreement. Send it soon after the meeting, while memories match. When Oyelabs sends minutes is an Oyelabs rule: follow the rule in the handbook card below.\n\nMinutes are not a transcript. They record what was decided, what each person will do and by when, and what is still open. Any request that changes the [[term:scope-baseline|scope baseline]] is written as 'raise a [[term:change-request|CR]]', never as 'agreed to add'.\n\nThe common mistake is writing a summary of the discussion and stopping there. 'Discussed reminders' commits nobody to anything. 'Decision: reminders are out of scope; PM to send CR-006 by Tuesday 13 October' is what protects you when the client later says the reminders were promised.",
      level: "intermediate",
      estMinutes: 35,
      webRefs: [
        { label: "Confluence: Meeting minutes template", url: "https://www.atlassian.com/software/confluence/templates/meeting-notes", kind: "docs", verifiedAt: "2026-10-02T12:04:38Z" },
        { label: "Microsoft Support: Take meeting notes in Microsoft Teams", url: "https://support.microsoft.com/en-us/teams/meetings/take-meeting-notes-in-microsoft-teams", kind: "docs", verifiedAt: "2026-10-02T12:04:39Z" },
        { label: "Asana: Meeting Minutes template", url: "https://asana.com/templates/meeting-minutes", kind: "article", verifiedAt: "2026-10-02T12:04:39Z" },
        { label: "ProjectManager: Meeting Minutes template", url: "https://www.projectmanager.com/templates/meeting-minutes-template", kind: "article", verifiedAt: "2026-10-02T12:04:39Z" },
      ],
      video: {
        title: "How to write meeting minutes LIKE A PRO [With meeting minutes example!]",
        channel: "Emelie Lindström - Productivity & Work Skills",
        url: "https://www.youtube.com/watch?v=cST_Q5VpLRw",
        videoId: "cST_Q5VpLRw",
        verifiedAt: "2026-10-02T12:05:43Z",
      },
      alternateVideos: [
        {
          title: "Minutes of Meeting | How  to write Meeting Minutes | Format | Example | Exercise",
          channel: "Nihir Shah",
          url: "https://www.youtube.com/watch?v=NHsTLSN6ozo",
          videoId: "NHsTLSN6ozo",
          verifiedAt: "2026-10-02T12:05:43Z",
        },
      ],
      handbook: {
        stages: ["custom-client-kickoff", "custom-sprints", "wl-demo-call"],
        rules: ["mom-after-every-client-meeting", "cr-when-needed"],
        templates: ["mom"],
      },
      sections: [
        {
          heading: "When it is used and who owns it",
          body: "Write a [[term:mom|MoM]] after any client meeting where a decision, a scope point or an action came up. In practice that is almost every client meeting:\n\n- the client kickoff;\n- discovery workshops and the white-label demo call;\n- [[term:sprint]] demos and design reviews;\n- weekly status calls;\n- [[term:go-no-go]] meetings and escalation calls.\n\nInternal stand-ups do not need formal minutes. An [[term:eod-update|EOD update]] or the board covers them.\n\n**Who does what**\n\n- **Fills:** the PM. On a large call, a team member can take notes, but the PM edits and sends.\n- **Approves:** nobody signs. The email asks attendees to reply with corrections by a set time. No reply means the minutes stand.\n- **Receives:** every attendee, the client [[term:spoc|SPOC]] even if absent, and internal [[term:stakeholder|stakeholders]] such as the account manager.\n\nFor the deadline and channel, follow the Oyelabs rule in the handbook card below.",
        },
        {
          heading: "Field by field: what good entries look like",
          body: "Walk the template's sections in order.\n\n1. **Meeting details (title, date, time, attendees).** Good: 'Sprint 3 demo, Thu 8 Oct 2026, 3 pm BST. Client: Sarah (operations director, SPOC), Tom (clinic manager). Oyelabs: PM, tech lead, QA.' Include the time zone and each person's role. Mistake: first names only, so nobody knows later who had the authority to decide.\n2. **Agenda.** Copy the agenda you sent before the call. Mistake: leaving it out, so readers cannot see which planned items were skipped.\n3. **Discussion summary.** Two to five short bullets of context, not a transcript. Mistake: pages of 'he said, she said' that hide the decisions.\n4. **Decisions.** One line each, in plain words, naming who decided. Good: 'Booking flow approved as demoed (Sarah).' Mistake: 'Client seemed happy with the flow', which is a feeling, not a decision.\n5. **Action items (owner, due date).** Each action has a verb, one named owner and a real date. Good: 'Send CR for WhatsApp reminders – PM – Tue 13 Oct.' Client actions belong here too. Mistake: 'Team to look into it', or 'ASAP'.\n6. **Open questions.** Questions nobody could answer, with who will find out. Mistake: dropping them, so they surface again in UAT as surprises.\n7. **Next meeting.** Date, time and purpose. Mistake: 'next week', which nobody can put in a calendar.\n\nTwo rules cut across every field. First, a request that changes the [[term:scope-baseline|baseline]] is recorded as out of scope with a [[term:change-request|CR]] action, never as agreed work. Second, write neutral facts. Minutes may be forwarded to the client's CEO.",
        },
        {
          heading: "What good looks like: a worked example",
          body: "Project: a white-label grocery app rebranded for a supermarket chain in Oman. Meeting: the configuration review, Wednesday 14 October 2026, 11 am GST.\n\n**Decisions**\n\n- Delivery zones for Muscat approved as shown (client operations head).\n- Arabic is the default app language; English is the second language (client marketing lead).\n- A loyalty-points screen is not in the core product. It is out of scope for setup; PM to estimate it as a [[term:customisation]].\n\n**Action items**\n\n- Send the loyalty-points estimate and CR – PM – Mon 19 Oct.\n- Send live [[term:payment-gateway-account|payment gateway]] keys through the password manager – client finance lead – Thu 22 Oct.\n- Upload the Arabic store descriptions – client marketing lead – Fri 23 Oct.\n- Fix the splash-screen colour to the brand hex – Oyelabs developer – Fri 16 Oct.\n\n**Open question:** Does the chain charge a different delivery fee in Salalah? The client operations head will confirm by 19 October.\n\n**Next meeting:** UAT kickoff, Wednesday 28 October, 11 am GST.\n\nWhy this is good: every decision names who made it. Every action has one owner and a date. The loyalty request is fenced off as a CR instead of being quietly promised. And the payment keys action names the safe channel.",
        },
        {
          heading: "Common mistakes and how to recover",
          body: "- **Sent days late.** The client remembers the call differently, and the minutes start an argument. Recovery: send now, flag any point you are unsure of as 'to confirm', and ask for corrections by a set date.\n- **A scope request recorded as agreed.** 'Client asked for WhatsApp reminders, team to add' is a promise. Recovery: send a correction at once: 'Clarification: reminders are outside the signed scope; a CR with the estimate follows by Tuesday.' Do it before anyone starts work.\n- **Actions without owners or dates.** Nothing moves. Recovery: in the next meeting, read each open action aloud and get a name and a date.\n- **Only Oyelabs actions listed.** Client [[term:client-dependency|dependencies]] such as keys, content and accounts slip silently. Recovery: always add a client actions block and carry overdue ones into the [[term:status-report|status report]].\n- **The client disputes the minutes weeks later.** Recovery: point to the sent date and the correction window. If the dispute is real, record the corrected decision in the next minutes rather than editing old ones.\n- **Credentials pasted into the minutes.** Recovery: rotate the keys, delete the message where you can, and use the approved secure channel from now on.",
        },
        {
          heading: "Your checklist",
          body: "Before you press send:\n\n- Title, date, time zone and attendees with roles are there.\n- Every decision is one line and names who decided.\n- Every action has a verb, one owner and a calendar date.\n- Client actions are listed, not only Oyelabs actions.\n- Anything outside the [[term:scope-baseline|baseline]] is recorded as a [[term:change-request|CR]] action, not as agreed work.\n- Open questions name who will find the answer.\n- The next meeting has a date and a purpose.\n- No passwords, keys or personal opinions.\n- The email asks for corrections by a set time.\n- Overdue actions are carried into the next [[term:status-report|status report]].",
        },
      ],
      sop: [
        {
          title: "Where Oyelabs minutes are written, sent and stored",
          prompt: "[Oyelabs SOP – admin to fill] The MoM template and tool (Word, Teams notes, the tracker), the email subject format, who is always copied, the correction window wording, and where sent minutes are stored for each project.",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pmp-e02-mom-q1",
          prompt: "In a sprint demo for a Laravel booking platform, the client says 'Could patients also get a WhatsApp reminder the day before?' Reminders are not in the signed SOW. How should the minutes record it?",
          options: [
            "Decision: reminders are out of scope. Action: PM to send a CR with an estimate by a named date",
            "Decision: team to add WhatsApp reminders next sprint",
            "Leave it out of the minutes until the estimate is ready",
            "Discussion: client mentioned reminders",
          ],
          correctIndex: 0,
          explanation: "The minutes must fence the request off as a CR with an owner and a date. Writing 'team to add' turns it into a free promise, and leaving it out loses the trail.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-e02-mom-q2",
          prompt: "Which of these are well-written action items? (Select all that apply.)",
          options: [
            "Send live Stripe keys through the password manager – client finance lead – Thu 22 Oct",
            "Fix the old logo on the calendar page – tech lead – Wed 21 Oct",
            "Team to look into the reminder idea ASAP",
            "Client to send content soon",
          ],
          correctIndex: 0,
          correctIndices: [0, 1],
          explanation: "A good action has a verb, one named owner and a real date. 'Team' and 'client' are not owners, and 'ASAP' and 'soon' are not dates.",
        },
        {
          id: "pmp-e02-mom-q3",
          prompt: "Who normally fills and sends the MoM for a client meeting at an agency?",
          options: ["The PM", "The client SPOC", "The tech lead", "The account manager"],
          correctIndex: 0,
          explanation: "The PM owns the record of client meetings. Someone else can take notes on a busy call, but the PM edits and sends, because the PM is accountable for scope and actions.",
        },
        {
          id: "pmp-e02-mom-q4",
          prompt: "Two weeks after a demo, the client says 'We never agreed that the admin panel would be English only.' Your minutes, sent the same day, record that decision and nobody replied. What do you do?",
          options: [
            "Point calmly to the minutes and their correction window, then treat any new wish as a change request",
            "Rewrite the old minutes so they match what the client now says",
            "Agree to add Arabic for free to keep the relationship",
            "Tell the client the minutes are legally binding",
          ],
          correctIndex: 0,
          explanation: "Minutes that went out promptly with a correction window are your evidence. Editing them after the fact destroys their value. They are a record, not a contract, so claiming they are 'legally binding' overstates them.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-e02-mom-q5",
          prompt: "What is the main difference between minutes and a transcript?",
          options: [
            "Minutes record decisions, actions with owners and dates, and open questions; a transcript records everything said",
            "Minutes are shorter but contain the same content in the same order",
            "A transcript is sent to the client; minutes stay internal",
            "Minutes are only written for kickoffs",
          ],
          correctIndex: 0,
          explanation: "A recording or transcript is raw material. Minutes are the distilled outcome that people act on. Sending a transcript hides the decisions in noise.",
        },
        {
          id: "pmp-e02-mom-q6",
          prompt: "During a call, the client reads out the payment gateway's live secret key so the developer can 'note it down'. How should this appear in the minutes?",
          options: [
            "Not at all: record an action to share the keys through the approved secure channel, and ask for the key to be rotated if it was exposed",
            "In full, so the team can find it later",
            "With the middle characters masked",
            "In a separate attachment to the minutes email",
          ],
          correctIndex: 0,
          explanation: "Minutes are forwarded widely. Credentials never go in them, masked or attached. Record the action to use the secure channel instead.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-e02-mom-q7",
          prompt: "Which items belong in the 'Open questions' section? (Select all that apply.)",
          options: [
            "Whether therapists should see each other's calendars, which nobody on the call could answer",
            "Whether the delivery fee differs in Salalah, which the client will confirm by Monday",
            "The approved booking flow",
            "The date of the next demo",
          ],
          correctIndex: 0,
          correctIndices: [0, 1],
          explanation: "Open questions are unresolved points, ideally with who will find the answer. An approved flow is a decision, and the next demo date has its own field.",
        },
        {
          id: "pmp-e02-mom-q8",
          prompt: "Your minutes list five Oyelabs actions and none for the client, although the client promised brand assets and store account access. What risk does this create?",
          options: [
            "Client dependencies slip silently, and the delay later looks like Oyelabs' fault",
            "None: client actions are the client's business",
            "The client may feel micromanaged, so leaving them out is better",
            "The minutes become too long to read",
          ],
          correctIndex: 0,
          explanation: "Client dependencies drive many agency delays. If they are not in the minutes with dates, there is no record when they slip. Listing them is factual, not micromanagement.",
        },
        {
          id: "pmp-e02-mom-q9",
          prompt: "You wrote 'Decision: approved' in the minutes, but the person who said it was the client's junior designer, not the SPOC who approves designs. What is the best fix?",
          options: [
            "Record who said it and add an action for the SPOC to confirm the approval in writing",
            "Keep 'approved', since someone from the client said it",
            "Remove the item from the minutes",
            "Ask the junior designer to sign the minutes",
          ],
          correctIndex: 0,
          explanation: "A decision is only as good as the authority of the person who made it. Naming the decider shows the gap, and the action gets the real approval on record.",
        },
      ],
      practice: {
        kind: "form",
        variant: "mom",
        templateId: "mom",
        prompt: "You are the PM. Write the minutes of this sprint demo from the call notes below. Record decisions, every action with one owner and a due date, the open question and the next meeting. Remember the year is 2026.",
        context:
          "Sprint 3 demo – Laravel + React booking platform for a UK physio clinic chain. Thursday 8 October 2026, 3 pm BST, Teams.\n\nPresent: Client – Sarah (operations director, SPOC), Tom (clinic manager). Oyelabs – PM, tech lead, QA.\n\nPM: We demoed online booking and the therapist calendar. Feedback?\n\nSarah: The booking flow is great. Approved as shown.\n\nTom: Can patients get a WhatsApp reminder the day before? We lose a lot to no-shows.\n\nPM: Reminders are not in the signed scope. I will raise a change request with an estimate.\n\nSarah: Fine, send it by Tuesday the 13th.\n\nTom: The logo on the calendar page is the old one.\n\nTech lead: That is on us. We will fix it by Wednesday the 21st.\n\nSarah: I still owe you the cancellation policy text. I will send it Monday the 12th.\n\nPM: We also need the Stripe live keys before UAT, through the password manager, not email.\n\nSarah: I will ask finance. Aim for Friday the 16th.\n\nTom: Should therapists see each other's calendars? Nobody here knows.\n\nPM: Let us keep that open; Sarah, could you check with the clinical lead before the next demo?\n\nSarah: Yes.\n\nPM: Next demo is Thursday 22 October, same time.",
        fields: [
          { id: "title", label: "Meeting title", input: "text", required: true },
          { id: "date", label: "Meeting date", input: "date", required: true },
          { id: "attendees", label: "Attendees (name, side and role)", input: "textarea", required: true },
          { id: "decisions", label: "Decisions", input: "textarea", required: true },
          { id: "actions", label: "Action items (action – owner – due date)", input: "textarea", required: true },
          { id: "actionCount", label: "How many action items did you record?", input: "number", required: true },
          {
            id: "crItem",
            label: "Which request must go through a change request?",
            input: "select",
            options: ["WhatsApp reminders", "Old logo on the calendar page", "Cancellation policy text", "Stripe live keys"],
            required: true,
          },
          { id: "openQuestions", label: "Open questions (and who will answer)", input: "textarea", required: true },
          { id: "nextMeeting", label: "Next meeting date", input: "date", required: true },
        ],
        checks: [
          { fieldId: "date", expected: "2026-10-08" },
          { fieldId: "actionCount", expected: 5 },
          { fieldId: "crItem", expected: "WhatsApp reminders" },
          { fieldId: "nextMeeting", expected: "2026-10-22" },
        ],
        rubric: [
          { label: "Decisions are explicit and name who decided", points: 2, description: "Lists the booking-flow approval by Sarah and records WhatsApp reminders as out of scope, pending a CR. No feelings or discussion recap in the decisions." },
          { label: "Every action has one owner and a real date", points: 3, description: "Five actions: CR (PM, 13 Oct), logo fix (tech lead, 21 Oct), cancellation text (Sarah, 12 Oct), Stripe keys via password manager (Sarah/finance, 16 Oct), calendar-visibility answer (Sarah, before 22 Oct). Client actions included." },
          { label: "Scope and security handled correctly", points: 2, description: "Reminders are not written as agreed work. The keys action names the secure channel, and no credentials appear." },
          { label: "Clear and neutral", points: 1, description: "Short lines, roles given, neutral wording a client CEO could read." },
        ],
        sampleAnswer: {
          title: "Sprint 3 demo – clinic booking platform",
          date: "2026-10-08",
          attendees: "Client: Sarah (operations director, SPOC), Tom (clinic manager). Oyelabs: PM, tech lead, QA.",
          decisions: "1. Booking flow approved as demoed (Sarah).\n2. WhatsApp day-before reminders are outside the signed scope; they will be estimated as a change request (agreed by Sarah).",
          actions: "1. Send CR with estimate for WhatsApp reminders – PM – Tue 13 Oct.\n2. Replace the old logo on the calendar page – tech lead – Wed 21 Oct.\n3. Send cancellation policy text – Sarah – Mon 12 Oct.\n4. Share Stripe live keys through the password manager (not email) – Sarah with client finance – Fri 16 Oct.\n5. Confirm with the clinical lead whether therapists may see each other's calendars – Sarah – before Thu 22 Oct.",
          actionCount: "5",
          crItem: "WhatsApp reminders",
          openQuestions: "Should therapists see each other's calendars? Sarah to confirm with the clinical lead before the next demo.",
          nextMeeting: "2026-10-22",
        },
      },
    },
    // -----------------------------------------------------------------------
    // RAG status report
    // -----------------------------------------------------------------------
    {
      id: "pmp-e02-status-report",
      moduleId: "pmp-e02",
      trackId: "pm",
      title: "RAG status report",
      summary:
        "The weekly [[term:status-report|status report]] is the one page a busy client sponsor actually reads. It says, in a few seconds, whether the project is on track, and if not, what the client must do about it. At an agency, it is also your early-warning record. If go-live slips in week 12, the reports from weeks 8 to 11 show whether you warned the client in time.\n\nThe PM fills it from the board, the [[term:raid-log|RAID log]] and the week's minutes. The client sponsor and [[term:spoc|SPOC]] receive it, with internal [[term:stakeholder|stakeholders]] copied. The tech lead checks the facts before it goes. How often and when it is sent is an Oyelabs rule: follow the rule in the handbook card below.\n\nThe heart of the report is the [[term:rag-status|RAG status]]: Green, Amber or Red, overall and for schedule, scope and budget. ProjectManager describes Amber as within about 10% of target and still deliverable within approved tolerances. That band is typical, not universal: some teams use 5%, others up to 20%. Use the thresholds your project agreed.\n\nThe common mistake is the 'watermelon' report: green outside, red inside. A PM keeps it green to avoid an awkward call, then jumps straight to Red. An honest Amber three weeks early, with a named client action, is worth far more than a surprise Red.",
      level: "intermediate",
      estMinutes: 40,
      webRefs: [
        { label: "Confluence: Project status report template", url: "https://www.atlassian.com/software/confluence/templates/project-status", kind: "docs", verifiedAt: "2026-10-02T12:04:40Z" },
        { label: "ProjectManager: RAG Status in Project Management", url: "https://www.projectmanager.com/blog/rag-status", kind: "article", verifiedAt: "2026-10-02T12:04:40Z" },
        { label: "Asana: Status Report template for projects", url: "https://asana.com/templates/status-report", kind: "article", verifiedAt: "2026-10-02T12:04:41Z" },
        { label: "ProjectManager: Project Status Reports guide", url: "https://www.projectmanager.com/guides/status-report", kind: "article", verifiedAt: "2026-10-02T12:04:40Z" },
      ],
      video: {
        title: "What is a RAG Report? ...or a Traffic Light Report?",
        channel: "Online PM Courses - Mike Clayton",
        url: "https://www.youtube.com/watch?v=xadyhn3GjJc",
        videoId: "xadyhn3GjJc",
        verifiedAt: "2026-10-02T12:05:43Z",
      },
      alternateVideos: [
        {
          title: "How to Use RAG Status in Project Status Reports",
          channel: "Stuart Taylor - Project Management",
          url: "https://www.youtube.com/watch?v=Z6N5NypIJmg",
          videoId: "Z6N5NypIJmg",
          verifiedAt: "2026-10-02T12:05:43Z",
        },
      ],
      handbook: {
        stages: ["custom-sprints", "custom-support", "wl-configuration"],
        rules: ["weekly-status-report"],
        templates: ["status-report-rag"],
      },
      sections: [
        {
          heading: "When it is used and who owns it",
          body: "Send a [[term:status-report|status report]] every week for every active project: custom builds, white-label setups and active support plans. Send it even in a quiet week. A missing report makes clients assume bad news.\n\n**Who does what**\n\n- **Fills:** the PM, from the board, the [[term:raid-log|RAID log]], the week's [[term:mom|minutes]] and the plan.\n- **Checks:** the tech lead confirms the delivery facts. The account manager sees any budget or [[term:change-request|CR]] lines before a Red goes out.\n- **Receives:** the client sponsor and [[term:spoc|SPOC]], plus internal stakeholders.\n- **Approves:** nobody signs. But any 'decision needed' line is a real request, and it must be chased.\n\nThe report is not the place to break bad news for the first time. If the status moves to Red, call the sponsor first, then send the report. For the cadence, follow the Oyelabs rule in the handbook card below.",
        },
        {
          heading: "Field by field: header and RAG",
          body: "1. **Project.** The name the client uses, plus the type. Good: 'White-label grocery app – Oman supermarket chain'.\n2. **Reporting week.** The week number and the end date. Good: 'Week 7 (ending Fri 16 Oct 2026)'. Mistake: no date, so old reports cannot be compared.\n3. **Overall RAG.** One colour. It is a judgement, not an average. It is usually as bad as the worst dimension that threatens a committed date or cost.\n4. **Schedule RAG.** Compare forecast dates with baseline [[term:milestone|milestones]]. A typical rule: Green on track; Amber at risk but recoverable inside the agreed tolerance (ProjectManager's example is within about 10%); Red when a committed date will be missed without a change of plan.\n5. **Scope RAG.** Green when work matches the signed baseline. Amber when requests are pending as CRs, or [[term:scope-creep|creep]] is building. Red when the team is building unapproved work.\n6. **Budget RAG.** Spend against the approved budget, including approved CRs. On a fixed bid, this is Oyelabs' effort burn. Agree internally how much of that the client sees.\n\nEvery Amber or Red needs one line saying why, and what brings it back to Green. A colour without a reason is noise.\n\nSome reports add Blue for complete, or Grey for not enough information. Only use them if the client has seen the key.",
        },
        {
          heading: "Field by field: the narrative",
          body: "7. **Completed this week.** Outcomes the client recognises, not tickets. Good: 'Customer and driver apps rebranded; three cities configured.' Mistake: pasting 40 ticket titles.\n8. **Planned next week.** Three to five outcomes. Next week's report checks them, so do not over-promise.\n9. **Milestones and dates.** Baseline date, forecast date, and the change. Good: 'Go-live: baseline 6 Nov, forecast 13 Nov (+1 week).' Mistake: quietly changing the baseline.\n10. **Top risks.** The two or three that matter, each with an owner and a response, taken from the [[term:raid-log|RAID log]].\n11. **Open issues.** Problems happening now, with an owner and the next step.\n12. **Decisions needed from client.** The decision, who makes it, by when, and the impact of no answer. Good: 'Confirm delivery fee per zone – client operations head – by Tue 20 Oct – otherwise checkout configuration slips.'\n13. **Client dependencies due.** Keys, content and accounts, with due dates. Mark overdue ones clearly. They often explain your Amber.\n14. **Comments.** Anything else, briefly. Mistake: hiding the real news here, under the RAG line, where nobody reads it.",
        },
        {
          heading: "What good looks like: a worked example",
          body: "Project: a React Native fitness app for a US client. Week 9, ending Friday 23 October 2026.\n\n- **Overall: Amber.** **Schedule: Amber.** **Scope: Green.** **Budget: Green.**\n- **Why Amber:** the App Store build is ready, but the client's [[term:apple-developer-account|Apple Developer]] organisation enrolment is still pending. If it is not approved by 30 October, the store launch moves from 9 to 16 November.\n- **Completed:** subscription paywall finished and tested; workout history synced across devices; 18 of 22 sprint stories done.\n- **Next week:** final regression; [[term:uat]] build to the client; store screenshots.\n- **Milestones:** UAT start, baseline 26 Oct, forecast 26 Oct. Store launch, baseline 9 Nov, forecast 9 Nov at risk.\n- **Top risk:** Apple enrolment delay – client SPOC – the client has called Apple support; PM checking daily.\n- **Decision needed:** approve the free-trial length (7 or 14 days) – client product owner – by Tue 27 Oct.\n- **Client dependencies:** privacy policy URL, due 21 Oct, overdue.\n\nWhy this is good: the colour has a reason, a date and a recovery path. The client can see exactly which of their actions moves it back to Green.",
        },
        {
          heading: "Common mistakes and how to recover",
          body: "- **The watermelon report.** Green for weeks, then a sudden Red. Recovery: call the sponsor today, explain plainly what you knew and when, and send a Red report with options: descope, add effort at a cost, or move the date. From now on, report Amber early.\n- **Amber forever.** A project Amber for six weeks with no change teaches the client to ignore the colour. Recovery: either the risk is real, so escalate it, or it is managed, so it goes back to Green.\n- **Red as a weapon.** Marking Red to pressure the client over a late dependency. Recovery: state the dependency and its impact factually. The colour reflects the project, not blame.\n- **Decisions buried.** A decision request in Comments goes unanswered. Recovery: move it to its own line with an owner and a date, and ask for it in the next call.\n- **Numbers that do not match the board.** The client checks Jira and loses trust. Recovery: have the tech lead confirm the facts before sending.\n- **Missed week.** Recovery: send it now and say so briefly. Do not skip to next week as if nothing happened.",
        },
        {
          heading: "Your checklist",
          body: "- Project and week-ending date are correct.\n- Overall, schedule, scope and budget RAG are all set.\n- Every Amber or Red has a reason and a path back to Green.\n- Completed and next-week items are client-readable outcomes.\n- Milestones show baseline and forecast, not a silently moved date.\n- Top risks and issues come from the [[term:raid-log|RAID log]], with owners.\n- Each decision needed has an owner, a deadline and the impact of no answer.\n- Overdue [[term:client-dependency|client dependencies]] are flagged.\n- The tech lead has checked the numbers.\n- If anything turned Red, you called the sponsor before sending.",
        },
      ],
      sop: [
        {
          title: "Oyelabs RAG thresholds and report format",
          prompt: "[Oyelabs SOP – admin to fill] The thresholds Oyelabs uses for Green, Amber and Red on schedule, scope and budget, whether budget RAG is shown to fixed-bid clients, the report tool and file format, and the send day and time.",
        },
        {
          title: "Internal review before a Red report",
          prompt: "[Oyelabs SOP – admin to fill] Who must see a report before it goes out Red (delivery head, account manager), and how quickly the client sponsor must be called.",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pmp-e02-status-report-q1",
          prompt: "Go-live is 6 November. The client's payment gateway live keys are a week overdue. If they arrive by 21 October, the date holds; if not, go-live slips about a week. Under a typical RAG rule, what is the schedule status?",
          options: ["Amber", "Green", "Red", "Grey"],
          correctIndex: 0,
          explanation: "The date is at risk but still recoverable with a known client action, which is Amber under a typical rule. Red means a committed date will be missed without a change of plan; that is not yet true.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-e02-status-report-q2",
          prompt: "A PM has reported Green for five weeks while knowing the integration was behind, then reports Red one week before UAT. What is this pattern called, and what is the main damage?",
          options: [
            "A watermelon report: the client lost the chance to act early and stops trusting the colours",
            "Optimism bias: no real damage, since the final status was honest",
            "Scope creep: the client added too much work",
            "Gold-plating: the team built more than needed",
          ],
          correctIndex: 0,
          explanation: "Green outside, red inside. The harm is the lost warning time and the lost trust. Being honest at the end does not undo either.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-e02-status-report-q3",
          prompt: "Which belong in a good 'Decisions needed from client' line? (Select all that apply.)",
          options: [
            "The decision itself, stated plainly",
            "Who on the client side makes it",
            "The deadline, and what slips if there is no answer",
            "The developer who will build it",
            "A list of all closed tickets",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "A decision request needs what, who and by when, plus the impact of no answer, so the sponsor can act. The developer and ticket list are delivery detail.",
        },
        {
          id: "pmp-e02-status-report-q4",
          prompt: "ProjectManager describes Amber as roughly 'within 10 percent' of target. How should you treat that figure on an Oyelabs project?",
          options: [
            "As a typical value; use the thresholds agreed for your project",
            "As an industry standard every client expects",
            "As a contractual limit",
            "As irrelevant, because RAG is purely a gut feeling",
          ],
          correctIndex: 0,
          explanation: "The same source says the band can be 5% or up to 20%. It is a typical value, not a standard. RAG is a judgement, but it should rest on agreed thresholds.",
        },
        {
          id: "pmp-e02-status-report-q5",
          prompt: "A client asks you to add a referral programme, and the team has started building it before the CR is approved. What is the scope RAG?",
          options: ["Red", "Green", "Amber", "Blue"],
          correctIndex: 0,
          explanation: "Building unapproved work is uncontrolled scope change, and it puts budget and dates at risk. A pending CR with no work started would typically be Amber.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-e02-status-report-q6",
          prompt: "Your status will move to Red for the first time this week. What should you do before sending the report?",
          options: [
            "Call the client sponsor, explain the cause and the options, then send the report",
            "Send the report and wait for the client to call",
            "Keep it Amber one more week in case the team catches up",
            "Copy the client's CEO so the news gets attention",
          ],
          correctIndex: 0,
          explanation: "A Red should never be a surprise in an inbox. A short call first lets you present options. Holding it Amber is the watermelon mistake.",
        },
        {
          id: "pmp-e02-status-report-q7",
          prompt: "Which entries make good 'Completed this week' lines for a client? (Select all that apply.)",
          options: [
            "Customer and driver apps rebranded with the new colours and logo",
            "Three cities configured with delivery zones",
            "JIRA-4512, JIRA-4519, JIRA-4520 closed",
            "Refactored the OrderService class",
          ],
          correctIndex: 0,
          correctIndices: [0, 1],
          explanation: "Clients read outcomes they recognise. Ticket numbers and internal refactors mean nothing to a sponsor; keep them on the board.",
        },
        {
          id: "pmp-e02-status-report-q8",
          prompt: "A project has sat at Amber for six weeks for the same reason, and nothing has changed. What is the best next step?",
          options: [
            "Decide whether the risk is real and escalate it, or managed and back to Green",
            "Keep reporting Amber; it is accurate",
            "Switch to Red to get attention",
            "Remove the RAG line until it changes",
          ],
          correctIndex: 0,
          explanation: "A permanent Amber teaches the client to ignore the colour. Either act on the risk through escalation or accept it is controlled. Red should reflect facts, not a wish for attention.",
        },
        {
          id: "pmp-e02-status-report-q9",
          prompt: "Where should the top risks in the status report come from?",
          options: [
            "The project's RAID log, with the same owners and responses",
            "Whatever the PM remembers on Friday afternoon",
            "The client's own risk list only",
            "The sales proposal",
          ],
          correctIndex: 0,
          explanation: "The RAID log is the single register. Pulling from it keeps the report consistent week to week, and it means each risk has an owner and a response.",
        },
      ],
      practice: {
        kind: "form",
        variant: "status",
        templateId: "status-report-rag",
        prompt: "Write this week's status report from the board export and the PM's notes. Use the RAG rule given in the notes.",
        context:
          "Board export – white-label grocery app, Oman supermarket chain – week ending Friday 16 October 2026\n\n| Item | Type | Status | Owner |\n|---|---|---|---|\n| Rebrand customer app | Story | Done | Developer |\n| Rebrand driver app | Story | Done | Developer |\n| Configure 3 cities and zones | Story | Done | PM |\n| Arabic RTL review | Story | In QA | QA |\n| Loyalty points custom module (CR-002, approved) | Story | In progress, 60% | Developer |\n| Store screenshots | Story | Not started | Designer |\n| Payment gateway live keys | Client dependency | Overdue, was due 9 Oct | Client SPOC |\n| Apple organisation enrolment | Client dependency | Waiting for D-U-N-S | Client SPOC |\n\nPM notes: go-live baseline is Friday 6 November. Without the gateway keys by Wednesday 21 October, payment QA cannot finish and go-live slips about one week. Spend is within the approved budget including CR-002. No unapproved work. RAG rule for this project: Green on track; Amber when a date is at risk but recoverable with a named action; Red when a committed date will be missed without a change of plan. The client must still confirm the delivery fee per zone.",
        fields: [
          { id: "project", label: "Project", input: "text", required: true },
          { id: "weekEnding", label: "Week ending", input: "date", required: true },
          { id: "overall", label: "Overall RAG", input: "select", options: ["Green", "Amber", "Red"], required: true },
          { id: "schedule", label: "Schedule RAG", input: "select", options: ["Green", "Amber", "Red"], required: true },
          { id: "scope", label: "Scope RAG", input: "select", options: ["Green", "Amber", "Red"], required: true },
          { id: "budget", label: "Budget RAG", input: "select", options: ["Green", "Amber", "Red"], required: true },
          { id: "storiesDone", label: "Stories done this week", input: "number", required: true },
          { id: "completed", label: "Completed this week", input: "textarea", required: true },
          { id: "next", label: "Planned next week", input: "textarea", required: true },
          { id: "risks", label: "Top risks and open issues (owner, response)", input: "textarea", required: true },
          { id: "decisions", label: "Decisions needed and client dependencies due", input: "textarea", required: true },
        ],
        checks: [
          { fieldId: "weekEnding", expected: "2026-10-16" },
          { fieldId: "overall", expected: "Amber" },
          { fieldId: "schedule", expected: "Amber" },
          { fieldId: "scope", expected: "Green" },
          { fieldId: "budget", expected: "Green" },
          { fieldId: "storiesDone", expected: 3 },
        ],
        rubric: [
          { label: "Explains the Amber and the way back to Green", points: 3, description: "States that go-live on 6 Nov is at risk by about a week unless the overdue gateway keys arrive by 21 Oct, and names the client SPOC as owner." },
          { label: "Client-readable progress", points: 2, description: "Completed and next-week items are outcomes (rebranded apps, cities configured; RTL QA, loyalty module, screenshots), not ticket ids." },
          { label: "Decisions and dependencies are actionable", points: 2, description: "Delivery fee per zone has an owner and a deadline; gateway keys flagged overdue; Apple enrolment / D-U-N-S listed as a risk with owner." },
          { label: "Concise and factual", points: 1, description: "No blame, no padding; the sponsor can read it in under a minute." },
        ],
        sampleAnswer: {
          project: "White-label grocery app – Oman supermarket chain",
          weekEnding: "2026-10-16",
          overall: "Amber",
          schedule: "Amber",
          scope: "Green",
          budget: "Green",
          storiesDone: "3",
          completed: "Customer and driver apps rebranded. Three cities and their delivery zones configured.",
          next: "Finish Arabic RTL QA. Loyalty points module (CR-002) to QA. Start store screenshots. Payment QA as soon as the live keys arrive.",
          risks: "Issue: payment gateway live keys overdue since 9 Oct – client SPOC – needed by Wed 21 Oct, otherwise go-live moves from 6 Nov to about 13 Nov. Risk: Apple organisation enrolment waiting for D-U-N-S – client SPOC – PM checking twice a week; could delay the iOS release.",
          decisions: "Decision: confirm delivery fee per zone – client SPOC – by Tue 20 Oct, otherwise checkout configuration slips. Dependencies: gateway live keys via the password manager (overdue, needed by 21 Oct); D-U-N-S number for Apple enrolment.",
        },
      },
    },
    // -----------------------------------------------------------------------
    // RAID log
    // -----------------------------------------------------------------------
    {
      id: "pmp-e02-raid-log",
      moduleId: "pmp-e02",
      trackId: "pm",
      title: "RAID log",
      summary:
        "A [[term:raid-log|RAID log]] is one register of the things that can sink a project: [[term:risk|risks]], [[term:assumption|assumptions]], [[term:issue|issues]] and [[term:dependency|dependencies]]. Agencies differ on the letters: some read A as actions and D as decisions. The Oyelabs template uses risks, assumptions, issues and dependencies.\n\nThe four types are easy to mix up, and the difference drives what you do. A risk has not happened yet: you reduce its chance or impact. An issue is happening now: you resolve it. An assumption is something you planned on as true: you validate it, and if it proves false it becomes an issue or a [[term:change-request|CR]]. A dependency is something you need from someone else: you track the date and chase the owner. At an agency, most dependencies are [[term:client-dependency|client dependencies]]: store accounts, keys, content, data.\n\nThe PM owns the log. It starts at the BD handover from the SOW's assumptions and the sales notes. It grows at the internal kickoff with a pre-mortem, and it is reviewed every week. Each entry has one owner, often on the client side. The client sees the relevant items through the [[term:status-report|status report]] and its top risks.\n\nThe common mistake is a log written once at kickoff and never opened again. A stale log is worse than none, because it gives false comfort. A second mistake is never closing the loop. A risk that happens must be moved to issues, and a broken assumption must be raised with the client at once, because it usually means a change to scope, date or cost.",
      level: "advanced",
      estMinutes: 45,
      isMilestone: true,
      webRefs: [
        { label: "Confluence: Risk register template", url: "https://www.atlassian.com/software/confluence/templates/risk-register", kind: "docs", verifiedAt: "2026-10-02T12:04:42Z" },
        { label: "Atlassian Team Playbook: Dependency Mapping", url: "https://www.atlassian.com/team-playbook/plays/dependency-mapping", kind: "docs", verifiedAt: "2026-10-02T12:04:41Z" },
        { label: "Asana: RAID Log (risks, assumptions, issues, decisions)", url: "https://asana.com/resources/raid-log", kind: "article", verifiedAt: "2026-10-02T12:04:43Z" },
        { label: "ProjectManager: What Is a RAID Log and Why Use One?", url: "https://www.projectmanager.com/blog/raid-log-use-one", kind: "article", verifiedAt: "2026-10-02T12:04:42Z" },
      ],
      video: {
        title: "How to Use RAID Log in REAL-LIFE Project (+ Template)",
        channel: "Tactical Project Manager",
        url: "https://www.youtube.com/watch?v=inZI16nIvdo",
        videoId: "inZI16nIvdo",
        verifiedAt: "2026-10-02T12:05:44Z",
      },
      alternateVideos: [
        {
          title: "RAID Log in Project Management (FREE Risk Register Template Included!)",
          channel: "Alvin the PM - Become a Certified Project Manager",
          url: "https://www.youtube.com/watch?v=1i_pYJXs-H0",
          videoId: "1i_pYJXs-H0",
          verifiedAt: "2026-10-02T12:05:44Z",
        },
      ],
      handbook: {
        stages: ["custom-bd-handover", "custom-internal-kickoff", "custom-sprints"],
        rules: ["weekly-status-report"],
        templates: ["raid-log-template"],
      },
      sections: [
        {
          heading: "When it is used and who owns it",
          body: "The [[term:raid-log|RAID log]] lives for the whole project.\n\n- **BD handover:** seed it from the SOW's [[term:assumption|assumptions]] and [[term:client-dependency|client dependencies]], and from anything sales promised.\n- **Internal kickoff:** add [[term:risk|risks]] from a pre-mortem. The team imagines the project has failed and lists why.\n- **Every week:** review it before writing the [[term:status-report|status report]]. Asana's advice is to review the RAID log during weekly status meetings.\n- **Closure:** carry what was learned into the closure report.\n\n**Who does what**\n\n- **Fills and maintains:** the PM. The tech lead adds technical risks.\n- **Owns each entry:** one named person per line, Oyelabs or client.\n- **Receives:** the delivery team sees all of it. The client sees the items that need them, through the status report or a shared view. Some agencies share the whole log; agree this at kickoff.",
        },
        {
          heading: "Telling the four types apart",
          body: "Ask one question per entry: **has it happened, and whose is it?**\n\n- **[[term:risk|Risk]]:** an uncertain future event that would hurt scope, time, cost or quality. 'Apple enrolment may take weeks because the client has no D-U-N-S number.' Response: reduce the chance or the impact.\n- **[[term:issue|Issue]]:** a problem happening now. 'The payment sandbox has been down for two days; checkout testing is blocked.' Response: resolve or escalate.\n- **[[term:assumption|Assumption]]:** something the plan treats as true without proof. 'The client's existing API returns product stock in real time.' Response: validate it early. If it is false, raise it with the client as an issue, and often as a [[term:change-request|CR]].\n- **[[term:dependency|Dependency]]:** something the project needs from someone else, by a date. 'Courier API documentation from the client's logistics partner by week 6.' Response: track the date and chase the owner.\n\nTwo traps. First, the same topic can change type. A dependency that misses its date becomes an issue. A risk that happens becomes an issue. Move it and link the IDs; do not just edit the text. Second, a risk worded as a certainty ('the client will be late') is either an issue or an opinion. Write risks as 'may … because …, which would …'.",
        },
        {
          heading: "Field by field: what good entries look like",
          body: "1. **ID.** A type prefix and number: R-03, A-02, I-05, D-01. Never reuse an ID.\n2. **Type.** Risk, assumption, issue or dependency.\n3. **Description.** Cause, event and effect in one sentence. Good: 'Client has no D-U-N-S number, so Apple enrolment may take weeks, which would delay iOS release.' Mistake: 'Apple account'.\n4. **Raised on.** The date it was logged.\n5. **Owner.** One named person, client side when the action is theirs. Mistake: 'Client' or 'Team'.\n6. **Likelihood** and 7. **Impact.** Use the project's scale, for example 1 to 3 or low, medium, high. Mostly for risks.\n8. **Rating.** Likelihood × impact, to sort the list. The top few go into the status report.\n9. **Response or action.** A concrete next step. Good: 'Start D-U-N-S request in week 1; PM checks status each Monday.' Mistake: 'Monitor'.\n10. **Due date.** When the action or dependency is due.\n11. **Status.** Open, in progress, closed, or moved to issue (with the new ID).\n12. **Last reviewed.** The date of the last weekly review. Mistake: dates that are months old, which shows the log is dead.",
        },
        {
          heading: "What good looks like: a worked example",
          body: "Project: a Laravel school-management system for a client in Kenya. Week 4 review.\n\n- **A-01, assumption.** Client provides existing student data in the agreed CSV format by week 5. Owner: client IT lead. Action: ask for a 50-row sample this week to validate the format. Status: open.\n- **R-02, risk.** Exam results are published on one day for 3,000 parents, which may overload the shared hosting and slow the parent app. Owner: tech lead. Likelihood medium, impact high. Action: load-test in week 10; propose a hosting upgrade to the client if needed.\n- **D-03, dependency.** M-Pesa payment API credentials from the client's bank. Owner: client finance lead. Due: week 7. Status: requested.\n- **I-04, issue.** The client's sample CSV has no class field. Raised from A-01 when the sample arrived. Owner: PM. Action: agree a mapping with the client IT lead by Friday; assess whether the import needs a CR. A-01 is closed and linked to I-04.\n\nWhy this is good: each line has one owner and a concrete action. The failed assumption was found early with a sample and turned into a tracked issue, not left to surface in UAT.",
        },
        {
          heading: "Common mistakes and how to recover",
          body: "- **Written once, never reviewed.** Recovery: book a 15-minute weekly review, update 'Last reviewed', and close stale lines.\n- **Everything is a risk.** Issues and dependencies hidden as risks never get chased. Recovery: re-sort with the question 'has it happened, and whose is it?'\n- **Owner is 'client'.** Nobody acts. Recovery: name the person and confirm in the next call.\n- **Responses that say 'monitor'.** Recovery: replace with an action that changes the chance or impact, with a date.\n- **A broken assumption absorbed silently.** The team works extra to cover it, and the budget bleeds. Recovery: raise it with the client now, as an issue with an impact. If it changes scope, time or cost, it needs a [[term:change-request|CR]].\n- **Too many lines.** A 120-line log hides the five that matter. Recovery: sort by rating, close what is closed, and report the top three.",
        },
        {
          heading: "Your checklist",
          body: "- Seeded from the SOW's assumptions and dependencies at handover.\n- Pre-mortem risks added at the internal kickoff.\n- Every entry has a type, one named owner, an action and a date.\n- Risks are worded as 'may … because …, which would …'.\n- Assumptions have a validation step and date.\n- Overdue dependencies and risks that happened are moved to issues with linked IDs.\n- Reviewed every week, with 'Last reviewed' updated.\n- The top items flow into the [[term:status-report|status report]].\n- Broken assumptions are raised with the client, not absorbed.",
        },
      ],
      sop: [
        {
          title: "Oyelabs RAID log location and rating scale",
          prompt: "[Oyelabs SOP – admin to fill] Where the RAID log lives (sheet, tracker), the likelihood and impact scale Oyelabs uses, whether the full log is shared with clients, and who reviews it with the PM each week.",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pmp-e02-raid-log-q1",
          prompt: "Kickoff for a white-label food-delivery app. The client says 'We'll get the Apple developer account sorted.' They do not yet have a D-U-N-S number. How should this go in the RAID log?",
          options: [
            "As a dependency on the client SPOC with a due date, plus a risk that enrolment may take weeks",
            "As an issue, because the account does not exist yet",
            "As an assumption that the account will be ready in time, with no owner",
            "It does not belong in the log; it is the client's job",
          ],
          correctIndex: 0,
          explanation: "The account is something the project needs from the client by a date, which is a dependency, and the D-U-N-S wait creates a real risk. Nothing has gone wrong yet, so it is not an issue.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-e02-raid-log-q2",
          prompt: "The SOW says 'Estimate assumes the client's existing API returns stock levels in real time.' In sprint 3 the team finds it only updates nightly. What happens in the RAID log?",
          options: [
            "Close the assumption, open a linked issue, and raise the impact with the client, likely as a CR",
            "Leave the assumption open and let the team work around it",
            "Change the assumption's text to say 'nightly'",
            "Record it as a new risk",
          ],
          correctIndex: 0,
          explanation: "A false assumption is now a real problem, so it becomes an issue. Because the estimate rested on it, the extra work usually changes scope, time or cost. Editing the text hides the history.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-e02-raid-log-q3",
          prompt: "Which of these are issues rather than risks? (Select all that apply.)",
          options: [
            "The payment sandbox has been down for two days and checkout testing is blocked",
            "The client's designer left last week and nobody is approving screens",
            "Store review may reject the app because of the subscription wording",
            "Traffic on results day may overload the server",
          ],
          correctIndex: 0,
          correctIndices: [0, 1],
          explanation: "Issues are happening now. The sandbox outage and the missing approver are current problems. Store rejection and overload are uncertain future events, so they are risks.",
        },
        {
          id: "pmp-e02-raid-log-q4",
          prompt: "Which risk description is written best?",
          options: [
            "The client has no D-U-N-S number, so Apple enrolment may take weeks, which would delay the iOS release",
            "Apple account",
            "The client will definitely be late with Apple",
            "Risk of delays",
          ],
          correctIndex: 0,
          explanation: "Cause, event and effect make the risk actionable and ratable. A certainty is an issue or an opinion, and one-word entries cannot be acted on.",
        },
        {
          id: "pmp-e02-raid-log-q5",
          prompt: "A risk line's response says 'Monitor'. Why is that weak?",
          options: [
            "It changes neither the chance nor the impact and sets no date, so nothing actually happens",
            "Monitoring is only allowed for issues",
            "Risks should never have a response",
            "It is fine; monitoring is the standard response",
          ],
          correctIndex: 0,
          explanation: "A good response is an action with an owner and a date that reduces likelihood or impact, for example 'load-test in week 10'. 'Monitor' often means nobody looks again.",
        },
        {
          id: "pmp-e02-raid-log-q6",
          prompt: "The courier's API documentation was due from the client's logistics partner in week 6. It is now week 8 and integration is blocked. What should happen to the dependency line?",
          options: [
            "Move it to an issue with a linked ID, an owner and an escalation step",
            "Keep it as a dependency and change the due date to week 10",
            "Delete it, since it is late",
            "Turn it into an assumption",
          ],
          correctIndex: 0,
          explanation: "A missed dependency that blocks work is a current problem: an issue. Quietly pushing the date hides the slip from the status report.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-e02-raid-log-q7",
          prompt: "When should a RAID log normally be first created and then reviewed? (Select all that apply.)",
          options: [
            "Seeded at the BD handover from the SOW's assumptions and dependencies",
            "Extended at the internal kickoff with a pre-mortem",
            "Reviewed weekly, before the status report",
            "Created only after the first issue appears",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "The log is most useful when it starts before the work and is kept alive weekly. Waiting for the first issue misses the point of risk management.",
        },
        {
          id: "pmp-e02-raid-log-q8",
          prompt: "Some agencies read the A and D in RAID as 'actions' and 'decisions'. What should a PM do on a project where the client uses that version?",
          options: [
            "Agree the meaning at kickoff and keep assumptions and dependencies tracked somewhere visible",
            "Insist the client is wrong",
            "Stop tracking dependencies",
            "Keep two separate logs with the same name",
          ],
          correctIndex: 0,
          explanation: "Both readings are in use. What matters is a shared meaning, and that client dependencies and assumptions are still tracked, because they drive most agency delays.",
        },
        {
          id: "pmp-e02-raid-log-q9",
          prompt: "The log has 110 open lines, most untouched for two months. What is the best recovery?",
          options: [
            "Review it with the tech lead, close or merge stale lines, sort by rating, and report the top few",
            "Add a new tab and start again without looking at the old lines",
            "Send all 110 lines to the client",
            "Leave it, since a long log shows thoroughness",
          ],
          correctIndex: 0,
          explanation: "A stale, long log hides what matters and gives false comfort. Cleaning, rating and surfacing the top items restores its value. Dumping it on the client shifts work without insight.",
        },
      ],
      practice: {
        kind: "categorize",
        mode: "generic",
        prompt: "You are setting up the RAID log for a React Native and Laravel food-delivery app for a client in Qatar, at the end of week 3. Sort each note from the kickoff, the SOW and this week's calls into the right RAID type. Ask: has it happened yet, and is it something we planned on, or something we need from someone else?",
        categories: [
          { id: "risk", label: "Risk" },
          { id: "assumption", label: "Assumption" },
          { id: "issue", label: "Issue" },
          { id: "dependency", label: "Dependency" },
        ],
        items: [
          { id: "i1", text: "The client has no D-U-N-S number yet, so Apple organisation enrolment may take several weeks and delay the iOS launch.", explanation: "Uncertain future event with a cause and an impact: a risk." },
          { id: "i2", text: "The estimate assumes the restaurant menu data is supplied as one CSV in our format.", explanation: "Something the plan treats as true without proof: an assumption, to be validated with a sample." },
          { id: "i3", text: "The SMS provider's sandbox has rejected every OTP for two days; login testing is blocked.", explanation: "Happening now and blocking work: an issue." },
          { id: "i4", text: "Live payment gateway keys from the client's finance team are needed by week 6 for payment QA.", explanation: "Something we need from someone else by a date: a dependency." },
          { id: "i5", text: "The SOW states that maps and geocoding use the client's own Google Maps billing account.", explanation: "A planning premise written into the SOW: an assumption. If false, it changes cost." },
          { id: "i6", text: "Ramadan falls during UAT, and the client's testers may have reduced hours, stretching the UAT window.", explanation: "May happen, with an impact on the schedule: a risk." },
          { id: "i7", text: "The courier partner's API documentation, promised by the client for week 5.", explanation: "An input from a third party via the client, by a date: a dependency." },
          { id: "i8", text: "The client's designer left last week and nobody is approving screens; two stories are waiting.", explanation: "A current problem stopping progress: an issue." },
          { id: "i9", text: "The plan assumes the client will consolidate design feedback through one SPOC per round.", explanation: "A working premise the plan relies on: an assumption." },
          { id: "i10", text: "The client's privacy policy must be live on their domain before store submission.", explanation: "A client deliverable the release needs: a dependency." },
          { id: "i11", text: "The store may reject the app if the subscription terms are unclear on the paywall.", explanation: "An uncertain future event: a risk, reduced by checking the wording against the store guidelines." },
          { id: "i12", text: "Yesterday's staging deployment wiped the test restaurants, and QA has lost a day.", explanation: "It has already happened: an issue." },
        ],
        answer: {
          i1: "risk",
          i2: "assumption",
          i3: "issue",
          i4: "dependency",
          i5: "assumption",
          i6: "risk",
          i7: "dependency",
          i8: "issue",
          i9: "assumption",
          i10: "dependency",
          i11: "risk",
          i12: "issue",
        },
      },
    },
    // -----------------------------------------------------------------------
    // Escalation matrix
    // -----------------------------------------------------------------------
    {
      id: "pmp-e02-escalation-matrix",
      moduleId: "pmp-e02",
      trackId: "pm",
      title: "Escalation matrix",
      summary:
        "An [[term:escalation-matrix|escalation matrix]] says who to contact at each level, on both sides, for which kind of problem, and after how long. It turns [[term:escalation]] from a panic or a political move into an agreed process. At an agency, that protects both relationships. The client knows they can reach Oyelabs leadership without going around the PM, and the PM knows when it is right to go above the client [[term:spoc|SPOC]].\n\nThe PM drafts it before the client kickoff, using the levels and contacts in the Oyelabs rule (follow the rule in the handbook card below). It is agreed at the kickoff, filled in with real names, emails and phone numbers for both sides, and shared with everyone on the project. It is updated whenever someone changes role, and again at go-live, when support contacts take over.\n\nEach row has a level, a trigger, the time spent at the previous level before moving up, the contacts on each side, an expected [[term:response-time|response time]] and a channel. Escalation sources describe the same idea: levels, the people at each level, and a time before an issue moves up. Timings vary. ProjectManager's example sets 24 hours for critical and 72 hours for high issues. Treat that as an example only, and use what your contract and kickoff agreed.\n\nThe common mistake is a matrix that exists only in the kickoff deck, with role names and no phone numbers. When a [[term:p1-p4|P1]] hits on a Friday night, nobody can find it. The other mistake is skipping levels: going straight to the client's founder over a level-1 matter burns trust on both sides.",
      level: "advanced",
      estMinutes: 40,
      webRefs: [
        { label: "Atlassian: Escalation Policies for Incidents", url: "https://www.atlassian.com/incident-management/on-call/escalation-policies", kind: "docs", verifiedAt: "2026-10-02T12:04:21Z" },
        { label: "PagerDuty Knowledge Base: Escalation Policy Basics", url: "https://support.pagerduty.com/main/docs/escalation-policies", kind: "docs", verifiedAt: "2026-10-02T12:04:43Z" },
        { label: "ProjectManager: Escalation Matrix how-to guide", url: "https://www.projectmanager.com/blog/escalation-matrix", kind: "article", verifiedAt: "2026-10-02T12:04:22Z" },
        { label: "Smartsheet: Free Escalation Matrix Templates", url: "https://www.smartsheet.com/content/escalation-matrix-templates", kind: "article", verifiedAt: "2026-10-02T12:04:43Z" },
      ],
      video: {
        title: "Escalation Matrix!!! The real meaning & purpose of it👍👍👍",
        channel: "K Dinesh Kumar",
        url: "https://www.youtube.com/watch?v=Q8fjudh7pAo",
        videoId: "Q8fjudh7pAo",
        verifiedAt: "2026-10-02T12:05:44Z",
      },
      alternateVideos: [
        {
          title: "Escalation Matrix Guide: Incident Management Essentials",
          channel: "CodeLucky",
          url: "https://www.youtube.com/watch?v=K8C7CeTs93k",
          videoId: "K8C7CeTs93k",
          verifiedAt: "2026-10-02T12:05:44Z",
        },
      ],
      handbook: {
        stages: ["custom-client-kickoff", "wl-golive"],
        rules: ["escalation-levels", "hotfix-approval"],
        templates: ["escalation-matrix-template"],
      },
      sections: [
        {
          heading: "When it is used and who owns it",
          body: "The matrix is drafted before the client kickoff, agreed in it, and used for the life of the project and the support period.\n\n- **Drafted by:** the PM, using the Oyelabs levels and contacts. Follow the Oyelabs rule in the handbook card below.\n- **Agreed with:** the client [[term:spoc|SPOC]] and sponsor at kickoff. The client fills in their own names and numbers.\n- **Approved internally by:** the delivery head, whose name is on level 2.\n- **Received by:** everyone on both sides, and pinned in the project channel and drive.\n- **Updated:** when anyone changes role or leaves, and at [[term:go-live|go-live]], when [[term:support]] or [[term:hypercare]] contacts may replace delivery contacts.\n\nIt is used in two ways. Either side can use it to escalate a problem that is stuck. And during hypercare and support, it works with [[term:severity]] levels to decide who is woken up for what.",
        },
        {
          heading: "Field by field: what good entries look like",
          body: "1. **Level.** Usually three: level 1 (PM and client SPOC), level 2 (delivery head and client operations lead or sponsor), level 3 (leadership on both sides). Smartsheet's examples run project contact, then PM, then account manager, then the next management level.\n2. **When to escalate (trigger).** Concrete and observable. Good: 'Unresolved at level 1 after the agreed window; RAG Red; a P1 production issue; a payment dispute.' Mistake: 'serious problems'.\n3. **Time at previous level before escalating.** The window a level gets before anyone goes higher. Write the number agreed at kickoff, for example a typical 2 working days for delivery blockers, and much less for a P1. ProjectManager's 24 h and 72 h are an example only.\n4. **Oyelabs contact.** Role, name, email and phone, plus a backup. Mistake: a role with no name, or one person with no backup.\n5. **Client contact.** The same on the client side. Mistake: leaving it for the client to 'send later'.\n6. **Expected response time.** How fast the contact will acknowledge, not fix. Keep it separate from [[term:resolution-time|resolution time]], which belongs to the [[term:sla|SLA]].\n7. **Channel.** For example email with the project ID in the subject, then a call for levels 2 and 3. Production incidents may need a phone call first.\n\nOne rule for every level: whoever escalates tells the person they are going above, first. 'I'll take this to our delivery head today if we can't agree' keeps trust intact.",
        },
        {
          heading: "What good looks like: a worked example",
          body: "Project: a Laravel and React marketplace for an Australian retailer. Agreed at kickoff; the times are what this client agreed, not a standard.\n\n- **Level 1.** Trigger: day-to-day blockers, late inputs, design disagreements. Oyelabs: PM (name, email, mobile); backup: tech lead. Client: e-commerce manager; backup: digital coordinator. Response: same working day. Channel: project Slack, then email.\n- **Level 2.** Trigger: a level-1 matter unresolved after 2 working days, any RAG Red, a [[term:p1-p4|P1]] in production, or a disputed [[term:change-request|CR]]. Oyelabs: delivery head. Client: head of digital. Response: within 4 working hours. Channel: email with the project ID, followed by a call.\n- **Level 3.** Trigger: a commercial dispute, a threat to terminate, or a level-2 matter unresolved after 3 working days. Oyelabs: leadership. Client: COO. Response: next working day. Channel: call, confirmed by email.\n- **Time zones:** Oyelabs contacts list their working hours in AEST overlap. A P1 outside those hours goes to the on-call number.\n\nWhy this is good: triggers are observable, every level has names and backups, response times are realistic for the time-zone gap, and P1 has its own path.",
        },
        {
          heading: "Common mistakes and how to recover",
          body: "- **Role names only.** At 11 pm on launch night, nobody knows who 'Delivery head' is. Recovery: fill in names, numbers and backups, and re-send it.\n- **Skipping a level.** The client's founder emails Oyelabs leadership about a late screen. Recovery: leadership acknowledges, loops in the PM, and the PM and SPOC resolve it at level 1. Afterwards, remind both sides of the matrix calmly.\n- **Escalating as a threat.** A PM warns the SPOC 'or I'll go to your CEO'. Recovery: apologise and reframe: escalation brings in people who can decide, it is not a punishment.\n- **Escalating too late.** A blocker sat for three weeks because the PM did not want to look weak. Recovery: escalate now with facts, impact and options, and record it in the [[term:status-report|status report]].\n- **Out of date after go-live.** The client calls a developer who has moved to another project. Recovery: update the matrix at go-live with support contacts.\n- **Mixing response and resolution.** The client expects a fix in 4 hours because the matrix said 'respond in 4 hours'. Recovery: separate the two, and point to the SLA for resolution.",
        },
        {
          heading: "Your checklist",
          body: "- Three levels (or what the Oyelabs rule sets), each with a concrete trigger.\n- A time window per level, agreed at kickoff and marked as such.\n- Names, emails, phones and backups on both sides.\n- Response time kept separate from resolution time.\n- A channel per level, and a separate path for [[term:p1-p4|P1]] production issues.\n- Time zones and working hours stated.\n- Delivery head has approved the Oyelabs side.\n- Shared with everyone and pinned where people will find it.\n- Updated on any role change and at go-live.",
        },
      ],
      sop: [
        {
          title: "Oyelabs escalation contacts and time windows",
          prompt: "[Oyelabs SOP – admin to fill] The Oyelabs names and roles for each level (delivery head, leadership), backups, the out-of-hours or on-call number for production issues, and the default time windows Oyelabs proposes at kickoff.",
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pmp-e02-escalation-matrix-q1",
          prompt: "The client's founder emails Oyelabs leadership directly because a settings screen was delivered a day late. The PM and client SPOC have not discussed it. What is the best handling?",
          options: [
            "Leadership acknowledges politely, loops in the PM, and the PM resolves it with the SPOC at level 1",
            "Leadership takes over the project from the PM",
            "Ignore the email because it skipped the matrix",
            "The PM complains to the founder about the SPOC",
          ],
          correctIndex: 0,
          explanation: "A level-1 matter belongs at level 1. Acknowledging keeps the founder's trust; routing it back keeps the matrix meaningful. Ignoring a founder is never the answer.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-e02-escalation-matrix-q2",
          prompt: "ProjectManager's example matrix sets 24 hours for critical and 72 hours for high issues. How should you use those numbers?",
          options: [
            "As an example; agree the project's own windows at kickoff and write them into the matrix",
            "As the industry standard every contract must use",
            "As resolution times Oyelabs guarantees",
            "Not at all; matrices should never contain times",
          ],
          correctIndex: 0,
          explanation: "Timings vary by contract and time zone. Times are part of a good matrix, but they must be the ones this project agreed.",
        },
        {
          id: "pmp-e02-escalation-matrix-q3",
          prompt: "Which are good escalation triggers? (Select all that apply.)",
          options: [
            "A level-1 blocker unresolved after the agreed 2 working days",
            "The project's overall RAG turns Red",
            "A P1 production issue",
            "The PM feels the client is difficult",
            "Any question the PM cannot answer immediately",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Triggers must be observable facts. Feelings and normal unknowns are handled in the usual cadence; escalating them devalues the matrix.",
        },
        {
          id: "pmp-e02-escalation-matrix-q4",
          prompt: "The matrix says the level-2 contact will 'respond within 4 hours'. The client expects a production bug fixed in 4 hours. What is the confusion?",
          options: [
            "Response time (acknowledging) was taken as resolution time (fixing), which belongs to the SLA",
            "The matrix is wrong: 4 hours is always resolution time",
            "The client is right, so Oyelabs must fix it in 4 hours",
            "Response time only applies to level 3",
          ],
          correctIndex: 0,
          explanation: "A matrix promises who acknowledges and how fast. Fix times come from the SLA and severity. Keep the two clearly separate in the matrix.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-e02-escalation-matrix-q5",
          prompt: "You need to escalate a stuck approval above the client SPOC to their sponsor. What should you do first?",
          options: [
            "Tell the SPOC you are taking it to level 2 and why, then escalate with facts and options",
            "Email the sponsor quietly and copy nobody",
            "Wait another week to be safe",
            "Ask a developer to message the sponsor",
          ],
          correctIndex: 0,
          explanation: "No-surprise escalation keeps the SPOC relationship intact. Going around them quietly feels like betrayal, and waiting only adds delay.",
        },
        {
          id: "pmp-e02-escalation-matrix-q6",
          prompt: "Which details should every level of a usable escalation matrix include? (Select all that apply.)",
          options: [
            "Named contacts with email and phone on both sides",
            "A backup for each contact",
            "The channel to use",
            "The developers' personal social media accounts",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Names, numbers, backups and a channel make the matrix work at 11 pm. Personal social accounts are not a business channel.",
        },
        {
          id: "pmp-e02-escalation-matrix-q7",
          prompt: "A white-label app goes live. The matrix still lists the delivery developers who have moved to other projects. When should it have been updated?",
          options: [
            "At go-live, when support and hypercare contacts take over",
            "Only at project closure",
            "Only when the client asks",
            "Never; the kickoff version is final",
          ],
          correctIndex: 0,
          explanation: "Go-live changes who answers. An outdated matrix sends a live-production problem to the wrong person.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-e02-escalation-matrix-q8",
          prompt: "A PM tells the client SPOC 'Approve the designs by Friday or I'm escalating to your CEO.' What is wrong?",
          options: [
            "It uses escalation as a threat instead of a way to bring in someone who can decide",
            "Nothing; it creates urgency",
            "The PM should have threatened Oyelabs leadership instead",
            "Escalation is only for production issues",
          ],
          correctIndex: 0,
          explanation: "Escalation should be framed as getting a decision unblocked, with facts and options. As a threat, it damages the working relationship the project depends on.",
        },
        {
          id: "pmp-e02-escalation-matrix-q9",
          prompt: "Oyelabs is in India and the client in Australia. Which addition makes the matrix most useful?",
          options: [
            "Each contact's working hours in the overlap, and a separate out-of-hours path for P1 issues",
            "Remove phone numbers to avoid late calls",
            "Use only email for every level",
            "List contacts only on the Oyelabs side",
          ],
          correctIndex: 0,
          explanation: "Time zones decide whether a response time is realistic. A P1 path out of hours prevents a live outage waiting for the next morning.",
        },
      ],
      practice: {
        kind: "categorize",
        mode: "generic",
        prompt: "This project's agreed matrix: **Level 1** (PM and client SPOC): day-to-day blockers, late inputs and disagreements. **Level 2** (Oyelabs delivery head and client operations lead): a level-1 matter unresolved after 2 working days, overall RAG Red, a P1 production issue, or a disputed CR. **Level 3** (leadership on both sides): a commercial or payment dispute, a threat to terminate, or a level-2 matter unresolved after 3 working days. Anything that needs no escalation is handled in the normal cadence: stand-ups, minutes, the status report. Sort each situation to where it should go now.",
        categories: [
          { id: "none", label: "No escalation: normal cadence" },
          { id: "l1", label: "Level 1: PM and client SPOC" },
          { id: "l2", label: "Level 2: delivery head and client operations lead" },
          { id: "l3", label: "Level 3: leadership on both sides" },
        ],
        items: [
          { id: "e1", text: "The client asks what time Thursday's sprint demo starts.", explanation: "A routine question: answer it in the normal channel." },
          { id: "e2", text: "Brand assets were due yesterday and have not arrived.", explanation: "A late input, first day: raise it at level 1 with the SPOC." },
          { id: "e3", text: "The client SPOC and the PM disagree on whether a filter is in scope; the conversation started this morning.", explanation: "A fresh disagreement belongs at level 1 until its window expires." },
          { id: "e4", text: "The same scope disagreement is still unresolved after 3 working days.", explanation: "Level 1 had its 2-working-day window, so it moves to level 2." },
          { id: "e5", text: "Checkout is failing for every customer in production on launch day.", explanation: "A P1 production issue goes straight to level 2 under this matrix." },
          { id: "e6", text: "This week's status report turns overall RAG Red because go-live will be missed.", explanation: "Red RAG is a level-2 trigger." },
          { id: "e7", text: "The client has not paid the milestone 2 invoice, 45 days overdue, and disputes it.", explanation: "A payment dispute is a level-3 matter." },
          { id: "e8", text: "The client says they will terminate the contract if the next demo slips.", explanation: "A threat to terminate is a level-3 trigger." },
          { id: "e9", text: "A disputed CR has been with the delivery head and client operations lead for 4 working days without agreement.", explanation: "Level 2 had its 3-day window, so it moves to level 3." },
          { id: "e10", text: "A developer finished a story a day early.", explanation: "Good news: report it in the stand-up or the status report." },
          { id: "e11", text: "The client's QA lead reports a typo on the About page in staging.", explanation: "A minor defect: log it as a normal bug, no escalation." },
          { id: "e12", text: "The client's payment gateway keys are a day late and the SPOC has not replied to one email.", explanation: "Still within level 1: chase the SPOC directly, by call if needed." },
        ],
        answer: {
          e1: "none",
          e2: "l1",
          e3: "l1",
          e4: "l2",
          e5: "l2",
          e6: "l2",
          e7: "l3",
          e8: "l3",
          e9: "l3",
          e10: "none",
          e11: "none",
          e12: "l1",
        },
      },
    },
  ],
} satisfies Module;
