import type { Module } from "@/types/curriculum";

/** Joins lines into one Markdown body. */
const md = (...lines: string[]) => lines.join("\n");

export default {
  id: "pmp-d02",
  trackId: "pm",
  name: "Client meetings: Running delivery",
  description:
    "Step-by-step playbooks for the recurring delivery meetings: the daily stand-up, sprint planning, the weekly client status call and the sprint demo. Each gives the purpose, attendees, prep checklist, a timed agenda, a sample script for overseas clients on Teams, traps and the follow-up.",
  topics: [
    // -----------------------------------------------------------------------
    // Daily stand-up
    // -----------------------------------------------------------------------
    {
      id: "pmp-d02-daily-standup",
      moduleId: "pmp-d02",
      trackId: "pm",
      title: "The daily stand-up (Daily Scrum)",
      summary:
        "The daily stand-up is a 15-minute check where the developers inspect progress towards the [[term:sprint]] goal and adjust the plan for the next day. The Scrum Guide calls it the Daily Scrum and says it is for the developers. It is not a status report to the PM, and the 2020 Guide no longer requires the \"three questions\".\n\nAt an agency the stand-up has one extra job: it is the earliest point where a [[term:client-dependency]] or [[term:blocker]] becomes visible. A missing API key spotted at Tuesday's stand-up can be chased the same morning. The same key found on Thursday afternoon costs the sprint. For the PM, the most valuable output of a stand-up is a short list of blockers with owners, and the one or two that need the client today.\n\nHow to run it well. Same time every day, chosen to fit the team's working hours (and, if the client's product owner joins, a time that overlaps both time zones). Walk the board from right to left, closest-to-done items first, so finishing beats starting. Anything longer than a minute goes to a named follow-up right after. You note blockers and escalate the client ones in the project's Teams channel within the hour.\n\nThe common mistake is to turn it into a round of status reports to the PM, or into a problem-solving meeting that runs 40 minutes. The second mistake at agencies is letting the client join and then nobody feels safe to say \"I'm stuck\". If the client attends, agree upfront what the meeting is for, and keep sensitive discussion in a separate internal follow-up.",
      level: "intermediate",
      estMinutes: 30,
      webRefs: [
        { label: "Scrum Guide (2020)", url: "https://scrumguides.org/scrum-guide.html", kind: "spec", verifiedAt: "2026-10-02T12:04:11Z" },
        { label: "Atlassian: Standups for agile teams", url: "https://www.atlassian.com/agile/scrum/standups", kind: "article", verifiedAt: "2026-10-02T12:04:13Z" },
        { label: "Mountain Goat Software: Daily Scrum Meeting", url: "https://www.mountaingoatsoftware.com/agile/scrum/meetings/daily-scrum", kind: "article", verifiedAt: "2026-10-02T12:04:13Z" },
      ],
      video: {
        title: "Daily Scrum Explained: A Better Way to Run It",
        channel: "Mountain Goat Software: Agile & Scrum Mastery",
        url: "https://www.youtube.com/watch?v=MZdK4SX0mfI",
        videoId: "MZdK4SX0mfI",
        verifiedAt: "2026-10-02T12:05:29Z",
      },
      alternateVideos: [
        {
          title: "A Real Daily Standup Meeting Example",
          channel: "DataMiner by Skyline Communications",
          url: "https://www.youtube.com/watch?v=T8GcCl8w-_E",
          videoId: "T8GcCl8w-_E",
          verifiedAt: "2026-10-02T12:05:29Z",
        },
      ],
      handbook: {
        stages: ["custom-sprints"],
        rules: ["escalation-levels"],
        templates: ["raid-log-template"],
      },
      sections: [
        {
          heading: "Purpose and when it happens",
          body: md(
            "The stand-up happens every working day of a [[term:sprint]], at the same time, for at most 15 minutes. The Scrum Guide's purpose is to inspect progress towards the sprint goal and adapt the plan.",
            "",
            "For an agency PM it also:",
            "- surfaces [[term:blocker|blockers]] and [[term:client-dependency|client dependencies]] while there is still time to act;",
            "- feeds the [[term:eod-update]] and the weekly [[term:status-report]];",
            "- shows early when the sprint goal is at [[term:risk]], so you can warn the client before the demo, not at it.",
            "",
            "It is not a meeting to solve problems. Problems get a named follow-up straight after.",
          ),
        },
        {
          heading: "Who attends",
          body: md(
            "- **Developers, QA and the designer** working on the sprint: they own the meeting.",
            "- **PM / Scrum Master:** keeps the timebox, notes blockers. Listen more than you talk.",
            "- **Tech lead:** usually as a developer.",
            "- **Client product owner:** optional. The Scrum Guide says the Product Owner joins only as someone working on backlog items. Many agencies invite the client's PO a few times a week for quick answers. If you do, agree that the meeting stays the team's, and that sensitive issues go to an internal follow-up.",
            "",
            "Nobody else. Observers turn a stand-up into a performance.",
          ),
        },
        {
          heading: "Prepare: checklist",
          body: md(
            "- The sprint board is up to date before the call (ask the team to move their cards first).",
            "- The sprint goal is written at the top of the board.",
            "- You know which client dependencies are due today or overdue.",
            "- A fixed Teams meeting link in the channel, same time daily, inside everyone's working hours.",
            "- A short running list for blockers: item – blocker – owner – needed from whom – by when.",
            "- If the client's PO joins, check they have the board link and know the 15-minute rule.",
          ),
        },
        {
          heading: "Timed agenda template",
          body: md(
            "A 15-minute stand-up, walking the board:",
            "",
            "1. 0:00–0:01 Sprint goal and days left (one line)",
            "2. 0:01–0:10 Walk the board from right to left: items in QA, in review, in progress. For each: what moves it forward today, and anything blocking it",
            "3. 0:10–0:13 Blockers and client dependencies: owner and next step for each",
            "4. 0:13–0:15 Who stays for which follow-up; anything the client must hear today",
            "",
            "Follow-ups start at 0:15 with only the people needed.",
          ),
        },
        {
          heading: "Sample script",
          body: md(
            "- **Opening:** “Morning. Sprint goal: patients can book and pay. Six working days left. Let's walk the board from QA backwards.”",
            "- **Moving along:** “Thanks, Ravi. That sounds like a 10-minute talk with Meera. Can you two stay after?”",
            "- **Surfacing a blocker:** “Anything stopping this moving today?” Then: “Who owns getting it unblocked, and by when?”",
            "- **Client dependency:** “The payment keys were due Monday. I'll message their SPOC straight after this and update you by 1 pm.”",
            "- **If the client's PO is on the call:** “Mark, one quick question for you: should the cancellation email go to the clinic as well as the patient?”",
            "- **Sprint goal at risk:** “If the keys don't arrive by Thursday, payments won't be demoable. I'll flag that to the client today.”",
            "- **Closing:** “Two follow-ups: Ravi and Meera on the API, me and the tech lead on the keys. Thanks, all.”",
          ),
        },
        {
          heading: "What to show",
          body: md(
            "Share the sprint board in Teams, filtered to this sprint, with the sprint goal visible and the columns from left (to do) to right (done).",
            "",
            "Show the blockers list or the [[term:raid-log]] entries due this week only if a blocker is discussed. Do not show burndown charts every day; once or twice a week is enough to spot a trend.",
          ),
        },
        {
          heading: "Traps and how to recover",
          body: md(
            "- **It becomes a report to the PM.** People face you and recite tickets. Walk the board instead of the people, and ask about the sprint goal, not individual busyness.",
            "- **Problem solving runs to 40 minutes.** Stop it kindly: “Great discussion. Let's take it to a follow-up.”",
            "- **Nobody says they are stuck while the client listens.** Hold a two-minute internal check after the client drops, or keep the client to two days a week.",
            "- **The same blocker for three days.** It is now an [[term:issue]]: log it, give it an owner, and escalate per the escalation rule card below.",
            "- **Remote team members in other time zones.** Rotate the time or accept an async written update in the channel on their off days.",
            "- **People join late every day.** Start on time anyway; the habit fixes itself.",
          ),
        },
        {
          heading: "Follow-up within 24 hours",
          body: md(
            "A stand-up does not need formal minutes. Its follow-up is faster than 24 hours: within about an hour, the PM sends one message to the client SPOC for any client blocker, and logs lasting blockers in the [[term:raid-log]]. Formal minutes are needed only when a decision affecting scope or dates was taken.",
            "",
            "Template for the client message in the Teams channel or email:",
            "- **Subject / first line:** Blocker: payment gateway keys needed by Thursday",
            "- **What:** “We need the live and sandbox keys for the payment gateway.”",
            "- **Why it matters:** “Without them by Thursday, payment cannot be shown in next Tuesday's demo.”",
            "- **Ask:** “Could you send them through the secure link by Thursday 12:00 your time?”",
            "- **Owner on our side:** PM, who will confirm receipt.",
          ),
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pmp-d02-daily-standup-q1",
          prompt: "According to the Scrum Guide, what is the Daily Scrum for?",
          options: [
            "Developers inspecting progress towards the sprint goal and adapting the plan for the next day",
            "Developers reporting their hours to the PM",
            "Showing the client what was built yesterday",
            "Solving every technical problem the team has",
          ],
          correctIndex: 0,
          explanation: "It is a planning event for the developers. Status reporting and problem solving happen elsewhere.",
        },
        {
          id: "pmp-d02-daily-standup-q2",
          prompt: "Which are true of the Daily Scrum in the 2020 Scrum Guide? (Select all that apply.)",
          options: [
            "It is timeboxed to 15 minutes",
            "It is held at the same time and place every day",
            "The developers can choose its structure and techniques",
            "It must use the three questions: yesterday, today, blockers",
            "It is not the only time developers may adjust their plan",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 4],
          explanation: "The 2020 Guide removed the mandatory three questions. Teams pick their own format, such as walking the board.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d02-daily-standup-q3",
          prompt: "Why walk the board from right to left (closest to done first)?",
          options: [
            "It focuses the team on finishing work rather than starting new work",
            "Because Teams displays boards backwards",
            "It makes the meeting longer and more thorough",
            "So the PM can check each person's hours",
          ],
          correctIndex: 0,
          explanation: "Starting with the items nearest done puts attention on what is stuck in review or QA, which is usually where sprints lose days.",
        },
        {
          id: "pmp-d02-daily-standup-q4",
          prompt: "At Tuesday's stand-up, a developer says the payment API keys, due from the client on Monday, have not arrived. The demo is next Tuesday. What do you do?",
          options: [
            "Message the client SPOC within the hour with what is needed, why, and by when, and log it as a dependency risk",
            "Wait until Friday's status call to mention it",
            "Ask the developer to use fake keys and say nothing",
            "Remove payments from the sprint without telling anyone",
          ],
          correctIndex: 0,
          explanation: "The stand-up's value is early warning. A same-day, specific ask gives the client time to act and protects the demo.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d02-daily-standup-q5",
          prompt: "Two developers start debating an API design during the stand-up. It is minute 9. What do you say?",
          options: [
            "“Good topic. Can you two take it to a follow-up right after?”",
            "“Let's all solve it now; the board can wait.”",
            "“Please stop talking about work.”",
            "Nothing; it is the developers' meeting",
          ],
          correctIndex: 0,
          explanation: "Protect the timebox while respecting the topic. Only the people needed stay for the follow-up.",
        },
        {
          id: "pmp-d02-daily-standup-q6",
          prompt: "The client's product owner joins your stand-up daily, and you notice developers stopped mentioning problems. What are good fixes? (Select all that apply.)",
          options: [
            "Agree with the client that the meeting stays the team's, and keep their attendance to a few days a week",
            "Hold a two-minute internal check after the client leaves",
            "Ask the team to hide problems until the sprint ends",
            "Invite the client to a separate short Q&A slot instead",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 3],
          explanation: "Psychological safety matters more than visibility. Hidden problems surface later and bigger.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d02-daily-standup-q7",
          prompt: "The same blocker has been mentioned at three stand-ups in a row. What has changed?",
          options: [
            "It is now an issue: log it with an owner and escalate per the escalation rule",
            "Nothing; blockers often last a week",
            "The developer should stop mentioning it",
            "It becomes the client's problem automatically",
          ],
          correctIndex: 0,
          explanation: "A blocker that does not move needs a different level of attention. Logging and escalating is how it gets unstuck.",
        },
        {
          id: "pmp-d02-daily-standup-q8",
          prompt: "Your team is in India and two contractors work from Eastern Europe. The stand-up is at 10:00 India time. What is a sensible approach?",
          options: [
            "Find a slot inside everyone's working hours, or accept a written async update from those outside it",
            "Make the contractors join at 06:30 their time",
            "Drop them from the stand-up entirely",
            "Hold two separate stand-ups with different sprint goals",
          ],
          correctIndex: 0,
          explanation: "The stand-up must fit working hours to be sustainable. An async update keeps them in the loop without wrecking their day.",
        },
      ],
      practice: {
        kind: "form",
        variant: "mom",
        templateId: "mom",
        prompt:
          "From this stand-up for a React Native fitness app (Australian client), record the blockers and the follow-ups, and write the short message to the client SPOC.",
        context: md(
          "**Stand-up, day 6 of 10. Sprint goal: members can book a class and pay.**",
          "",
          "**Ravi (dev):** Class list done, in QA. Booking API: I'm waiting on Meera's endpoint change, should be today.",
          "**Meera (dev):** Endpoint change done by lunch.",
          "**Sunil (dev):** Payments: still no Stripe keys from the client. They were due Monday. I can't test the live flow.",
          "**Anita (QA):** Class list: found one crash on Android 12. Logging it now. Also I still don't have the test account the client promised.",
          "**PM:** So, client blockers: Stripe keys and the test account. Ravi and Meera, follow-up on the endpoint after this. I'll message the client after the stand-up.",
        ),
        fields: [
          { id: "blockers", label: "Blockers (item – owner – needed from whom – by when)", input: "textarea", required: true },
          { id: "clientBlockers", label: "Number of blockers that need the client", input: "number", required: true },
          {
            id: "riskToGoal",
            label: "Is the sprint goal at risk?",
            input: "select",
            options: ["No", "Yes: payments cannot be tested without the client's keys", "Yes: the class list is not done"],
            required: true,
          },
          { id: "followUps", label: "Follow-ups after the stand-up", input: "textarea", required: true },
          { id: "clientMessage", label: "Message to the client SPOC", input: "textarea", required: true },
        ],
        checks: [
          { fieldId: "clientBlockers", expected: 2 },
          { fieldId: "riskToGoal", expected: "Yes: payments cannot be tested without the client's keys" },
        ],
        rubric: [
          { label: "Client message is specific", points: 2, description: "Names the Stripe keys and the test account, why they matter (payments in the sprint goal and demo), and a clear deadline in the client's time zone." },
          { label: "Internal blockers have owners", points: 2, description: "Endpoint change (Meera, by lunch); Android crash logged by Anita." },
          { label: "Short and polite", points: 1 },
        ],
        sampleAnswer: {
          blockers:
            "- Payments: Stripe keys – Sunil – client SPOC – overdue since Monday.\n- QA: test account – Anita – client SPOC – overdue.\n- Booking API: endpoint change – Meera – internal – today lunch.",
          clientBlockers: "2",
          riskToGoal: "Yes: payments cannot be tested without the client's keys",
          followUps: "- Ravi and Meera: booking endpoint, straight after stand-up.\n- PM: message client SPOC within the hour; log keys in the RAID log.",
          clientMessage:
            "Hi Jess, two items we need to keep payments in this sprint's demo: the Stripe sandbox and live keys (due Monday) and the QA test account. Could you send both through the secure link by Thursday 12:00 Sydney time? Without them we can't test payments before Tuesday's demo. I'll confirm as soon as they arrive.",
        },
      },
      sop: [
        {
          title: "Our stand-up rules",
          prompt:
            "[Oyelabs SOP – admin to fill] The standard stand-up time and length, whether client product owners may attend (and how often), where blockers are logged, and how fast a client blocker must be raised with the client SPOC.",
        },
      ],
    },

    // -----------------------------------------------------------------------
    // Sprint planning
    // -----------------------------------------------------------------------
    {
      id: "pmp-d02-sprint-planning",
      moduleId: "pmp-d02",
      trackId: "pm",
      title: "Sprint planning",
      summary:
        "Sprint planning decides what the team will deliver in the next [[term:sprint]] and how. The Scrum Guide frames it as three questions: why is this sprint valuable, what can be done, and how will the chosen work get done. Its timebox is up to eight hours for a one-month sprint, so typically about two to four hours for a two-week sprint.\n\nAt an agency, sprint planning has a client-facing edge. The client's product owner (or [[term:spoc]]) sets priorities from the [[term:backlog]], but your team owns how much fits. Every sprint commitment is also a small promise to an overseas client who will see it at the demo. So planning must check three things the Scrum Guide does not mention: [[term:client-dependency|client dependencies]] for each item, the [[term:definition-of-ready]], and whether an item has crept in without a [[term:change-request]].\n\nHow to run it. Before the meeting, refine the top of the backlog with the client so the items are ready. In the meeting, agree a sprint goal in one sentence, pull items in priority order up to the team's real capacity (after holidays and support load), and leave out anything blocked by a missing client input. Split large items. Confirm the [[term:acceptance-criteria]] the client will check at the demo.\n\nThe common mistake is to commit to whatever the client asks, then miss it in front of them two weeks later. A second mistake is planning items that need client inputs you do not yet have. A sprint full of \"waiting for the client\" looks, at the demo, like your team failed.",
      level: "intermediate",
      estMinutes: 40,
      webRefs: [
        { label: "Scrum Guide (2020)", url: "https://scrumguides.org/scrum-guide.html", kind: "spec", verifiedAt: "2026-10-02T12:04:11Z" },
        { label: "Atlassian: Sprint Planning", url: "https://www.atlassian.com/agile/scrum/sprint-planning", kind: "article", verifiedAt: "2026-10-02T12:04:12Z" },
        { label: "Mountain Goat Software: Sprint Planning Meeting", url: "https://www.mountaingoatsoftware.com/agile/scrum/meetings/sprint-planning-meeting", kind: "article", verifiedAt: "2026-10-02T12:04:12Z" },
        { label: "The Digital Project Manager: Sprint Planning Meeting Guide", url: "https://thedigitalprojectmanager.com/project-management/sprint-planning-meeting/", kind: "article", verifiedAt: "2026-10-02T12:04:12Z" },
      ],
      video: {
        title: "Sprint Planning Meetings | 12 Tips To Run Them Like a Scrum Pro",
        channel: "The Digital Project Manager",
        url: "https://www.youtube.com/watch?v=FC7WH7OPQqg",
        videoId: "FC7WH7OPQqg",
        verifiedAt: "2026-10-02T12:05:29Z",
      },
      alternateVideos: [
        {
          title: "06 - Sprint Planning Meeting - Scrum Foundations eLearning Series",
          channel: "Scrum Alliance",
          url: "https://www.youtube.com/watch?v=H23LUCBFjkw",
          videoId: "H23LUCBFjkw",
          verifiedAt: "2026-10-02T12:05:29Z",
        },
      ],
      handbook: {
        stages: ["custom-sprints"],
        rules: ["cr-when-needed", "mom-after-every-client-meeting"],
        templates: ["mom"],
      },
      sections: [
        {
          heading: "Purpose and when it happens",
          body: md(
            "Sprint planning opens every [[term:sprint]]. It answers the Scrum Guide's three questions:",
            "1. **Why** is this sprint valuable? This becomes the sprint goal.",
            "2. **What** can be done? Items pulled from the [[term:backlog]] up to real capacity.",
            "3. **How** will it get done? The team breaks items into tasks.",
            "",
            "At an agency, many teams split it in two: a short client part (goal and priorities, 30–45 minutes, typical) and an internal part (sizing and tasks). The client sees what they will get at the demo; the team keeps its technical discussion internal.",
            "",
            "Only items that meet the [[term:definition-of-ready]] and are within the agreed scope go in. Anything new goes through a [[term:change-request]] first.",
          ),
        },
        {
          heading: "Who attends",
          body: md(
            "**Client part:**",
            "- **Client product owner or [[term:spoc]]:** sets priorities and answers questions.",
            "- **PM:** facilitates, protects capacity and scope.",
            "- **Tech lead:** sanity-checks feasibility.",
            "",
            "**Internal part:**",
            "- the whole delivery team: developers, QA, designer, tech lead and PM.",
            "",
            "The client PO decides *what matters most*. The team decides *how much fits*. Keep those two roles clear in the room.",
          ),
        },
        {
          heading: "Prepare: checklist",
          body: md(
            "- Backlog refined with the client in the last few days: the top items have [[term:acceptance-criteria]] and estimates.",
            "- Team capacity calculated: working days minus leave, public holidays (both countries if relevant), and support or [[term:hypercare]] load on other projects.",
            "- Carry-over from the last sprint, and why.",
            "- Client dependencies for each candidate item: content, keys, accounts, decisions. Mark the ones not yet received.",
            "- A draft sprint goal to propose.",
            "- Check the next [[term:milestone]] and what this sprint must contribute to it.",
            "- Send the candidate list to the client PO a day ahead.",
          ),
        },
        {
          heading: "Timed agenda template",
          body: md(
            "Client part on Teams, 45 minutes (typical for a two-week sprint):",
            "",
            "1. 0:00–0:05 Last sprint in one line: done, carried over, why",
            "2. 0:05–0:12 Capacity this sprint and any known gaps (leave, holidays)",
            "3. 0:12–0:20 Propose the sprint goal; agree it in one sentence",
            "4. 0:20–0:35 Walk candidate items in priority order; confirm acceptance criteria; exclude blocked items",
            "5. 0:35–0:40 Client dependencies needed this sprint, with dates",
            "6. 0:40–0:45 Read back the goal and the committed items; demo date",
            "",
            "Internal part straight after: 60–90 minutes for task breakdown and the final check that the commitment fits.",
          ),
        },
        {
          heading: "Sample script",
          body: md(
            "- **Opening:** “Last sprint we finished seven of eight items; the export carried over because the sample file came late. This sprint we have 34 points of capacity, as Ravi is on leave Thursday and Friday.”",
            "- **Goal:** “I'd propose the goal: ‘Members can book and pay for a class on Android and iOS.’ Does that match what matters most for you?”",
            "- **Protecting capacity:** “Those four items fill our capacity. If notifications matter more than reports, we can swap them. We can't add both.”",
            "- **Excluding a blocked item:** “The Apple Health story needs your developer account. Until it's set up, I'd keep it in the backlog so we don't commit to something we can't finish.”",
            "- **Spotting new scope:** “Promo codes aren't in the backlog or the scope. I'll raise a change request so you can see the impact.”",
            "- **Closing:** “So: goal, four items, and two things we need from you, the copy by Tuesday and the test account by Wednesday. Demo is Thursday the 24th at 10:00 Sydney time.”",
          ),
        },
        {
          heading: "What to show",
          body: md(
            "- The backlog, sorted by priority, with estimates and a ready / not ready marker.",
            "- A capacity line: the number of points or days available, so the client sees where the line falls.",
            "- The sprint goal, written large.",
            "- The milestone plan, to show how this sprint contributes.",
            "- A list of client dependencies for the sprint, with dates.",
          ),
        },
        {
          heading: "Traps and how to recover",
          body: md(
            "- **The client pushes more in.** Show the capacity line and offer a swap: “Which of these comes out?”",
            "- **Items are not ready.** Do not commit to them. Plan a refinement session and pull the next ready item.",
            "- **A planned item depends on a missing client input.** Leave it out, or split out the part you can do without it.",
            "- **The client adds a new feature during planning.** Note it and route it to a [[term:change-request]], following the rule card below.",
            "- **Carry-over every sprint.** The team is overcommitting. Plan to the average actually delivered, not the hoped-for number.",
            "- **The client PO does not turn up.** Plan with the agreed priorities and send the plan for confirmation the same day.",
          ),
        },
        {
          heading: "Follow-up within 24 hours",
          body: md(
            "Send a short [[term:mom]] to the client PO with the sprint goal, the committed items and the dependencies. This becomes what the demo is judged against.",
            "",
            "Template:",
            "- **Subject:** Sprint 6 plan – goal, scope and what we need from you",
            "- **Sprint goal:** one sentence.",
            "- **Committed items:** list with links.",
            "- **Not in this sprint:** items left out and why (capacity, waiting for input).",
            "- **Client dependencies:** item – owner – date.",
            "- **Change requests raised:** if any.",
            "- **Demo:** date and time in both time zones.",
          ),
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pmp-d02-sprint-planning-q1",
          prompt: "Which three questions does sprint planning answer in the Scrum Guide? (Select all that apply.)",
          options: [
            "Why is this sprint valuable?",
            "What can be done this sprint?",
            "How will the chosen work get done?",
            "Who is to blame for last sprint's carry-over?",
            "How much will the client be invoiced?",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Why, what and how. Blame and invoicing are not part of the event.",
        },
        {
          id: "pmp-d02-sprint-planning-q2",
          prompt: "In planning, who decides what matters most, and who decides how much fits?",
          options: [
            "The client's product owner sets priority; the delivery team decides how much fits",
            "The PM decides both",
            "The client decides both",
            "The tech lead decides priority; the client decides capacity",
          ],
          correctIndex: 0,
          explanation: "Splitting priority and capacity is what stops over-commitment. The client should not set the team's capacity, and the PM should not set business priority.",
        },
        {
          id: "pmp-d02-sprint-planning-q3",
          prompt: "A top-priority story needs the client's Apple developer account, which does not exist yet. What do you do in planning?",
          options: [
            "Keep it out of the sprint (or split out the part that does not need the account) and ask for the account with a date",
            "Commit to it and hope the account arrives",
            "Commit to it and blame the client at the demo",
            "Create the account under the agency's name",
          ],
          correctIndex: 0,
          explanation: "Committing to blocked work makes your team look like it failed. Splitting or deferring keeps the commitment honest, and the store account must be the client's own.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d02-sprint-planning-q4",
          prompt: "What is a typical timebox for sprint planning in a two-week sprint?",
          options: [
            "About two to four hours, scaled down from the Guide's eight hours for a one-month sprint",
            "Exactly eight hours",
            "Fifteen minutes",
            "A full two days",
          ],
          correctIndex: 0,
          explanation: "The Guide sets a maximum of eight hours for a one-month sprint; shorter sprints usually take proportionally less.",
        },
        {
          id: "pmp-d02-sprint-planning-q5",
          prompt: "Halfway through planning, the client asks for promo codes, which are not in the backlog or the SOW. What is it, and what do you do?",
          options: [
            "New scope: note it, and raise a change request so the client sees the impact before it enters any sprint",
            "A small item: add it to the sprint",
            "A bug: fix it this sprint",
            "Ignore it; it will be forgotten",
          ],
          correctIndex: 0,
          explanation: "Planning is a common place for scope creep. New items enter the backlog through the change-request process, not straight into a sprint.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d02-sprint-planning-q6",
          prompt: "Your team has carried over work for four sprints running. What is the most likely fix?",
          options: [
            "Plan to the average actually delivered, not the hoped-for number",
            "Ask the team to work weekends",
            "Make sprints shorter without changing anything else",
            "Stop showing the client what was planned",
          ],
          correctIndex: 0,
          explanation: "Constant carry-over means the plan is wrong, not the team. Using real delivered velocity makes commitments the client can trust.",
        },
        {
          id: "pmp-d02-sprint-planning-q7",
          prompt: "What should you subtract when working out a sprint's capacity? (Select all that apply.)",
          options: [
            "Planned leave",
            "Public holidays in the team's country",
            "Support or hypercare time on other projects",
            "The client's preferred deadline",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Capacity is the time actually available. The client's deadline is a constraint on the plan, not an input to capacity.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d02-sprint-planning-q8",
          prompt: "Why send the sprint plan to the client in writing after planning?",
          options: [
            "It records the goal, committed items and dependencies, which the demo will be judged against",
            "Because the Scrum Guide requires a signed sprint plan",
            "So the client can approve every task",
            "It is only needed for fixed-bid projects",
          ],
          correctIndex: 0,
          explanation: "A written plan prevents 'I thought this sprint included X' at the demo, and puts the client's dependencies on record.",
        },
      ],
      practice: {
        kind: "form",
        variant: "mom",
        templateId: "mom",
        prompt: "Write the sprint plan minutes for this client part of sprint planning for a React Native fitness app (Australian client).",
        context: md(
          "**Sprint 6 planning, client part, Teams, 45 min.** Client: Jess (PO). Oyelabs: PM, tech lead.",
          "",
          "**PM:** Capacity is 40 points. In priority order: A Class booking (13), B Payments (8), C Booking history (8), D Push reminders (5), E Apple Health sync (13).",
          "**Tech lead:** E needs the client's Apple developer account, which isn't set up yet.",
          "**Jess:** Account will take a couple of weeks. Leave E out then.",
          "**PM:** A to D is 34 points, so it fits. Goal: 'Members can book, pay and see their history.'",
          "**Jess:** Agreed. Can we also add promo codes?",
          "**PM:** Promo codes are new scope. I'll send a change request with the impact.",
          "**Jess:** Fine. I'll send the reminder copy by Tuesday.",
          "**PM:** Demo is Thursday 24th, 10:00 Sydney time.",
        ),
        fields: [
          { id: "goal", label: "Sprint goal", input: "text", required: true },
          { id: "committed", label: "Number of items committed", input: "number", required: true },
          {
            id: "appleHealth",
            label: "What happens to Apple Health sync?",
            input: "select",
            options: ["Committed this sprint", "Left in the backlog until the client's Apple account exists", "Split and half committed", "Dropped from the project"],
            required: true,
          },
          {
            id: "promo",
            label: "How are promo codes handled?",
            input: "select",
            options: ["Added to this sprint", "Change request to be raised", "Bug", "Already in scope"],
            required: true,
          },
          { id: "dependencies", label: "Client dependencies (item – owner – date)", input: "textarea", required: true },
          { id: "demo", label: "Demo date and time", input: "text", required: true },
        ],
        checks: [
          { fieldId: "committed", expected: 4 },
          { fieldId: "appleHealth", expected: "Left in the backlog until the client's Apple account exists" },
          { fieldId: "promo", expected: "Change request to be raised" },
        ],
        rubric: [
          { label: "Goal is one clear sentence", points: 1 },
          { label: "Dependencies have owners and dates", points: 2, description: "Reminder copy – Jess – Tuesday; Apple developer account – client – date to agree." },
          { label: "States what is out of the sprint and why", points: 2, description: "Apple Health left out (blocked); promo codes need a CR first." },
        ],
        sampleAnswer: {
          goal: "Members can book, pay and see their history.",
          committed: "4",
          appleHealth: "Left in the backlog until the client's Apple account exists",
          promo: "Change request to be raised",
          dependencies: "- Push reminder copy – Jess – Tuesday.\n- Apple developer account (for Apple Health later) – client – date to confirm.\n- PM – promo codes CR with impact – this week.",
          demo: "Thursday 24th, 10:00 Sydney time",
        },
      },
      sop: [
        {
          title: "Our sprint set-up",
          prompt:
            "[Oyelabs SOP – admin to fill] The standard sprint length, whether the client product owner joins planning, how capacity is calculated (leave, holidays, support load), the estimation unit (points or hours), and where the sprint plan is shared with the client.",
        },
      ],
    },

    // -----------------------------------------------------------------------
    // Weekly status
    // -----------------------------------------------------------------------
    {
      id: "pmp-d02-weekly-status",
      moduleId: "pmp-d02",
      trackId: "pm",
      title: "Weekly client status meeting",
      summary:
        "The weekly status meeting is the client's regular view of the project's health. For an overseas client, it may be the only time they think about the project all week. A written [[term:status-report]] with an honest [[term:rag-status]] goes with it, and the follow-the-sun reality of agency work makes the written part as important as the call.\n\nIts job is not to recite what happened. It is to make sure the client knows three things: are we on track, what do you need from me, and what is coming. That means the call is built around [[term:risk|risks]], [[term:issue|issues]], [[term:client-dependency|client dependencies]] and decisions. Completed work is a quick context line. The Oyelabs rule on weekly status reports, in the handbook card below, sets the cadence and content.\n\nHow to run it. Build the report from the board and the [[term:raid-log]], not from memory. Set the RAG for schedule, scope and budget, then the overall colour, and write one line of reason for every colour that is not green. Send the report before the call (or straight after, if the client prefers). In a 30-minute call (typical), lead with the RAG and its reasons, spend most of the time on decisions and dependencies, and close with actions and owners.\n\nThe common mistake is the \"watermelon\" report: green on the outside, red inside. The PM avoids an awkward call for three weeks, then turns red the week before a [[term:milestone]]. The client stops trusting every green. Amber early, with a recovery plan, is a sign of control. The second mistake is decisions buried at the end of a long update, where the call runs out of time.",
      level: "advanced",
      estMinutes: 45,
      webRefs: [
        { label: "Atlassian Team Playbook: Stakeholder Communications Plan", url: "https://www.atlassian.com/team-playbook/plays/stakeholder-communications-plan", kind: "docs", verifiedAt: "2026-10-02T12:04:13Z" },
        { label: "Atlassian: Project Status Report tips and templates", url: "https://www.atlassian.com/agile/project-management/status-report", kind: "article", verifiedAt: "2026-10-02T12:04:14Z" },
        { label: "TeamGantt: How to Write a Weekly Project Status Report", url: "https://www.teamgantt.com/project-status-report-template", kind: "article", verifiedAt: "2026-10-02T12:04:15Z" },
        { label: "Asana: Meeting Agenda templates and examples", url: "https://asana.com/resources/meeting-agenda", kind: "article", verifiedAt: "2026-10-02T12:04:16Z" },
      ],
      video: {
        title: "How to Run Project Status Meetings",
        channel: "American Management Association",
        url: "https://www.youtube.com/watch?v=iIss0K-W9UQ",
        videoId: "iIss0K-W9UQ",
        verifiedAt: "2026-10-02T12:05:30Z",
      },
      alternateVideos: [
        {
          title: "How to Lead a Meeting as a Project Manager | Explained in 8 Minutes",
          channel: "Max Mao",
          url: "https://www.youtube.com/watch?v=XsDSoWKroTk",
          videoId: "XsDSoWKroTk",
          verifiedAt: "2026-10-02T12:05:30Z",
        },
      ],
      handbook: {
        stages: ["custom-sprints"],
        rules: ["weekly-status-report", "escalation-levels", "mom-after-every-client-meeting"],
        templates: ["status-report-rag", "raid-log-template", "mom"],
      },
      sections: [
        {
          heading: "Purpose and when it happens",
          body: md(
            "The weekly status meeting runs every week from kickoff to closure, at a fixed day and time. It goes with the written [[term:status-report]] the Oyelabs rule requires.",
            "",
            "Its purpose is to answer three client questions:",
            "- **Are we on track?** The [[term:rag-status]] for schedule, scope and budget, and overall, each with a reason.",
            "- **What do you need from me?** Decisions and [[term:client-dependency|client dependencies]] with dates.",
            "- **What is coming?** Next week's work and the next [[term:milestone]].",
            "",
            "It is where [[term:risk|risks]] are raised early and agreed actions are tracked. If the status is red, it is also where you trigger the [[term:escalation]] path in the rule card below.",
          ),
        },
        {
          heading: "Who attends",
          body: md(
            "**Client side:** the [[term:spoc]], and the sponsor at least once a month or whenever the status is amber or red.",
            "",
            "**Oyelabs side:**",
            "- **PM:** owns the report and runs the call.",
            "- **Tech lead:** when a technical risk or decision is on the agenda.",
            "- **Delivery head or account manager:** when the status is red, or a commercial point is raised.",
            "",
            "Keep it small. A status call with ten people becomes a presentation, and nobody makes decisions.",
          ),
        },
        {
          heading: "Prepare: checklist",
          body: md(
            "- Export the sprint board: done, in progress, blocked.",
            "- Update the [[term:raid-log]]: new risks, issues and overdue dependencies.",
            "- Compare plan with forecast for the next milestone.",
            "- Set the RAG for schedule, scope and budget using the agreed definitions, then the overall colour, and write one reason line per non-green colour.",
            "- List decisions needed as yes/no questions with a date.",
            "- Fill in the status report template and send it a few hours before the call, or at least have it ready to share.",
            "- Put the time in both zones in the recurring Teams invite; check for public holidays on both sides.",
          ),
        },
        {
          heading: "Timed agenda template",
          body: md(
            "A 30-minute Teams call (typical):",
            "",
            "1. 0:00–0:03 Overall RAG in one line, and what changed since last week",
            "2. 0:03–0:08 Done this week and planned next week (headlines only; the report has the detail)",
            "3. 0:08–0:15 Risks and issues: top three, with owners and mitigations",
            "4. 0:15–0:23 Decisions needed and client dependencies due",
            "5. 0:23–0:27 Milestones and dates: on track or forecast change",
            "6. 0:27–0:30 Recap of actions, owners and dates",
            "",
            "If time runs short, cut item 2, never item 4.",
          ),
        },
        {
          heading: "Sample script",
          body: md(
            "- **Opening with the colour:** “Overall we're amber this week, down from green. The reason is one: the payment keys are four days late. Everything else is on plan.”",
            "- **Giving the plan with the colour:** “We can still make the UAT date of the 24th if the keys arrive by Friday. After that, every day of delay moves UAT by a day.”",
            "- **Asking for a decision:** “We need one decision today: do you want the delivery fee per zone or flat? We need it by Wednesday to keep the sprint.”",
            "- **Steering away from detail:** “The full list is in the report. Shall we spend our time on the two decisions?”",
            "- **When the client asks 'Why amber, nothing is late yet?':** “Because waiting for it to be late would leave you no time to act. Amber means a real risk with a plan.”",
            "- **Closing:** “Recap: Sara sends the keys by Friday, Mark confirms the delivery fee by Wednesday, I send the minutes today. Same time next week.”",
          ),
        },
        {
          heading: "What to show",
          body: md(
            "- The one-page status report: RAG at the top, then completed, planned, risks, issues, decisions, dependencies.",
            "- A simple milestone timeline with the forecast against the plan.",
            "- The RAID log entries that changed this week.",
            "",
            "Do not walk the full board ticket by ticket. Link it in the report for the client to explore.",
          ),
        },
        {
          heading: "Traps and how to recover",
          body: md(
            "- **The watermelon.** You kept a red project green. Fix it now: “I should have flagged this earlier. Here is where we really are and the plan.” Then escalate per the rule card.",
            "- **Amber forever.** A month of amber with no recovery is red. Change it and escalate.",
            "- **The client sends someone new each week.** Send the report to the SPOC and the sponsor regardless, so decisions don't depend on who attends.",
            "- **Decisions not taken.** Record them as open, with the impact of waiting: “Each day without a decision moves the milestone by a day.”",
            "- **The client turns it into a CR negotiation.** Park it: “Let's book 30 minutes tomorrow for the change request so we finish the status today.”",
            "- **Client misses the call.** Send the report anyway and ask for decisions in writing by a date.",
          ),
        },
        {
          heading: "Follow-up within 24 hours",
          body: md(
            "Send the final status report and a short [[term:mom]] for decisions and actions, the same day where possible (typical). Follow the Oyelabs rules in the handbook cards below on cadence and minutes.",
            "",
            "Template:",
            "- **Subject:** [Project] – status week 6 – Amber – 2 decisions needed",
            "- **Overall RAG** and one-line reason.",
            "- **Decisions taken** in the call.",
            "- **Decisions still needed:** question – from whom – by when – impact of waiting.",
            "- **Client dependencies due:** item – owner – date.",
            "- **Actions:** owner – action – date.",
            "- **Next status:** day and time in both time zones.",
          ),
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pmp-d02-weekly-status-q1",
          prompt: "What are the three questions a weekly status meeting should answer for the client?",
          options: [
            "Are we on track? What do you need from me? What is coming next?",
            "Who worked the most hours? Which tickets closed? How many bugs?",
            "Is the client happy? Is the team happy? Is BD happy?",
            "What is the budget? What is the price? What is the margin?",
          ],
          correctIndex: 0,
          explanation: "Health, asks and outlook. Ticket counts and hours are detail for the report, not the call.",
        },
        {
          id: "pmp-d02-weekly-status-q2",
          prompt: "Nothing is late yet, but the client's payment keys are four days overdue and UAT depends on them. You have a plan if they arrive by Friday. What is the schedule RAG?",
          options: ["Amber", "Green", "Red", "No colour until something is late"],
          correctIndex: 0,
          explanation: "A real risk to a date with a recovery plan is amber. Waiting until it is late to change the colour leaves the client no time to act.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d02-weekly-status-q3",
          prompt: "What is a 'watermelon' status report?",
          options: [
            "A report that shows green while the project is really red underneath",
            "A report with too many colours",
            "A report sent in summer",
            "A report that is red but recovers to green",
          ],
          correctIndex: 0,
          explanation: "Green outside, red inside. It destroys trust in every future green.",
        },
        {
          id: "pmp-d02-weekly-status-q4",
          prompt: "Which belong in the weekly status report? (Select all that apply.)",
          options: [
            "RAG for schedule, scope and budget, with reasons for any non-green",
            "Decisions needed from the client, with dates",
            "Client dependencies due",
            "Top risks with owners and mitigations",
            "Every developer's hours for the week",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 3],
          explanation: "The report gives health, asks and risks. Individual hours are internal.",
        },
        {
          id: "pmp-d02-weekly-status-q5",
          prompt: "Your call has 10 minutes left and you have not reached the decisions. What do you cut?",
          options: [
            "The 'done this week' walkthrough; point to the report and move to decisions",
            "The decisions; email them later",
            "The recap of actions",
            "Nothing; overrun by 30 minutes",
          ],
          correctIndex: 0,
          explanation: "Completed work is already in writing. Decisions need the client live.",
        },
        {
          id: "pmp-d02-weekly-status-q6",
          prompt: "A workstream has been amber for five weeks with no recovery. What should you do?",
          options: [
            "Turn it red and escalate per the escalation rule, with what you need to recover",
            "Keep it amber; it is not late yet",
            "Turn it green to reassure the client",
            "Stop reporting on that workstream",
          ],
          correctIndex: 0,
          explanation: "Amber without a working recovery plan is red. Escalating is how you get the decision or help that recovery needs.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d02-weekly-status-q7",
          prompt: "Mid-call, the client starts negotiating the price of a change request. What do you do?",
          options: [
            "Acknowledge it and book a separate 30-minute call for the CR, then finish the status",
            "Spend the rest of the call on the CR",
            "Give a discount to end the topic",
            "Refuse to discuss it at all",
          ],
          correctIndex: 0,
          explanation: "A CR negotiation needs the right people and time. Parking it respectfully keeps the status call doing its job.",
        },
        {
          id: "pmp-d02-weekly-status-q8",
          prompt: "You realise you have reported green for three weeks while a key integration was failing. Which steps are right? (Select all that apply.)",
          options: [
            "Correct the status now and own it plainly",
            "Give the real picture with a recovery plan and dates",
            "Escalate per the escalation rule if a commitment is at risk",
            "Wait one more week in case it fixes itself",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "The longer a watermelon lasts, the worse the reveal. Own it, give the plan, and escalate.",
          isEdgeCaseOrInterviewQuestion: true,
        },
      ],
      practice: {
        kind: "form",
        variant: "status",
        templateId: "status-report-rag",
        prompt:
          "Write this week's status report from the board export for a white-label food-delivery app for a client in the UAE. RAG rules for this exercise: Green = on plan; Amber = a real risk to a date, scope or budget, with a recovery plan; Red = a commitment will be missed without a client or management decision.",
        context: md(
          "**Week 6. Next milestone: UAT build to client on 24 Oct (today is 14 Oct).** Budget: on plan. No scope changes.",
          "",
          "| Item | Status | Note |",
          "|---|---|---|",
          "| Branding on all apps | Done | |",
          "| City configuration (2 cities) | Done | |",
          "| Order tracking | Done | |",
          "| Loyalty custom module | In progress | 70% |",
          "| Payment gateway | Blocked | Client keys due 8 Oct, not received. Built against sandbox; UAT still on 24 Oct if keys arrive by 17 Oct |",
          "| Delivery fee per zone | Waiting | Client decision needed: per zone or flat |",
          "| Apple enrolment | In progress | Client's D-U-N-S details pending |",
        ),
        fields: [
          { id: "overall", label: "Overall RAG", input: "select", options: ["Green", "Amber", "Red"], required: true },
          { id: "schedule", label: "Schedule RAG", input: "select", options: ["Green", "Amber", "Red"], required: true },
          { id: "scope", label: "Scope RAG", input: "select", options: ["Green", "Amber", "Red"], required: true },
          { id: "completed", label: "Items completed this week", input: "number", required: true },
          { id: "reason", label: "Reason for any non-green RAG and the recovery plan", input: "textarea", required: true },
          { id: "decisions", label: "Decisions needed from the client (with dates)", input: "textarea", required: true },
          { id: "dependencies", label: "Client dependencies due", input: "textarea", required: true },
        ],
        checks: [
          { fieldId: "overall", expected: "Amber" },
          { fieldId: "schedule", expected: "Amber" },
          { fieldId: "scope", expected: "Green" },
          { fieldId: "completed", expected: 3 },
        ],
        rubric: [
          { label: "Non-green reason is specific with a recovery plan", points: 2, description: "Payment keys overdue since 8 Oct; built against sandbox; UAT on 24 Oct holds if keys arrive by 17 Oct; each day later moves UAT." },
          { label: "Decisions phrased as questions with dates", points: 2, description: "Delivery fee: per zone or flat, by a stated date." },
          { label: "Dependencies have owners and dates", points: 2, description: "Payment keys (client, by 17 Oct); D-U-N-S details for Apple enrolment (client SPOC)." },
        ],
        sampleAnswer: {
          overall: "Amber",
          schedule: "Amber",
          scope: "Green",
          completed: "3",
          reason:
            "Schedule amber: the payment-gateway keys were due 8 Oct and have not arrived. We built against the sandbox, so UAT on 24 Oct holds if the keys arrive by 17 Oct; each day after that moves UAT by about a day.",
          decisions: "- Delivery fee: per zone or flat? Needed by 16 Oct to keep the sprint.",
          dependencies: "- Payment gateway live keys – client SPOC – by 17 Oct.\n- D-U-N-S details for Apple enrolment – client SPOC – this week.",
        },
      },
      sop: [
        {
          title: "Our status call format",
          prompt:
            "[Oyelabs SOP – admin to fill] Oyelabs' RAG definitions and thresholds, the standard status call length, whether the report is sent before or after the call, the default recipients (SPOC, sponsor, delivery head), and where reports are archived.",
        },
      ],
    },

    // -----------------------------------------------------------------------
    // Sprint demo
    // -----------------------------------------------------------------------
    {
      id: "pmp-d02-sprint-demo",
      moduleId: "pmp-d02",
      trackId: "pm",
      title: "Sprint review and client demo",
      summary:
        "The sprint demo is where the client sees working software and gives feedback. The Scrum Guide's sprint review is a working session with stakeholders, not a presentation: the team shows what was done, and everyone discusses what to do next. At an agency it is also the moment the client decides whether to trust your status reports, because they see with their own eyes whether the [[term:sprint]] goal was met.\n\nA good demo shows only work that meets the [[term:definition-of-done]], on a stable [[term:staging-environment]] with realistic test data. It is organised around user scenarios, not tickets: \"A member books a class and pays.\" It ends with decisions: what is accepted, what feedback becomes a backlog item, and what is a [[term:change-request]]. Atlassian's \"Demo Trust\" play captures the shape: set the stage, then demo, discuss, decide.\n\nHow to run it. Prepare the script and the data the day before, and rehearse with the developer who will drive. Open with the sprint goal and whether it was met. Demo each scenario, then stop and ask a specific question. Write feedback live and label it. Close with a read-back and the next sprint's focus, then send the [[term:mom]].\n\nThe common mistake is demoing unfinished work \"just to show progress\". When it breaks, the client remembers the crash, not the progress. The second mistake is saying yes in the room to \"can it also do…\". Demos are where clients get excited and ask for more. Acknowledge the idea, label it, and assess it as a change request so the scope stays honest.",
      level: "advanced",
      isMilestone: true,
      estMinutes: 55,
      webRefs: [
        { label: "Scrum Guide (2020)", url: "https://scrumguides.org/scrum-guide.html", kind: "spec", verifiedAt: "2026-10-02T12:04:11Z" },
        { label: "Atlassian Team Playbook: Demo Trust", url: "https://www.atlassian.com/team-playbook/plays/demo-trust", kind: "docs", verifiedAt: "2026-10-02T12:04:14Z" },
        { label: "Atlassian: What is a Sprint Review?", url: "https://www.atlassian.com/agile/scrum/sprint-reviews", kind: "article", verifiedAt: "2026-10-02T12:04:16Z" },
        { label: "Mountain Goat Software: Sprint Review Meeting", url: "https://www.mountaingoatsoftware.com/agile/scrum/meetings/sprint-review", kind: "article", verifiedAt: "2026-10-02T12:04:16Z" },
      ],
      video: {
        title: "How to Facilitate the Sprint Review",
        channel: "Scrum.org",
        url: "https://www.youtube.com/watch?v=Fbp9eLbcf7A",
        videoId: "Fbp9eLbcf7A",
        verifiedAt: "2026-10-02T12:05:30Z",
      },
      alternateVideos: [
        {
          title: "A Real Sprint Review Meeting Example",
          channel: "DataMiner by Skyline Communications",
          url: "https://www.youtube.com/watch?v=as9IYFrTiKc",
          videoId: "as9IYFrTiKc",
          verifiedAt: "2026-10-02T12:05:30Z",
        },
        {
          title: "Sprint Review: More Than Just a Demo",
          channel: "Mountain Goat Software: Agile & Scrum Mastery",
          url: "https://www.youtube.com/watch?v=9WzoYrtXR-A",
          videoId: "9WzoYrtXR-A",
          verifiedAt: "2026-10-02T12:05:30Z",
        },
      ],
      handbook: {
        stages: ["custom-sprints"],
        rules: ["mom-after-every-client-meeting", "cr-when-needed", "secure-credential-sharing"],
        templates: ["mom", "cr-form"],
      },
      sections: [
        {
          heading: "Purpose and when it happens",
          body: md(
            "The demo happens at the end of every [[term:sprint]], before the retrospective. The Scrum Guide sets the sprint review at up to four hours for a one-month sprint; for a two-week sprint, about one hour is typical.",
            "",
            "Its purpose is to:",
            "- show working software that meets the [[term:definition-of-done]];",
            "- check it against the [[term:acceptance-criteria]] the client agreed in planning;",
            "- collect feedback and turn it into decisions: accepted, backlog item, or [[term:change-request]];",
            "- agree what the next sprint should focus on.",
            "",
            "It is not formal acceptance. That happens at [[term:uat]] and [[term:sign-off]]. Say so, so the client does not feel rushed into approving.",
          ),
        },
        {
          heading: "Who attends",
          body: md(
            "**Client side:** the product owner or [[term:spoc]], and the people who will use the feature (for example a studio manager). The sponsor for milestone demos.",
            "",
            "**Oyelabs side:**",
            "- **PM:** opens, keeps time, records feedback and decisions.",
            "- **Developer or QA driving the demo:** the person who knows the feature best. Rotate it; it builds the team's confidence with the client.",
            "- **Tech lead:** answers feasibility questions.",
            "- **Designer:** when new screens are shown.",
            "",
            "Atlassian's Demo Trust play suggests 4 to 6 people for a focused session.",
          ),
        },
        {
          heading: "Prepare: checklist",
          body: md(
            "- Only items that meet the definition of done. Leave out anything half-built.",
            "- A short demo script per scenario: user, steps, expected result.",
            "- Test data that looks real but is not real customer data; accounts logged in and ready.",
            "- Deploy to staging a day before and freeze it. Nobody deploys during the demo.",
            "- Rehearse once with the driver. Check notifications, email and payments in sandbox.",
            "- A backup: a short screen recording of each scenario in case the build or the connection fails.",
            "- For mobile, mirror the device or use an emulator at real size; turn off personal notifications.",
            "- Credentials for test accounts shared through the secure route, never pasted in the Teams chat.",
            "- Know your answer to “When can we have…” for the top two backlog items.",
          ),
        },
        {
          heading: "Timed agenda template",
          body: md(
            "A 60-minute Teams demo for a two-week sprint (typical):",
            "",
            "1. 0:00–0:05 Sprint goal, met or not, and what you will see",
            "2. 0:05–0:35 Demo by scenario, each followed by a short discussion and a decision",
            "3. 0:35–0:45 What was not finished and why; what changed in the plan",
            "4. 0:45–0:52 Feedback triage: each item labelled accepted, backlog, or change request",
            "5. 0:52–0:57 Next sprint focus and dependencies needed from the client",
            "6. 0:57–1:00 Read back decisions and actions; optional confidence vote (1 to 4)",
          ),
        },
        {
          heading: "Sample script",
          body: md(
            "- **Opening:** “Sprint goal was ‘members can book and pay for a class’. We met it on both platforms. Ravi will show you the booking flow as a member would use it.”",
            "- **Setting expectations:** “This is staging with test data. The formal sign-off comes in UAT, so today is about feedback.”",
            "- **Asking specific questions:** “Is this the information a member needs before they pay? Anything missing for your front desk?”",
            "- **Handling a new request:** “Loyalty points are a great idea for retention. They aren't in the current scope, so I'll send a change request with the time and cost by Friday. If you only need it for the investor demo, tell me, as that may change the size.”",
            "- **Something breaks:** “That's on us. Let me show the recording of the same flow, and we'll confirm the fix in tomorrow's update.”",
            "- **Asking for a decision:** “Can we treat booking as accepted for this sprint, with the two copy changes on the backlog?”",
            "- **Closing:** “Recap: booking accepted, two copy changes to the backlog, loyalty as a change request by Friday, and we need the reminder copy by Tuesday.”",
          ),
        },
        {
          heading: "What to show",
          body: md(
            "**Demo, not deck.** At most two slides: the sprint goal and a list of what is shown and what is not.",
            "",
            "Then the live product on staging, scenario by scenario, at the size the user will see it. Keep the board out of the demo; show it only when explaining what was not finished.",
            "",
            "Have the feedback list visible on a second screen or document, so the client sees each comment labelled as you go.",
          ),
        },
        {
          heading: "Traps and how to recover",
          body: md(
            "- **The build breaks.** Stay calm, own it, switch to the backup recording, and promise a follow-up. Never blame the developer in front of the client.",
            "- **“Can it also do…?”** Acknowledge, label it as a change request or backlog idea, and do not estimate on the call.",
            "- **The client treats the demo as UAT.** Remind them it is feedback on work in progress; formal acceptance comes at UAT.",
            "- **Feedback is all about colours.** Bring it back to the user scenario and the agreed design.",
            "- **The sprint goal was missed.** Say it first, not last: what was done, what was not, why, and the new plan.",
            "- **Silence.** Ask named, specific questions. Silence on Teams rarely means agreement.",
          ),
        },
        {
          heading: "Follow-up within 24 hours",
          body: md(
            "Send the [[term:mom]] within the Oyelabs deadline in the rule card below, with the recording link if the client agreed to recording. Raise change requests on the CR form.",
            "",
            "Template:",
            "- **Subject:** Sprint 6 demo – decisions and next steps",
            "- **Sprint goal:** met / partly met, one line.",
            "- **Shown and accepted:** list.",
            "- **Feedback:** item – label (backlog, CR, accepted change) – owner.",
            "- **Change requests:** CR number – impact to follow by [date].",
            "- **Not finished:** item – reason – new plan.",
            "- **Client dependencies:** item – owner – date.",
            "- **Next demo:** date, time in both time zones.",
          ),
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pmp-d02-sprint-demo-q1",
          prompt: "According to the Scrum Guide, what is the sprint review?",
          options: [
            "A working session where the team presents results to stakeholders and they discuss what to do next",
            "A slide presentation of ticket counts",
            "The client's formal acceptance of the release",
            "An internal team retrospective",
          ],
          correctIndex: 0,
          explanation: "The Guide says the team should avoid limiting it to a presentation. Formal acceptance is UAT; improvement is the retrospective.",
        },
        {
          id: "pmp-d02-sprint-demo-q2",
          prompt: "A feature is 80% built. The client is eager to see progress. Should it be in the demo?",
          options: [
            "No: show only work that meets the definition of done, and say briefly where the rest stands",
            "Yes: always show everything",
            "Yes, but without telling the client it is unfinished",
            "Only if the PM drives it",
          ],
          correctIndex: 0,
          explanation: "Half-built work breaks in demos, and the client remembers the crash. Report its status in words instead.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d02-sprint-demo-q3",
          prompt: "Which belong in your demo preparation? (Select all that apply.)",
          options: [
            "Freeze staging after deploying the day before",
            "Realistic test data that is not real customer data",
            "A backup recording of each scenario",
            "Deploying a last fix five minutes before the call",
            "A rehearsal with the person who will drive",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 4],
          explanation: "Last-minute deploys are the main cause of broken demos. Freeze, rehearse and keep a backup.",
        },
        {
          id: "pmp-d02-sprint-demo-q4",
          prompt: "During the demo, the founder says, 'Can we add loyalty points before the investor demo? It's tiny.' What do you say?",
          options: [
            "Acknowledge the idea, say it is outside the current scope, and offer a change request with time and cost, asking what the investor demo really needs",
            "“Sure, we'll squeeze it in this sprint.”",
            "“No, that's not possible.”",
            "Give a rough estimate on the call to keep the mood positive",
          ],
          correctIndex: 0,
          explanation: "Demos generate requests. Route them through change control, and ask about the underlying need: a demo-only version may be much smaller.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d02-sprint-demo-q5",
          prompt: "The booking flow crashes live in the demo. What is the best response?",
          options: [
            "Own it calmly, switch to the backup recording, and commit to a follow-up with the fix",
            "Blame the developer driving the demo",
            "End the demo immediately",
            "Pretend it is expected behaviour",
          ],
          correctIndex: 0,
          explanation: "Calm ownership plus a backup keeps the meeting useful and protects trust. Blame in front of the client damages both the team and the relationship.",
        },
        {
          id: "pmp-d02-sprint-demo-q6",
          prompt: "The client says, 'Great, so this is signed off then?' after the demo. What do you say?",
          options: [
            "“Thank you. Today is feedback on this sprint; formal sign-off happens at UAT against the acceptance criteria.”",
            "“Yes, it's all signed off now.”",
            "“No, you can't approve anything.”",
            "Say nothing and record it as signed off",
          ],
          correctIndex: 0,
          explanation: "Mixing demo feedback with formal acceptance causes disputes later. Keep sign-off in UAT, where acceptance criteria are checked properly.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d02-sprint-demo-q7",
          prompt: "How should each piece of demo feedback be recorded? (Select all that apply.)",
          options: [
            "Labelled as accepted, backlog item or change request",
            "With an owner",
            "Read back to the client before the call ends",
            "Kept only in the Teams recording",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2],
          explanation: "Labelled, owned and read back. A recording is not a decision record.",
        },
        {
          id: "pmp-d02-sprint-demo-q8",
          prompt: "The sprint goal was missed. When should you say so in the demo?",
          options: [
            "First, in the opening: what was done, what was not, why, and the new plan",
            "At the end, if there is time",
            "Not at all; show what works",
            "Only in the written follow-up",
          ],
          correctIndex: 0,
          explanation: "Clients find out anyway. Saying it upfront, with a plan, keeps trust; hiding it until the end looks evasive.",
        },
      ],
      practice: {
        kind: "roleplay",
        prompt:
          "You are 40 minutes into the sprint 5 demo on Teams for a multi-vendor ordering app (fixed bid, sprint 5 of 8). The demo went well. The founder unmutes with a new request.",
        scenarioId: "scope-creep",
        personaId: "startup-founder",
        maxTurns: 6,
        brief:
          "Acknowledge the idea, show it is outside the signed scope, find out what the investor demo really needs, offer a change request (or a trade-off or phase 2) with the impact on time and cost to follow, and close the demo with a clear next step. Then write the follow-up email.",
        rubric: [
          { label: "Clarity", points: 2, description: "Short, plain messages; the main point comes first; no jargon the client would not know." },
          {
            label: "Correct use of process and terms",
            points: 3,
            description: "Names the right process (change request, warranty, UAT triage, client-owned accounts) and uses agency terms correctly, explained where needed.",
          },
          { label: "Empathy", points: 2, description: "Acknowledges the client's situation and feelings; asks about the underlying need before defending a position." },
          {
            label: "A firm and fair scope position",
            points: 3,
            description: "Holds the signed scope and the rate card without conceding work for free, while offering fair options (phase it, trade off, a CR).",
          },
          { label: "A clear next step", points: 2, description: "Ends with a concrete next step: who does what, by when." },
          {
            label: "The follow-up email",
            points: 3,
            description: "A short email that confirms what was agreed, the decision or options, the owners and dates, in a professional tone.",
          },
        ],
        followUp: true,
      },
      sop: [
        {
          title: "Our demo rules",
          prompt:
            "[Oyelabs SOP – admin to fill] Which environment we demo from, when staging is frozen before a demo, test-data rules, who drives the demo, whether demos are recorded in Teams (and the consent wording), and the backup we keep.",
        },
      ],
    },
  ],
} satisfies Module;
