import type { Module } from "@/types/curriculum";

/** Joins lines into one Markdown body. */
const md = (...lines: string[]) => lines.join("\n");

export default {
  id: "pmp-d01",
  trackId: "pm",
  name: "Client meetings: Starting a project",
  description:
    "Step-by-step playbooks for the four meetings that start a project: the internal kickoff, the client kickoff, discovery workshops and the client design review. Each one gives the purpose, attendees, prep checklist, a timed agenda, a sample script for overseas clients on Teams, traps and the follow-up.",
  topics: [
    // -----------------------------------------------------------------------
    // Internal kickoff
    // -----------------------------------------------------------------------
    {
      id: "pmp-d01-internal-kickoff",
      moduleId: "pmp-d01",
      trackId: "pm",
      title: "Internal kickoff meeting",
      summary:
        "The internal kickoff is the meeting where the delivery team first sees the deal as BD sold it, before the client ever sees the team. It sits between the BD handover and the client kickoff. At an agency this matters more than anywhere else: the [[term:sow]] was written by someone who will not build it, and every promise BD made on a sales call is now your team's problem.\n\nIts job is simple. By the end, every person on the team can say the same thing about the [[term:scope-baseline]], the [[term:out-of-scope]] list, the [[term:milestone]] dates, who owns what ([[term:raci]]), and the top [[term:risk|risks]]. The team also agrees what it needs from the client and by when, so those [[term:client-dependency|client dependencies]] can be asked for in the client kickoff, not discovered in sprint 3.\n\nHow to run it. Read the SOW and the BD handover notes yourself first, and mark every vague line. Book 60 to 90 minutes (typical) with the tech lead, designer, QA and the BD owner. Walk the scope, then run a short pre-mortem: \"It is go-live day and this project failed. Why?\" Turn the answers into a [[term:raid-log]]. Close with a draft client kickoff agenda and owners for each prep item.\n\nThe common mistake is to skip it because \"the client kickoff is tomorrow anyway\". The team then hears the scope for the first time in front of the client, the tech lead questions an estimate on the call, and the client learns your team is not aligned. The second mistake is to make it a reading of the SOW. Nobody remembers a reading. They remember the risks they raised themselves.",
      level: "intermediate",
      estMinutes: 35,
      webRefs: [
        { label: "Atlassian Team Playbook: Project Kickoff", url: "https://www.atlassian.com/team-playbook/plays/project-kickoff", kind: "docs", verifiedAt: "2026-10-02T12:04:06Z" },
        { label: "Atlassian Team Playbook: Pre-mortem", url: "https://www.atlassian.com/team-playbook/plays/pre-mortem", kind: "docs", verifiedAt: "2026-10-02T12:04:06Z" },
        { label: "Atlassian Team Playbook: Roles and Responsibilities", url: "https://www.atlassian.com/team-playbook/plays/roles-and-responsibilities", kind: "docs", verifiedAt: "2026-10-02T12:04:06Z" },
        { label: "The Digital Project Manager: How To Run Project Kickoff Meetings", url: "https://thedigitalprojectmanager.com/project-management/how-to-run-a-great-project-kick-off-meeting/", kind: "article", verifiedAt: "2026-10-02T12:04:06Z" },
      ],
      video: {
        title: "Kickoff Meeting [YOUR GUIDE TO STARTING PROJECTS]",
        channel: "Adriana Girdler",
        url: "https://www.youtube.com/watch?v=0PQLEyFEgag",
        videoId: "0PQLEyFEgag",
        verifiedAt: "2026-10-02T12:05:19Z",
      },
      alternateVideos: [
        {
          title: "How to Run a Brilliant Project Kick Off Meeting | The Everyday Project Manager",
          channel: "The Everyday Project Manager",
          url: "https://www.youtube.com/watch?v=ccgKREwz0jg",
          videoId: "ccgKREwz0jg",
          verifiedAt: "2026-10-02T12:05:19Z",
        },
      ],
      handbook: {
        stages: ["custom-bd-handover", "custom-internal-kickoff"],
        rules: ["secure-credential-sharing"],
        templates: ["kickoff-agenda", "raid-log-template", "mom"],
      },
      sections: [
        {
          heading: "Purpose and when it happens",
          body: md(
            "The internal kickoff happens after the BD handover and before the client kickoff, usually within a few working days of the signed [[term:sow]] (typical). It is a team-only meeting, so people can question estimates and name risks openly.",
            "",
            "It has four outcomes:",
            "- one shared reading of the [[term:scope-baseline]], including what is [[term:out-of-scope]];",
            "- named owners for each workstream ([[term:raci]]);",
            "- a first [[term:raid-log]] from a short pre-mortem;",
            "- a draft agenda and a list of asks for the client kickoff.",
            "",
            "For a white-label project, it is also where the team confirms which parts are the [[term:core-product]], which are [[term:configuration]] and which are [[term:customisation]], before anyone promises otherwise to the client.",
          ),
        },
        {
          heading: "Who attends",
          body: md(
            "- **PM** (you): runs it, owns the outputs.",
            "- **BD owner** who sold the deal: explains the promises, the client's politics and anything said on calls that is not in the SOW. Ask for the first 20 minutes at least.",
            "- **Tech lead or architect**: challenges the [[term:estimate]] and the technical [[term:assumption|assumptions]].",
            "- **Designer, QA lead** and any senior developer already assigned.",
            "- **Delivery head**: optional, but invite them when the deal is large, [[term:fixed-bid]], or has an unusual clause.",
            "",
            "Keep it to the people who will deliver. Atlassian's kickoff play suits 3 to 14 people; past about eight, split the risk discussion into smaller groups.",
          ),
        },
        {
          heading: "Prepare: checklist",
          body: md(
            "- Read the signed SOW, proposal and BD handover notes. Highlight every vague line (\"admin panel\", \"basic reports\", \"integration with their system\").",
            "- List the [[term:milestone|milestones]] and any [[term:milestone-billing]] dates from the contract.",
            "- Draft a list of [[term:client-dependency|client dependencies]]: content, API keys, store accounts, brand assets, test users.",
            "- Prepare a one-page scope summary: in scope, out of scope, assumptions.",
            "- Pre-fill a blank RAID log and the kickoff agenda template so the meeting edits, not starts from zero.",
            "- Check access: repository, project board, Teams channel, shared drive. Credentials go through the secure route in the rule card below, never in chat.",
            "- Book the Teams meeting with the SOW and scope summary attached, and ask attendees to read them first.",
          ),
        },
        {
          heading: "Timed agenda template",
          body: md(
            "A 60-minute version (typical; extend to 90 for large or fixed-bid deals):",
            "",
            "1. 0:00–0:05 Goal of the meeting and what we leave with",
            "2. 0:05–0:20 BD walkthrough: the client, why they bought, promises made, sensitive points",
            "3. 0:20–0:30 Scope walk: in scope, out of scope, vague lines to clarify with the client",
            "4. 0:30–0:42 Pre-mortem: \"It failed. Why?\" Silent writing, then group into themes",
            "5. 0:42–0:50 RAID: turn the top themes into risks with owners and mitigations",
            "6. 0:50–0:55 Roles, RACI and the client asks for the kickoff",
            "7. 0:55–1:00 Recap: actions, owners, dates, and the client kickoff date",
          ),
        },
        {
          heading: "Sample script",
          body: md(
            "- **Opening:** “Thanks all. In an hour we want three things: one view of scope, a risk list with owners, and the asks for Thursday's client kickoff. I'll keep time.”",
            "- **Inviting BD:** “Tell us what the client believes they bought, not just what the SOW says. What did you promise on calls?”",
            "- **Steering a vague line:** “‘Reports’ could be one CSV or a dashboard. We won't solve it here. I'm logging it as a question for discovery.”",
            "- **Starting the pre-mortem:** “Imagine it is go-live day and this project has failed badly. Take three minutes and write down why, one reason per sticky note.”",
            "- **When an estimate is challenged:** “Good catch. Is it a risk we can manage, or is the estimate wrong? If it is wrong, I'll raise it with BD and the delivery head today, before the client hears a date.”",
            "- **Asking for a decision:** “Can we agree the tech lead owns the architecture risk and reports on it each Friday?”",
            "- **Closing:** “Recap: five actions, all with owners and dates. Minutes and the RAID log go out today. Client kickoff is Thursday at 2 pm UK time.”",
          ),
        },
        {
          heading: "What to show",
          body: md(
            "Share your screen in Teams and work live in the documents rather than in slides:",
            "- the one-page scope summary, with vague lines highlighted;",
            "- the milestone and billing timeline from the contract;",
            "- a shared whiteboard (or the Teams whiteboard) for the silent pre-mortem;",
            "- the RAID log, filled in during the meeting;",
            "- the draft client kickoff agenda, so the team sees what will be said to the client.",
            "",
            "Editing the RAID log live means the output exists when the call ends.",
          ),
        },
        {
          heading: "Traps and how to recover",
          body: md(
            "- **The team finds the estimate is wrong.** Do not hide it until the client kickoff. Log it as a risk, and escalate to BD and the delivery head the same day with the size of the gap.",
            "- **BD cannot attend.** Get a recorded 15-minute briefing or written answers to your questions before the meeting. Never run it blind.",
            "- **It becomes a design or architecture debate.** Park it: “Tech lead and I take this offline and bring a proposal on Monday.”",
            "- **Someone says 'we always do it this way'.** Ask whether the SOW says so. If it does not, it is an assumption to confirm with the client.",
            "- **Silence in the pre-mortem.** Seed it with one reason yourself, such as late client content, then ask each person for one more by name.",
            "- **The client is on the invite by mistake.** Remove them before it starts. The value of this meeting is honest internal discussion.",
          ),
        },
        {
          heading: "Follow-up within 24 hours",
          body: md(
            "Send short internal minutes (the [[term:mom]]) to the team and BD, with the RAID log and the draft kickoff agenda attached. Check the handbook for the Oyelabs rules on minutes and credentials.",
            "",
            "Template:",
            "- **Subject:** Internal kickoff – [project] – minutes and RAID",
            "- **Decisions:** the scope reading we agreed; questions to raise with the client.",
            "- **Top risks:** three to five, each with an owner and a mitigation.",
            "- **Actions:** owner – action – due date.",
            "- **Client asks for kickoff:** the dependencies list with the dates we need them.",
            "- **Next:** client kickoff on [date, time in both time zones].",
          ),
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pmp-d01-internal-kickoff-q1",
          prompt: "Why does an agency hold an internal kickoff before the client kickoff, rather than one combined meeting?",
          options: [
            "So the team can challenge scope and estimates and name risks openly, then face the client aligned",
            "Because the client is not allowed to meet developers",
            "Because the contract requires two meetings",
            "So BD can renegotiate the price before the client meets the team",
          ],
          correctIndex: 0,
          explanation: "The internal kickoff is a safe room for disagreement. Raising an estimate problem in front of the client damages trust; raising it internally lets you fix it first.",
        },
        {
          id: "pmp-d01-internal-kickoff-q2",
          prompt: "Which outputs should exist when the internal kickoff ends? (Select all that apply.)",
          options: [
            "A first RAID log with owners",
            "A list of client dependencies with the dates you need them",
            "A draft client kickoff agenda",
            "Final UI designs approved by the team",
            "A shared reading of what is in and out of scope",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 4],
          explanation: "The internal kickoff produces alignment, risks and asks. Designs come much later, after discovery and the design stage.",
        },
        {
          id: "pmp-d01-internal-kickoff-q3",
          prompt: "During the scope walk, the tech lead says the 'integration with the client's ERP' line could be anything from a CSV import to a two-way live sync. What do you do in the meeting?",
          options: [
            "Log it as an open question and an assumption to confirm in discovery, with a risk if the estimate assumed the small version",
            "Pick the smaller version and tell the team that is the scope",
            "Spend the rest of the meeting designing the integration",
            "Ignore it until the client mentions it",
          ],
          correctIndex: 0,
          explanation: "Vague lines are risks. Log them, check what the estimate assumed, and resolve them with the client. Deciding alone, or designing it now, both go wrong.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d01-internal-kickoff-q4",
          prompt: "What is a pre-mortem?",
          options: [
            "The team imagines the project has already failed and lists the reasons, which become risks",
            "A review of a past failed project",
            "A meeting held just before go-live to check readiness",
            "A post-launch review with the client",
          ],
          correctIndex: 0,
          explanation: "Imagining failure makes people name risks they would otherwise keep quiet about. The reasons go into the RAID log with owners.",
        },
        {
          id: "pmp-d01-internal-kickoff-q5",
          prompt: "In the internal kickoff the team concludes the fixed-bid estimate is about 30% too low. The client kickoff is in two days. What is the best move?",
          options: [
            "Escalate to BD and the delivery head the same day with the size of the gap, before any date is given to the client",
            "Say nothing and hope the team can absorb it with overtime",
            "Tell the client at the kickoff that the price will go up",
            "Cut testing time quietly to fit the estimate",
          ],
          correctIndex: 0,
          explanation: "A known gap hidden from your own leadership becomes a crisis later. Escalate internally first so the company decides how to handle it; do not surprise the client on day one.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d01-internal-kickoff-q6",
          prompt: "Who should you insist on hearing from in the internal kickoff, even if only for 20 minutes?",
          options: ["The BD owner who sold the deal", "The client's CEO", "The finance team", "Every developer in the company"],
          correctIndex: 0,
          explanation: "BD knows what was promised on calls and what the client believes they bought. Without them you only have the SOW, which rarely tells the whole story.",
        },
        {
          id: "pmp-d01-internal-kickoff-q7",
          prompt: "A developer posts the client's staging server password in the internal kickoff chat so everyone has it. What should you do?",
          options: [
            "Remove it, ask for it to be rotated if needed, and share it through the secure route in the Oyelabs rule",
            "Leave it; the chat is internal",
            "Pin it so it is easy to find",
            "Email it to the whole team as well",
          ],
          correctIndex: 0,
          explanation: "Meeting chats are searchable and often shared later. Credentials go through the approved secure route; follow the rule card on this topic.",
        },
        {
          id: "pmp-d01-internal-kickoff-q8",
          prompt: "Which of these belong on the list of client asks prepared for the client kickoff? (Select all that apply.)",
          options: [
            "Payment-gateway sandbox and live account access",
            "Brand assets and content owners",
            "Test users and test data",
            "The team's internal velocity target",
            "A named SPOC who can approve decisions",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 4],
          explanation: "Client dependencies and a decision-maker are exactly what the client kickoff must secure. Internal velocity is not the client's business.",
          isEdgeCaseOrInterviewQuestion: true,
        },
      ],
      practice: {
        kind: "form",
        variant: "mom",
        templateId: "mom",
        prompt:
          "Write the internal minutes for this internal kickoff for a Laravel booking platform for a UK clinic chain. Use the transcript below.",
        context: md(
          "**Internal kickoff, Teams, 60 min.** PM (Asha), BD (Karan), tech lead (Vikram), designer (Neha), QA (Rahul).",
          "",
          "**Karan:** Client runs 12 clinics. They bought online booking, reminders and an admin panel. On the call I said SMS reminders 'should be fine', but the SOW only says email reminders.",
          "**Vikram:** SOW says 'integration with their patient system'. If that's a live two-way sync, our estimate is short by weeks.",
          "**Asha:** Logging both. SMS goes to discovery as an open question, not a promise. The integration is a risk; Vikram, can you size both versions by Monday?",
          "**Vikram:** Yes.",
          "**Neha:** I need their brand guidelines before wireframes.",
          "**Rahul:** And test patients that are not real people.",
          "**Asha:** Pre-mortem top reasons: late client content, the integration, and approvals dragging because we don't know who decides. Karan, who is the SPOC?",
          "**Karan:** Probably the operations director. I'll confirm by Friday.",
          "**Asha:** Then client asks for Thursday's kickoff: brand guidelines, test data, the API documentation for the patient system, and a named SPOC. I'll send minutes and the RAID log today.",
        ),
        fields: [
          { id: "decisions", label: "Decisions", input: "textarea", required: true },
          { id: "risks", label: "Top risks (owner and mitigation)", input: "textarea", required: true },
          { id: "actions", label: "Action items (owner – action – due date)", input: "textarea", required: true },
          {
            id: "sms",
            label: "How should SMS reminders be recorded?",
            input: "select",
            options: ["In scope, as promised by BD", "Open question for discovery (not in the SOW)", "Out of scope, do not mention to the client", "Bug to fix later"],
            required: true,
          },
          { id: "clientAsks", label: "Number of client asks for the kickoff", input: "number", required: true },
          { id: "next", label: "Next meeting", input: "text", required: true },
        ],
        checks: [
          { fieldId: "sms", expected: "Open question for discovery (not in the SOW)" },
          { fieldId: "clientAsks", expected: 4 },
        ],
        rubric: [
          { label: "Decisions are stated as decisions, not discussion", points: 2, description: "Lists the agreed reading: SMS is an open question; integration is a risk to size; asks for the client kickoff." },
          { label: "Risks have owners and mitigations", points: 2, description: "Integration (tech lead, size both versions by Monday), late content, unclear decision-maker (BD to confirm SPOC)." },
          { label: "Actions have an owner and a date", points: 2, description: "Vikram sizing by Monday, Karan SPOC by Friday, PM minutes and RAID today." },
          { label: "Short and scannable", points: 1, description: "Bullets, no transcript retelling." },
        ],
        sampleAnswer: {
          decisions:
            "- SMS reminders are not in the SOW (email only): raise as an open question in discovery, not a promise.\n- 'Integration with patient system' is ambiguous: treat as a risk until sized.\n- Client kickoff asks agreed (see below).",
          risks:
            "- Integration may be a two-way sync, estimate short by weeks – owner Vikram – size both versions.\n- Late client content (brand, test data) – owner Asha – ask with dates at kickoff.\n- Unclear decision-maker slows approvals – owner Karan – confirm SPOC.",
          actions:
            "- Vikram – size CSV import vs two-way sync – Monday.\n- Karan – confirm client SPOC – Friday.\n- Asha – send minutes and RAID log – today.\n- Asha – add client asks to the kickoff agenda – before Thursday.",
          sms: "Open question for discovery (not in the SOW)",
          clientAsks: "4",
          next: "Client kickoff, Thursday (time in UK and our time zone)",
        },
      },
      sop: [
        {
          title: "Our internal kickoff",
          prompt:
            "[Oyelabs SOP – admin to fill] Who must attend the internal kickoff (BD owner, delivery head, tech lead), how soon after the signed SOW it is held, its standard length, and where the scope summary and first RAID log are stored.",
        },
      ],
    },

    // -----------------------------------------------------------------------
    // Client kickoff
    // -----------------------------------------------------------------------
    {
      id: "pmp-d01-client-kickoff",
      moduleId: "pmp-d01",
      trackId: "pm",
      title: "Client kickoff meeting",
      summary:
        "The client kickoff is the first meeting where the client meets the delivery team. For an overseas client who has only spoken to BD, it is where they decide whether the people building their product are in control. It sets the rules of the whole project: who decides, how often you talk, what you need from them, and what is not included.\n\nA good kickoff ends with agreement on five things. The goals and how success is measured. The [[term:scope-baseline]], with the [[term:out-of-scope]] list said out loud. The [[term:milestone]] plan. The ways of working: [[term:spoc|SPOCs]], cadence, tools, the [[term:escalation-matrix]] and how changes are handled through a [[term:change-request]]. And the [[term:client-dependency|client dependencies]], each with a date.\n\nHow to run it. Send the agenda and a short deck a day ahead, in the Teams invite, with the time in both time zones. Book 60 to 90 minutes (typical). Open with introductions and the client's own words about why the project matters. Keep slides short and spend the time on questions. Close by reading back decisions and actions, and send the [[term:mom]] the same day.\n\nThe common mistake is to treat it as a celebration and skip the uncomfortable parts. If you do not name out-of-scope items and client dependencies on day one, every later conversation about them sounds like an excuse. The second mistake is to leave without a named decision-maker. A project with five people giving feedback and nobody approving will stall at design.",
      level: "advanced",
      estMinutes: 45,
      webRefs: [
        { label: "Confluence: Project kickoff template", url: "https://www.atlassian.com/software/confluence/templates/project-kickoff", kind: "docs", verifiedAt: "2026-10-02T12:04:07Z" },
        { label: "Asana: Project Kickoff Meeting 10-step guide", url: "https://asana.com/resources/project-kickoff-meeting", kind: "article", verifiedAt: "2026-10-02T12:04:08Z" },
        { label: "ProjectManager: How to write a project kickoff agenda", url: "https://www.projectmanager.com/blog/write-project-kickoff-meeting", kind: "article", verifiedAt: "2026-10-02T12:04:07Z" },
        { label: "The Digital Project Manager: Project Kickoff Guide", url: "https://thedigitalprojectmanager.com/project-management/project-kickoff-guide/", kind: "article", verifiedAt: "2026-10-02T12:04:07Z" },
      ],
      video: {
        title: "Client Kickoff Meeting Agenda | How To Set the Stage for Success",
        channel: "The Digital Project Manager",
        url: "https://www.youtube.com/watch?v=ZnWZQ3G-HkM",
        videoId: "ZnWZQ3G-HkM",
        verifiedAt: "2026-10-02T12:05:23Z",
      },
      alternateVideos: [
        {
          title: "How to Run New Client Kickoff Calls",
          channel: "Will Polliard",
          url: "https://www.youtube.com/watch?v=GMOLv_m3XTY",
          videoId: "GMOLv_m3XTY",
          verifiedAt: "2026-10-02T12:05:28Z",
        },
      ],
      handbook: {
        stages: ["custom-client-kickoff"],
        rules: ["mom-after-every-client-meeting", "weekly-status-report", "escalation-levels", "cr-when-needed"],
        templates: ["kickoff-agenda", "mom", "escalation-matrix-template"],
      },
      sections: [
        {
          heading: "Purpose and when it happens",
          body: md(
            "The client kickoff happens after the internal kickoff and before [[term:discovery]] or design work starts. It is the first meeting between the client and the delivery team.",
            "",
            "Its purpose is to agree how the project will run, not to design the product. You leave with:",
            "- goals and success criteria in the client's words;",
            "- the [[term:scope-baseline]] and the [[term:out-of-scope]] list, said out loud;",
            "- the [[term:milestone]] plan and the next two weeks in detail;",
            "- [[term:spoc|SPOCs]] on both sides and who approves what;",
            "- cadence: [[term:status-report]], demos, channels, and the [[term:escalation-matrix]];",
            "- [[term:client-dependency|client dependencies]] with owners and dates.",
            "",
            "For white-label projects the same meeting also confirms the [[term:client-owned-accounts]] the client must create, and the [[term:brand-kit]] you need.",
          ),
        },
        {
          heading: "Who attends",
          body: md(
            "**Client side:** the sponsor (at least for the first 15 minutes), the SPOC who will approve day to day, and the people who own content, IT access or integrations.",
            "",
            "**Oyelabs side:**",
            "- **PM** (you): runs the meeting and owns the follow-up.",
            "- **BD owner:** introduces the team and hands over the relationship in front of the client.",
            "- **Tech lead:** answers technical questions and owns the integration and environment asks.",
            "- **Designer:** when design starts soon, to hear the brand and taste expectations first-hand.",
            "",
            "Keep it under about ten people. If the client brings a large group, ask in advance who will approve decisions, and address them by name in the meeting.",
          ),
        },
        {
          heading: "Prepare: checklist",
          body: md(
            "- Outputs of the internal kickoff: scope summary, RAID log, client asks list.",
            "- Fill in the kickoff agenda template and build a deck of no more than about 12 slides.",
            "- Find a time inside both working days. Put both time zones in the Teams invite title or body, e.g. “Kickoff – 10:00 London / 14:30 India”.",
            "- Send the invite with the agenda and deck at least one working day ahead, and ask the client to confirm their SPOC and attendees.",
            "- Check Teams works for guests from their tenant: lobby settings, recording permission, and whether they can open shared files.",
            "- Prepare a draft escalation matrix and communication plan for them to confirm, not to design from scratch.",
            "- Agree with BD who says what in the first five minutes.",
            "- Test screen sharing and have the deck open locally as a PDF backup.",
          ),
        },
        {
          heading: "Timed agenda template",
          body: md(
            "A 75-minute Teams kickoff (typical length 60–90 minutes):",
            "",
            "1. 0:00–0:08 Introductions and roles (BD hands over to the PM)",
            "2. 0:08–0:18 Goals and success criteria, in the client's words",
            "3. 0:18–0:30 Scope summary, out-of-scope items and assumptions",
            "4. 0:30–0:40 Timeline, milestones and the next two weeks",
            "5. 0:40–0:50 Team, RACI and SPOCs; who approves what",
            "6. 0:50–0:58 Ways of working: cadence, tools, status report, change requests, escalation",
            "7. 0:58–1:06 Client dependencies with dates",
            "8. 1:06–1:11 Top risks and assumptions",
            "9. 1:11–1:15 Recap: decisions, actions, next meeting",
            "",
            "Protect slot 7. When the meeting overruns, it is the first thing dropped, and it is the one you will need most in sprint 3.",
          ),
        },
        {
          heading: "Sample script",
          body: md(
            "- **Opening:** “Good morning from our side, and thank you for making time. In the next 75 minutes we want to agree how we will work together, so nothing surprises either of us later. I'll share the agenda now. Is there anything you need to add?”",
            "- **Goals, in their words:** “Before our slides: in one sentence, what does success look like for you six months after launch?”",
            "- **Naming out of scope:** “To be clear about what this phase covers, these three items are not included: the native apps, the ERP integration and multi-currency. We can plan them as a phase 2 or a change request.”",
            "- **Steering back:** “That is a great question for discovery. I'm noting it so we cover it properly on Tuesday. Can we come back to the timeline?”",
            "- **Asking for the decision-maker:** “Who will approve designs and requirements on your side? We need one name, so feedback does not wait on a group.”",
            "- **Asking for dependencies:** “To keep the first milestone, we need the brand guidelines by the 14th and API access by the 21st. Who can own those?”",
            "- **Closing:** “Let me read back what we agreed… I'll send the minutes today. Please reply if anything is wrong; otherwise we will work from them.”",
          ),
        },
        {
          heading: "What to show",
          body: md(
            "A short deck, shared from Teams, with one idea per slide:",
            "- the team with photos, roles and who to contact for what;",
            "- goals and success criteria (leave a blank for the client's words);",
            "- scope in one slide, out of scope in another;",
            "- a milestone timeline, with the next two weeks in detail;",
            "- the RACI and the escalation matrix;",
            "- the communication plan: status report day, demo cadence, channels, response times;",
            "- the client dependency list with dates, as a table they can copy.",
            "",
            "For a white-label project, add a two-minute live tour of the [[term:core-product]] so the client sees what already exists before asking for changes.",
          ),
        },
        {
          heading: "Traps and how to recover",
          body: md(
            "- **The sponsor brings a new feature.** Write it down, thank them, and say: “We'll assess it as a change request after discovery so you see the impact on time and cost.” Never estimate on the call.",
            "- **No decision-maker named.** Do not close without one. If they cannot decide, agree a date by which they will name the SPOC, and put it in the minutes as an action.",
            "- **Late joiners and bad audio.** Recap the agenda in one line when someone joins. Ask people to use the Teams chat for questions if the line is poor.",
            "- **The client disagrees with the scope slide.** Do not argue on the call. “Let's check that against the SOW together this week.” Then do it with BD.",
            "- **Overrun.** Drop the risk slide before the dependencies slide; send the risks in writing.",
            "- **Silence from a polite client.** Ask direct, named questions: “Sarah, does the Thursday demo slot work for your team?”",
          ),
        },
        {
          heading: "Follow-up within 24 hours",
          body: md(
            "Send the [[term:mom]] the same day if you can (typical), and always within the Oyelabs deadline in the rule card below. Attach the deck, the confirmed escalation matrix and the dependency list.",
            "",
            "Template:",
            "- **Subject:** [Project] kickoff – minutes, decisions and next steps",
            "- **Attendees** on both sides.",
            "- **Goals and success criteria** as the client said them.",
            "- **Decisions:** scope confirmed, out-of-scope items, SPOCs, cadence.",
            "- **Client dependencies:** item – owner – date.",
            "- **Actions:** owner – action – due date.",
            "- **Open questions** for discovery.",
            "- **Next meeting:** discovery workshop 1, [date, both time zones].",
            "- Closing line: “Please reply by [date] if anything here is not as you understood it.”",
          ),
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pmp-d01-client-kickoff-q1",
          prompt: "What is the main purpose of the client kickoff?",
          options: [
            "To agree how the project will run: goals, scope, plan, roles, cadence and dependencies",
            "To design the main screens with the client",
            "To sign the contract",
            "To give a final fixed date for go-live",
          ],
          correctIndex: 0,
          explanation: "The kickoff sets the rules of engagement. Designing happens later, the contract is already signed, and detailed dates follow discovery.",
        },
        {
          id: "pmp-d01-client-kickoff-q2",
          prompt: "Which items should the client kickoff agree before it ends? (Select all that apply.)",
          options: [
            "A named SPOC who approves decisions",
            "Client dependencies with owners and dates",
            "The out-of-scope list, said out loud",
            "The final colour palette",
            "Status report and demo cadence",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 4],
          explanation: "Decision-maker, dependencies, scope boundaries and cadence prevent the most common later disputes. Colours belong to the design stage.",
        },
        {
          id: "pmp-d01-client-kickoff-q3",
          prompt: "Twenty minutes into the kickoff, the client's founder says: 'We'll also need an Arabic version, that's easy, right?' Arabic is not in the SOW. What do you say?",
          options: [
            "Note it, say it is outside the current scope, and offer to assess it as a change request after discovery with the impact on time and cost",
            "Agree, because the kickoff should feel positive",
            "Say it cannot be done",
            "Give a rough estimate on the call so the founder is happy",
          ],
          correctIndex: 0,
          explanation: "On day one you set the pattern for every future request. Acknowledge, name it as out of scope, and route it to the change-request process. Never estimate live.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d01-client-kickoff-q4",
          prompt: "Your client is in Sydney and your team is in India. What should the Teams invite include?",
          options: [
            "The time in both time zones, the agenda and the deck, sent at least a working day ahead",
            "Only your local time; Teams converts it",
            "Just the meeting link",
            "The agenda only after the meeting",
          ],
          correctIndex: 0,
          explanation: "Teams converts times, but forwarded emails and calendar copies often do not. Writing both times prevents no-shows; the agenda lets the client bring the right people.",
        },
        {
          id: "pmp-d01-client-kickoff-q5",
          prompt: "The kickoff is running 15 minutes late. Which agenda item should you protect, and which can go into the minutes instead?",
          options: [
            "Protect client dependencies with dates; move the risk slide into the written follow-up",
            "Protect the team photo slide; drop dependencies",
            "Protect goals; drop the decision-maker question",
            "End the meeting and reschedule everything",
          ],
          correctIndex: 0,
          explanation: "Dependencies need the client to commit live to owners and dates. Risks can be shared in writing. Dropping dependencies is the classic mistake that causes sprint-3 delays.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d01-client-kickoff-q6",
          prompt: "The client brings six people, all of whom say they will give design feedback. What is the best response?",
          options: [
            "Ask who has final approval, and agree that one SPOC consolidates feedback per round",
            "Accept feedback from all six separately",
            "Ask four of them to leave the call",
            "Let the designer decide whose feedback counts",
          ],
          correctIndex: 0,
          explanation: "Many reviewers with no approver is how designs get stuck in endless rounds. One consolidating SPOC with approval rights keeps revision rounds meaningful.",
        },
        {
          id: "pmp-d01-client-kickoff-q7",
          prompt: "Why should out-of-scope items be named in the kickoff, not just written in the SOW?",
          options: [
            "Because later 'that's not included' sounds like an excuse if it was never said out loud",
            "Because the SOW is confidential",
            "Because out-of-scope items are free if not mentioned",
            "Because the client cannot read the SOW",
          ],
          correctIndex: 0,
          explanation: "People remember what was said in the room far better than a clause. Naming it early makes later change requests feel fair, not defensive.",
        },
        {
          id: "pmp-d01-client-kickoff-q8",
          prompt: "Which of these belong in the kickoff minutes? (Select all that apply.)",
          options: [
            "Goals and success criteria in the client's words",
            "Client dependencies: item, owner, date",
            "A line asking the client to reply by a date if anything is wrong",
            "A full word-for-word transcript",
            "The next meeting with both time zones",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 4],
          explanation: "Minutes record decisions, actions and dependencies, and invite corrections. A transcript is too long to read and hides the decisions.",
          isEdgeCaseOrInterviewQuestion: true,
        },
      ],
      practice: {
        kind: "rank",
        prompt:
          "Order the agenda for a 75-minute Teams kickoff with a UK retailer for a Laravel + React marketplace. The client has only spoken to BD until now.",
        items: [
          { id: "intro", label: "Introductions and roles; BD hands over to the PM" },
          { id: "goals", label: "Goals and success criteria, in the client's own words" },
          { id: "scope", label: "Scope summary, out-of-scope items and assumptions" },
          { id: "timeline", label: "Timeline, milestones and the next two weeks" },
          { id: "raci", label: "Team, RACI and SPOCs: who approves what" },
          { id: "ways", label: "Ways of working: status report, demo cadence, change requests, escalation" },
          { id: "deps", label: "Client dependencies with owners and dates" },
          { id: "recap", label: "Recap of decisions and actions; next meeting" },
        ],
        correctOrder: ["intro", "goals", "scope", "timeline", "raci", "ways", "deps", "recap"],
        explanation:
          "Start with people, then why (goals) before what (scope) and when (timeline). Roles and ways of working come next, because dependencies only make sense once the client knows who owns what and how you will chase it. Dependencies come late but before the recap, so they get committed owners and dates. Always end by reading back decisions and actions.",
      },
      sop: [
        {
          title: "Our client kickoff deck",
          prompt:
            "[Oyelabs SOP – admin to fill] Where the standard Oyelabs client kickoff deck lives, which slides are mandatory, who from BD attends, whether kickoffs are recorded in Teams (and the consent wording), and the default communication plan we offer clients.",
        },
      ],
    },

    // -----------------------------------------------------------------------
    // Discovery workshops
    // -----------------------------------------------------------------------
    {
      id: "pmp-d01-discovery-workshop",
      moduleId: "pmp-d01",
      trackId: "pm",
      title: "Discovery and requirements workshops",
      summary:
        "[[term:discovery|Discovery]] workshops turn the client's idea into requirements the team can estimate, design and test. At an agency they are where most future disputes are prevented or created. Every feature the client imagines but nobody writes down becomes a \"bug\" in [[term:uat]].\n\nA workshop is not an interview where the client talks and you type. You lead it. Each session has a narrow goal, such as \"the booking flow for a returning patient\", and ends with written outputs: [[term:user-story|user stories]] with [[term:acceptance-criteria]], open questions with owners, [[term:assumption|assumptions]] to confirm, and anything that is [[term:out-of-scope]] parked visibly.\n\nHow to run one. Send the questions in advance so the client brings the right people. Walk real scenarios end to end, not feature lists: \"A patient cancels an hour before. What happens?\" Show a rough flow or [[term:wireframe]] and let the client correct it. Read back what you heard at the end of every topic. After the series, the outputs become a [[term:brd]] or backlog that the client signs off, and then the [[term:requirement-freeze]] in the handbook applies.\n\nThe common mistake is to collect a wish list and call it requirements. A list of nouns (\"reports, notifications, admin\") cannot be estimated or tested. The second mistake is not saying \"that is outside this phase\" during the workshop. If you write a [[term:nice-to-have]] down without a label, the client will believe it was agreed.",
      level: "advanced",
      estMinutes: 50,
      webRefs: [
        { label: "GOV.UK Service Manual: How the discovery phase works", url: "https://www.gov.uk/service-manual/agile-delivery/how-the-discovery-phase-works", kind: "spec", verifiedAt: "2026-10-02T12:04:07Z" },
        { label: "NN/g: Discovery phase definition", url: "https://www.nngroup.com/articles/discovery-phase/", kind: "article", verifiedAt: "2026-10-02T12:04:09Z" },
        { label: "NN/g: Stakeholder Interviews 101", url: "https://www.nngroup.com/articles/stakeholder-interviews/", kind: "article", verifiedAt: "2026-10-02T12:04:09Z" },
        { label: "Asana: Requirements Gathering in 6 steps", url: "https://asana.com/resources/requirements-gathering", kind: "article", verifiedAt: "2026-10-02T12:04:10Z" },
      ],
      video: {
        title: "Requirements Gathering Workshop Technique I Use As A Business Analyst",
        channel: "Stefano - The Agile Business Analyst",
        url: "https://www.youtube.com/watch?v=Y-ojnxDOQog",
        videoId: "Y-ojnxDOQog",
        verifiedAt: "2026-10-02T12:05:28Z",
      },
      alternateVideos: [
        {
          title: "Discovery Kick-off Workshops",
          channel: "NNgroup",
          url: "https://www.youtube.com/watch?v=zcm6eLZXiVU",
          videoId: "zcm6eLZXiVU",
          verifiedAt: "2026-10-02T12:05:28Z",
        },
        {
          title: "Requirements Workshop - JAD Session (Example  workshop agenda)",
          channel: "The Business Analysis Doctor - IIBA Certification",
          url: "https://www.youtube.com/watch?v=s25hs8YazTo",
          videoId: "s25hs8YazTo",
          verifiedAt: "2026-10-02T12:05:28Z",
        },
      ],
      handbook: {
        stages: ["custom-discovery"],
        rules: ["requirement-freeze-after-signoff", "mom-after-every-client-meeting", "cr-when-needed"],
        templates: ["mom", "requirement-signoff"],
      },
      sections: [
        {
          heading: "Purpose and when it happens",
          body: md(
            "Discovery workshops run after the client kickoff and before design and build. Agencies often run them as a short series, for example two to four sessions over one to two weeks (typical), or as a paid discovery phase. GOV.UK describes a full discovery as typically 4 to 8 weeks, and says you should not start building during it.",
            "",
            "Each workshop has one narrow goal and produces:",
            "- [[term:user-story|user stories]] or flows with [[term:acceptance-criteria]];",
            "- open questions, each with an owner and a date;",
            "- [[term:assumption|assumptions]] and [[term:dependency|dependencies]] for the RAID log;",
            "- a visible parking lot of [[term:out-of-scope]] or [[term:phase-2]] ideas.",
            "",
            "At the end of the series, the outputs become a [[term:brd]] or backlog for [[term:sign-off]].",
          ),
        },
        {
          heading: "Who attends",
          body: md(
            "**Client side:** the SPOC who will approve requirements, plus the people who do the work today: an operations manager, a front-desk lead, a finance user. Ask for doers, not only managers.",
            "",
            "**Oyelabs side:**",
            "- **PM or business analyst:** facilitates and owns the outputs.",
            "- **Tech lead:** checks feasibility live and spots integration risks.",
            "- **Designer:** sketches flows or wireframes as you talk.",
            "- **QA lead** for at least one session: QA asks the edge-case questions that become acceptance criteria.",
            "",
            "Keep each session to about six to eight people. Split by user group rather than inviting everyone to everything.",
          ),
        },
        {
          heading: "Prepare: checklist",
          body: md(
            "- One goal per workshop, written in the invite (“Booking and cancellation for patients”).",
            "- Questions sent at least two working days ahead, so the client can collect answers and bring examples.",
            "- Ask for real artefacts: current spreadsheets, paper forms, screenshots of the tool they use today.",
            "- Draft a first flow or rough wireframe to react to; people correct a draft faster than they describe from nothing.",
            "- Re-read the [[term:sow]] for this area, so you know what is in and out before the client starts talking.",
            "- Set up a shared board or document for live notes, plus a visible “parking lot” column.",
            "- For long sessions with overseas clients, plan a break every 60 minutes; video fatigue is real across time zones.",
          ),
        },
        {
          heading: "Timed agenda template",
          body: md(
            "A 90-minute Teams workshop on one area (typical):",
            "",
            "1. 0:00–0:05 Goal, agenda and what we will have at the end",
            "2. 0:05–0:15 Current process: how it works today and what hurts",
            "3. 0:15–0:45 Walk the main scenario end to end on a draft flow; correct it live",
            "4. 0:45–0:50 Break",
            "5. 0:50–1:10 Edge cases and exceptions: cancellations, failures, roles, notifications",
            "6. 1:10–1:20 Read back stories and acceptance criteria for the main scenario",
            "7. 1:20–1:27 Parking lot: label each item as open question, phase 2 or change request",
            "8. 1:27–1:30 Actions, owners, dates; next workshop",
          ),
        },
        {
          heading: "Sample script",
          body: md(
            "- **Opening:** “Today we only cover booking and cancellation. By the end we'll have the main flow agreed and a list of questions with owners. Other topics go in the parking lot so we don't lose them.”",
            "- **Scenario prompt:** “Walk me through the last time a patient booked. Which screen did your receptionist open first?”",
            "- **Edge case:** “What happens if the patient cancels one hour before? Is there a fee, and who decides?”",
            "- **Steering:** “Reporting is important. It's on the parking lot for Thursday's session. Back to the cancellation rule.”",
            "- **Naming scope gently:** “SMS reminders aren't in the current scope. I'll note it as an open question and we'll show you the impact if you want it, so you can decide.”",
            "- **Reading back:** “Let me read back what I heard: a patient can cancel free until 24 hours before; after that the clinic decides. Is that right?”",
            "- **Closing with decisions:** “Three questions are open. Priya, can you confirm the cancellation fee rule by Wednesday?”",
          ),
        },
        {
          heading: "What to show",
          body: md(
            "- A draft user flow for the scenario, drawn before the meeting, edited live on screen.",
            "- Rough [[term:wireframe|wireframes]] or the current [[term:core-product]] screens (for white-label), so the client reacts to something concrete.",
            "- The live notes document, with stories and acceptance criteria appearing as you speak.",
            "- The parking lot column, visible at all times, so the client sees their ideas are recorded and labelled.",
            "",
            "Avoid polished designs in discovery. A beautiful mock-up makes clients comment on colours instead of the process.",
          ),
        },
        {
          heading: "Traps and how to recover",
          body: md(
            "- **The wish list.** The client lists features. Ask “Who uses it, when, and what happens next?” for each one until it becomes a scenario.",
            "- **The loudest person decides.** Check with the approving SPOC before writing anything as agreed: “Priya, are you happy for this to be the rule?”",
            "- **Endless edge cases.** Timebox. Log the rare ones as open questions and agree a default.",
            "- **Scope creep in the room.** Label it in the parking lot as phase 2 or [[term:change-request]] candidate. Never leave it unlabelled.",
            "- **No doers in the room.** If only managers came, write the assumptions down and ask for a 30-minute follow-up with a real user.",
            "- **Answers you cannot give.** “I don't want to guess on payments. Our tech lead will confirm by Thursday.”",
          ),
        },
        {
          heading: "Follow-up within 24 hours",
          body: md(
            "Send the [[term:mom]] with the updated stories attached, within the Oyelabs deadline in the rule card below. The stories, once complete, go to formal sign-off with the requirement sign-off template.",
            "",
            "Template:",
            "- **Subject:** Discovery workshop 2 – booking and cancellation – outputs",
            "- **Agreed:** the main flow and its rules, in plain sentences.",
            "- **Stories and acceptance criteria:** link to the document.",
            "- **Open questions:** question – owner – date.",
            "- **Assumptions** we will work with unless told otherwise.",
            "- **Parking lot:** each item labelled phase 2, change request or open question.",
            "- **Next workshop:** topic and time in both time zones.",
          ),
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pmp-d01-discovery-workshop-q1",
          prompt: "What should every discovery workshop produce, at minimum?",
          options: [
            "Stories or flows with acceptance criteria, open questions with owners, and a labelled parking lot",
            "A signed contract amendment",
            "Final UI designs",
            "A list of feature names",
          ],
          correctIndex: 0,
          explanation: "Outputs must be testable and owned. A list of feature names cannot be estimated or tested.",
        },
        {
          id: "pmp-d01-discovery-workshop-q2",
          prompt: "Which questions turn a wish list into requirements? (Select all that apply.)",
          options: [
            "Who uses this, and when?",
            "What happens next, and what if it fails?",
            "How do you do this today?",
            "Which colour do you like for the button?",
            "How will you know it works? (the acceptance test)",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 4],
          explanation: "Scenario, exceptions, current process and acceptance turn a noun into a requirement. Colours are a design-stage question.",
        },
        {
          id: "pmp-d01-discovery-workshop-q3",
          prompt: "In a workshop the client says, 'Oh, and we need a loyalty programme.' It is not in the SOW. You write it down. What else must you do?",
          options: [
            "Label it visibly as phase 2 or a change-request candidate, and say so out loud",
            "Nothing; writing it down is enough",
            "Add it to the user stories so the client is happy",
            "Delete it after the meeting",
          ],
          correctIndex: 0,
          explanation: "An unlabelled note looks like agreement. Labelling it in front of the client prevents the 'but we discussed it in discovery' dispute.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d01-discovery-workshop-q4",
          prompt: "Why do you show a rough draft flow rather than ask the client to describe the process from scratch?",
          options: [
            "People correct a draft much faster and more accurately than they describe from nothing",
            "Because the design is already final",
            "Because clients are not allowed to explain their process",
            "To save the designer's time later",
          ],
          correctIndex: 0,
          explanation: "A draft gives the conversation something concrete to fix. Keep it rough so the client corrects the process, not the colours.",
        },
        {
          id: "pmp-d01-discovery-workshop-q5",
          prompt: "Only the client's managers came to the workshop. Nobody who does the daily work attended. What is the best move?",
          options: [
            "Write the answers as assumptions and ask for a short follow-up session with a real user",
            "Cancel the workshop",
            "Treat the managers' answers as final requirements",
            "Make up the details from similar projects",
          ],
          correctIndex: 0,
          explanation: "Managers often describe the official process, not the real one. Log assumptions and validate them with a doer before sign-off.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d01-discovery-workshop-q6",
          prompt: "The client's finance lead asks, 'Can your system calculate VAT for three countries?' Nobody on your side knows. What do you say?",
          options: [
            "“I don't want to guess. Our tech lead will confirm by Thursday, and it goes on the open-questions list.”",
            "“Yes, that's easy.”",
            "“No, that's impossible.”",
            "Change the subject",
          ],
          correctIndex: 0,
          explanation: "A guessed yes becomes a commitment. An owned question with a date keeps trust and accuracy.",
        },
        {
          id: "pmp-d01-discovery-workshop-q7",
          prompt: "What happens to the requirements once the client signs them off?",
          options: [
            "They become the baseline; later changes go through the change-request process, per the requirement-freeze rule",
            "They can still be changed freely until UAT",
            "They are only a guide and not binding",
            "They are replaced by the designs",
          ],
          correctIndex: 0,
          explanation: "Sign-off creates the baseline the estimate and dates rest on. Check the requirement-freeze rule card for how Oyelabs applies it.",
        },
        {
          id: "pmp-d01-discovery-workshop-q8",
          prompt: "Which items belong in the follow-up after a discovery workshop? (Select all that apply.)",
          options: [
            "Agreed rules in plain sentences",
            "Open questions with owner and date",
            "Assumptions you will work with unless told otherwise",
            "The labelled parking lot",
            "The Teams recording instead of written notes",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 3],
          explanation: "A recording is not a record of decisions; nobody re-watches 90 minutes. Written agreements, questions, assumptions and the labelled parking lot are what the client confirms.",
          isEdgeCaseOrInterviewQuestion: true,
        },
      ],
      practice: {
        kind: "form",
        variant: "mom",
        templateId: "mom",
        prompt: "Write the minutes for this discovery workshop on booking and cancellation for a UK clinic chain's Laravel booking platform.",
        context: md(
          "**Discovery workshop 2, Teams, 90 min.** Client: Priya (operations director, SPOC), Tom (front-desk lead). Oyelabs: PM, tech lead, designer.",
          "",
          "**PM:** Today is booking and cancellation only.",
          "**Tom:** Patients book online or by phone. Front desk needs to book on their behalf.",
          "**PM:** So staff can create a booking for a patient. Agreed?",
          "**Priya:** Yes.",
          "**Tom:** Cancellations: free until 24 hours before. After that, we charge a fee, but I'm not sure how much.",
          "**Priya:** I'll confirm the fee rule with finance by Wednesday.",
          "**Tom:** Can patients get SMS reminders? Everyone has them.",
          "**PM:** SMS isn't in the current scope; email reminders are. I'll note it as an open question and we can show the impact if you want it.",
          "**Priya:** Fine. Also we'd love a loyalty scheme one day.",
          "**PM:** Parking that as phase 2.",
          "**Tech lead:** Do we import existing bookings from the old system?",
          "**Priya:** Not sure. Tom will send an export sample by Friday.",
          "**PM:** Designer will update the booking flow by Thursday. Next workshop: reporting, Tuesday 10:00 London.",
        ),
        fields: [
          { id: "agreed", label: "Agreed rules", input: "textarea", required: true },
          { id: "openQuestions", label: "Open questions (owner – date)", input: "textarea", required: true },
          {
            id: "sms",
            label: "How is SMS reminders recorded?",
            input: "select",
            options: ["Agreed requirement", "Open question (not in current scope)", "Phase 2", "Bug"],
            required: true,
          },
          {
            id: "loyalty",
            label: "How is the loyalty scheme recorded?",
            input: "select",
            options: ["Agreed requirement", "Open question (not in current scope)", "Phase 2", "Bug"],
            required: true,
          },
          { id: "actionCount", label: "Number of action items with an owner", input: "number", required: true },
          { id: "actions", label: "Action items (owner – action – due date)", input: "textarea", required: true },
          { id: "next", label: "Next meeting", input: "text", required: true },
        ],
        checks: [
          { fieldId: "sms", expected: "Open question (not in current scope)" },
          { fieldId: "loyalty", expected: "Phase 2" },
          { fieldId: "actionCount", expected: 3 },
        ],
        rubric: [
          { label: "Agreed rules written as testable sentences", points: 2, description: "Staff can book for a patient; free cancellation until 24 hours before; a fee applies after (amount open)." },
          { label: "Open questions have owners and dates", points: 2, description: "Fee rule – Priya – Wednesday; data import – Tom export sample – Friday; SMS impact if wanted." },
          { label: "Scope is labelled, not implied", points: 2, description: "SMS and loyalty are clearly not agreed scope." },
          { label: "Clear next meeting with time zone", points: 1 },
        ],
        sampleAnswer: {
          agreed:
            "- Front-desk staff can create a booking on a patient's behalf.\n- Cancellation is free until 24 hours before the appointment; after that a fee applies (amount to confirm).",
          openQuestions:
            "- Cancellation fee amount and rule – Priya – Wednesday.\n- Import of existing bookings needed? – Tom to send export sample – Friday.\n- SMS reminders: not in scope; PM to show impact if the client wants it.",
          sms: "Open question (not in current scope)",
          loyalty: "Phase 2",
          actionCount: "3",
          actions: "- Priya – confirm fee rule with finance – Wednesday.\n- Tom – send old-system export sample – Friday.\n- Designer – update booking flow – Thursday.",
          next: "Workshop 3: reporting, Tuesday 10:00 London",
        },
      },
      sop: [
        {
          title: "Our discovery format",
          prompt:
            "[Oyelabs SOP – admin to fill] Whether Oyelabs sells discovery as a paid phase, the standard number and length of workshops, who facilitates (PM or BA), the requirements format we deliver (BRD, backlog, stories) and where workshop notes are stored.",
        },
      ],
    },

    // -----------------------------------------------------------------------
    // Design review
    // -----------------------------------------------------------------------
    {
      id: "pmp-d01-design-review",
      moduleId: "pmp-d01",
      trackId: "pm",
      title: "Design review with the client",
      summary:
        "A client design review is where the client reacts to [[term:wireframe|wireframes]], [[term:mockup|mock-ups]] or a [[term:prototype]] and decides what is approved. At an agency it is a scope meeting as much as a design meeting. Every \"could we also add…\" said while looking at a screen is a possible [[term:change-request]], and every vague \"I don't love it\" is a revision round you will pay for.\n\nYour job as PM is to make the meeting produce decisions. For each screen or flow, the outcome is one of three: approve, revise (with specific, consolidated feedback) or reject (with the reason). Feedback should be tied to user goals and the agreed requirements, not taste. The [[term:spoc]] consolidates feedback so the designer gets one list per round, and the rule on design revision rounds in the handbook applies.\n\nHow to run it. Send the designs a day before with what to look for. Open by restating the goal and the requirements for each screen. Let the designer present the reasoning, then ask structured questions: \"Does this flow let a returning customer reorder in two taps?\". Record each decision live. Treat new screens or behaviour as change requests, not revisions. Close by reading back decisions, then get written [[term:design-approval]].\n\nThe common mistake is to leave without decisions: \"Let us think about it\" turns into three extra rounds. The second is to accept a new feature as a \"small design tweak\". If it was not in the signed requirements, it changes scope, whatever screen it appears on.",
      level: "advanced",
      estMinutes: 45,
      webRefs: [
        { label: "Confluence: Design review template", url: "https://www.atlassian.com/software/confluence/templates/design-review", kind: "docs", verifiedAt: "2026-10-02T12:04:10Z" },
        { label: "NN/g: Design Critiques", url: "https://www.nngroup.com/articles/design-critiques/", kind: "article", verifiedAt: "2026-10-02T12:04:11Z" },
        { label: "Atlassian Team Playbook: Sparring (structured peer feedback)", url: "https://www.atlassian.com/team-playbook/plays/sparring", kind: "docs", verifiedAt: "2026-10-02T12:04:10Z" },
      ],
      video: {
        title: "How to Present UX Design Ideas",
        channel: "NNgroup",
        url: "https://www.youtube.com/watch?v=2brmo3wgG48",
        videoId: "2brmo3wgG48",
        verifiedAt: "2026-10-02T12:05:29Z",
      },
      alternateVideos: [
        {
          title: "UX Design Critiques: 3 Tips for Effective Feedback",
          channel: "NNgroup",
          url: "https://www.youtube.com/watch?v=CBm9gdwshf8",
          videoId: "CBm9gdwshf8",
          verifiedAt: "2026-10-02T12:05:29Z",
        },
        {
          title: "Advice for explaining design rationale",
          channel: "femke.design",
          url: "https://www.youtube.com/watch?v=B1rKtQpgo9k",
          videoId: "B1rKtQpgo9k",
          verifiedAt: "2026-10-02T12:05:29Z",
        },
      ],
      handbook: {
        stages: ["custom-design"],
        rules: ["design-revision-rounds", "cr-when-needed", "mom-after-every-client-meeting"],
        templates: ["mom", "cr-form"],
      },
      sections: [
        {
          heading: "Purpose and when it happens",
          body: md(
            "Design reviews happen in the UI/UX stage, after requirements are agreed and before build starts on those screens. There is usually one review per round (wireframes, then high-fidelity mock-ups, sometimes a clickable [[term:prototype]]).",
            "",
            "The purpose is to leave with a decision for every screen or flow:",
            "- **Approve:** it goes to build.",
            "- **Revise:** specific, consolidated changes for the next round.",
            "- **Reject:** with the reason and which requirement it fails.",
            "",
            "Feedback that changes signed-off behaviour or adds screens is not a revision. It is a [[term:change-request]], and the revision-round rule in the handbook card below decides how many rounds are included.",
          ),
        },
        {
          heading: "Who attends",
          body: md(
            "**Client side:** the [[term:spoc]] who approves designs, plus the people who represent the users (for example, a store manager for a staff app). Brand or marketing owners for the high-fidelity round.",
            "",
            "**Oyelabs side:**",
            "- **Designer:** presents the reasoning, not just the pixels.",
            "- **PM:** facilitates, records decisions and spots scope changes.",
            "- **Tech lead:** for the first review at least, to flag designs that cost more to build than the estimate assumed.",
            "",
            "Too many client reviewers without one approver is the main cause of endless rounds. Agree in advance who approves.",
          ),
        },
        {
          heading: "Prepare: checklist",
          body: md(
            "- Map each screen to the requirement or [[term:user-story]] it serves.",
            "- Send the design link (Figma or similar) one working day before, with three questions for the client to think about.",
            "- Check the design against the [[term:sow]] and [[term:acceptance-criteria]]: is anything here that was not agreed? If so, raise it internally first.",
            "- Ask the tech lead to flag anything expensive (custom animations, complex filters).",
            "- Check client viewers can open the link from their tenant without a login wall.",
            "- Prepare a decision log: screen – decision – feedback – owner.",
            "- Know which revision round this is, and how many are included.",
          ),
        },
        {
          heading: "Timed agenda template",
          body: md(
            "A 60-minute Teams review of one flow (typical):",
            "",
            "1. 0:00–0:05 Goal, round number, what we need to decide today",
            "2. 0:05–0:10 Recap of the requirements and the users for this flow",
            "3. 0:10–0:25 Designer walks the flow end to end with the reasoning",
            "4. 0:25–0:45 Screen-by-screen questions and feedback; decision recorded per screen",
            "5. 0:45–0:52 New ideas raised: label each as revision, change request or phase 2",
            "6. 0:52–0:57 Read back decisions and the consolidated revision list",
            "7. 0:57–1:00 Approval route and date for the next round",
          ),
        },
        {
          heading: "Sample script",
          body: md(
            "- **Opening:** “This is round two of the checkout flow. Today we need a decision on each of the five screens: approve, revise or reject.”",
            "- **Framing feedback:** “Rather than whether you like it, can we check it against the goal: can a returning customer reorder in two taps?”",
            "- **Turning taste into specifics:** “When you say it feels heavy, is it the amount of text, the colour, or the number of steps?”",
            "- **Spotting a change request:** “Adding a wishlist is a new screen and new behaviour, so it isn't a revision. I'll send a change request with the impact by Friday, so you can decide.”",
            "- **Asking for the decision:** “So, the home screen: are we approving it as shown?”",
            "- **Handling conflicting reviewers:** “Mark wants a larger banner and Lina wants it smaller. Sara, as approver, which way should we go?”",
            "- **Closing:** “Two approved, two revise, one change request. Sara, please send any extra comments by Wednesday as one list, and we'll share round three on the 18th.”",
          ),
        },
        {
          heading: "What to show",
          body: md(
            "- The flow as a clickable prototype, so the client experiences the steps, not separate pictures.",
            "- Each screen next to the requirement it meets.",
            "- For mobile, the screens at the real device size; a full-width desktop share makes mobile text look huge.",
            "- The decision log on a second screen or shared document, filled in live.",
            "- For white-label, the [[term:core-product]] screen next to the rebranded version, so the client sees what is [[term:configuration]] and what would be [[term:customisation]].",
          ),
        },
        {
          heading: "Traps and how to recover",
          body: md(
            "- **“Let me think about it.”** Agree a date for the decision and put it in the minutes. Silence is not approval unless the rules say so.",
            "- **Taste feedback** (“make it pop”). Ask which user goal is affected, or offer two options to pick from.",
            "- **A new feature hidden as a tweak.** Name it as a change request on the call, calmly, before the designer agrees to it.",
            "- **The CEO joins late and overrules.** Thank them, record the new direction, and check with the SPOC whether this resets the round. Flag the impact in the follow-up.",
            "- **Feedback arrives after the meeting from six people.** Send it back to the SPOC for one consolidated list.",
            "- **Rounds keep coming.** Count them openly: “This is round four; two were included. I'll send the options for continuing.”",
          ),
        },
        {
          heading: "Follow-up within 24 hours",
          body: md(
            "Send the [[term:mom]] with the decision log. Ask for written [[term:design-approval]] on approved screens. Raise any [[term:change-request]] with the CR form.",
            "",
            "Template:",
            "- **Subject:** Checkout design review, round 2 – decisions",
            "- **Decisions:** screen – approve / revise / reject – note.",
            "- **Consolidated revisions** for the next round.",
            "- **Change requests raised:** item – CR number – impact to follow by [date].",
            "- **Rounds used:** 2 of [included].",
            "- **Actions:** owner – action – date.",
            "- “Please reply ‘approved’ for the approved screens by [date], so build can start.”",
          ),
        },
      ],
      challengeType: "quiz",
      quiz: [
        {
          id: "pmp-d01-design-review-q1",
          prompt: "What should a client design review produce for each screen?",
          options: [
            "A decision: approve, revise with specific feedback, or reject with a reason",
            "A list of the client's favourite colours",
            "A new estimate for the whole project",
            "A signed contract amendment",
          ],
          correctIndex: 0,
          explanation: "Without a decision per screen, the review just produces opinions, and opinions produce extra rounds.",
        },
        {
          id: "pmp-d01-design-review-q2",
          prompt: "While reviewing the checkout mock-ups, the client says: 'Let's add a wishlist button here, it's just one icon.' A wishlist was not in the requirements. What is it?",
          options: [
            "A change request, because it adds new behaviour and data, even if the visual change is small",
            "A design revision within the current round",
            "A bug in the design",
            "A clarification",
          ],
          correctIndex: 0,
          explanation: "The size of the icon is irrelevant. A wishlist needs storage, screens and logic that were not agreed, so it changes scope.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d01-design-review-q3",
          prompt: "Which are good ways to turn vague design feedback into actionable feedback? (Select all that apply.)",
          options: [
            "Ask which user goal is affected",
            "Ask whether it is the text, colour or number of steps",
            "Offer two concrete options to choose from",
            "Tell the client their taste is wrong",
            "Check it against the agreed requirement",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 4],
          explanation: "Specific questions and options tied to goals and requirements make feedback usable. Arguing about taste only creates friction.",
        },
        {
          id: "pmp-d01-design-review-q4",
          prompt: "Six client stakeholders each email you separate design comments after the review, and two contradict each other. What do you do?",
          options: [
            "Send them back to the SPOC for one consolidated list with the conflict resolved",
            "Ask the designer to apply all of them",
            "Pick the comments you agree with",
            "Apply the most senior person's comments without telling anyone",
          ],
          correctIndex: 0,
          explanation: "One consolidated list per round from the approver is what keeps revision rounds countable and conflicts resolved by the client, not by you.",
        },
        {
          id: "pmp-d01-design-review-q5",
          prompt: "The client ends the review with 'Let me think about it.' What should go in the minutes?",
          options: [
            "The pending decision, the screens affected, and the date by which the client will decide",
            "That the designs are approved",
            "Nothing until the client replies",
            "That the project is on hold",
          ],
          correctIndex: 0,
          explanation: "An open decision with a date keeps the plan honest and shows the impact of waiting. Assuming approval is risky unless the rules say silence counts.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d01-design-review-q6",
          prompt: "Why bring the tech lead to at least the first design review?",
          options: [
            "To flag designs that would cost more to build than the estimate assumed",
            "To approve the colours",
            "Because the client must meet every developer",
            "To present the designs instead of the designer",
          ],
          correctIndex: 0,
          explanation: "A beautiful custom interaction approved by the client can break the estimate. Catching it in review is far cheaper than in build.",
        },
        {
          id: "pmp-d01-design-review-q7",
          prompt: "You are in round four of a stage with two included revision rounds. What is the right move?",
          options: [
            "Say so openly and offer options for the extra rounds, following the Oyelabs revision-round rule",
            "Keep revising quietly to keep the client happy",
            "Refuse any more feedback",
            "Start building without approval",
          ],
          correctIndex: 0,
          explanation: "Counting rounds openly keeps the commercial terms fair. Silent extra rounds become unpaid work and set a pattern; refusing all feedback damages the relationship.",
          isEdgeCaseOrInterviewQuestion: true,
        },
        {
          id: "pmp-d01-design-review-q8",
          prompt: "Which belong in the design review follow-up? (Select all that apply.)",
          options: [
            "Decision per screen",
            "Consolidated revisions for the next round",
            "Change requests raised, with when the impact will be sent",
            "A request for written approval of approved screens",
            "The designer's personal opinion of the client",
          ],
          correctIndex: 0,
          correctIndices: [0, 1, 2, 3],
          explanation: "Decisions, revisions, CRs and written approval make the review count. Keep it professional.",
        },
      ],
      practice: {
        kind: "form",
        variant: "mom",
        templateId: "mom",
        prompt: "Write the minutes for this round-2 design review of a React checkout flow for a Dubai-based online grocery client.",
        context: md(
          "**Design review, round 2 of 2 included. Teams, 60 min.** Client: Sara (SPOC, approver), Mark (marketing). Oyelabs: PM, designer, tech lead.",
          "",
          "**Designer:** Five screens: cart, address, delivery slot, payment, confirmation.",
          "**Sara:** Cart and confirmation are fine as they are.",
          "**Mark:** The delivery slot screen feels busy. Can we show only the next three days?",
          "**Sara:** Agreed, three days.",
          "**Mark:** And add a wishlist button on the cart. It's just an icon.",
          "**PM:** A wishlist is new behaviour, not in the requirements. I'll send a change request with the impact by Friday.",
          "**Sara:** OK.",
          "**Sara:** The payment screen shows a provider we didn't choose. Please redo it with our gateway.",
          "**Tech lead:** Address screen is fine, but the map pin needs the client's maps API key.",
          "**Sara:** I'll send it Monday. Address approved.",
        ),
        fields: [
          {
            id: "slot",
            label: "Decision: delivery slot screen",
            input: "select",
            options: ["Approve", "Revise", "Reject"],
            required: true,
          },
          {
            id: "payment",
            label: "Decision: payment screen",
            input: "select",
            options: ["Approve", "Revise", "Reject"],
            required: true,
          },
          {
            id: "wishlist",
            label: "How is the wishlist recorded?",
            input: "select",
            options: ["Revision in this round", "Change request (new scope)", "Bug", "Approved"],
            required: true,
          },
          { id: "approvedCount", label: "Number of screens approved", input: "number", required: true },
          { id: "revisions", label: "Consolidated revisions for the next round", input: "textarea", required: true },
          { id: "actions", label: "Action items (owner – action – due date)", input: "textarea", required: true },
        ],
        checks: [
          { fieldId: "slot", expected: "Revise" },
          { fieldId: "payment", expected: "Revise" },
          { fieldId: "wishlist", expected: "Change request (new scope)" },
          { fieldId: "approvedCount", expected: 3 },
        ],
        rubric: [
          { label: "Revisions are specific", points: 2, description: "Slot screen: show the next three days only. Payment: use the client's chosen gateway." },
          { label: "Actions have owners and dates", points: 2, description: "Sara: maps API key Monday. PM: wishlist CR with impact Friday. Designer: next round." },
          { label: "Notes that this was the last included round", points: 1, description: "Round 2 of 2: further rounds follow the revision-round rule." },
        ],
        sampleAnswer: {
          slot: "Revise",
          payment: "Revise",
          wishlist: "Change request (new scope)",
          approvedCount: "3",
          revisions: "- Delivery slot: show only the next three days.\n- Payment: redo with the client's chosen gateway.\nNote: this was round 2 of 2 included.",
          actions: "- Sara – send maps API key – Monday.\n- PM – send wishlist CR with time and cost impact – Friday.\n- Designer – share revised slot and payment screens – date agreed in the plan.",
        },
      },
      sop: [
        {
          title: "Our design review set-up",
          prompt:
            "[Oyelabs SOP – admin to fill] Which design tool and share settings we use with clients, how design approval is captured (email reply, comment, signed form), and who from Oyelabs must attend client design reviews.",
        },
      ],
    },
  ],
} satisfies Module;
